### PR TITLE
depends: Fix Qt build with XCode 9.3

### PR DESCRIPTION
**Pull request by fanquake**
Building Qt with Xcode 9.3 is currently broken with:
```
compiling kernel/qmacgesturerecognizer.cpp
fontdatabases/mac/qfontengine_coretext.mm:775:20: error: qualified reference to 'QFixed' is a constructor name rather than a type in this context
    return QFixed::QFixed(int(CTFontGetUnitsPerEm(ctfont)));
                   ^
compiling .moc/moc_qfbscreen_p.cpp
1 error generated.
make[2]: *** [.obj/qfontengine_coretext.o] Error 1
make[2]: *** Waiting for unfinished jobs....

```
This patch should fix that, and will hopefully be the last time we have to patch Qt 5.7.

I've only made minor adjustments from the [original patch](https://codereview.qt-project.org/#/c/224900/), so that it will apply, although still not completely cleanly. We can cleanup if required.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

**Comment by Sjors** [comment]
I was initially confused by the PR description into thinking bitcoin-qt didn't build, but you're referring to QT itself via the depends system.

I didn't try before updating the command line tools in Xcode 9.3, but indeed building QT on macOS 10.13.4 is broken for me:

```
cd depends
make
...
compiling util/qundoview.cpp
rm -f ../../lib/libQt5Widgets.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq ../../lib/libQt5Widgets.a .obj/qaction.o .obj/qactiongroup.o .obj/qapplication.o
...
.obj/moc_qmacstyle_mac_p.o .obj/moc_qmacnativewidget_mac.o .obj/moc_qmaccocoaviewcontainer_mac.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libQt5Widgets.a(qstylepainter.o) has no symbols
...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../lib/libQt5Widgets.a(qscroller_mac.o) has no symbols
make: *** [/Volumes/SSD/src/bitcoin/depends/work/build/x86_64-apple-darwin17.5.0/qt/5.7.1-78660355bf0/qtbase/.stamp_built] Error 2
```

This PR fixes it for me.

**Review by theuni — APPROVED** [review]
utACK 5b4fc3eca429456628a5db4e4090da294eb1eba1
