### PR TITLE
[WIP] [depends] Qt 5.6.1

### LINKED ISSUE #7999: [depends] Qt fails to build on OSX 10.11, Xcode 7.3.1
```
In file included from qcocoacursor.mm:35:
./qcocoawindow.h:223:11: warning: 'devicePixelRatio' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    qreal devicePixelRatio() const;
          ^
../../../../include/QtGui/5.5.0/QtGui/qpa/../../../../../src/gui/kernel/qplatformwindow.h:110:19: note: overridden virtual function is here
    virtual qreal devicePixelRatio() const;
                  ^
qcocoacursor.mm:76:20: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef e = CGEventCreateMouseEvent(0, kCGEventMouseMoved, pos, 0);
                   ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: 
      candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^
26 warnings and 1 error generated.
make[4]: *** [.obj/qcocoacursor.o] Error 1
```

This seems to be fixed in [Qt 5.5.1](https://code.qt.io/cgit/qt/qtbase.git/commit/src/plugins/platforms/cocoa/qcocoacursor.mm?id=02ea0235216beef390e9868ff770c7a54d70db83&h=5.5), but probably isn't worth an intermediate bump to 5.5.1 if we're going to shift to 5.6 soon?

### PR DESCRIPTION
**Pull request by fanquake**
### Bump Qt to 5.6.1

The major changes are:
LTS - 5.6 is the new Long Term Support release, the previous being 4.8
Windows 10 is fully supported
High-DPI support, details [here](http://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/)
Improved C++11 support by `adding reverse iterators for all our container classes, a key_iterator for QHash and QMap, and a const_iterator for QByteArray.`

Maybe worth noting that 5.6 is the will be the last version before some open source licensing changes take place, more details [here](https://blog.qt.io/blog/2016/01/13/new-agreement-with-the-kde-free-qt-foundation/).

Qt 5.6.0 - [release post](https://blog.qt.io/blog/2016/03/16/qt-5-6-released/)
Qt 5.6.1 - [release post](https://blog.qt.io/blog/2016/06/08/qt-5-6-1-released/)
- [ ] [Remove dbus from the qt build?](https://github.com/bitcoin/bitcoin/pull/7993#issuecomment-223114395)

Fixes #7999

~~OpenSSL 1.0.2h
I had issues compiling with 1.0.1k, and had to remove the `no-cms` and `no-rc2` configure options for 1.0.2h, otherwise the build would fail.
I also had to add a `make depend` step before building.~~

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Nice! Have you tested this already over a gitian build?

**Comment by jonasschnelli** [comment]
Got gitian compile issues:
https://bitcoin.jonasschnelli.ch/pulls/8053/

```
making depend in crypto...
make[2]: Entering directory `/home/ubuntu/build/bitcoin/depends/work/build/i686-pc-linux-gnu/openssl/1.0.2h-08249684d6f/crypto'
../util/domd: 31: ../util/domd: makedepend: not found
mv: cannot stat 'Makefile.new': No such file or directory
make[2]: *** [local_depend] Error 127
make[2]: Leaving directory `/home/ubuntu/build/bitcoin/depends/work/build/i686-pc-linux-gnu/openssl/1.0.2h-08249684d6f/crypto'
make[1]: *** [depend] Error 1
```

**Comment by theuni** [comment]
Why not stick with 1.0.1k and drop no-cms and no-rc2? IIRC I had no trouble building that way when I tested qt 5.6. I'd really rather not require makedepend.

Alternatively, we could upstream the qt change to work properly without these. Either way, I don't think switching to 1.0.2 could be done lightly.

I assume the patches were dropped because they didn't apply cleanly? We'll need to check these. The mingw patch fixes a build-time problem with older gcc (4.6 iirc). Now that we require c++11, I think we can probably drop that.

The other is much more subtle, and fixes a runtime issue. See bb44d9e7546e6118cd91db5bbe471a3ce2ee7fcd for info there.

**Comment by arowser** [comment]
Can one of the admins verify this patch?

**Comment by fanquake** [comment]
This is now building successfully on OSX 10.11.5, plugging `./configure --prefix=/depends/x86_64-apple-darwin15.5.0` into configure.

Still investigating dropping the patches. I'll have to push a few more minor changes if they can be dropped.
@jonasschnelli Can you retest?
@theuni Is there any value in bumping our libxcb dependancy?

**Comment by laanwj** [comment]
I guess we'd have to tackle #7945 as well, to make sure this gets tested.

**Comment by jonasschnelli** [comment]
Still fails:
```
qxcbintegration.h:42:21: fatal error: xcb/xcb.h: No such file or directory
```
Build logs: https://bitcoin.jonasschnelli.ch/pulls/8053/

**Comment by laanwj** [comment]
Let's try to get this in for 0.13, Qt is the single most important dependency to bump from a user perspective.

**Comment by fanquake** [comment]
I'll rebase on master and look at removing dbus

**Comment by jonasschnelli** [comment]
The bump to Qt5.6 would give users on Linux/Windows "full" HiDPI support which somehow is extremely convenient these days (most new computers/laptops come with a HiDPI capable screen). 
There are some ugly glitches with Qt5.5 (https://github.com/bitcoin/bitcoin/issues/6472) and I guess more and more users will use HiDPI resolution on Linux/Mac.

It would be nice if we could bump to Qt5.6 before 0.13, but I agree, it is a little bit late. On the other hand, we still have the rc phase (I don't expect people reporting Qt5.6 relevant HiDPI issues before the rc phase).

**Comment by laanwj** [comment]
It's not too late. The best time to test it is in the rc phase as different people will be testing it on different environments.

**Comment by theuni** [comment]
5.6.1 was released yesterday, may as well target that.

I'm working on build/toolchain stuff atm, I'll try to take a look at the xcb issue asap.

**Comment by fanquake** [comment]
Rebased on master and updated to Qt 5.6.1

**Comment by fanquake** [comment]
The xcb patch no longer applies cleanly, will look at this again later today.

**Comment by laanwj** [comment]
It complains about the missing patch now...
```
/bin/sh: 1: cannot open /home/travis/build/bitcoin/bitcoin/depends/work/build/x86_64-unknown-linux-gnu/qt/5.6.1-697d96c0681/.patches-697d96c0681/fix-xcb-include-order.patch: No such file
```

**Comment by jonasschnelli** [comment]
Using this commit (https://github.com/jonasschnelli/bitcoin/commit/0102b7f0226370290e9a9d8aa88c44df3cbec3d8) let me compile Qt5.6.1 (depends/linux), but I had to manually create the `Qt5XcbQpa.pc` and the `Qt5PlatformSupport.pc`.
I could not figure out why these two pkgconfig files where not generated.
@theuni any ideas?

**Comment by paveljanik** [comment]
See https://bugreports.qt.io/browse/QTBUG-50073

**Comment by fanquake** [comment]
QT 5.7 has been [released](https://blog.qt.io/blog/2016/06/16/qt-5-7-released/).

"
Starting with Qt 5.7, we will require a C++11 compliant compiler to build and use Qt. This allows us to use many of the new features in Qt itself, and renew our codebase using features such as constexpr, move semantics, range-for and auto. These efforts are well under way and will continue throughout the next versions.
"
#### Qt Core
Qt uses poll() instead of select() in it’s event loop allowing for more than 1024 file descriptors
Qt now uses std::atomic for it’s atomic classes

**Comment by laanwj** [comment]
Okay this is getting confusing, is it just me or is Qt now releasing a new version every two weeks?

**Comment by jonasschnelli** [comment]
Indeed.
Qt7 has been released yesterday. We might want to go with Qt5.6.1 for 0.13.

**Comment by laanwj** [comment]
> Qt7 has been released yesterday. We might want to go with Qt5.6.1 for 0.13.

+1

**Comment by theuni** [comment]
Agreed on 5.6.1 for 0.13. I should be able to look at the xcb patch in the
next week or so.

Though it's worth noting for a future pr: 5.7 improves a few build-related
things for us:
- allows for split native tools build.
- passes flags (like -D and -B only to the host toolchain)

(I'm on mobile so those are from memory, may not be 100% accurate. I also
haven't tested that those work as intended.)

The first should allow us to split up the build into more reasonable chunks
(native_qttools and qtlibs).

The second should allow us to drop the xcb patch in favor of using more
detailed flags. It should also allow us to drop the hackish env vars we use.

**Comment by MarcoFalke** [comment]
Removed 0.13 milestone, as #8210 is merged
