### PR TITLE
Fix re-declared scoped enum as unscoped (Causes issues with some compilers)

### PR DESCRIPTION
**Pull request by donaloconnor**
MSVC fails to compile with the changes made in #10742 

The problem is enum types were changed to scoped (`enum class`) but in some places `enum` as an unscoped is used. 

This is a very simple fix and I've tested it.

Edit: Had to remove enum altogether - `enum class` doesn't compile on clang.

### CODE REVIEW

File: src/rest.cpp [hunk 1]
```diff
@@ -33,7 +33,7 @@ enum class RetFormat {
 };
 
 static const struct {
-    enum RetFormat rf;
+    enum class RetFormat rf;
```
Comment (MarcoFalke) [inline src/rest.cpp]: Fails on clang with:

```
rest.cpp:36:10: error: reference to scoped enumeration must use 'enum' not 'enum class'
    enum class RetFormat rf;
         ^~~~~~
rest.cpp:71:13: error: reference to scoped enumeration must use 'enum' not 'enum class'
static enum class RetFormat ParseDataFormat(std::string& param, const std::string& strReq)
            ^~~~~~
2 errors generated.

Comment (donaloconnor) [reply src/rest.cpp]: argh should have gone with my first version (just removing enum altogether!).

I'll update the PR soon.
Thanks!

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Comment by donaloconnor** [comment]
Okay - done finally (Got my branch into a messed up state which automatically closed the PR) :(

**Comment by sipa** [comment]
utACK 43f3dec009c43c0df2ef4ff62a9327de0148d959

**Comment by practicalswift** [comment]
utACK 43f3dec009c43c0df2ef4ff62a9327de0148d959

Thanks for fixing this!

**Comment by promag** [comment]
utACK 43f3dec.

**Review by jonasschnelli — APPROVED** [review]
utACK 43f3dec009c43c0df2ef4ff62a9327de0148d959
