### ISSUE TITLE
Bitcoin fails to build on OpenBSD 6.5

### ISSUE THREAD

**Issue by grim-trigger** [bitcoin/bitcoin#15951]
Bitcoin fails to build on OpenBSD 6.5 amd64.

This bug appears to have been introduced in 2c35fe6

gmake exits with the following error:

```
  CXX      util/libbitcoin_util_a-threadnames.o
util/threadnames.cpp:26:5: error: use of undeclared identifier
      'pthread_set_name_np'
    pthread_set_name_np(pthread_self(), name);
    ^
1 error generated.
gmake[2]: *** [Makefile:8653: util/libbitcoin_util_a-threadnames.o] Error 1
gmake[2]: Leaving directory '/home/bitcoin/bitcoin/src'
gmake[1]: *** [Makefile:13396: all-recursive] Error 1
gmake[1]: Leaving directory '/home/bitcoin/bitcoin/src'
gmake: *** [Makefile:775: all-recursive] Error 1
Making check in src
gmake[1]: Entering directory '/home/bitcoin/bitcoin/src'
gmake[2]: Entering directory '/home/bitcoin/bitcoin/src'
  CXX      util/libbitcoin_util_a-threadnames.o
util/threadnames.cpp:26:5: error: use of undeclared identifier
      'pthread_set_name_np'
    pthread_set_name_np(pthread_self(), name);
    ^
1 error generated.
gmake[2]: *** [Makefile:8653: util/libbitcoin_util_a-threadnames.o] Error 1
gmake[2]: Leaving directory '/home/bitcoin/bitcoin/src'
gmake[1]: *** [Makefile:13396: check-recursive] Error 1
gmake[1]: Leaving directory '/home/bitcoin/bitcoin/src'
gmake: *** [Makefile:775: check-recursive] Error 1
```
Configured using:

```
./configure --with-gui=qt5 CC=cc CXX=c++ \
    BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" \
    BDB_CFLAGS="-I${BDB_PREFIX}/include" \
    LDFLAGS="-L${BDB_PREFIX}/lib -L/usr/X11R6/lib" \
    CPPFLAGS="-I${BDB_PREFIX}/include -I/usr/X11R6/include" \
    --disable-dependency-tracking
```

**Comment by fanquake** [comment]
cc @jamesob

**Comment by grim-trigger** [comment]
It's just some missing #includes.

https://man.openbsd.org/pthread_set_name_np

Here is a workaround diff for compiling on openbsd:

```
diff --git a/src/util/threadnames.cpp b/src/util/threadnames.cpp
index 7b0d744ae..f7df267c6 100644
--- a/src/util/threadnames.cpp
+++ b/src/util/threadnames.cpp
@@ -9,6 +9,9 @@
 #include <atomic>
 #include <thread>
 
+#include <pthread.h>
+#include <pthread_np.h>
+
 #include <util/threadnames.h>
 
 #ifdef HAVE_SYS_PRCTL_H
```

A subsequent `gmake check` passes all tests.

**Comment by practicalswift** [comment]
Would the CirrusCI integration discussed in #15338 have caught this?

**Comment by grim-trigger** [comment]
Yes, and if better tools are available, they should be used. See _Reg. XII_ [1].

[1] https://en.wikipedia.org/wiki/Rules_for_the_Direction_of_the_Mind

XII: _Finally we ought to employ all the help of understanding, imagination, sense and memory, first for the purpose of having a distinct intuition of simple propositions; partly also in order to compare the propositions_

**Comment by MarcoFalke** [comment]
Yeah, it fails on the master branch in my repo:

https://cirrus-ci.com/github/MarcoFalke/bitcoin/master

**Comment by MarcoFalke** [comment]
@grim-trigger Mind to create a pull request with your fix?

**Comment by practicalswift** [comment]
@MarcoFalke How has the CirrusCI experience been? Is it stable, or is it build-roulette? :-)

**Comment by MarcoFalke** [comment]
There have been some timeouts or intermittent issues, but no real issues. Though, I am not sure if the regular devs that can respin travis can also respin cirrus ci. There is also some cost to having different solutions with different permission setups.

**Comment by gbtwbnyz** [comment]
ok

**Comment by fanquake** [comment]
Fixed in #15968.
