### PR TITLE
Add AssertLockHeld assertions in CWallet::ListCoins

### PR DESCRIPTION
**Pull request by ryanofsky**
Fixes TODO from #10295

### CODE REVIEW

**Comment by sipa** [comment]
utACK 5c7a7de7b38a84a3ba1e6c26dd1af67236dad891

**Comment by laanwj** [comment]
**Be careful here: this is dependent on a PR that has not been merged yet. Do not merge.**

**Comment by ryanofsky** [comment]
> Be careful here: this is dependent on a PR that has not been merged yet. Do not merge.

Dependent PR #10244 got merged, so this is now safe to merge too.

---

Rebased 5c7a7de7b38a84a3ba1e6c26dd1af67236dad891 -> 8392051595c615216f3857d54a80cf708ed1f29e ([pr/listlock.1](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.1) -> [pr/listlock.2](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.2)) due to conflict with #11126
Rebased 8392051595c615216f3857d54a80cf708ed1f29e -> cc69e88921725bed4b1e11823914aa8e418b7220 ([pr/listlock.2](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.2) -> [pr/listlock.3](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.3))
Rebased cc69e88921725bed4b1e11823914aa8e418b7220 -> a6c634013b7cf5d74bea68e51c011effcd7fc11d ([pr/listlock.3](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.3) -> [pr/listlock.4](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.4)) due to conflicts with #10295 and #12333
Rebased a6c634013b7cf5d74bea68e51c011effcd7fc11d -> 8740c61a334b3774984cfd1a3d67e33e68adb96a ([pr/listlock.4](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.4) -> [pr/listlock.5](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.5))

**Comment by ryanofsky** [comment]
Rebased 8740c61a334b3774984cfd1a3d67e33e68adb96a -> 545e85eccc2441c6d7745bb90d88dc14718455a2 ([pr/listlock.5](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.5) -> [pr/listlock.6](https://github.com/ryanofsky/bitcoin/commits/pr/listlock.6)) due to conflict with #12920

**Comment by MarcoFalke** [comment]
@ryanofsky Are you still working on this? If so, mind to respond to my previous question from April?

**Comment by MarcoFalke** [comment]
Missing locking annotations:

```
wallet/wallet.cpp:2362:5: error: calling function 'AvailableCoins' requires holding mutex 'cs_wallet' exclusively [-Werror,-Wthread-safety-analysis]
    AvailableCoins(availableCoins);
    ^
wallet/wallet.cpp:2373:5: error: calling function 'ListLockedCoins' requires holding mutex 'cs_wallet' exclusively [-Werror,-Wthread-safety-analysis]
    ListLockedCoins(lockedCoins);
    ^

**Comment by laanwj** [comment]
Closing as this seems to be inactive, let me know if you start work on this again and I should reopen it.

**Comment by ryanofsky** [comment]
> Closing as this seems to be inactive, let me know if you start work on this again and I should reopen it.

This PR can be reopened. There isn't actually any work that needs to be done here since the clang errors @MarcoFalke reported were fixed by @skeees in #13423 (f393a533bebc088985f94c725b9af881500ba998).

**Comment by MarcoFalke** [comment]
@ryanofsky What I mean with locking annotations is the clang-annotations in the header file:

```diff
diff --git a/src/wallet/wallet.h b/src/wallet/wallet.h
index 05ae9a1bbf..da326517c0 100644
--- a/src/wallet/wallet.h
+++ b/src/wallet/wallet.h
@@ -764,7 +764,7 @@ public:
     /**
      * Return list of available coins and locked coins grouped by non-change output address.
      */
-    std::map<CTxDestination, std::vector<COutput>> ListCoins() const;
+    std::map<CTxDestination, std::vector<COutput>> ListCoins() const EXCLUSIVE_LOCKS_REQUIRED(cs_main, cs_wallet);
 
     /**
      * Find non-change parent output.
```

Without these, it is only a best-guess runtime-check that the correct locks are taken for this method.

**Comment by MarcoFalke** [comment]
utACK 545e85eccc2441c6d7745bb90d88dc14718455a2 (given that the clang lock annotations are included in this commit)

**Comment by promag** [comment]
utACK 62b6f0f.
