### PR TITLE
qt: Add Create Unsigned button to SendConfirmationDialog

### PR DESCRIPTION
**Pull request by achow101**
Instead of having different buttons or changing button behavior for making a PSBT, just have SendConfirmationDialog return whether the user wants a PSBT or a broadcasted transaction. Since this dialog is used by both the bumpFeeAction and the SendCoinsDialog, changes to both to support the different behavior is needed. They will check the return value of the SendConfirmationDialog for whether a PSBT needs to be created instead of checking whether private keys are disabled.

Strings used in this dialog are being slightly modified to work with both private keys enabled and disabled wallets.

Supersedes #18656 and #18655

### CODE REVIEW

**Comment by achow101** [comment]
@luke-jr suggested that such a button should be behind an expert mode thing but I'm not sure how to do that. It's not clear to me how that would look in the GUI. One thought I had was to have something like an "advanced options" box that could be hidden, but I don't know enough about Qt to implement such a thing.

**Comment by instagibbs** [comment]
Definitely an improvement from prior PRs. Have you looked at `Enable coin control features` in the options menu? I tend to agree with Luke here in that for a basic user it's still too much clutter and could confuse them into thinking they've sent when they have not so that might be a place to put that option if you can figure it out. Maybe the button could also automagically show up if and only if it's a no privkey wallet(or instructs the user to set the option?).

**Comment by Sjors** [comment]
This is very scary:

Schermafbeelding 2020-04-28 om 20 39 47

I don't think this model is a good place for this. It's main goal is to allow the user to check their transaction, not to make new decisions.

I think the current behaviour of showing "the right" button is good enough for now. I would prefer to add an option like "Create PSBT instead of sending transaction" in the Expert settings: 

Schermafbeelding 2020-04-28 om 20 46 24

This preference can later be stored in the wallet payload (so it becomes a per-wallet preference rather than global). See also "wallet config options" in #13044.

**Comment by achow101** [comment]
> I don't think this model is a good place for this. It's main goal is to allow the user to check their transaction, not to make new decisions.

I don't see how making new decisions is mutually exclusive with checking the transaction. Users are still checking the transaction.

> I think the current behaviour of showing "the right" button is good enough for now. Under the hood it could be separate buttons of course, I don't care too deeply.

The whole point of this is to move away from having private keys disabled change what buttons do. I disagree that showing "the right button" is a good design decision.

**Comment by achow101** [comment]
I've added a checkbox in the options to enable/disable showing the `Create Unsigned` button. The button will be shown for `privateKeysDisabled` too.

**Comment by Sjors** [comment]
Thanks for adding the setting.

For watch-only wallets, the send screen still says `Create Unsigned`:

Schermafbeelding 2020-04-29 om 09 50 33

That should be `Send` for consistency. But that could be confusing; a user might know they need a PSBT, but they only see a "Send" button. 

So I think your original approach of adding the Create Unsigned button in the Send screen (and the extra menu option for bump fee) was better, at least when combined with the setting you added. That way:
* nothing changes for new users with a default wallet with private keys
* for watch-only wallets by default users will see a disabled Send button and a Create PSBT
* with the setting enabled, users with a private key wallet will see both buttons

**Comment by achow101** [comment]
> That should be `Send` for consistency. But that could be confusing; a user might know they need a PSBT, but they only see a "Send" button.

That could be changed to say "Create". I think "Create" is broad enough to imply "make and send" and "make unsigned".

> So I think your original approach of adding the Create Unsigned button in the Send screen (and the extra menu option for bump fee) was better, at least when combined with the setting you added. That way:

The whole point of this PR is because that may confuse users. I also like this approach as it is simpler.

File: src/qt/forms/optionsdialog.ui [hunk 1]
```diff
@@ -226,6 +226,13 @@
             </property>
            </widget>
           </item>
+          <item>
+           <widget class="QCheckBox" name="m_enable_create_unsigned">
+            <property name="text">
+             <string>Enable Create Unsigned button</string>
```
Comment (luke-jr) [inline src/qt/forms/optionsdialog.ui:232]: Maybe this should be a more general "Enable Advanced PSBT Controls"?

File: src/qt/optionsmodel.cpp [hunk 2]
```diff
@@ -80,6 +80,11 @@ void OptionsModel::Init(bool resetSettings)
         settings.setValue("fCoinControlFeatures", false);
     fCoinControlFeatures = settings.value("fCoinControlFeatures", false).toBool();
 
+    if (!settings.contains("m_make_unsigned_button")) {
```
Comment (luke-jr) [inline src/qt/optionsmodel.cpp:83]: I'm not sure if we have a standard naming schema for QSettings at this point, but `m_` seems wrong at least? (Since they're typeless, keeping the hungarian notation makes sense...)

File: src/qt/sendcoinsdialog.cpp [hunk 3]
```diff
@@ -306,17 +306,14 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
     question_string.append("<br /><span style='font-size:10pt;'>");
-    if (model->wallet().privateKeysDisabled()) {
-        question_string.append(tr("Please, review your transaction proposal. This will produce a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
-    } else {
-        question_string.append(tr("Please, review your transaction."));
+    if (model->getOptionsModel()->getMakeUnsignedButton() || model->wallet().privateKeysDisabled()) {
+        question_string.append(tr("Please review your transaction.<br/>The <b>Create Unsigned</b> button can be used to produce a Partially Signed Bitcoin Transaction (PSBT) which can be saved or copied and then signed with a PSBT-compatible wallet (e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.)").arg(PACKAGE_NAME));
+    }
+    if (!model->wallet().privateKeysDisabled()) {
+        question_string.append(tr("<br/>The <b>Send</b> button will create, sign, and broadcast this transaction."));
```
Comment (luke-jr) [inline src/qt/sendcoinsdialog.cpp:316]: The new prompt sounds too complicated for normal users...

File: src/qt/sendcoinsdialog.cpp [hunk 4]
```diff
@@ -379,20 +376,25 @@ void SendCoinsDialog::on_sendButton_clicked()
...
 
-    const QString confirmation = model->wallet().privateKeysDisabled() ? tr("Confirm transaction proposal") : tr("Confirm send coins");
-    const QString confirmButtonText = model->wallet().privateKeysDisabled() ? tr("Create Unsigned") : tr("Send");
-    SendConfirmationDialog confirmationDialog(confirmation, question_string, informative_text, detailed_text, SEND_CONFIRM_DELAY, confirmButtonText, this);
+    const QString confirmation = tr("Confirm send coins");
+    const QString confirmButtonText = tr("Send");
+    const QString psbt_button_text = tr("Create Unsigned");
+
+    // Show the Create Unsigned button if set in the options or if private keys are disabled.
+    bool show_unsigned_button = model->getOptionsModel()->getMakeUnsignedButton() || model->wallet().privateKeysDisabled();
```
Comment (luke-jr) [inline src/qt/sendcoinsdialog.cpp:384]: Can we move this up to have the `||` only done once?

File: src/qt/sendcoinsdialog.cpp [hunk 5]
```diff
@@ -959,49 +962,59 @@ void SendCoinsDialog::coinControlUpdateLabels()
...
     }
 }
 
-void SendConfirmationDialog::updateYesButton()
+void SendConfirmationDialog::updateButtons()
 {
     if(secDelay > 0)
     {
         yesButton->setEnabled(false);
         yesButton->setText(confirmButtonText + " (" + QString::number(secDelay) + ")");
```
Comment (luke-jr) [inline src/qt/sendcoinsdialog.cpp:1005]: We shouldn't count down if we're leaving it disabled...

File: src/qt/sendcoinsdialog.cpp [hunk 6]
```diff
@@ -959,49 +962,59 @@ void SendCoinsDialog::coinControlUpdateLabels()
...
+        if (m_psbt_button) {
+            m_psbt_button->setEnabled(false);
+            m_psbt_button->setText(m_psbt_button_text + " (" + QString::number(secDelay) + ")");
```
Comment (luke-jr) [inline src/qt/sendcoinsdialog.cpp:1008]: Seems harmless to countdown unconditionally here.

**Review by luke-jr — CHANGES_REQUESTED** [review]

File: src/qt/sendcoinsdialog.cpp (hunk 6 above)
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp:1008]: `m_psbt_button` is nullptr when it isn't being shown.

File: src/qt/sendcoinsdialog.cpp (hunk 4 above)
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp:384]: It is though.

File: src/qt/forms/optionsdialog.ui (hunk 1 above)
Comment (achow101) [reply src/qt/forms/optionsdialog.ui:232]: Done

File: src/qt/optionsmodel.cpp (hunk 2 above)
Comment (achow101) [reply src/qt/optionsmodel.cpp:83]: Done

File: src/qt/sendcoinsdialog.cpp (hunk 3 above)
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp]: I've reverted it back to the original prompt with a slight modification

File: src/qt/sendcoinsdialog.cpp (hunk 5 above)
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp]: Done

File: src/qt/sendcoinsdialog.cpp [hunk 7]
```diff
@@ -306,15 +306,12 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
-    } else {
-        question_string.append(tr("Are you sure you want to send?"));
-    }
-
     question_string.append("<br /><span style='font-size:10pt;'>");
+    question_string.append(tr("Do you want to create this transaction?"));
     if (model->wallet().privateKeysDisabled()) {
         question_string.append(tr("Please, review your transaction proposal. This will produce a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
+    } else if (model->getOptionsModel()->getEnablePSBTControls()) {
+        question_string.append(tr("Please, review your transaction. You can create and send this or transaction. Or you can create a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet. Or you can ").arg(PACKAGE_NAME));
```
Comment (luke-jr) [inline src/qt/sendcoinsdialog.cpp:314]: PSBTs aren't Bitcoin Core specific, though, so `PACKAGE_NAME` seems to be the wrong substitution to use here?

Comment (luke-jr) [inline src/qt/sendcoinsdialog.cpp:314]: "Or you can "...what?

Comment (achow101) [reply src/qt/sendcoinsdialog.cpp:314]: Oops, removed.

Comment (achow101) [reply src/qt/sendcoinsdialog.cpp]: This is just the same as the string above.

**Review by jarolrod — COMMENTED** [review]
Testing 768ef5c, does not compile on Arch Linux (kernel 5.8.16) with Qt 5.15.2.
Failures are related to `QPainterPath` found in `qt/trafficgraphwidget.cpp`
Below are the failures:
``` 
qt/trafficgraphwidget.cpp:55:9: error: invalid use of incomplete type ‘class QPainterPath’
   55 |         path.moveTo(x, YMARGIN + h);
      |         ^~~~

qt/trafficgraphwidget.cpp:59:13: error: invalid use of incomplete type ‘class QPainterPath’
   59 |             path.lineTo(x, y);
      |             ^~~~
qt/trafficgraphwidget.cpp:61:9: error: invalid use of incomplete type ‘class QPainterPath’
   61 |         path.lineTo(x, YMARGIN + h);
      |         ^~~~
qt/trafficgraphwidget.cpp:109:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be define
  109 |         QPainterPath p;
      |                      ^
qt/trafficgraphwidget.cpp:116:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be define
  116 |         QPainterPath p;
      |                      ^


```

**Comment by luke-jr** [comment]
@jarolrod You probably need to merge with master... That's an old issue unrelated to this PR

**Comment by jarolrod** [comment]
> @jarolrod You probably need to merge with master... That's an old issue unrelated to this PR

Thank! Wasn't aware, now I know. False alarm, I merged and 768ef5c compiles.

File: src/qt/sendcoinsdialog.cpp [hunk 8]
```diff
@@ -322,15 +322,12 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
-    }
-
     question_string.append("<br /><span style='font-size:10pt;'>");
+    question_string.append(tr("Do you want to create this transaction?"));
     if (model->wallet().privateKeysDisabled() && !model->wallet().hasExternalSigner()) {
         question_string.append(tr("Please, review your transaction proposal. This will produce a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
+    } else if (model->getOptionsModel()->getEnablePSBTControls()) {
+        question_string.append(tr("Please, review your transaction. You can create and send this or transaction. Or you can create a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
     } else {
         question_string.append(tr("Please, review your transaction."));
```
Comment (jarolrod) [inline src/qt/sendcoinsdialog.cpp:332]: while here, add a translator comment for this string

```diff
+    /*: Text to prompt user to review the details of the transaction
+        they are attempting to send. */
     question_string.append(tr("Please, review your transaction."));
```

File: src/qt/walletmodel.cpp [hunk 9]
```diff
@@ -506,12 +504,15 @@ bool WalletModel::bumpFee(uint256 hash, uint256& new_hash)
         questionString.append(tr("Warning: This may pay the additional fee by reducing change outputs or adding inputs, when necessary. It may add a new change output if one does not already exist. These changes may potentially leak privacy."));
     }
 
-    SendConfirmationDialog confirmationDialog(tr("Confirm fee bump"), questionString);
+    // Show the Craete Unsigned button if the option is set or private keys are disabled
+    bool show_unsigned_button = getOptionsModel()->getEnablePSBTControls() || m_wallet->privateKeysDisabled();
+
+    SendConfirmationDialog confirmationDialog(tr("Confirm fee bump"), questionString, "", "", SEND_CONFIRM_DELAY, "Send", !m_wallet->privateKeysDisabled(), "Create Unsigned", show_unsigned_button, nullptr);
```
Comment (jarolrod) [inline src/qt/walletmodel.cpp:510]: shouldn't `"Send"` and `"Create Unsigned"` be translatable? 

```suggestion
    SendConfirmationDialog confirmationDialog(tr("Confirm fee bump"), questionString, "", "", SEND_CONFIRM_DELAY, tr("Send"), !m_wallet->privateKeysDisabled(), tr("Create Unsigned"), show_unsigned_button, nullptr);
```

**Review by jarolrod — COMMENTED** [review]
Concept ACK

Will think about the changes over and give this another sweep through tomorrow. Some feedback for now. Mainly translator comments.

**Comment by Sjors** [comment]
tACK 72e0239

Although "Increase fee" can correctly create a PSBT, if you actually broadcast it the transaction list tab is confusing, because it doesn't mark the original as replaced (until it's confirmed). But that's a separate bug.

File: src/qt/sendcoinsdialog.cpp [hunk 10]
```diff
@@ -322,15 +322,12 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
     }
 
-    if (model->wallet().privateKeysDisabled() && !model->wallet().hasExternalSigner()) {
-        question_string.append(tr("Do you want to draft this transaction?"));
-    } else {
-        question_string.append(tr("Are you sure you want to send?"));
-    }
-
     question_string.append("<br /><span style='font-size:10pt;'>");
+    question_string.append(tr("Do you want to create this transaction?"));
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp:330]: Done

File: src/qt/walletmodel.cpp [hunk 11]
```diff
@@ -506,12 +504,15 @@ bool WalletModel::bumpFee(uint256 hash, uint256& new_hash)
         questionString.append(tr("Warning: This may pay the additional fee by reducing change outputs or adding inputs, when necessary. It may add a new change output if one does not already exist. These changes may potentially leak privacy."));
     }
 
-    SendConfirmationDialog confirmationDialog(tr("Confirm fee bump"), questionString);
+    // Show the Craete Unsigned button if the option is set or private keys are disabled
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/walletmodel.cpp]: Done

File: src/qt/sendcoinsdialog.cpp [hunk 12]
```diff
@@ -322,15 +322,12 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
     if (model->wallet().privateKeysDisabled() && !model->wallet().hasExternalSigner()) {
         question_string.append(tr("Please, review your transaction proposal. This will produce a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
+    } else if (model->getOptionsModel()->getEnablePSBTControls()) {
+        question_string.append(tr("Please, review your transaction. You can create and send this or transaction. Or you can create a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp]: Done

[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp]: Done

File: src/qt/sendcoinsdialog.cpp [hunk 13]
```diff
@@ -322,15 +322,12 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
-    if (model->wallet().privateKeysDisabled() && !model->wallet().hasExternalSigner()) {
-        question_string.append(tr("Do you want to draft this transaction?"));
-    } else {
-        question_string.append(tr("Are you sure you want to send?"));
-    }
-
     question_string.append("<br /><span style='font-size:10pt;'>");
+    question_string.append(tr("Do you want to create this transaction?"));
     if (model->wallet().privateKeysDisabled() && !model->wallet().hasExternalSigner()) {
         question_string.append(tr("Please, review your transaction proposal. This will produce a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp:335]: Done

File: src/qt/walletmodel.cpp [hunk 14]
```diff
@@ -480,10 +480,8 @@ bool WalletModel::bumpFee(uint256 hash, uint256& new_hash)
         return false;
     }
 
-    const bool create_psbt = m_wallet->privateKeysDisabled();
-
     // allow a user based fee verification
-    QString questionString = create_psbt ? tr("Do you want to draft a transaction with fee increase?") : tr("Do you want to increase the fee?");
+    QString questionString = tr("Do you want to increase the fee?");
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/walletmodel.cpp:485]: Done

File: src/qt/sendcoinsdialog.cpp (hunk 8 above)
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp:343]: Done

File: src/qt/walletmodel.cpp (hunk 9 above)
Comment (achow101) [reply src/qt/walletmodel.cpp]: Done

File: src/qt/sendcoinsdialog.cpp [hunk 15]
```diff
@@ -324,16 +324,22 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
 
-    if (model->wallet().privateKeysDisabled() && !model->wallet().hasExternalSigner()) {
-        question_string.append(tr("Do you want to draft this transaction?"));
-    } else {
-        question_string.append(tr("Are you sure you want to send?"));
-    }
-
     question_string.append("<br /><span style='font-size:10pt;'>");
+    /*: Message displayed when attempting to create a transaction. Cautionary text to prompt the user to verify
+     * that the displayed transaction details represent the transaction the user intends to create */
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp]: Done

File: src/qt/forms/optionsdialog.ui [hunk 16]
```diff
@@ -236,6 +236,13 @@
             </property>
            </widget>
           </item>
+          <item>
+           <widget class="QCheckBox" name="m_enable_psbt_controls">
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/forms/optionsdialog.ui:240]: Done

File: src/qt/forms/optionsdialog.ui [hunk 17]
```diff
@@ -236,6 +236,13 @@
...
+            <property name="text">
+             <string>Enable Advanced PSBT Controls</string>
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/forms/optionsdialog.ui]: Done

File: src/qt/sendcoinsdialog.cpp [hunk 18]
```diff
@@ -324,16 +324,22 @@ bool SendCoinsDialog::PrepareSendText(QString& question_string, QString& informa
...
+        /*: Text to inform a user attempting to create a transaction of their current options. At this stage,
+         * a user can only create a PSBT. This string is displayed when private keys are disabled and an external
+         * signer is not available */
         question_string.append(tr("Please, review your transaction proposal. This will produce a Partially Signed Bitcoin Transaction (PSBT) which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
+    } else if (model->getOptionsModel()->getEnablePSBTControls()) {
+        /*: Text to inform a user attempting to create a transaction of their current options. At this stage,
+         * a user can send their transaction or create a PSBT. This string is displayed when both private keys
+         * and PSBT controls are enabled */
+        question_string.append(tr("Please, review your transaction. You can create and send this transaction or you can create a Partially Signed Bitcoin Transaction (PSBT), which you can save or copy and then sign with e.g. an offline %1 wallet, or a PSBT-compatible hardware wallet.").arg(PACKAGE_NAME));
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/qt/sendcoinsdialog.cpp]: Done

**Comment by achow101** [comment]
Moved to the GUI repo: https://github.com/bitcoin-core/gui/pull/441
