### PR TITLE
Fix Windows build errors introduced in #10498

### LINKED ISSUE #12386: Windows Build Error
<pre><code>
  GEN      qt/forms/ui_transactiondescdialog.h
  GEN      qt/paymentrequest.pb.h
  GEN      qt/bitcoin.moc
  GEN      qt/bitcoinamountfield.moc
  GEN      qt/intro.moc
  GEN      qt/overviewpage.moc
  GEN      qt/rpcconsole.moc
  CXX      qt/qt_bitcoin_qt-bitcoin.o
qt/bitcoin.cpp: In function ‘int main(int, char**)’:
qt/bitcoin.cpp:709:173: error: invalid static_cast from type ‘WId {aka long long unsigned int}’ to type ‘HWND {aka HWND__*}’
             WinShutdownMonitor::registerShutdownBlockReason(QObject::tr("%1 didn't yet exit safely...").arg(QObject::tr(PACKAGE_NAME)), static_cast<HWND>(app.getMainWinId()));
                                                                                                                                                                             ^
make[2]: *** [qt/qt_bitcoin_qt-bitcoin.o] Error 1
Makefile:8181: recipe for target 'qt/qt_bitcoin_qt-bitcoin.o' failed
make[2]: Leaving directory '/usr/src/bitcoin/src'
make[1]: *** [all-recursive] Error 1
Makefile:9419: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/bitcoin/src'
Makefile:747: recipe for target 'all-recursive' failed
</code></pre>

build on WSL

### PR DESCRIPTION
**Pull request by practicalswift**
Fix Windows build errors introduced in #10498

Fixes #12386

cc @ken2812221, @Sjors, @MarcoFalke and @floreslorca

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK f40df29d96a29197f9949b63da80f9ba3152fc79

**Comment by Sjors** [comment]
Tested on a Gitian VM:

```
cd bitcoin
git remote add practicalswift https://github.com/practicalswift/bitcoin
git fetch practicalswift
cd ..
./gitian-build.sh -u https://github.com/practicalswift/bitcoin --detach-sign -c -b -o w sjors fix-windows-build
fix-windows-build
```

Build succeeds, but I do see some warnings (not sure if related), e.g.:

```
In file included from /home/ubuntu/build/bitcoin/depends/i686-w64-mingw32/share/../include/boost/thread/win32/condition_variable.hpp:9:0,
                 from /home/ubuntu/build/bitcoin/depends/i686-w64-mingw32/share/../include/boost/thread/condition_variable.hpp:14,
                 from ./util.h:31,
                 from ./addrman.h:14,
                 from init.cpp:12:
/home/ubuntu/build/bitcoin/depends/i686-w64-mingw32/share/../include/boost/thread/win32/thread_primitives.hpp:177:55: warning: conflicts with previous declaration ‘void* boost::detail::win32::GetModuleHandleA(const char*)’ [enabled by default]
                 __declspec(dllimport) void* __stdcall GetModuleHandleA(char const*);                             
```

I copied the executables over to a Windows 10 VM and was able to launch QT.

File: src/qt/bitcoin.cpp [hunk 1]
```diff
@@ -706,7 +706,7 @@ int main(int argc, char *argv[])
         if (BitcoinCore::baseInitialize()) {
             app.requestInitialize();
 #if defined(Q_OS_WIN) && QT_VERSION >= 0x050000
-            WinShutdownMonitor::registerShutdownBlockReason(QObject::tr("%1 didn't yet exit safely...").arg(QObject::tr(PACKAGE_NAME)), static_cast<HWND>(app.getMainWinId()));
```
Comment (ushan007) [inline src/qt/bitcoin.cpp]: Why are you wraiting
