### PR TITLE
doc: recommend `--disable-external-signer` in OpenBSD build guide

### PR DESCRIPTION
**Pull request by theStack**
Building the master branch with the default build settings (i.e. with external signer support enabled) leads to the following errors on my OpenBSD 6.9 machine:

```
In file included from util/system.cpp:9:
In file included from /usr/local/include/boost/process.hpp:25:
In file included from /usr/local/include/boost/process/group.hpp:32:
/usr/local/include/boost/process/detail/posix/wait_group.hpp:38:17: error: no member named 'waitid' in the global namespace
        ret = ::waitid(P_PGID, p.grp, &status, WEXITED | WNOHANG);
              ~~^
/usr/local/include/boost/process/detail/posix/wait_group.hpp:38:24: error: use of undeclared identifier 'P_PGID'
        ret = ::waitid(P_PGID, p.grp, &status, WEXITED | WNOHANG);
                       ^
/usr/local/include/boost/process/detail/posix/wait_group.hpp:38:48: error: use of undeclared identifier 'WEXITED'
        ret = ::waitid(P_PGID, p.grp, &status, WEXITED | WNOHANG);
                                               ^
/usr/local/include/boost/process/detail/posix/wait_group.hpp:144:17: error: no member named 'waitid' in the global namespace
        ret = ::waitid(P_PGID, p.grp, &siginfo, WEXITED | WSTOPPED | WNOHANG);
              ~~^
/usr/local/include/boost/process/detail/posix/wait_group.hpp:144:24: error: use of undeclared identifier 'P_PGID'
        ret = ::waitid(P_PGID, p.grp, &siginfo, WEXITED | WSTOPPED | WNOHANG);
                       ^
/usr/local/include/boost/process/detail/posix/wait_group.hpp:144:49: error: use of undeclared identifier 'WEXITED'
        ret = ::waitid(P_PGID, p.grp, &siginfo, WEXITED | WSTOPPED | WNOHANG);
                                                ^
/usr/local/include/boost/process/detail/posix/wait_group.hpp:144:59: error: use of undeclared identifier 'WSTOPPED'
        ret = ::waitid(P_PGID, p.grp, &siginfo, WEXITED | WSTOPPED | WNOHANG);
                                                          ^
7 errors generated.
```

This PR recommends passing `--disable-external-signer` in the OpenBSD build guide ([as suggested by laanwj](https://github.com/bitcoin/bitcoin/pull/22294#issuecomment-867452411)). The same commit also bumps the OpenBSD version mentioned in the header to 6.9 -- I recently used this document to setup a Bitcoin Core build on 6.9 and the description and all mentioned versions were still valid (before external signer support was enabled by default).

Would be nice if another OpenBSD user could confirm the build error.

### CODE REVIEW

**Review by fanquake — COMMENTED** [review]
Concept ACK. Looks like `waitid` was missing from the BSDs for a while, but was added to FreeBSD in the 10.0 release and NetBSD in the 8.0 release. However it's still missing on OpenBSD as of 6.9.

**Comment by laanwj** [comment]
There isn't really another workaround for this, so until there is I think documenting it like this makes sense. Another option would be to have `configure.ac` detect the lack of this function and preemptively disable the feature, but that might be confusing to users that expect the feature to be enabled by default…

**Comment by laanwj** [comment]
ACK e65d1d49864d047764eb2b444b2fc806b67e051c

File: doc/build-openbsd.md [hunk 1]
```diff
@@ -67,22 +67,29 @@ export AUTOMAKE_VERSION=1.16
 ```
 Make sure `BDB_PREFIX` is set to the appropriate path from the above steps.
 
+Note that building with external signer support currently fails on OpenBSD,
+hence you have to explicitely disable it by passing the parameter
```
Comment (hebasto) [inline doc/build-openbsd.md:71]: typo?

```
doc/build-openbsd.md:71: explicitely ==> explicitly
```
