### ISSUE TITLE
Test `policyestimator_tests/BlockPolicyEstimates` failure

### ISSUE THREAD

**Issue by martinus** [bitcoin/bitcoin#29000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I have a reproducible test case failure on my machine. I've bisected it to commit 714523918ba2b853fc69bee6b04a33ba0c828bf5. Since this commit, the test case `policyestimator_tests/BlockPolicyEstimates` fails, but only when I use my builds script:

```sh
chrt -i 0 make -j32 check
```

`chrt` runs the make command in idle priority (I use that so I can smoothly browse while testing). I have an AMD 7950x with 16 cores/32 threads. When I remove `chrt -i 0` the test works. I suspect that it fails because for whatever reason it can't run in parallel with another test, but so far I couldn't narrow it down.

```
❯ chrt -i 0 make -j32 check |grep error
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
make[3]: *** [Makefile:22606: test/policyestimator_tests.cpp.test] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:20548: check-am] Error 2
make[1]: *** [Makefile:20213: check-recursive] Error 1
make: *** [Makefile:813: check-recursive] Error 1
```

### Expected behaviour

All unit tests should succeed

### Steps to reproduce

```sh
./autogen.sh
./configure CXX=clang++ CC=clang --disable-wallet --with-guid=no
chrt -i 0 make -j32 check
```

### Relevant log output

I uploaded the full log of `chrt -i 0 make -j32 check >out.txt` here: https://gist.github.com/martinus/5d6795cd618f7d203e95d4f5426746f0

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

160d23677ad

### Operating system and version

Linux 6.6.2-201.fc39.x86_64

### Machine specifications

AMD 7950x

**Comment by martinus** [comment]
Right above the end of the loop? Yes, this seems to do the trick, I've run it 10 times and it always worked

**Comment by ismaelsadeeq** [comment]
Thats because the fee estimator now updates asynchronously, and there are about 200 `removeForBlock`
https://github.com/bitcoin/bitcoin/blob/6d5790956f45e3de5c6c4ee6fda21878b0d1287b/src/test/policyestimator_tests.cpp#L98

We suppose to wait for the fee estimator to catch up right after the loop below line 113 just as @maflcko said.

I will open a pull that will fix this and some outstanding comments from @willcl-ark in #28368
