### ISSUE TITLE
ci: failure in `sock_tests` in i686 NO IPC

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#35199]
https://github.com/bitcoin/bitcoin/actions/runs/25275669000/job/74105140405#step:11:2951:
```bash
test/sock_tests.cpp(19): Entering test suite "sock_tests"
test/sock_tests.cpp(137): Entering test case "send_and_receive"
2026-05-03T09:41:16.711748Z [unknown] [test/util/random.cpp:48] [SeedRandomStateForTest] Setting random seed for current tests to RANDOM_CTX_SEED=b6c3fe918d70654743df2723c1b1b525cea9a447aef6d3db4379cce5dc415c62
2026-05-03T09:41:16.712263Z [test] [init/common.cpp:156] [LogPackageVersion] Bitcoin Core version v31.99.0-d07571caa0fe (debug build)
2026-05-03T09:41:16.712327Z [test] [init/common.cpp:102] [SetLoggingCategories] Log output may contain privacy-sensitive information. Be cautious when sharing logs.
2026-05-03T09:41:16.712444Z [test] [kernel/context.cpp:20] [operator()] Using the 'x86_shani(1way;2way)' SHA256 implementation
2026-05-03T09:41:16.712458Z [test] [random.cpp:110] [ReportHardwareRand] Using RdSeed as an additional entropy source
2026-05-03T09:41:16.712469Z [test] [random.cpp:113] [ReportHardwareRand] Using RdRand as an additional entropy source
test/sock_tests.cpp(34): fatal error: in "sock_tests/send_and_receive": critical check s != static_cast<SOCKET>(-1) has failed
test/sock_tests.cpp(137): Leaving test case "send_and_receive"; testing time: 1241us
test/sock_tests.cpp(158): Entering test case "recv_until_terminator_limit"
2026-05-03T09:41:16.713005Z [test] [test/util/random.cpp:48] [SeedRandomStateForTest] Setting random seed for current tests to RANDOM_CTX_SEED=b6c3fe918d70654743df2723c1b1b525cea9a447aef6d3db4379cce5dc415c62
2026-05-03T09:41:16.713368Z [test] [init/common.cpp:156] [LogPackageVersion] Bitcoin Core version v31.99.0-d07571caa0fe (debug build)
2026-05-03T09:41:16.713429Z [test] [init/common.cpp:102] [SetLoggingCategories] Log output may contain privacy-sensitive information. Be cautious when sharing logs.
test/sock_tests.cpp(34): fatal error: in "sock_tests/recv_until_terminator_limit": critical check s != static_cast<SOCKET>(-1) has failed
test/sock_tests.cpp(158): Leaving test case "recv_until_terminator_limit"; testing time: 932us
test/sock_tests.cpp(147): Entering test case "wait"
2026-05-03T09:41:16.713965Z [test] [test/util/random.cpp:48] [SeedRandomStateForTest] Setting random seed for current tests to RANDOM_CTX_SEED=b6c3fe918d70654743df2723c1b1b525cea9a447aef6d3db4379cce5dc415c62
2026-05-03T09:41:16.714309Z [test] [init/common.cpp:156] [LogPackageVersion] Bitcoin Core version v31.99.0-d07571caa0fe (debug build)
2026-05-03T09:41:16.714368Z [test] [init/common.cpp:102] [SetLoggingCategories] Log output may contain privacy-sensitive information. Be cautious when sharing logs.
test/sock_tests.cpp(34): fatal error: in "sock_tests/wait": critical check s != static_cast<SOCKET>(-1) has failed
test/sock_tests.cpp(147): Leaving test case "wait"; testing time: 895us
test/sock_tests.cpp(38): Entering test case "constructor_and_destructor"
2026-05-03T09:41:16.714886Z [test] [test/util/random.cpp:48] [SeedRandomStateForTest] Setting random seed for current tests to RANDOM_CTX_SEED=b6c3fe918d70654743df2723c1b1b525cea9a447aef6d3db4379cce5dc415c62
2026-05-03T09:41:16.715219Z [test] [init/common.cpp:156] [LogPackageVersion] Bitcoin Core version v31.99.0-d07571caa0fe (debug build)
2026-05-03T09:41:16.715280Z [test] [init/common.cpp:102] [SetLoggingCategories] Log output may contain privacy-sensitive information. Be cautious when sharing logs.
test/sock_tests.cpp(34): fatal error: in "sock_tests/constructor_and_destructor": critical check s != static_cast<SOCKET>(-1) has failed
test/sock_tests.cpp(38): Leaving test case "constructor_and_destructor"; testing time: 887us
test/sock_tests.cpp(60): Entering test case "move_assignment"
2026-05-03T09:41:16.715797Z [test] [test/util/random.cpp:48] [SeedRandomStateForTest] Setting random seed for current tests to RANDOM_CTX_SEED=b6c3fe918d70654743df2723c1b1b525cea9a447aef6d3db4379cce5dc415c62
2026-05-03T09:41:16.716125Z [test] [init/common.cpp:156] [LogPackageVersion] Bitcoin Core version v31.99.0-d07571caa0fe (debug build)
2026-05-03T09:41:16.716188Z [test] [init/common.cpp:102] [SetLoggingCategories] Log output may contain privacy-sensitive information. Be cautious when sharing logs.
test/sock_tests.cpp(34): fatal error: in "sock_tests/move_assignment": critical check s != static_cast<SOCKET>(-1) has failed
test/sock_tests.cpp(60): Leaving test case "move_assignment"; testing time: 875us
test/sock_tests.cpp(48): Entering test case "move_constructor"
2026-05-03T09:41:16.716698Z [test] [test/util/random.cpp:48] [SeedRandomStateForTest] Setting random seed for current tests to RANDOM_CTX_SEED=b6c3fe918d70654743df2723c1b1b525cea9a447aef6d3db4379cce5dc415c62
2026-05-03T09:41:16.717014Z [test] [init/common.cpp:156] [LogPackageVersion] Bitcoin Core version v31.99.0-d07571caa0fe (debug build)
2026-05-03T09:41:16.717074Z [test] [init/common.cpp:102] [SetLoggingCategories] Log output may contain privacy-sensitive information. Be cautious when sharing logs.
test/sock_tests.cpp(34): fatal error: in "sock_tests/move_constructor": critical check s != static_cast<SOCKET>(-1) has failed
test/sock_tests.cpp(48): Leaving test case "move_constructor"; testing time: 877us
test/sock_tests.cpp(19): Leaving test suite "sock_tests"; testing time: 5865us
```

**Comment by fanquake** [comment]
Happening in a number of jobs:
https://github.com/bitcoin/bitcoin/actions/runs/25274080662/job/74101068747#step:11:3051
https://github.com/bitcoin/bitcoin/actions/runs/25275669316/job/74105141912#step:11:2975

**Comment by l0rinc** [comment]
Could this be caused by the Copy Fail fix in the latest Docker seccomp hardening in https://github.com/moby/moby/pull/52501?

The Docker 29.4.2 release notes say:

> Block AF_ALG sockets and the socketcall(2) multiplexer in the default seccomp profile to prevent in-container privilege escalation via the kernel crypto API ("Copy Fail").

The failing call is https://github.com/bitcoin/bitcoin/blob/52c3381fa8f4194f9da7cf69e411602c3c7e161d/src/test/sock_tests.cpp#L33 (not the mentioned `AF_ALG`), but seems like a plausible explanation for `sock_tests` failing at the first `socket()` call, before any test-specific logic runs.

---


Edit: Added https://github.com/bitcoin/bitcoin/pull/35202 to work around the restriction
