### PR TITLE
wallet: warn against accidental unsafe older() import

### PR DESCRIPTION
**Pull request by Sjors**
[BIP 379](https://github.com/bitcoin/bips/blob/master/bip-0379.md) ([Miniscript](https://bitcoin.sipa.be/miniscript/)) allows relative height and time locks that have no consensus meaning in [BIP 68](https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki) (relative timelocks) / [BIP 112](https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki) (`CHECKSEQUENCEVERIFY`). This is (ab)used by some protocols, e.g. [by Lightning to encode extra data](https://delvingbitcoin.org/t/exploring-extended-relative-timelocks/1818/23), but is unsafe when used unintentionally: `older(65536)` is equivalent to `older(1)`.

This PR emits a warning when `importdescriptors` contains such a descriptor.

The first commit makes `SEQUENCE_LOCKTIME` flags reusable by other tests.

The main commit adds the `ForEachNode` helper to `miniscript.h` which is then used in the `MiniscriptDescriptor` constructor to check for `Fragment::OLDER` with unsafe values. These are stored in `m_warnings`, which the RPC code then collects via `Warnings()`.

It adds both a unit and functional test.

---

A previous version of this PR prevented the import, unless the user opted in with an `unsafe` flag. It also used string parsing in the RPC code.

---

Based on:
- [x] https://github.com/bitcoin/bitcoin/pull/33914

### CODE REVIEW

File: src/wallet/rpc/backup.cpp [hunk 1]
```diff
@@ -158,6 +160,30 @@ static UniValue ProcessDescriptorImport(CWallet& wallet, const UniValue& data, c
         if (parsed_descs.empty()) {
             throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, error);
         }
+
+        // Additional safety checks for valid descriptors
+        size_t pos{0};
+        while (!unsafe && (pos = descriptor.find("older(", pos)) != std::string::npos) {
```
Comment (w0xlt) [inline src/wallet/rpc/backup.cpp]: Wouldn't it be better to have this logic inside the miniscript files?

Comment (Sjors) [reply src/wallet/rpc/backup.cpp]: Maybe, but I'm worried it would add a ton of code churn in order to either:
1. bubble these values up; or
2. have the descriptor and miniscript parser take an `unsafe` argument to change its behavior (or some more general `parse_options` argument)

File: test/functional/wallet_importdescriptors.py [hunk 2]
```diff
@@ -770,5 +772,48 @@ def run_test(self):
             assert_equal(w_multipath.getrawchangeaddress(address_type="bech32"), w_multisplit.getrawchangeaddress(address_type="bech32"))
         assert_equal(sorted(w_multipath.listdescriptors()["descriptors"], key=lambda x: x["desc"]), sorted(w_multisplit.listdescriptors()["descriptors"], key=lambda x: x["desc"]))
 
+        self.log.info("Test older() safety")
+
+        for flag in [0, SEQUENCE_LOCKTIME_TYPE_FLAG]:
+            self.log.debug("Importing a safe value always works")
+            height_delta = 65535 + (1 << 22 if flag is SEQUENCE_LOCKTIME_TYPE_FLAG else 0)
```
Comment (w0xlt) [inline test/functional/wallet_importdescriptors.py]: nit
```suggestion
            height_delta = 65535 + (flag if flag is SEQUENCE_LOCKTIME_TYPE_FLAG else 0)
```

File: src/wallet/rpc/backup.cpp (hunk 1 above)
Comment (Sjors) [reply src/wallet/rpc/backup.cpp]: That said, I'm not a huge fan of this much string parsing logic either.

File: src/wallet/rpc/backup.cpp [hunk 3]
```diff
@@ -319,6 +345,7 @@ RPCHelpMan importdescriptors()
                                     },
                                     {"internal", RPCArg::Type::BOOL, RPCArg::Default{false}, "Whether matching outputs should be treated as not incoming payments (e.g. change)"},
                                     {"label", RPCArg::Type::STR, RPCArg::Default{""}, "Label to assign to the address, only allowed with internal=false. Disabled for ranged descriptors"},
+                                    {"unsafe", RPCArg::Type::BOOL, RPCArg::Default{false}, "Allow the import of descriptors that contain height or time locks with no consensus meaning, e.g. older(65536)"},
```
Comment (brunoerg) [inline src/wallet/rpc/backup.cpp]: fac503e7d551d1cbeb11cdb43b222f24c6de002e: Worth adding this field in the examples (`HelpExampleCli`)?

**Review by brunoerg — COMMENTED** [review]
I've reviewed the code and it looks great - Just a question: Instead of having this new field and prevent the import (any user have reported an accidental import?), couldn't we just throw a warning?

File: src/wallet/rpc/backup.cpp (hunk 3 above)
Comment (brunoerg) [reply src/wallet/rpc/backup.cpp]: Also, it would need a release note.

**Comment by Sjors** [comment]
@brunoerg perhaps a warning is good enough yes. In that case we wouldn't need the `unsafe` option. Will give it some thought.

**Comment by Sjors** [comment]
I switched to emitting a warning.

I'll look into modifying miniscript / descriptor classes to avoid the string parsing. Though unless people really don't like it, I think it could be done as a followup.

File: src/wallet/rpc/backup.cpp (hunk 3 above)
Comment (Sjors) [reply src/wallet/rpc/backup.cpp]: I dropped this option, so probably no longer needed to document it? I expect it's quite rare for people to even encounter the warning.

**Comment by Sjors** [comment]
Rebased. Fixed bug in the functional test found by an AI overlord, apparently using `is` isn't safe: https://stackoverflow.com/a/28864111 

> I'll look into modifying miniscript / descriptor classes to avoid the string parsing.

Done, and also added a unit test. It's a bit more code and complexity, but more robust and extendable than parsing strings.

Since c1e6a9f1e7331fa2c1c73a0dd17056570283e443 is no longer relevant for this PR I dropped it.

**Review by brunoerg — APPROVED** [review]
ACK fe06b92429206aee66d33c843195235f4bb27181 - This new approach of just warning is better than the previous one, nice! I haven't reviewed the code in depth, just did a light code review but tested the behavior in practice and worked fine. 

Also, I ran a mutation analysis on these changes and the only uncaught mutant is:
```diff
         // Traverse miniscript tree for unsafe use of older()
         miniscript::ForEachNode(*m_node, [&](const miniscript::Node<uint32_t>& node) {
-            if (node.fragment == miniscript::Fragment::OLDER) {
+            if (1==1) {
                 const uint32_t raw = node.k;
                 const uint32_t value_part = raw & ~CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG;
                 if (value_part > CTxIn::SEQUENCE_LOCKTIME_MASK) {
```

it means we're not really testing that the warning is produced exclusively for the `older()` fragment, nothing critical and can be ignored but I think a simple test case could solve it. e.g.:

```diff
diff --git a/src/test/descriptor_tests.cpp b/src/test/descriptor_tests.cpp
index 9e06e78fe9..fb35dfd05a 100644
--- a/src/test/descriptor_tests.cpp
+++ b/src/test/descriptor_tests.cpp
@@ -1260,6 +1260,15 @@ BOOST_AUTO_TEST_CASE(descriptor_test)

 BOOST_AUTO_TEST_CASE(descriptor_older_warnings)
 {
+    {
+        FlatSigningProvider keys;
+        std::string err;
+        // Using after() with a large timestamp (> 65535)
+        auto descs = Parse("wsh(and_v(v:pk(0379e45b3cf75f9c5f9befd8e9506fb962f6a9d185ac87001ec44a8d3df8d4a9e3),after(1000000)))", keys, err, /*require_checksum=*/false);
+        BOOST_REQUIRE(!descs.empty());
+        BOOST_CHECK(descs[0]->Warnings().empty()); // Ensure the older() warning is really being applied only for this fragment
+    }
+
```

**Comment by Sjors** [comment]
@brunoerg thanks, I added your test against false positive warnings for `after()`, which passes.

fe06b92429206aee66d33c843195235f4bb27181  -> 5e9737ff493a96566f4fc11b1733b4b5a5393f6b:  [compare](https://github.com/bitcoin/bitcoin/compare/fe06b92429206aee66d33c843195235f4bb27181..5e9737ff493a96566f4fc11b1733b4b5a5393f6b)

**Review by brunoerg — APPROVED** [review]
reACK 5e9737ff493a96566f4fc11b1733b4b5a5393f6b

File: src/script/descriptor.h [hunk 4]
```diff
@@ -165,6 +165,9 @@ struct Descriptor {
      * @param[out] ext_pubs Any extended public keys
      */
     virtual void GetPubKeys(std::set<CPubKey>& pubkeys, std::set<CExtPubKey>& ext_pubs) const = 0;
+
+    // Semantic/safety warnings (includes subdescriptors).
```
Comment (pythcoiner) [inline src/script/descriptor.h]: nit (for consistency)
```suggestion
    /** Semantic/safety warnings (includes subdescriptors). */
```

File: src/script/miniscript.h [hunk 5]
```diff
@@ -7,8 +7,10 @@
 
 #include <algorithm>
 #include <compare>
+#include <concepts>
```
Comment (pythcoiner) [inline src/script/miniscript.h:10]: nit: not sure if those includes are stricly required?

File: test/functional/wallet_importdescriptors.py [hunk 6]
```diff
@@ -58,6 +59,7 @@ def test_importdesc(self, req, success, error_code=None, error_message=None, war
         if 'warnings' in result[0]:
             observed_warnings = result[0]['warnings']
         assert_equal("\n".join(sorted(warnings)), "\n".join(sorted(observed_warnings)))
+        self.log.debug(result)
```
Comment (pythcoiner) [inline test/functional/wallet_importdescriptors.py:62]: nit: should we keep this debug log?

Comment (Sjors) [reply test/functional/wallet_importdescriptors.py:62]: Yes, it's only printed when you set the log level to debug and it's useful for debugging if the test breaks.

File: src/script/miniscript.h (hunk 5 above)
Comment (Sjors) [reply src/script/miniscript.h:10]: There's some sort of linter command that can check this, but I forgot which.

**Comment by pythcoiner** [comment]
tACK 5e9737ff49 code review + test importing few "Liana" descriptor with timelocks > 65535

File: src/script/miniscript.h (hunk 5 above)
Comment (pythcoiner) [reply src/script/miniscript.h:10]: build success even w/o those 2 (added) includes on my side

Comment (Sjors) [reply src/script/miniscript.h:10]: That doesn't really say much, because indirect includes will succeed but we try to avoid those. Though maybe not for std stuff?

File: src/script/descriptor.cpp [hunk 7]
```diff
@@ -1530,7 +1542,24 @@ class MiniscriptDescriptor final : public DescriptorImpl
...
+    {
+        // Traverse miniscript tree for unsafe use of older()
+        miniscript::ForEachNode(*m_node, [&](const miniscript::Node<uint32_t>& node) {
+            if (node.fragment == miniscript::Fragment::OLDER) {
+                const uint32_t raw = node.k;
+                const uint32_t value_part = raw & ~CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG;
+                if (value_part > CTxIn::SEQUENCE_LOCKTIME_MASK) {
+                    const bool is_time = (raw & CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG) != 0;
+                    if (is_time) {
+                        m_warnings.push_back(strprintf("older(%u - 1<<22) > 65535 is unsafe", raw));
```
Comment (achow101) [inline src/script/descriptor.cpp]: In 5e9737ff493a96566f4fc11b1733b4b5a5393f6b "wallet: warn against accidental unsafe older() import"

This warning is basically incomprehensible. It would be better to actually write out what it means, i.e. "time based relative locktime > 65535 is unsafe"

File: src/script/miniscript.h (hunk 5 above)
Comment (Sjors) [reply src/script/miniscript.h:10]: The Tidy CI job runs IWYU and doesn't complain: https://github.com/bitcoin/bitcoin/actions/runs/17605378583/job/50015040929?pr=33135#step:9:6218

File: src/script/descriptor.cpp (hunk 7 above)
Comment (Sjors) [reply src/script/descriptor.cpp]: I went for a slight variant: `relative locktime > 65535 * 512 seconds is unsafe`

**Review by scgbckbone — COMMENTED** [review]
What is the reason for allowing to import `older(65536)` ? I do not see rationale here, only mention of "previous version" that disallowed importing. I'd prefer older version if that is the case. Complete prohibition, even with `unsafe`. Importing `older(65536)` is not what user wants if resulting script is `older(1)` anyways.

**Comment by Rob1Ham** [comment]
I have a question as it relates to relative timelocks using the older() fragment if one were programming an epoch time based timelock.

The smallest value that can be used to have the miniscript compiler interpret a relative timelock is older(4194305) (calculated by following the BIP68 spec of: 1 |= (1 << 22)). This is a 1 unit timelock of duration 512 seconds.

The maximum value for a relative epoch timelock is older(4259839) which is 65,535 unit timelock, resulting in 33,554,431 seconds, or 388 days.

For example, if you wanted a 4 day epoch time based timelock, you could use older(4194979) (512 seconds maps neatly onto 4 days, which is 512 * 675 = 345600 seconds = 4 days.

This was something I stumbled upon 2 years ago going deeper into the miniscript compiler, I personally am not using relative timelocks with epoch time right now (and don't know anyone who does), but wanted to call this out.

**Comment by scgbckbone** [comment]
Thanks Rob. I completely forget about that 22nd bit to change to time-based lock.

To update my previous comment: anything without consensus meaning should not be allowed to import. 

Only `older(1 - 65535)` & `older(4194305 - 4259839)` should be importable.

**Comment by Sjors** [comment]
As I mentioned in the PR description, there are applications - including the lightning protocol - that use these extra bits. I don't know if they use descriptors internally to represent them, but if they do, then banning these values would mean they can't import these descriptors.

There's also nothing in the BIP that bans (or even discourages or warns about) these values, so we wouldn't be compatible with other wallets.

**Comment by pythcoiner** [comment]
reACK [fb72cc3](https://github.com/bitcoin/bitcoin/pull/33135/commits/fb72cc33be570d12fc6b76146fc89047e58f5aaf)

**Review by brunoerg — APPROVED** [review]
reACK fb72cc33be570d12fc6b76146fc89047e58f5aaf

**Comment by achow101** [comment]
ACK fb72cc33be570d12fc6b76146fc89047e58f5aaf

**Comment by achow101** [comment]
Silent merge conflict?

```
Running 2 test cases...
./test/descriptor_tests.cpp(1272): fatal error: in "descriptor_tests/descriptor_older_warnings": critical check !descs.empty() has failed

*** 1 failure is detected in the test module "Bitcoin Core Test Suite"
```

**Comment by Sjors** [comment]
Got the same error when I rebased, working on a fix...

**Comment by Sjors** [comment]
Rebased and improved the test error logging:

```cpp
    // A safe boundary value should yield no warnings.
    {
        FlatSigningProvider keys;
        std::string err;
        auto descs = Parse("wsh(and_v(v:pk(0379e45b3cf75f9c5f9befd8e9506fb962f6a9d185ac87001ec44a8d3df8d4a9e3),older(65535)))", keys, err, /*require_checksum=*/false);
        BOOST_REQUIRE_MESSAGE(!descs.empty(), err);
```

This fails with:

```
test/descriptor_tests.cpp:1265: Entering test case "descriptor_older_warnings"
test/descriptor_tests.cpp:1272: fatal error: in "descriptor_tests/descriptor_older_warnings": Invalid characters in payload
```

I'm confused 😕

**Comment by Sjors** [comment]
#33914 fixes this. I based this PR on it, though if that takes too long to and I could also just wrap the test string literals in `std::string(...)`.

**Comment by Sjors** [comment]
Lost the first commit in that rebase, let's try again...

**Comment by Sjors** [comment]
Rebased after #33914 so the test should pass again.

File: src/script/descriptor.cpp [hunk 8]
```diff
@@ -1537,7 +1549,24 @@ class MiniscriptDescriptor final : public DescriptorImpl
...
+            if (node.fragment == miniscript::Fragment::OLDER) {
+                const uint32_t raw = node.k;
+                const uint32_t value_part = raw & ~CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG;
+                if (value_part > CTxIn::SEQUENCE_LOCKTIME_MASK) {
+                    const bool is_time = (raw & CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG) != 0;
+                    if (is_time) {
+                        m_warnings.push_back(strprintf("relative locktime > 65535 * 512 seconds is unsafe"));
+                    } else {
+                        m_warnings.push_back(strprintf("older(%u) > 65535 is unsafe", raw));
+                    }
```
Comment (rkrux) [inline src/script/descriptor.cpp]: Nit: some consistency in the warning format would be easier on the eyes.

```diff
diff --git a/src/script/descriptor.cpp b/src/script/descriptor.cpp
index 8289120164..132d695a1a 100644
--- a/src/script/descriptor.cpp
+++ b/src/script/descriptor.cpp
@@ -1557,11 +1557,11 @@ public:
                 const uint32_t raw = node.k;
                 const uint32_t value_part = raw & ~CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG;
                 if (value_part > CTxIn::SEQUENCE_LOCKTIME_MASK) {
-                    const bool is_time = (raw & CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG) != 0;
-                    if (is_time) {
-                        m_warnings.push_back(strprintf("relative locktime > 65535 * 512 seconds is unsafe"));
+                    const bool is_time_based = (raw & CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG) != 0;
+                    if (is_time_based) {
+                        m_warnings.push_back(strprintf("time-based relative locktime: older(%u) > (65535 * 512) seconds is unsafe", raw));
                     } else {
-                        m_warnings.push_back(strprintf("older(%u) > 65535 is unsafe", raw));
+                        m_warnings.push_back(strprintf("height-based relative locktime: older(%u) > 65535 blocks is unsafe", raw));
                     }
                 }
             }
```

**Review by rkrux — APPROVED** [review]
lgtm ACK 189437a3dedefce3945ab2a8c05785eb283c2c6f

Shared a non-blocking nit.

**Review by brunoerg — APPROVED** [review]
reACK 189437a3dedefce3945ab2a8c05785eb283c2c6f

File: src/script/descriptor.cpp (hunk 8 above)
Comment (Sjors) [reply src/script/descriptor.cpp]: Taken (and updated the test)

**Review by rkrux — APPROVED** [review]
lgtm re-ACK 76c092ff805833a9adf84f669f0455bc2e0bba8b

**Comment by Sjors** [comment]
@brunoerg @pythcoiner can you re-review the latest push?

**Review by brunoerg — APPROVED** [review]
reACK 76c092ff805833a9adf84f669f0455bc2e0bba8b

**Comment by pythcoiner** [comment]
reACK 76c092ff80

**Comment by achow101** [comment]
ACK 76c092ff805833a9adf84f669f0455bc2e0bba8b
