### PR TITLE
depends: Fix `zeromq` build on OpenBSD

### PR DESCRIPTION
**Pull request by hebasto**
On the master branch @ 66e82dc90c598c9c42ff980693ef5367a845e1d0, the `zeromq` package fails to build on OpenBSD 7.5:
```
[ 19%] Building CXX object CMakeFiles/objects.dir/src/io_thread.cpp.o
/home/hebasto/bitcoin/depends/work/build/amd64-unknown-openbsd7.5/zeromq/4.3.5-df5b1b9f936/src/io_thread.cpp:14:22: error: static_cast from 'std::nullptr_t' to 'poller_t::handle_t' (aka 'int') is not allowed
    _mailbox_handle (static_cast<poller_t::handle_t> (NULL))
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

This [regression](https://github.com/bitcoin/bitcoin/pull/29723#issuecomment-2261513105) was overlooked by me in https://github.com/bitcoin/bitcoin/pull/29723.

This PR fixes the issue by backporting an upstream commit from https://github.com/zeromq/libzmq/pull/4659.

### CODE REVIEW

**Comment by hebasto** [comment]
Friendly ping @theStack  :)

**Review by theStack — APPROVED** [review]
tACK 89b1d5c818a33440c0c497aa78721fb9b0af35a5

Verified on OpenBSD 7.5 that building the zeromq depends build via
```
$ gmake -C depends NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_NATPMP=1 NO_UPNP=1 NO_USDT=1 NO_BDB=1
```
fails on master (same error message as in the PR description) and succeeds on the PR branch. Checked also that the introduced patch matches https://github.com/zeromq/libzmq/pull/4659/commits/f9a798c9fb26124206ae2a3e72225f6d9dd8c646.
