### ISSUE TITLE
Unable to compile on native macOS after 3caee16946575e71e90ead9ac531f5a3a1259307

### ISSUE THREAD

**Issue by rex4539** [bitcoin/bitcoin#20259]
Introduced with 3caee16946575e71e90ead9ac531f5a3a1259307.

```
CXXLD    qt/test/test_bitcoin-qt
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_xonly_pubkey_parse", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_schnorrsig_verify", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bitcoin-tx] Error 1
make[2]: *** Waiting for unfinished jobs....
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_xonly_pubkey_parse", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_schnorrsig_verify", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bitcoin-wallet] Error 1
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_xonly_pubkey_parse", referenced from:
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_xonly_pubkey_parse", referenced from:
  "_secp256k1_xonly_pubkey_parse", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_schnorrsig_verify", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_schnorrsig_verify", referenced from:
  "_secp256k1_schnorrsig_verify", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bench/bench_bitcoin] Error 1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bitcoind] Error 1
make[2]: *** [bitcoin-node] Error 1
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_xonly_pubkey_parse", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_schnorrsig_verify", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/test_bitcoin] Error 1
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_xonly_pubkey_parse", referenced from:
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
Undefined symbols for architecture x86_64:
  "_secp256k1_xonly_pubkey_tweak_add_check", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_schnorrsig_verify", referenced from:
  "_secp256k1_xonly_pubkey_parse", referenced from:
  "_secp256k1_xonly_pubkey_parse", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::CheckPayToContract(XOnlyPubKey const&, uint256 const&, bool) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
  "_secp256k1_schnorrsig_verify", referenced from:
  "_secp256k1_schnorrsig_verify", referenced from:
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
      XOnlyPubKey::VerifySchnorr(uint256 const&, Span<unsigned char const>) const in libbitcoin_consensus.a(libbitcoin_consensus_a-pubkey.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [qt/test/test_bitcoin-qt] Error 1
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bitcoin-gui] Error 1
make[2]: *** [qt/bitcoin-qt] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by MarcoFalke** [comment]
Does `make distclean` help?

**Comment by rex4539** [comment]
Indeed it does :)

**Comment by sipa** [comment]
Yeah, this is expected unfortunately.
