### PR TITLE
threading: remove ancient CRITICAL_SECTION macros

### PR DESCRIPTION
**Pull request by theuni**
Now that #32467 is merged, the only remaining usage of our old `CRITICAL_SECTION` macros (other than tests) is in `getblocktemplate()` and it can safely be replaced with a `REVERSE_LOCK`.

This PR makes that replacement, replaces the old `CRITICAL_SECTION` macro usage in tests, then deletes the macros themselves.

~While testing this a few weeks ago, I noticed that `REVERSE_LOCK` does not currently work properly with our thread-safety annotations as after the `REVERSE_LOCK` is acquired, clang still believes that the mutex is locked. #32465 fixes this problem. Without that fix, this PR would potentially allow a false-negative if code were added in the future to this chunk of `getblocktemplate` which required `cs_main` to be locked.~

~I added a test for the reverse lock here in the form of a compiler warning in `reverselock_tests.cpp` to simulate that possibility. This PR will therefore cause a new warning (and should fail a warnings-as-errors ci check) until #32465 is merged and this is rebased on top of it.~

Edit: Rebased on top of #32465, so this should now pass tests.

### CODE REVIEW

**Comment by theuni** [comment]
As mentioned in the description, failing tests are just demonstrating the borked REVERSE_LOCK fixed by #32465.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by fjahr** [comment]
Concept ACK

**Review by furszy — COMMENTED** [review]
Code review ACK ee98ad2e9d2be9a72c15c5c1ef93bfd3d5ed015c, will hop into #32465.

**Comment by theuni** [comment]
Pushed a small additional commit that removes a now-unnecessary template instantiation. Just a little janitorial work, but it will make some future changes more obviously correct.

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/6734127736553472?logs=ci#L3223
```bash
[12:12:21.305] /ci_container_base/src/test/reverselock_tests.cpp:23:9: error: cannot call function 'AssertLockNotHeldInline' while mutex 'mutex' is held [-Werror,-Wthread-safety-analysis]
[12:12:21.305]    23 |         AssertLockNotHeld(mutex);
[12:12:21.305]       |         ^
[12:12:21.305] /ci_container_base/src/sync.h:141:31: note: expanded from macro 'AssertLockNotHeld'
[12:12:21.305]   141 | #define AssertLockNotHeld(cs) AssertLockNotHeldInline(#cs, __FILE__, __LINE__, &cs)
[12:12:21.305]       |                               ^
[12:12:21.305] 1 error generated.
```

**Comment by theuni** [comment]
> https://cirrus-ci.com/task/6734127736553472?logs=ci#L3223
> 
> ```shell
> [12:12:21.305] /ci_container_base/src/test/reverselock_tests.cpp:23:9: error: cannot call function 'AssertLockNotHeldInline' while mutex 'mutex' is held [-Werror,-Wthread-safety-analysis]
> [12:12:21.305]    23 |         AssertLockNotHeld(mutex);
> [12:12:21.305]       |         ^
> [12:12:21.305] /ci_container_base/src/sync.h:141:31: note: expanded from macro 'AssertLockNotHeld'
> [12:12:21.305]   141 | #define AssertLockNotHeld(cs) AssertLockNotHeldInline(#cs, __FILE__, __LINE__, &cs)
> [12:12:21.305]       |                               ^
> [12:12:21.305] 1 error generated.
> ```

As expected :) From description:

> I added a test for the reverse lock here in the form of a compiler warning in reverselock_tests.cpp to simulate that possibility. This PR will therefore cause a new warning (and should fail a warnings-as-errors ci check) until https://github.com/bitcoin/bitcoin/pull/32465 is merged and this is rebased on top of it.

**Comment by fanquake** [comment]
@theuni want to rebase this now that #32465 is in?

**Comment by fanquake** [comment]
Put this on `30.0`.

**Comment by maflcko** [comment]
This is tagged for 30.0, but feature freeze is in less than two weeks, and it still needs rebase, so it'll likely miss the milestone.

**Comment by fanquake** [comment]
> This is tagged for 30.0, but feature freeze is in less than two weeks, and it still needs rebase, so it'll likely miss the milestone.

Feature freeze doesn't seem important here, given this isn't a feature; it's part of a cleanup of which the prior PRs have already landed, so landing this any time before branch off seems fine (assuming it gets rebased, have pinged @theuni).

File: src/rpc/mining.cpp [hunk 1]
```diff
@@ -704,7 +704,7 @@ static RPCHelpMan getblocktemplate()
     NodeContext& node = EnsureAnyNodeContext(request.context);
     ChainstateManager& chainman = EnsureChainman(node);
     Mining& miner = EnsureMining(node);
-    LOCK(cs_main);
+    WAIT_LOCK(cs_main, csmain_lock);
```
Comment (sedited) [inline src/rpc/mining.cpp:707]: Not really related to this PR, but I really don't like how long the scope of the lock is here. We could reduce this a bit by doing something like
```diff
diff --git a/src/rpc/mining.cpp b/src/rpc/mining.cpp
index b710c605bc..750ca72bb4 100644
--- a/src/rpc/mining.cpp
+++ b/src/rpc/mining.cpp
@@ -707,2 +706,0 @@ static RPCHelpMan getblocktemplate()
-    WAIT_LOCK(cs_main, csmain_lock);
-    uint256 tip{CHECK_NONFATAL(miner.getTip()).value().hash};
@@ -737,0 +736 @@ static RPCHelpMan getblocktemplate()
+            LOCK(cs_main);
@@ -775,0 +775,3 @@ static RPCHelpMan getblocktemplate()
+    WAIT_LOCK(cs_main, cs_main_lock);
+    uint256 tip{CHECK_NONFATAL(miner.getTip()).value().hash};
+
@@ -814 +816 @@ static RPCHelpMan getblocktemplate()
-            REVERSE_LOCK(csmain_lock, cs_main);
+            REVERSE_LOCK(cs_main_lock, cs_main);
```
but then going on to hold it through the entire marshalling block also does not seem ideal.

**Review by sedited — APPROVED** [review]
ACK 46ca7712cb5fcf759cfc9f4f32d74215c8c83763

**Comment by maflcko** [comment]
review ACK 46ca7712cb5fcf759cfc9f4f32d74215c8c83763 📌

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: review ACK 46ca7712cb5fcf759cfc9f4f32d74215c8c83763 📌
V2n3Eh8Fc5sBB4pkAgZwhO+niN3JRgn02KN6u3xaWJyYem/L+0JNJeiBY543bvMUZO6moB6cpFgOcoXMz3FDDA==
```

</details>

**Comment by fjahr** [comment]
Code review ACK 46ca7712cb5fcf759cfc9f4f32d74215c8c83763

**Review by furszy — COMMENTED** [review]
ACK 46ca7712cb5fcf759cfc9f4f32d74215c8c83763
