### PR TITLE
RPC/Wallet: Convert walletprocesspsbt to use options parameter

### PR DESCRIPTION
**Pull request by luke-jr**
`walletprocesspsbt` has a single logical positional argument and a bunch that only make sense as named options. Convert them to an actual options Object for a better positional API.

Retains backward compatibility for now.

### CODE REVIEW

**Comment by Aruto7709p** [comment]
bnb1p5tus3kyl8euzu385pwzcj00wu7rjkpq4x5mqr

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/24963/commits/31ffd7782bf241ca09c7e192769ae9506bd2352f

**Review by pk-b2 — APPROVED** [review]
ACK 31ffd7782bf241ca09c7e192769ae9506bd2352f

- Built branch locally and exercised various manual test using both versions of the RPC
- Verified that passed in arguments get accepted
- Throws error when passing in options argument + additional invalid arguments

**Comment by achow101** [comment]
tbh I prefer #19762 instead of having options objects, but I don't feel strongly either way about this PR.

**Comment by luke-jr** [comment]
>tbh I prefer https://github.com/bitcoin/bitcoin/pull/19762 instead of having options objects, but I don't feel strongly either way about this PR.

#19762 is complimentary to options objects, not an alternative to them.

**Comment by achow101** [comment]
There's a silent merge conflict with master.

```
wallet/rpc/spend.cpp: In function ‘RPCHelpMan wallet::walletprocesspsbt()’:
wallet/rpc/spend.cpp:1515:75: error: ‘OMITTED_NAMED_ARG’ is not a member of ‘RPCArg::Optional’
 1515 |                     {"options|sign", RPCArg::Type::OBJ, RPCArg::Optional::OMITTED_NAMED_ARG, "",
      |                                                                           ^~~~~~~~~~~~~~~~~
wallet/rpc/spend.cpp: In lambda function:
wallet/rpc/spend.cpp:1574:9: error: ‘RPCTypeCheckArgument’ was not declared in this scope
 1574 |         RPCTypeCheckArgument(options, UniValue::VOBJ);
      |         ^~~~~~~~~~~~~~~~~~~~
wallet/rpc/spend.cpp: In function ‘RPCHelpMan wallet::walletprocesspsbt()’:
wallet/rpc/spend.cpp:1619:5: error: no matching function for call to ‘RPCHelpMan::RPCHelpMan(<brace-enclosed initializer list>)’
 1619 |     };
      |     ^
In file included from wallet/rpc/spend.cpp:10:
./rpc/util.h:364:5: note: candidate: ‘RPCHelpMan::RPCHelpMan(std::string, std::string, std::vector<RPCArg>, RPCResults, RPCExamples, RPCMethodImpl)’
  364 |     RPCHelpMan(std::string name, std::string description, std::vector<RPCArg> args, RPCResults results, RPCExamples examples, RPCMethodImpl fun);
      |     ^~~~~~~~~~
./rpc/util.h:364:79: note:   no known conversion for argument 3 from ‘<brace-enclosed initializer list>’ to ‘std::vector<RPCArg>’
  364 |     RPCHelpMan(std::string name, std::string description, std::vector<RPCArg> args, RPCResults results, RPCExamples examples, RPCMethodImpl fun);
      |                                                           ~~~~~~~~~~~~~~~~~~~~^~~~
./rpc/util.h:362:5: note: candidate: ‘RPCHelpMan::RPCHelpMan(std::string, std::string, std::vector<RPCArg>, RPCResults, RPCExamples)’
  362 |     RPCHelpMan(std::string name, std::string description, std::vector<RPCArg> args, RPCResults results, RPCExamples examples);
      |     ^~~~~~~~~~
./rpc/util.h:362:5: note:   candidate expects 5 arguments, 6 provided
./rpc/util.h:359:7: note: candidate: ‘RPCHelpMan::RPCHelpMan(const RPCHelpMan&)’
  359 | class RPCHelpMan
      |       ^~~~~~~~~~
./rpc/util.h:359:7: note:   candidate expects 1 argument, 6 provided
./rpc/util.h:359:7: note: candidate: ‘RPCHelpMan::RPCHelpMan(RPCHelpMan&&)’
./rpc/util.h:359:7: note:   candidate expects 1 argument, 6 provided
```

**Comment by fanquake** [comment]
Drafted for now. Needs a PR description and rebasing to fix the merge conflict:
```bash
wallet/rpc/spend.cpp:1541:75: error: no member named 'OMITTED_NAMED_ARG' in 'RPCArg::Optional'
                    {"options|sign", RPCArg::Type::OBJ, RPCArg::Optional::OMITTED_NAMED_ARG, "",
                                                        ~~~~~~~~~~~~~~~~~~^
wallet/rpc/spend.cpp:1600:9: error: use of undeclared identifier 'RPCTypeCheckArgument'
        RPCTypeCheckArgument(options, UniValue::VOBJ);
        ^
2 errors generated.
```

**Comment by luke-jr** [comment]
Rebased

**Review by ryanofsky — COMMENTED** [review]
Light code review ACK baf99a9c789779e89e7684a550e16cf1fb7ce862

File: src/rpc/util.cpp [hunk 1]
```diff
@@ -720,8 +720,13 @@ UniValue RPCHelpMan::GetArgMap() const
...
         std::vector<std::string> arg_names = SplitString(arg.m_names, '|');
+        RPCArg::Type argtype = arg.m_type;
+        size_t arg_num = 0;
         for (const auto& arg_name : arg_names) {
-            push_back_arg_info(m_name, i, arg_name, arg.m_type);
+            if (!arg.m_type_per_name.empty()) {
+                argtype = arg.m_type_per_name.at(arg_num++);
+            }
+            push_back_arg_info(m_name, i, arg_name, argtype);
             if (arg.m_type == RPCArg::Type::OBJ_NAMED_PARAMS) {
```
[the remark this answers is not in the document]
Comment (luke-jr) [reply src/rpc/util.cpp]: Fixed

File: src/wallet/rpc/spend.cpp [hunk 2]
```diff
@@ -1547,17 +1547,24 @@ RPCHelpMan walletprocesspsbt()
...
-            "       \"DEFAULT\"\n"
-            "       \"ALL\"\n"
-            "       \"NONE\"\n"
-            "       \"SINGLE\"\n"
-            "       \"ALL|ANYONECANPAY\"\n"
-            "       \"NONE|ANYONECANPAY\"\n"
-            "       \"SINGLE|ANYONECANPAY\""},
-                    {"bip32derivs", RPCArg::Type::BOOL, RPCArg::Default{true}, "Include BIP 32 derivation paths for public keys if we know them"},
-                    {"finalize", RPCArg::Type::BOOL, RPCArg::Default{true}, "Also finalize inputs if possible"},
+                    {"options|sign", {RPCArg::Type::OBJ, RPCArg::Type::BOOL}, RPCArg::Optional::OMITTED, "",
```
[the remark this answers is not in the document]
Comment (luke-jr) [reply src/wallet/rpc/spend.cpp]: Done

**Comment by fanquake** [comment]
```bash
 2023-12-28T00:06:54.183352Z [scheduler] [util/thread.cpp:22] [TraceThread] scheduler thread exit
unknown location:0: fatal error: in "psbt_wallet_tests/parse_hd_keypath": NonFatalCheckError: Internal bug detected: !(param_type & POSITIONAL) || inner.m_opts.also_positional
rpc/util.cpp:536 (RPCHelpMan)
```

**Review by vincenzopalazzo — COMMENTED** [review]
I think the CI is complaing regarding the help command

```
stdout:
2023-12-28T22:14:56.493000Z TestFramework (INFO): PRNG seed is: 8647031483739335376
2023-12-28T22:14:56.493000Z TestFramework (INFO): Initializing test directory /ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231228_220750/rpc_help_5
2023-12-28T22:14:56.823000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
    self.run_test()
  File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/rpc_help.py", line 54, in run_test
    self.test_client_conversion_table()
  File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/rpc_help.py", line 72, in test_client_conversion_table
    raise AssertionError("RPC client conversion table ({}) and RPC server named arguments mismatch!\n{}".format(
AssertionError: RPC client conversion table (/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/src/rpc/client.cpp) and RPC server named arguments mismatch!
{('walletprocesspsbt', 1, 'bip32derivs'), ('walletprocesspsbt', 1, 'finalize')}
```

**Comment by luke-jr** [comment]
There we go, tests all happy now

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/24963/commits/f43f992b7318086859f710b920b4427e6c657fe8

**Review by ryanofsky — COMMENTED** [review]
Code review f43f992b7318086859f710b920b4427e6c657fe8. I think this looks pretty close, and the approach taken in this PR to preserves backwards compatibility seems pretty clean. I would have thought prior to this PR that we might need to break backwards compatibility to convert existing named parameters to options, but this is not the case. Two things I think should be improved:

1. Lack of enforcement for m_type_per_name vector. Right now the MatchesType implementation just checks if the parameter has any of the specified types, not if the parameter has the right type corresponding to its name. For example you could pass options=true and it would be accepted even though options is supposed to be an object. I left a suggestion to fix this.
2. Changes to RPCHelpMan::GetArgMap() seem unnecessary and don't actually affect dump_all_command_conversions output.

I think it could also be nice if this PR was expanded to make the same changes to createwallet as it is making walletprocesspsbt. This came up recently https://github.com/bitcoin/bitcoin/pull/29129#pullrequestreview-1804913032.

Some notes on how this PR works:

- The first commit just loosens up RPCArg type checking so it can accept multiple types (e.g. object and bool) for the same positional parameter. Inadvertently it also allows it to accept multiple types for the named parameters, which is probably not intended and not good in this case, but I suggested a possible fix below.
- The second commit takes advantage of less restrictive type checking in `walletprocesspsbt` to allow the second parameter to be either an options object or a bool, instead of just a bool, and updates the implementation to handle both these cases.
- The second commit also moves parameter definitions 2-5 into a nested options object.
- To retain backwards compatibility, the second commit adds the old parameters 3-5 as hidden parameters after the options object at position 2, so they can be passed by position. It also specifies `.also_positional = true` for each option to avoid errors about the outer parameters and inner options having duplicate names. And it raises a too many parameters error if these parameters are specified along with the options object.

File: src/rpc/util.cpp [hunk 3]
```diff
@@ -793,9 +793,15 @@ UniValue RPCHelpMan::GetArgMap() const
     for (int i{0}; i < int(m_args.size()); ++i) {
         const auto& arg = m_args.at(i);
         std::vector<std::string> arg_names = SplitString(arg.m_names, '|');
+        RPCArg::Type argtype = arg.m_type;
```
[the remark this answers is not in the document]
Comment (luke-jr) [reply src/rpc/util.cpp:796]: But if there's only one name here, it's unclear what name the bool type is for? Or we're assuming it can only be used as a positional param at that point?

[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/rpc/util.cpp:796]: re: https://github.com/bitcoin/bitcoin/pull/24963#discussion_r1467815704

> But if there's only one name here, it's unclear what name the bool type is for? Or we're assuming it can only be used as a positional param at that point?

Yes, that's a good point. The change I suggested to `wallet/rpc/spend.cpp` makes the code less clear, even if it is removes some code that is technically unnecessary. So your version is better.

In case anybody is following this though, the github comment this is responding to was mostly about `RPCHelpMan::GetArgMap`, which can still be simplified.

**Comment by achow101** [comment]
Are you still working on this?

**Comment by luke-jr** [comment]
CI failure appears to be a CI bug unrelated to this PR. I don't see a way to un-draft...

File: src/rpc/util.cpp [hunk 4]
```diff
@@ -846,13 +852,15 @@ UniValue RPCArg::MatchesType(const UniValue& request) const
...
     if (IsOptional() && request.isNull()) return true;
-    const auto exp_type{ExpectedType(m_type)};
-    if (!exp_type) return true; // nothing to check
+    for (auto type : m_type_per_name.empty() ? std::vector<RPCArg::Type>{m_type} : m_type_per_name) {
+        const auto exp_type{ExpectedType(type)};
+        if (!exp_type) return true; // nothing to check
 
-    if (*exp_type != request.getType()) {
-        return strprintf("JSON value of type %s is not of expected type %s", uvTypeName(request.getType()), uvTypeName(*exp_type));
+        if (*exp_type == request.getType()) {
```
[the remark this answers is not in the document]
Comment (luke-jr) [reply src/rpc/util.cpp:865]: Fixed bug in this and added it, along with tests

**Comment by luke-jr** [comment]
Rebased to workaround CI bugs for now (is someone going to fix them?)

**Comment by achow101** [comment]
> Rebased to workaround CI bugs for now (is someone going to fix them?)

Considering that CI is failing immediately after a `walletprocesspsbt` call, and that RPC is being changed in this PR, I'm inclined to think that it's probably not a CI issue.

**Comment by luke-jr** [comment]
>Considering that CI is failing immediately after a walletprocesspsbt call, and that RPC is being changed in this PR, I'm inclined to think that it's probably not a CI issue.

Yes, there was a new issue introduced by the added commits too. But there was also a CI issue: it failed to merge into master before building.

**Comment by luke-jr** [comment]
Assuming the remaining CI failure is #31307

**Review by ryanofsky — APPROVED** [review]
Code review ACK 40143bafb52927eb40ecfde0ea722934213eb902.

This is a pretty simple change to the RPC framework that should make it easy to add new options to RPCs like [createwallet](https://github.com/bitcoin/bitcoin/pull/29129#pullrequestreview-1804913032) that currently accept too many positional parameters, without having to increase the number of positional parameters they already accept.

Without this PR, the only ways to add a new options to an RPC like `createwallet` without breaking backward compatibility are to add the option as a top-level parameter, where it can be specified as:

```bash
bitcoin-cli -named createwallet wallet_name option_name=option_value
bitcoin-cli createwallet wallet_name null null null null null null null option_value
```

or to add a new OBJ_NAMED_PARAMS parameter where it can be specified as:

```bash
bitcoin-cli -named createwallet wallet_name option_name=option_value
bitcoin-cli createwallet wallet_name null null null null null null null '{"option_name": "option_value"}'
```

The first approach is unsafe because it allows `option_value` to be specified by position instead of name in an error prone way when there are too many positions. The second approach is safe, but not very appealing because it still increases the number of positional arguments, and doesn't display the old and new arguments in the same way in the documentation, or allow them to be accessed in the same way in the RPC implementation.

By contrast, this PR allows completely modernizing RPCs that accept a lot of positional parameters while retaining backwards compatibility. E.g. it would allow a new `createwallet` option to be passed as:

```bash
bitcoin-cli -named createwallet wallet_name option_name=option_value
bitcoin-cli createwallet wallet_name '{"option_name": "option_value"}'
```

And it would show all options consistently in the documentation, and give callers ability to pass every option as a named parameter or as a field in an options object.

Notes on how this PR works:

- The first commit "RPC: Support specifying different types for param aliases" (04d7864764e46cd8625b9a5a1ccd271512c6bb64) allows multiple types to be specified for parameters if the parameters have aliases, like: `"options|sign", {RPCArg::Type::OBJ_NAMED_PARAMS, RPCArg::Type::BOOL}`. It enforces that the number of types is the same as the number of aliases. Previously it was only possible to specify a single type for a parameter, even if it had multiple aliases. Additionally:
  - It updates the `RPCArg::MatchesType()` function used to validate incoming RPC requests to accept any of the types specified in the list, instead of just the first type. If named parameters were passed, this commit does not enforce that the specific type corresponding to the named alias was used, but the third commit fixes this.
  - It fixes `RPCHelpMan::GetArgMap()`, which is used to generate `bitcoin-cli -regtest help dump_all_command_conversions` output, to output the correct type for each alias, instead just outputting the first type.
- The second commit updates `walletprocesspsbt` to take advantage of the support for alias types added in the first commit. Specifically:
  - It changes the second parameter from `"sign"` accepting a bool to `"options|sign"` accepting an options object or a bool.
  - It copies former definitions of the parameters 2-5 ("sign", "sighashtype", "bip32derivs", "finalize") into the options definition so they can be passed as options or named parameters by RPC clients.
  - It keeps parameters 3-5 intact but marks them as hidden. Keeping these parameters allows clients to continue to pass them as positional parameters instead of as named parameters or options fields.
  - It marks all the options `{.also_positional = true}` to avoid errors from the RPC framework about options and parameters having duplicate names.
  - It updates the implementation of `walletprocesspsbt` to read options and named arguments out of the `options` object, but keeps code for reading positional arguments out of the `params` object if no `options` object is present.
- The third commit adds stricter type checking to ensure that if a parameter has multiple aliases and each alias has an assigned type, and the parameter is passed by name instead of position, the parameter must have the expected type for that name. This prevents a bug described https://github.com/bitcoin/bitcoin/pull/24963#discussion_r1450616033, and the fourth commit just adds a test for this bug.

**Comment by achow101** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing work on this, please leave a comment so that it can be reopened.

Marking as up for grabs.
