### PR TITLE
bench: Add missing pow.h header

### PR DESCRIPTION
**Pull request by laanwj**
Fix a build error introduced in #13219.

```
.../bitcoin/src/bench/block_assemble.cpp:42:13:error: use of undeclared identifier 'CheckProofOfWork'
    while (!CheckProofOfWork(block->GetHash(), block->nBits, Params().GetConsensus())) {
```

### CODE REVIEW

**Comment by sipa** [comment]
ACK cec84c2f1a359676ac4d206f10ee936d4d7db9b5, build is broken without it.

**Comment by MarcoFalke** [comment]
ACK, seems this was a silent merge conflict with 5b35b9276858f6841ab4b688883461f602e9f937

**Comment by MarcoFalke** [comment]
Also my lack of using iwyu
