### PR TITLE
[amount] Add tests and make GetFee() monotonic

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@laanwj raised the concern that it should be mentioned in the release notes, but I would be really surprised if anyone was [relying](https://xkcd.com/1172/) on this behavior.

Current master fails the unit test (see travis):

```cpp
test/amount_tests.cpp(23): error: check feeRate.GetFee(0) == 0 has failed [1000 != 0]
test/amount_tests.cpp(32): error: check feeRate.GetFee(0) == 0 has failed [123 != 0]
test/amount_tests.cpp(33): error: check feeRate.GetFee(8) == 1 has failed [123 != 1]

**Comment by laanwj** [comment]
I'd like some more details here, you left the opening post empty!

What do you mean with "make GetFee() monotonic", and what purpose does this have?

**Comment by MarcoFalke** [comment]
> What do you mean with "make GetFee() monotonic",

The current behavior of the code is `CFeeRate(1000).GetFee(0) == 1000` and `CFeeRate(123).GetFee(8) == 123`, which is obviously wrong. This was introduced in d88af56 (#4465).

> monotonic

Please have a look at the following sketches:

`master`:
screenshot from 2016-03-17 17-53-24

`patch`:
screenshot from 2016-03-17 17-53-45

> what purpose does this have

The purpose of this pull is to get rid of unexpected behavior.

File: src/amount.cpp [hunk 1]
```diff
@@ -19,10 +19,10 @@ CFeeRate::CFeeRate(const CAmount& nFeePaid, size_t nSize)
 
 CAmount CFeeRate::GetFee(size_t nSize) const
 {
-    CAmount nFee = nSatoshisPerK*nSize / 1000;
+    CAmount nFee = nSatoshisPerK * nSize / 1000;
 
-    if (nFee == 0 && nSatoshisPerK > 0)
-        nFee = nSatoshisPerK;
+    if (nFee == 0 && nSize != 0 && nSatoshisPerK != 0)
+        nFee = CAmount(1);
```
Comment (MarcoFalke) [inline src/amount.cpp]: Ideally this code should be removed entirely, but I don't see that happening soon taking into account the limited effect and the substantial amount of refactoring in wallet code.

**Comment by laanwj** [comment]
Thanks for the plots, that makes things a lot more clear. That outlier around 0 clearly looks wrong.
Yes, this change makes sense.

utACK

**Comment by jonasschnelli** [comment]
utACK

File: src/amount.cpp [hunk 2]
```diff
@@ -19,10 +19,10 @@ CFeeRate::CFeeRate(const CAmount& nFeePaid, size_t nSize)
 
 CAmount CFeeRate::GetFee(size_t nSize) const
 {
-    CAmount nFee = nSatoshisPerK*nSize / 1000;
+    CAmount nFee = nSatoshisPerK * nSize / 1000;
 
-    if (nFee == 0 && nSatoshisPerK > 0)
-        nFee = nSatoshisPerK;
+    if (nFee == 0 && nSize != 0 && nSatoshisPerK != 0)
```
Comment (morcos) [inline src/amount.cpp]: I don't understand the `!= 0` here.  Why would you turn a small negative fee rate into a small positive one?
@sdaftuar can comment on the vagaries of negative CFeeRates, they are already fraught with peril, but they can exist at least via `prioritisetransaction`.  I think it would be much safer to keep this as `> 0`.

Comment (MarcoFalke) [inline src/amount.cpp]: Thanks, I didn't know negative rates exist.

Added tests for negative rates in another commit.

Comment (MarcoFalke) [inline src/amount.cpp]: @morcos Actually, I don't think we support negative amounts for `nSatoshisPerK` right now. 64-bit platforms will convert `nSatoshisPerK` to `unsiged` (`size_t`). 32-bit platforms will convert `nSize` to signed `CAmount`.

Comment (morcos) [inline src/amount.cpp]: TBH, I'm not sure exactly what happens.  Although I thought nSatoshiPerK was a CAmount which is an int64_t.  I'm not sure it's meant to support negative rates, but at some point we need to either make sure they are supported or prevent against them.  All I'm suggesting is that right now we don't change any edge case behavior around negative amounts, b/c its already fragile.

Comment (MarcoFalke) [inline src/amount.cpp]: > at some point we need to either make sure they are supported or prevent against them

I think we agree on this but I'd rather not do it as part of this pull.

**Comment by morcos** [comment]
@MarcoFalke thanks.

utACK fad13b1

**Comment by jtimon** [comment]
Somehow I missed this. Even if it's kind of meaningless now, "posthumous utACK".

I'll test this now by rebasing https://github.com/bitcoin/bitcoin/compare/master...jtimon:0.12.99-feerate and repeating the rpc tests locally. I still don't know them all that well, does it make sense for me to run the all the rpc tests with the -extended label for anything that could be affected by changes in CFeeRate ?

File: src/test/amount_tests.cpp [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+    BOOST_CHECK_EQUAL(feeRate.GetFee(1), 1);
+    BOOST_CHECK_EQUAL(feeRate.GetFee(121), 121);
+    BOOST_CHECK_EQUAL(feeRate.GetFee(999), 999);
+    BOOST_CHECK_EQUAL(feeRate.GetFee(1e3), 1e3);
+    BOOST_CHECK_EQUAL(feeRate.GetFee(9e3), 9e3);
+
+    feeRate = CFeeRate(123);
+    // Truncates the result, if not integer
+    BOOST_CHECK_EQUAL(feeRate.GetFee(0), 0);
+    BOOST_CHECK_EQUAL(feeRate.GetFee(8), 1); // Special case: returns 1 instead of 0
```
Comment (jtimon) [inline src/test/amount_tests.cpp]: Now the special case is less special, but, yes, is still a special case, so thank you for documenting it.

**Comment by laanwj** [comment]
> Somehow I missed this. Even if it's kind of meaningless now, "posthumous utACK".

No, it's not meaningless. Reviewing commits that are merged is also essential.

**Comment by MarcoFalke** [comment]
> repeating the rpc tests locally

I can't think of any way your results should be different by rebasing onto this pull. This only has an effect if the size and/or fee rate is really small.

**Comment by jtimon** [comment]
> I can't think of ...

Well, I can think of them. That doesn't mean they make sense, see #7731
