### PR TITLE
Updated Windows build doc for WSL/Xenial workaround

### PR DESCRIPTION
**Pull request by sipsorcery**
An update to the Windows build document that provides workarounds for the broken 64 bit mingw32 cross compiler on WSL/Xenial.

This update is an alternative to pull request #11437. While that pull request takes a valid approach by stating building on WSL should be avoided I think it is more useful to give Windows developers a workaround option. 

The instructions have been tested on:
- Ubuntu 14.04 and 64 bit mingw32 tool chain
- Ubuntu 16.04 and 64 bit mingw32 tool chain
- Ubuntu 17.04 and 64 bit mingw32 tool chain
- Windows Subsystem for Linux (Windows 10 OS Build 15063.608) and 32 bit mingw32 tool chain
- Windows Subsystem for Linux (Windows 10 OS Build 15063.608) and 64 bit mingw32 tool chain

Related items:
- Serious incompatibility problems w/ newer mingw-64 on Ubuntu #8653
- `-fstack-protector-all` triggers crashes in mingw-w64 5.3.1 #8732
- Windows build appears broken on WSL (buntu okay) #10269
- Compilation error for windows target #11437

### CODE REVIEW

File: doc/build-windows.md [hunk 1]
```diff
@@ -66,12 +69,32 @@ See also: [dependencies.md](dependencies.md).
...
 
-To build executables for Windows 64-bit, install the following dependencies:
+THe first step is to install the mingw-w64 cross-compilation tool chain. Due to different Ubuntu
+packages for each distribution and problems with the Xenial packages the steps for each are different.
+
+Ubuntu Trusty 14.04:
+
+	sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
+
+Ubuntu Xenial 16.04 and Windows Subsystem for Linux (*)(**):
```
Comment (MeshCollider) [inline doc/build-windows.md]: Use footnotes (`[^1]`) rather than `*` because `*` is used for formatting. (Same in other places).

File: doc/build-windows.md [hunk 2]
```diff
@@ -6,8 +6,11 @@ Below are some notes on how to build Bitcoin Core for Windows.
 Most developers use cross-compilation from Ubuntu to build executables for
 Windows. This is also used to build the release binaries.
 
-Currently only building on Ubuntu Trusty 14.04 is supported.
-Other versions are unsupported or known to be broken (e.g. Ubuntu Xenial 16.04).
+Building on Ubuntu Trusty 14.04 is recommended.
+It is possible to build on Ubuntu Xenial 16.04. Follow the Windows Subsystem for Linux
+steps since it uses the same Ubuntu version.
+Building on Ubuntu Zesty 17.04 has been verified to work using the same stesp as for
```
Comment (MeshCollider) [inline doc/build-windows.md]: `stesp` -> `steps`

File: doc/build-windows.md [hunk 3]
```diff
@@ -107,3 +135,20 @@ as they appear in the release `.zip` archive. This can be done in the following
 way. This will install to `c:\workspace\bitcoin`, for example:
 
     make install DESTDIR=/mnt/c/workspace/bitcoin
+
+Footnotes
+---------
+
+[^1] There is currently a bug in the 64 bit mingw-w64 cross compiler packaged for WSL/Ubuntu Xenial 16.04 that
```
Comment (MeshCollider) [inline doc/build-windows.md]: Colon after `[^1]` :)

File: doc/build-windows.md [hunk 4]
```diff
@@ -66,12 +69,32 @@ See also: [dependencies.md](dependencies.md).
...
+	sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
+
+Ubuntu Xenial 16.04 and Windows Subsystem for Linux ([^1][^2]):
+
+    sudo apt install software-properties-common
+    sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu zesty universe"
+    sudo apt update
+    sudo apt upgrade
+    sudo wget http://archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils_2.28-3ubuntu1_amd64.deb
+    sduo dpkg -i binutils_2.28-3ubuntu1_amd64.deb
```
Comment (MeshCollider) [inline doc/build-windows.md]: Sudo

File: doc/build-windows.md [hunk 5]
```diff
@@ -83,10 +106,15 @@ Then build using:
 
 To build executables for Windows 32-bit, install the following dependencies:
 
-    sudo apt-get install g++-mingw-w64-i686 mingw-w64-i686-dev 
+    sudo apt install g++-mingw-w64-i686 mingw-w64-i686-dev
```
Comment (MeshCollider) [inline doc/build-windows.md]: The trailing whitespace failure is the end of this line I think. Sorry for so many little reviews :) Remember to squash all your commits at the end

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/5e31c532e2fa1f2261ed0f94739a57cf8d5ee7e9
Will hopefully have some time to test this soon

**Comment by NicolasDorier** [comment]
thank you, this will save me so much time! Trying this.

**Comment by molxyz** [comment]
There's a misspelled word:  `sduo dpkg -i binutils_2.28-3ubuntu1_amd64.deb`

**Comment by sipsorcery** [comment]
@molxyz have you got the latest version? That typo was fixed.

**Comment by molxyz** [comment]
@sipsorcery Ah yes.. sorry I forgot to refresh the page, got it now. This is great, thank you.

**Comment by NicolasDorier** [comment]
Still another problem on my WSL, probably unrelated though.

```
configure: error: No working boost sleep implementation found.
```

I think I give up with WSL, keeping my docker :/

**Comment by sipsorcery** [comment]
@NicolasDorier I did see that error once or twice and I believe it was around the same time as I was getting the error about the std::mutex header missing. I haven't seen it for a while though and I'd estimate I've re-installed and built bitcoin on WSL at least half a dozen times in the last week. My suggestion would be to either completely uninstall WSL using lxrun /uninstall /full and then reinstall or at the very least clean the dependencies, including boost, from your bitcoin source tree with git clean -x -f -d.

File: doc/build-windows.md [hunk 6]
```diff
@@ -6,8 +6,11 @@ Below are some notes on how to build Bitcoin Core for Windows.
 Most developers use cross-compilation from Ubuntu to build executables for
 Windows. This is also used to build the release binaries.
 
-Currently only building on Ubuntu Trusty 14.04 is supported.
-Other versions are unsupported or known to be broken (e.g. Ubuntu Xenial 16.04).
+Building on Ubuntu Trusty 14.04 is recommended.
+It is possible to build on Ubuntu Xenial 16.04. Follow the Windows Subsystem for Linux
```
Comment (laanwj) [inline doc/build-windows.md]: Should mention early that 16.04 produces incorrect code, so that people don't get started with it and come to the conclusion later that it's broken.

Comment (sipsorcery) [reply doc/build-windows.md]: There is no bad code providing the mingw32 x-compiler on wsl/xenial is updated as per the instructions in the doc.

File: doc/build-windows.md [hunk 7]
```diff
@@ -6,8 +6,11 @@ Below are some notes on how to build Bitcoin Core for Windows.
...
+steps since it uses the same Ubuntu version.
```
Comment (MarcoFalke) [inline doc/build-windows.md]: This should probably mention that building on WSL currently is by following the building on Xenial notes. (not the other way round)

File: doc/build-windows.md [hunk 8]
```diff
@@ -6,8 +6,11 @@ Below are some notes on how to build Bitcoin Core for Windows.
...
+Building on Ubuntu Zesty 17.04 has been verified to work using the same steps as for
+Ubuntu Trusty 14.04.
```
Comment (MarcoFalke) [inline doc/build-windows.md]: I don't think this is true, given that there are two different sections. One for trusty, one for zesty.

File: doc/build-windows.md [hunk 9]
```diff
@@ -6,8 +6,11 @@ Below are some notes on how to build Bitcoin Core for Windows.
 Most developers use cross-compilation from Ubuntu to build executables for
 Windows. This is also used to build the release binaries.
 
-Currently only building on Ubuntu Trusty 14.04 is supported.
-Other versions are unsupported or known to be broken (e.g. Ubuntu Xenial 16.04).
+Building on Ubuntu Trusty 14.04 is recommended.
+It is possible to build on Ubuntu Xenial 16.04. Follow the Windows Subsystem for Linux
+steps since it uses the same Ubuntu version.
+Building on Ubuntu Zesty 17.04 has been verified to work using the same steps as for
```
Comment (MarcoFalke) [inline doc/build-windows.md]: I think you can write "17.04 or later", since 17.10 seems to work as well with the same steps.

File: doc/build-windows.md [hunk 10]
```diff
@@ -66,12 +69,29 @@ See also: [dependencies.md](dependencies.md).
...
-To build executables for Windows 64-bit, install the following dependencies:
+The first step is to install the mingw-w64 cross-compilation tool chain. Due to different Ubuntu
+packages for each distribution and problems with the Xenial packages the steps for each are different.
+
+Ubuntu Trusty 14.04:
 
     sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
 
-Then build using:
+Ubuntu Xenial 16.04 and Windows Subsystem for Linux ([^1][^2]):
```
Comment (MarcoFalke) [inline doc/build-windows.md]: Might want to remove WSL here, since it will no longer be true when the user runs a different ubuntu version than xenial in their WSL.

File: doc/build-windows.md [hunk 11]
```diff
@@ -66,12 +69,29 @@ See also: [dependencies.md](dependencies.md).
...
+
+    sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev software-properties-common
+    sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu zesty universe"
+    sudo apt update
+    sudo apt upgrade
+    sudo update-alternatives --config x86_64-w64-mingw32-g++ # Set the default mingw32 g++ compiler option to posix.
+
+Ubuntu Zesty 17.04 ([^2]):
+
+    sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
```
Comment (MarcoFalke) [inline doc/build-windows.md]: µnit: This installation step is the same for all three version. Might as well mention it only once, mention that no further steps are needed on trusty and that other versions require some workarounds: ...

File: doc/build-windows.md [hunk 12]
```diff
@@ -107,3 +132,20 @@ as they appear in the release `.zip` archive. This can be done in the following
 way. This will install to `c:\workspace\bitcoin`, for example:
 
     make install DESTDIR=/mnt/c/workspace/bitcoin
+
+Footnotes
```
Comment (MarcoFalke) [inline doc/build-windows.md]: Maybe ot: For some reason GitHub doesn't insert links to the footnotes for me.

**Review by maflcko — COMMENTED** [review]
Concept ACK. Some feedback and a nit.

File: doc/build-windows.md (hunk 10 above)
Comment (sipsorcery) [reply doc/build-windows.md]: Wouldn't it be better to leave it there and update the doc when WSL gets updated? I suspect the majority of devs reading this doc will be looking for WSL instructions.

File: doc/build-windows.md (hunk 12 above)
Comment (sipsorcery) [reply doc/build-windows.md]: Looks like that footnote is not supported on github. According to a comment on this SO [answer](https://stackoverflow.com/questions/25579868/how-to-add-footnotes-to-github-flavoured-markdown) that format is used on GitLab. I'll use the alternative suggestion of anchor links.

File: doc/build-windows.md [hunk 13]
```diff
@@ -66,12 +70,33 @@ See also: [dependencies.md](dependencies.md).
...
     sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
 
-Then build using:
+Ubuntu Trusty 14.04:
+
+    No further steps required
+
+Ubuntu Xenial 16.04 and Windows Subsystem for Linux <sup>[1](#footnote1),[2](#footnote2)</sup>:
+
+    sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev software-properties-common
```
Comment (MarcoFalke) [inline doc/build-windows.md]: µnit: Can remove the "g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"

File: doc/build-windows.md [hunk 14]
```diff
@@ -66,12 +70,33 @@ See also: [dependencies.md](dependencies.md).
...
+    sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu zesty universe"
+    sudo apt update
+    sudo apt upgrade
+    sudo update-alternatives --config x86_64-w64-mingw32-g++ # Set the default mingw32 g++ compiler option to posix.
+
+Ubuntu Zesty 17.04 <sup>[2](#footnote2)</sup>:
 
+    sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
```
Comment (MarcoFalke) [inline doc/build-windows.md]: µnit: Can remove this line.

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

File: doc/build-windows.md (hunk 12 above)
Comment (molxyz) [reply doc/build-windows.md]: This is great. I have tested on my WSL Ubuntu Xenial 16.04 several times and it works, but I have a question regarding this part: 
>sudo update-alternatives --config x86_64-w64-mingw32-g++

>There are 2 choices for the alternative x86_64-w64-mingw32-g++ (providing /usr/bin/x86_64-w64-mingw32-g++).

>  Selection    Path                                   Priority   Status
>------------------------------------------------------------
>  0            /usr/bin/x86_64-w64-mingw32-g++-win32   60        auto mode
>  1            /usr/bin/x86_64-w64-mingw32-g++-posix   30        manual mode
>  2            /usr/bin/x86_64-w64-mingw32-g++-win32   60        manual mode

The only choice is "1" to get bitcoin compiled successfully, the other choices cause errors in "make".  Is there a reason to leave 3 choices? Sorry, I'm still new to this and the choices made me confused at first until I tried them all.  
Thank you for doing this, I'm thrilled to be able to compile bitcoin on WSL again! :D

Comment (MarcoFalke) [reply doc/build-windows.md]: Note that "0" is the default and the options are 1 (posix) and 2 (win32).

**Comment by laanwj** [comment]
Needs rebase for #11437.

**Comment by sipsorcery** [comment]
#11437 is largely mutually exclusive to this update. It steers devs away from using WSL or Ubuntu 16 due to the non-standard build steps required. This pull request provides those non-standard build steps.

**Comment by NicolasDorier** [comment]
I made a fresh ubuntu WSL 16.04, was unable to install boost, I tried all sort of incantation without success...

```
libboost-all-dev : Depends: libboost-tools-dev but it is not going to be installed
                    Depends: libboost-atomic-dev but it is not going to be installed
                    Depends: libboost-chrono-dev but it is not going to be installed
                    Depends: libboost-context-dev but it is not going to be installed
                    Depends: libboost-coroutine-dev but it is not going to be installed
                    Depends: libboost-date-time-dev but it is not going to be installed
                    Depends: libboost-exception-dev but it is not going to be installed
                    Depends: libboost-fiber-dev but it is not going to be installed
                    Depends: libboost-graph-dev but it is not going to be installed
                    Depends: libboost-graph-parallel-dev but it is not going to be installed
                    Depends: libboost-iostreams-dev but it is not going to be installed
                    Depends: libboost-locale-dev but it is not going to be installed
                    Depends: libboost-log-dev but it is not going to be installed
                    Depends: libboost-math-dev but it is not going to be installed
                    Depends: libboost-mpi-dev but it is not going to be installed
                    Depends: libboost-mpi-python-dev but it is not going to be installed
                    Depends: libboost-python-dev but it is not going to be installed
                    Depends: libboost-random-dev but it is not going to be installed
                    Depends: libboost-regex-dev but it is not going to be installed
                    Depends: libboost-serialization-dev but it is not going to be installed
                    Depends: libboost-signals-dev but it is not going to be installed
                    Depends: libboost-test-dev but it is not going to be installed
                    Depends: libboost-timer-dev but it is not going to be installed
                    Depends: libboost-type-erasure-dev but it is not going to be installed
                    Depends: libboost-wave-dev but it is not going to be installed
```

**Comment by sipsorcery** [comment]
@NicolasDorier what type of VM, Ubuntu 16 version and platform (x86 or x64)?

I have run the install steps using the latest source form the bitcoin git repo on VMWare Workstation with Ubuntu 16.04.3 Server x64 without any problems and resulting in working Windows executables. 

I'm happy to check other permutations if you let me know what your configuration is.

**Comment by NicolasDorier** [comment]
This is x64.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Problems are on boost... I can't seems to be able to fetch boost for some reason.

**Comment by MarcoFalke** [comment]
Needs rebase on current master to solve merge conflicts.

**Comment by sipsorcery** [comment]
@MarcoFalke merge conflict is from #11437 which is largely mutually exclusive to this update. 

It's a question of whether to steers devs away from building on WSL/ Ubuntu 16 using non-standard build steps required or only recommend Ubuntu 14 & 17 as per #11437.

**Comment by MarcoFalke** [comment]
@sipsorcery Agree. Though, we can not merge your pull if there are merge conflicts (even if only minor).

I don't have WSL, so I can't help with testing and recommendations. How you solve the merge conflict is pretty much up to you. It doesn't matter if you use `-Xtheirs` or `-Xours` or solve it manually ...

**Comment by sipsorcery** [comment]
@MarcoFalke no worries, I've removed the conflict by pushing my change to the build-windows.md file on top of trunk.

**Comment by MeshCollider** [comment]
Just want to point out that your commit isn't associated with your GitHub account currently, you might have used a different email address? You might want to commit with the same email address so your account gets the credit :)

**Comment by sipsorcery** [comment]
@NicolasDorier is there any reason you're attempting to install boost packages with apt? 

If you only need boost for a bitcoin build the required includes and libraries get installed as part of the build steps that download and compile all the required dependencies.

cd depends
make HOST=x86_64-w64-mingw32

**Comment by NicolasDorier** [comment]
yes, I need it because I need to run python tests on WSL.

**Comment by sipa** [comment]
The python tests don't need boost?

**Comment by NicolasDorier** [comment]
They don't but I need to compile bitcoind as a linux binary, which need boost.

**Comment by sipa** [comment]
@NicolasDorier Using the depends build will do all that.

**Comment by sipsorcery** [comment]
On a related note the [Windows 10 Fall Creators Update](https://www.wired.com/story/how-to-get-windows-10-fall-creators-update/) gets released tomorrow (17 Oct 2017) and contains a [major update to WSL](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-wsl-in-windows-10-fall-creators-update/). The main update is that WSL will now be deployed as a Windows Store App and  users will need to choose from different Linux distros; currently Ubuntu (Xenial), openSUSE and SUSE Linux Enterprise Server.

**Comment by NicolasDorier** [comment]
my understanding was that

```
cd depends
make HOST=x86_64-w64-mingw32
```

will just install the deps for making a windows binary. I was unaware it was also adding the libboost dependencies for linux build. Trying that now.

**Comment by sipa** [comment]
`make HOST=x86_64-unknown-linux-gnu` will do a build of dependencies for Linux build on x86_64.

**Comment by NicolasDorier** [comment]
Trying. Maybe this is something to add as exception of Xenial 17.04 in the doc, since installing package with apt-get is not available?

**Comment by NicolasDorier** [comment]
Ok now

```
WARNING: 'automake-1.14' is missing on your system.
```

So `make HOST=x86_64-unknown-linux-gnu` does not run, I ran apt-get of autotools.

**Comment by sipsorcery** [comment]
@NicolasDorier the automake error seems to be generated in the protobuf dependency build. The same error was mentioned in #10269. I'm guessing it's triggered when the apt packages line up in a certain way.

The suggested workaround, which also worked for me in the past, is:

`make HOST=x86_64-unknown-linux-gnu AUTOMAKE=:`

**Comment by rebroad** [comment]
tested ACK

**Comment by laanwj** [comment]
@rebroad Thanks for testing

**Comment by josephky** [comment]
@NicolasDorier I had the same issue, what ended up working was the following:
make HOST=x86_64-w64-mingw32 AUTOCONF=: AUTOHEADER=: AUTOMAKE=: ACLOCAL=:

also I had found that downloading the repo natively from inside WSL was less likely to break things in the build than downloading it in Windows and then working on it from WSL

**Comment by MeshCollider** [comment]
Post-merge tested ACK on clean install of 64-bit Win10 Home 1709 build 16299.64

**Comment by NicolasDorier** [comment]
@josephky ha yes. There are some git config magic to do so git on Windows does not convert LF to CRLF on checkout. And that it convert CRLF to LF on check-in. I did that long time ago, now it works fine.

It was only `core.autocrlf=input` if I remember...
