### PR TITLE
Improve node network test

### PR DESCRIPTION
**Pull request by jnewbery**
Fixes race condition in the node_network_limited test case introduced in #11740. Also tidies up the test and removes redundant duplicate tests.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
utACK 9bb57c926665ecfeb61b185563757b3bd3452cbe
Would prefer a squash.

**Comment by jnewbery** [comment]
> Would prefer a squash.

Was just updating the original comment to say "Split into small commits for ease of review, but can be squashed into a single commit for merge." :slightly_smiling_face:

**Comment by laanwj** [comment]
utACK.

I'm ok with leaving this as seperate commits, however ecfe41d fails on its own:
```
2017-12-17 10:40:04.636000 TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/store/orion/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "test/functional/node_network_limited.py", line 52, in run_test
    assert_equal(self.getSignaledServiceFlags(), 1036)  # 1036 == 0x40C == 0100 0000 1100
AttributeError: 'NodeNetworkLimitedTest' object has no attribute 'getSignaledServiceFlags'
```

**Comment by promag** [comment]
Yeah, separate commits make it easy to review IMO.

**Comment by jnewbery** [comment]
> however ecfe41d fails on its own

Thanks @laanwj . Now fixed.

**Comment by MarcoFalke** [comment]
Sorry, needs rebase. Didn't notice there was already a pull open to fixup this test.

**Comment by jnewbery** [comment]
rebased

**Comment by MarcoFalke** [comment]
Thanks for the quick rebase. Checked that each commit does what it advertises and the tests pass. The refactoring will make the test twice as fast.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

utACK ee5efad6cfb60d8efe678b1a9285a73d265ea79b
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJaOXMsAAoJENLqSFDnUoslz6MP/iidLoKZOE32Nyl/Sbxf8+WN
BOQyFIZtXVarlLu3CiPfQId+lvaVlBPMRU0JEmp4JF0KAqWUsEgYphlQ2R0SBuvK
QnKiBJ0P4XazREr/yHVPTgog2S/SehfDN7hWwVcGrpyX1ryf1xV6RhCZIfGfxX8w
BLVB2+S1DZDwzClfax7hZYf1KYNoQIeTyQRd67HJ+5tpxISM56HJGZh58v/9zowg
nsaDA0Sz2HngjRP0sm5MXq2aFEbUT4VpHuMwt9xT48n9TqcwVMc3euUrKHNLeHS+
JP8T/1owhD6JMegfhKiT+wLvvvmBk6l71zrWxQfUnxiYIo1yL9FFYdKDCPja+DXB
oGHFHH8DMzPZ7RJGJdajaVZjHfNTLOkgflV8utFWvQk54Pq6ChyPmbmuw801XsWD
rIsQeU1C18rwWdADlkDk1Q2yPiYpc8htW9BVJGBNVbq9+ol7BYqUzpBLHEuhm4Kp
5ZS2C1dHNiyzb7vifGlWFvbkWnP/afievVOoGkqQ3D9NYSaQH3gXbzcWbwZZB1ye
vM2PxZ2hVcC7VbmKu1u6QwVMzGCQRl+aFp0P44uhRJ3QxCSc15JeUDLF9ATcR5px
AtSEo0ibPXMK9GcmU1vAcL1WlxhbrtlVg5kEIvKJE82JM5O3LTkfs3+J+UvS+zv1
bHZmiWFPNNDTxQ0lvbU4
=Rjh4
-----END PGP SIGNATURE-----
