### PR TITLE
tests: reset fIsBareMultisigStd after bare-multisig tests

### LINKED ISSUE #18015: Gitian-built unit tests fail on windows
Current master:

```
test_bitcoin.exe

Running 389 test cases...

test/script_p2sh_tests.cpp(200): error: in "script_p2sh_tests/set": txTo[1].IsStandard

test/script_p2sh_tests.cpp(200): error: in "script_p2sh_tests/set": txTo[2].IsStandard

test/script_p2sh_tests.cpp(200): error: in "script_p2sh_tests/set": txTo[3].IsStandard
```

https://github.com/bitcoin/bitcoin/blame/master/src/test/script_p2sh_tests.cpp#L200

### PR DESCRIPTION
**Pull request by fanquake**
Fixes: #18015

The bug this fixes is two-part.

1. The `fIsBareMultisigStd` global is being reused by other tests,
such as [script_p2sh_tests(set)](https://github.com/bitcoin/bitcoin/blob/master/src/test/script_p2sh_tests.cpp#L150), after being set to false.

2. The order our tests run in doesn't always? seem to be random,
which meant that the `script_p2sh` tests would only fail if they
were run in an order where the `transaction_tests` ran first,
mutating the `fIsBareMultisigStd` global.

This doesn't seem to happen when running make check, but if you
run `src/test/test_bitcoin and pass --random=99999`, the failure
in `script_p2sh` will occur (on most, but maybe not all systems):

```bash
src/test/test_bitcoin --random=99999
Running 389 test cases...
test/script_p2sh_tests.cpp:200: error: in "script_p2sh_tests/set": txTo[1].IsStandard
test/script_p2sh_tests.cpp:200: error: in "script_p2sh_tests/set": txTo[2].IsStandard
test/script_p2sh_tests.cpp:200: error: in "script_p2sh_tests/set": txTo[3].IsStandard

*** 3 failures are detected in the test module "Bitcoin Core Test Suite"
```

The new test for bare multisig was introduced in #17502.

### CODE REVIEW

**Comment by fanquake** [comment]
cc @theStack

**Comment by laanwj** [comment]
Good catch!
Concept ACK.

These kind of order-dependent stale state errors are kind of nasty, and hard to keep track of. Would it make sense to do this reset as part of the test fixture?

**Comment by fanquake** [comment]
> These kind of order-dependent stale state errors are kind of nasty, and hard to keep track of. Would it make sense to do this reset as part of the test fixture?

Yes, I think so. Tests really shouldn't be sharing any sort of global, mutable state, and them passing should not be dependent on the order in which they are run.

**Comment by MarcoFalke** [comment]
This can be fixed by parsing the command line arguments when the TestingSetup is constructed. Calling `AppInitParameterInteraction` will reset them to the default.

**Comment by practicalswift** [comment]
Concept ACK, but would be better if solved globally in `TestingSetup` rather than locally in `test_IsStandard`.

**Comment by MarcoFalke** [comment]
This is a nice one-line fix in the same fashion as we used to handle globals in unit tests in the past: If a unit-test changes them, they are reset by the same test to the value they were before.

As a follow-up it could make sense to normalize argument parsing and have the TestingSetup re-parse the arguments to set them to the default. Though, I suspect that that would be a larger change.

File: src/test/transaction_tests.cpp [hunk 1]
```diff
@@ -831,6 +831,7 @@ BOOST_AUTO_TEST_CASE(test_IsStandard)
     reason.clear();
     BOOST_CHECK(!IsStandardTx(CTransaction(t), reason));
     BOOST_CHECK_EQUAL(reason, "bare-multisig");
+    fIsBareMultisigStd = true;
```
Comment (MarcoFalke) [inline src/test/transaction_tests.cpp]:
```suggestion
    fIsBareMultisigStd = DEFAULT_PERMIT_BAREMULTISIG;
```

**Review by maflcko — APPROVED** [review]

File: src/test/transaction_tests.cpp (hunk 1 above)
Comment (Empact) [reply src/test/transaction_tests.cpp]: Alternatively, store the value at 824 and reload the stored value at 834.

Comment (fanquake) [reply src/test/transaction_tests.cpp]: Agree that using the constant is clearer.

**Comment by fanquake** [comment]
I've updated to use `DEFAULT_PERMIT_BAREMULTISIG` in place of `true`, and opened #18024 to follow up with the test setup suggestions.

**Review by theStack — COMMENTED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/18018/commits/1b96a3cd1ebe725896f59614903184289fe62c 
Sorry for introducing this bug.

**Comment by Empact** [comment]
Code Review ACK https://github.com/bitcoin/bitcoin/pull/18018/commits/1b96a3cd1ebe725896f59614903184289fe62cf8
