### PR TITLE
ci: fail iwyu job on compiler errors instead of silently logging them

### LINKED ISSUE #35361: ci: spurious output / errors in IWYU job
https://github.com/bitcoin/bitcoin/actions/runs/26292243180/job/77395542650:
Looks like IWYU is trying to run on libmultiprocess related code, and failing, but we shouldn't be trying to lint a subtree in the first place:
```bash
 /home/admin/actions-runner/_work/_temp/src/ipc/libmultiprocess/test/mp/test/test.cpp:5:10: fatal error: 'mp/test/foo.capnp.h' file not found
    5 | #include <mp/test/foo.capnp.h>
      |          ^~~~~~~~~~~~~~~~~~~~~

```
Along with other sporadic error output:
```bash
[1](https://github.com/bitcoin/bitcoin/actions/runs/26292243180/job/77395542650#step:11:11661)
error: no such file or directory: '/home/admin/actions-runner/_work/_temp/build/src/ipc/capnp/common.capnp.c++'
error: no input files
error: unable to handle compilation, expected exactly one compiler job in ''
error: no such file or directory: '/home/admin/actions-runner/_work/_temp/build/src/ipc/capnp/common.capnp.proxy-client.c++'
error: no input files
error: unable to handle compilation, expected exactly one compiler job in ''
error: no such file or directory: '/home/admin/actions-runner/_work/_temp/build/src/ipc/capnp/common.capnp.proxy-server.c++'
error: no input files
error: unable to handle compilation, expected exactly one compiler job in ''
error: no such file or directory: '/home/admin/actions-runner/_work/_temp/build/src/ipc/capnp/common.capnp.proxy-types.c++'
error: no input files
```

Ideally we'd have no sporadic errors / output, and wouldn't be trying to run linters/tools over subtrees at all.

I think that any errors in CI output/tooling should also be getting turned into real errors, so that they aren't missed/ignored?

### PR DESCRIPTION
**Pull request by David-Uka**
The IWYU invocation ends in `2>&1 || true`, added as a TODO when pipefail was introduced in fa99a3ccace. That `|| true` swallows the non-zero exit from a compiler `fatal error:` (for example a generated header that was not built before IWYU ran), so such errors only reached the raw CI logs and never failed the job, as reported in #35361.

Dropping the `|| true` lets pipefail propagate the failure, so the job fails loudly instead of passing silently. The recent header-generation fixes (#35468, #36228) mean the current master `iwyu` job is already free of such errors, so this does not turn CI red today.

Closes #35361.

### CODE REVIEW

**Review by hebasto — COMMENTED** [review]
Concept ACK.

cc @maflcko

File: ci/test/03_test_script.sh [hunk 1]
```diff
@@ -258,6 +258,18 @@ if [[ "${RUN_IWYU}" == true ]]; then
...
+    # iwyu_tool.py's non-zero exit is swallowed by "|| true" above, so a
+    # compiler "fatal error:" only ends up in the raw logs and never fails the
+    # job. IWYU cannot analyse a file that fails to compile, so treat any such
+    # error as a hard failure in both the enforced and non-enforced passes. A
+    # common cause is a generated header that was not built before IWYU ran.
+    # See https://github.com/bitcoin/bitcoin/issues/35361.
+    iwyu_fatal=$(grep -A1 "fatal error:" /tmp/iwyu_ci.out || true)
+    if [ -n "${iwyu_fatal}" ]; then
+      echo "${iwyu_fatal}"
+      echo "^^^ ⚠️ IWYU hit a compiler error and could not analyse the file above. If a generated header is missing, add its target to GOAL in ci/test/00_setup_env_native_iwyu.sh."
```
Comment (maflcko) [inline ci/test/03_test_script.sh:270]:
```suggestion
      echo "^^^ ⚠️ Failure generated from IWYU. IWYU hit a compiler error and could not analyse the file above. If a generated header is missing, add its target to GOAL in ci/test/00_setup_env_native_iwyu.sh."
```

nit: Could adjust the error message, so that the bot can read (https://github.com/maflcko/DrahtBot/blob/7554887cadb7c8fb614a278feef14ae399d125ce/webhook_features/src/features/ci_status.rs#L188) it too?

**Review by maflcko — APPROVED** [review]
lgtm, seems ugly to grep for "fatal error", but seems better to fail loudly then, instead of silently passing.

**Comment by maflcko** [comment]
> Those errors were only ever printed to the raw CI logs and never failed the job, because `iwyu_tool.py`'s non-zero exit is swallowed by `|| true`. That is how they went unnoticed for so long.

Actually, I don't think this is true. This was ignored due to pipefail not being set.

I set that in fa99a3ccace and added the `|| true` as a "TODO".

So I think the better fix would be to just remove the `|| true` now?

**Comment by David-Uka** [comment]
Good catch, thanks. Dropped the `|| true` so pipefail fails the job.

File: ci/test/03_test_script.sh [hunk 2]
```diff
@@ -256,7 +256,7 @@ if [[ "${RUN_IWYU}" == true ]]; then
              -Xiwyu --check_also='*/interfaces/*\.h' \
              -Xiwyu --check_also='*/primitives/transaction_identifier\.h' \
              -Xiwyu --check_also='*/rpc/protocol\.h' \
-             2>&1 || true
+             2>&1
     } | tee /tmp/iwyu_ci.out
```
Comment (maflcko) [inline ci/test/03_test_script.sh]:
```suggestion
     | tee /tmp/iwyu_ci.out
```

can remove the `{}`?

**Comment by David-Uka** [comment]
Applying just the suggestion leaves the opening `{` unbalanced (and `| tee` then needs a `\` on the preceding `2>&1`). Did you mean to drop the braces entirely and pipe `iwyu_tool.py ... 2>&1` straight into `tee`?

**Comment by maflcko** [comment]
```diff
diff --git a/ci/test/03_test_script.sh b/ci/test/03_test_script.sh
index b8bd0dd..ddc5949 100755
--- a/ci/test/03_test_script.sh
+++ b/ci/test/03_test_script.sh
@@ -243,9 +243,8 @@ if [[ "${RUN_IWYU}" == true ]]; then
 
   run_iwyu() {
     mv "${BASE_BUILD_DIR}/$1" "${BASE_BUILD_DIR}/compile_commands.json"
-    {
-      python3 /include-what-you-use/mapgen/iwyu-mapgen-clang-intrin.py --lang imp "$("clang-${IWYU_LLVM_V}" -print-resource-dir)/include" > "${BASE_BUILD_DIR}/clang.intrinsics.imp"
-      python3 /include-what-you-use/iwyu_tool.py \
+    python3 /include-what-you-use/mapgen/iwyu-mapgen-clang-intrin.py --lang imp "$("clang-${IWYU_LLVM_V}" -print-resource-dir)/include" > "${BASE_BUILD_DIR}/clang.intrinsics.imp"
+    python3 /include-what-you-use/iwyu_tool.py \
              -p "${BASE_BUILD_DIR}" "${MAKEJOBS}" -- \
              -Xiwyu --cxx17ns \
              -Xiwyu --mapping_file="${BASE_ROOT_DIR}/contrib/devtools/iwyu/bitcoin.core.imp" \
@@ -256,8 +255,7 @@ if [[ "${RUN_IWYU}" == true ]]; then
              -Xiwyu --check_also='*/interfaces/*\.h' \
              -Xiwyu --check_also='*/primitives/transaction_identifier\.h' \
              -Xiwyu --check_also='*/rpc/protocol\.h' \
-             2>&1
-    } | tee /tmp/iwyu_ci.out
+             2>&1 | tee /tmp/iwyu_ci.out
     python3 "/include-what-you-use/fix_includes.py" --nosafe_headers < /tmp/iwyu_ci.out
     python3 -c '
 import runpy

**Comment by David-Uka** [comment]
Applied your diff, thanks.

**Comment by maflcko** [comment]
lgtm ACK 622817f097d68cb1a59004ca7c115110d8bf64a0

**Comment by hebasto** [comment]
CI fails: https://github.com/bitcoin/bitcoin/actions/runs/35634651503/job/106763289406

**Comment by maflcko** [comment]
https://github.com/bitcoin/bitcoin/actions/runs/35634651503/job/106763289406?pr=36235#step:11:10912

```
include-what-you-use: /usr/lib/llvm-23/include/llvm/Support/Casting.h:656: decltype(auto) llvm::dyn_cast(From*) [with To = clang::UsingShadowDecl; From = const clang::NamedDecl]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
```

Maybe it should be minimized/bisected/reported/fixed upstream?

**Comment by David-Uka** [comment]
Localized it: IWYU aborts on a `clang::UsingShadowDecl` while analyzing the libmultiprocess subtree (`src/ipc/libmultiprocess/include/mp/proxy.h` and the `mp/test` TUs) — a single, deterministic abort. Looks like an upstream IWYU/llvm-23 bug rather than our code. I can report it upstream.

For this PR, would you prefer I exclude the libmultiprocess subtree from the IWYU compile DB (its output is already `git restore`d, so nothing is lost) to keep the job green while the upstream bug is open, or hold this until it's fixed upstream?

**Comment by hebasto** [comment]
> Localized it: IWYU aborts on a `clang::UsingShadowDecl` while analyzing the libmultiprocess subtree (`src/ipc/libmultiprocess/include/mp/proxy.h` and the `mp/test` TUs) — a single, deterministic abort. Looks like an upstream IWYU/llvm-23 bug rather than our code. I can report it upstream.

It's a generated source file for me:
```console
$ include-what-you-use -std=c++20 -Ibuild/src/ipc/libmultiprocess/include build/src/ipc/libmultiprocess/test/mp/test/foo.capnp.c++
include-what-you-use: /usr/lib/llvm-23/include/llvm/Support/Casting.h:656: decltype(auto) llvm::dyn_cast(From*) [with To = clang::UsingShadowDecl; From = const clang::NamedDecl]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
Aborted (core dumped)
```

**Comment by hebasto** [comment]
> ... would you prefer I exclude the libmultiprocess subtree from the IWYU compile DB...

See https://github.com/bitcoin/bitcoin/pull/36252.

**Comment by David-Uka** [comment]
Thanks, #36252 is the right fix — it drops the crashing libmultiprocess sources from the IWYU DB. Reviewed and ACK'd it. Once it lands I'll rebase this on top; CI should then be green.

**Comment by maflcko** [comment]
There should be no need to rebase. A maintainer can just re-run the CI  after the fix and it will turn green by itself.

Edit:

> Looks like an upstream IWYU/llvm-23 bug rather than our code. I can report it upstream.

Jup, a minimized repro could be reported.

**Comment by hebasto** [comment]
> https://github.com/bitcoin/bitcoin/actions/runs/35634651503/job/106763289406?pr=36235#step:11:10912
> 
> ```
> include-what-you-use: /usr/lib/llvm-23/include/llvm/Support/Casting.h:656: decltype(auto) llvm::dyn_cast(From*) [with To = clang::UsingShadowDecl; From = const clang::NamedDecl]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
> ```
> 
> Maybe it should be minimized/bisected/reported/fixed upstream?

See https://github.com/include-what-you-use/include-what-you-use/issues/2120.
