### PR TITLE
wallet: Fix `CWalletTx` malleated transaction metadata sync

### PR DESCRIPTION
**Pull request by achow101**
`SyncMetaData` is intended to handle the case of malleated transactions by copying the metadata from a presumed original transaction to all of the malleations of that transaction. However, it did not do this correctly, leading to both a crash that can be reached during `bumpfee`, and failing to actually copy the metadata to some malleated transactions.

The crash was reachable by having both the original transaction and a malleation of it in the wallet, then calling `bumpfee` on the original, and then calling `bumpfee` on the malleation. Calling `bumpfee` on the malleation would result in an assertion failure in `MarkReplaced`, hitting `Assert(!wtx.m_replaced_by_txid);`. This is reached since adding the RBF to the wallet causes a metadata sync between the original and the malleation, which copies `m_replaced_by_txid`. `MarkReplaced` is called soon afterwards, resulting in the crash. This is fixed by syncing the metadata after `MarkReplaced` sets `replaced_by_txid` during the RBF of the original transaction so that `bumpfee` refuses to bump the malleation in the first place as it will check `m_replaced_by_txid` before bumping.

The other issue is that if a RBF transaction is malleated, `SyncMetaData` was not copying the metadata from the original RBF transaction to the malleation.

These are fixed by changing `SyncMetaData` to find all of the malleations of a transaction rather than all of the conflicts and simplifying how it is called. Additionally, `CWalletTx::IsEquivalentTo` is used by `SyncMetaData` to determine whether a transaction is a malleation, and this PR pulls in https://github.com/bitcoin/bitcoin/pull/32723#issuecomment-3028112892 to make it explicitly clear which fields it is actually checking to determine the equivalence. Lastly, `SyncMetaData` is renamed to `SyncMalleatedTxMetadata` and `IsEquivalntTo` renamed to `IsMalleation` to clarify that these functions are for handling malleated txs.

The last 2 commits of this PR adds tests for these cases, and the first commit a test for basic `SyncMalleatedTxMetadata` functionality that should not change here.

### CODE REVIEW

File: src/primitives/transaction.h [hunk 1]
```diff
@@ -343,9 +349,17 @@ class CTransaction
...
     }
 
-    friend bool operator==(const CTransaction& a, const CTransaction& b)
+    bool Equals(const CTransaction& other, const EqualsOptions opts = {}) const
     {
-        return a.GetWitnessHash() == b.GetWitnessHash();
+        return nLockTime == other.nLockTime &&
+            version == other.version &&
+            vout == other.vout &&
+            std::ranges::equal(vin, other.vin, [&opts](const CTxIn self, const CTxIn other) {
```
Comment (jeanpablojp) [inline src/primitives/transaction.h:357]: could take these by reference here (but feel free to ignore)

**Review by jeanpablojp — COMMENTED** [review]
tACK fb59e6086531e5c54185984bc56a8bbed7cc1df0

Reproduced the crash on the merge base, it does abort. On the head the second bumpfee is refused.

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -721,44 +721,91 @@ void CWallet::Close()
...
+    }
+
+    auto it = txs.begin();
+    const CWalletTx* copy_from;
+    if (sync_from) {
+        copy_from = &wtx;
+    } else {
+        // When not sync_from, we want all the malleated wallet transactions to have the same metadata as
+        // the oldest. txs is sorted by nOrderPos already, so copy from the first one.
+        copy_from = *it;
```
Comment (vicjuma) [inline src/wallet/wallet.cpp:793]: What are the chances of actually dereferencing an empty set here? Probably checking `txs.empty()` might help before resorting to this

Comment (achow101) [reply src/wallet/wallet.cpp:793]: It should never happen. The provided `wtx` should always be in the set, and that is enforced by an `Assert` above.

**Comment by jeanpablojp** [comment]
I noticed that bumping the malleation instead of the original and then restarting the node loses the `replaced_by_txid` marker on both txs, and a second `bumpfee` is accepted afterwards.

`MarkReplaced` only persists the bumped tx, and on load the set re-syncs from the oldest one's stale record.

**Comment by achow101** [comment]
> I noticed that bumping the malleation instead of the original and then restarting the node loses the `replaced_by_txid` marker on both txs, and a second `bumpfee` is accepted afterwards.

Nice catch. Added to the test and a commit to fix.

**Comment by jeanpablojp** [comment]
re-ACK 740b3848e322f782b4382c641fe8be5aeb0f5580

**Comment by rkrux** [comment]
Concept ACK 740b384

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -721,44 +721,81 @@ void CWallet::Close()
...
+        for (auto& it = range.first; it != range.second; ++it) {
+            txin_conflicts.emplace(it->second);
+        }
+        // wtx should always be a candidate as this function is called after AddToSpends
+        Assert(txin_conflicts.contains(wtx.GetHash()));
+        if (first) {
+            candidate_malleated_txids = std::move(txin_conflicts);
+            first = false;
+            continue;
+        }
```
Comment (furszy) [inline src/wallet/wallet.cpp]: nit: can remove `first` and do a `candidate_malleated_txids.empty()` check here. After the first round, `candidate_malleated_txids` will no longer be empty.

File: src/wallet/wallet.cpp [hunk 4]
```diff
@@ -721,44 +721,81 @@ void CWallet::Close()
...
+        std::set<Txid> intersection;
+        std::set_intersection(
+            candidate_malleated_txids.begin(), candidate_malleated_txids.end(),
+            txin_conflicts.begin(), txin_conflicts.end(),
+            std::inserter(intersection, intersection.end())
+        );
+        if (intersection.empty()) {
+            // There are no transactions that have exactly the same inputs
+            return;
```
Comment (furszy) [inline src/wallet/wallet.cpp]: isn't this unreachable as the intersection will always contain wtx id? We call this after marking output as spends, so the wtx id should appear in all inputs `mapTxSpends.equal_range` vector

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -721,44 +721,81 @@ void CWallet::Close()
...
-        copyTo->m_message = copyFrom->m_message;
-        copyTo->m_comment = copyFrom->m_comment;
-        copyTo->m_comment_to = copyFrom->m_comment_to;
-        copyTo->m_replaces_txid = copyFrom->m_replaces_txid;
-        copyTo->m_replaced_by_txid = copyFrom->m_replaced_by_txid;
-        copyTo->m_messages = copyFrom->m_messages;
-        copyTo->m_payment_requests = copyFrom->m_payment_requests;
+    // Get the actual transactions, sorted by insertion order
+    std::set<CWalletTx*, WalletTxOrderComparator> txs;
+    for (const Txid& txid : candidate_malleated_txids) {
```
Comment (furszy) [inline src/wallet/wallet.cpp]: possible speedup: could store the ordering-wise lowest tx inside `candidate_malleated_txids` in the first loop, and before doing this loop, make a quick "IsMetadataEmpty()" check (which check against all fields except `nTimeSmart`), returning early if it is empty.

**Review by furszy — COMMENTED** [review]
Nice work, the crash is annoying.

Spent some time thinking if there was a faster and friendlier way of doing this and think I found one. This is the overall branch https://github.com/furszy/bitcoin-core/commits/pr35975 . Feel free to just push the branch here if you like it.

The main change is on the second commit c2bc5a66bdf2204a7ecb259426097fc397192385, because I suffered reading it a bit and thought that could also run faster. The new one furszy/bitcoin-core@36d2f22c44b8c1eb5a8f307e2c6fb7413db80fd8 takes advantage of the fact that all variants spend wtx's first input, so a single `mapTxSpends` lookup finds all candidates and the per-input intersection is not needed anymore.

Other than that, with `GetMalleatedVariants` decoupled in the commit mentioned above, the `MarkReplaced` change 267ce83e697e59e7a427654c30d84f5f65bb7515 can be written simpler furszy/bitcoin-core@661f8f0a6384e8bef9ee17ce74539df3d1fcf259

Then, lastly, while was there, couldn't contain myself from simplifying 8852df11e99b7eec033db7f6b21c552a209de12c to furszy/bitcoin-core@5149588e220ad06d29a1e237d7da4b08ed0b7671 and furszy/bitcoin-core@45031e5b4fc52770b159b83a3b6784770f6732cc .

**Comment by achow101** [comment]
Taken the suggestions

**Review by furszy — COMMENTED** [review]
Some extra coverage to squash in the last commit:

```patch
diff --git a/test/functional/wallet_txn_clone.py b/test/functional/wallet_txn_clone.py
--- a/test/functional/wallet_txn_clone.py	(revision 1b1e5f3b3621d8d4e7ec2d5cd4a382c4a5be165b)
+++ b/test/functional/wallet_txn_clone.py	(date 1789053048451)
@@ -171,21 +171,28 @@
         wallet = self.nodes[0].get_wallet_rpc("metadata_clone")
         def_wallet = self.nodes[0].get_wallet_rpc(self.default_wallet_name)
 
-        # Make non-segwit UTXOs that can be malleated
-        for _ in range(5):
-            def_wallet.sendtoaddress(wallet.getnewaddress(address_type="legacy"), 1)
+        # Make non-segwit UTXOs that can be malleated. Smaller than the spending amount
+        # to create multiple inputs.
+        for _ in range(6):
+            def_wallet.sendtoaddress(wallet.getnewaddress(address_type="legacy"), 0.5)
 
         self.generate(self.nodes[0], 1)
 
         # Bumping either should prevent the other from being bumped as well
         for bump_malleated in [False, True]:
             original_txid = wallet.sendtoaddress(def_wallet.getnewaddress(), 0.9, comment="testing", fee_rate=1)
             malleated_tx, malleated_txid = self.malleate_tx(wallet, original_txid)
 
             blockhash = self.generateblock(self.nodes[0], def_wallet.getnewaddress(), [malleated_tx])["hash"]
 
             assert_equal(wallet.gettransaction(malleated_txid)["comment"], "testing")
 
+            # Check synced comment was written to disk
+            wallet.unloadwallet()
+            self.nodes[0].loadwallet("metadata_clone")
+            assert_equal(wallet.gettransaction(malleated_txid)["comment"], "testing")
+
             # Put the malleated back into the mempol by invalidating the block
             self.nodes[0].invalidateblock(blockhash)
 
@@ -232,6 +239,13 @@
 
         self.generateblock(self.nodes[0], def_wallet.getnewaddress(), [malleated_tx])
 
+        txinfo = wallet.gettransaction(malleated_txid)
+        assert_equal(txinfo["comment"], "testing")
+        assert_equal(txinfo["replaces_txid"], orig_txid)
+
+        # Synced metadata must survive a reload
+        wallet.unloadwallet()
+        self.nodes[0].loadwallet("rbf_metadata_clone")
         txinfo = wallet.gettransaction(malleated_txid)
         assert_equal(txinfo["comment"], "testing")
         assert_equal(txinfo["replaces_txid"], orig_txid)
```

**Review by furszy — COMMENTED** [review]
ACK 1b1e5f3b3621d8d4e7ec2d5cd4a382c4a5be165b

Can quickly re-ack if you squash the coverage shared above.

**Comment by achow101** [comment]
Took the suggestion

**Review by furszy — COMMENTED** [review]
ACK c3298ba67c191424ee5c4e83558b3d9a14c49a51

**Review by sedited — APPROVED** [review]
utACK c3298ba67c191424ee5c4e83558b3d9a14c49a51

Could run clang-format, but I don't think that needs to hold up merging this.

**Comment by sedited** [comment]
Looks like there is a silent merge conflict after merging #35935:

```
[ 60%] Built target bitcoin-tx
/home/drgrid/bitcoin/src/wallet/wallet.cpp: In member function ‘void wallet::CWallet::SyncMalleatedTxMetadata(wallet::WalletBatch&, const wallet::CWalletTx&)’:
/home/drgrid/bitcoin/src/wallet/wallet.cpp:785:21: error: ‘class wallet::WalletBatch’ has no member named ‘WriteTx’; did you mean ‘WriteIC’?
  785 |         (void)batch.WriteTx(*copyTo);
      |                     ^~~~~~~
      |                     WriteIC
/home/drgrid/bitcoin/src/wallet/wallet.cpp: In member function ‘bool wallet::CWallet::MarkReplaced(const Txid&, const Txid&)’:
/home/drgrid/bitcoin/src/wallet/wallet.cpp:1035:20: error: ‘class wallet::WalletBatch’ has no member named ‘WriteTx’; did you mean ‘WriteIC’?
 1035 |         if (!batch.WriteTx(*variant)) {
      |                    ^~~~~~~
      |                    WriteIC
gmake[2]: *** [src/wallet/CMakeFiles/bitcoin_wallet.dir/build.make:457: src/wallet/CMakeFiles/bitcoin_wallet.dir/wallet.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2610: src/wallet/CMakeFiles/bitcoin_wallet.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 60%] Built target bitcoin-cli
[ 60%] Linking CXX static library ../../../../lib/libtest_fuzz.a
[ 60%] Built target test_fuzz
gmake: *** [Makefile:146: all] Error 2
ERROR: Running '/home/drgrid/.pre-merge-build.sh' failed.
```

**Comment by achow101** [comment]
> Looks like there is a silent merge conflict after merging #35935:

Rebased and fixed

File: src/primitives/transaction.h (hunk 1 above)
Comment (furszy) [inline src/primitives/transaction.h]: In 19d08a2e4b30ecd4f41b5b1673f925c465d1d92d:

Lambda copies `CTxIn` here, better to take refs:

```suggestion 
            std::ranges::equal(vin, other.vin, [&opts](const CTxIn& self, const CTxIn& other) {
```

Comment (achow101) [reply src/primitives/transaction.h]: Done

File: src/rpc/rawtransaction.cpp [hunk 6]
```diff
@@ -389,7 +389,7 @@ static RPCMethod getrawtransaction()
     }
 
     CTxUndo* undoTX {nullptr};
-    auto it = std::find_if(block.vtx.begin(), block.vtx.end(), [tx](CTransactionRef t){ return *t == *tx; });
```
Comment (furszy) [inline src/rpc/rawtransaction.cpp:392]: nano nit: this could really be a hash comparison as `getrawtransaction` receives a tx id?

```suggestion
    auto it = std::find_if(block.vtx.begin(), block.vtx.end(), [tx](CTransactionRef t){ return t->GetHash() == tx->GetHash(); });
```

**Review by furszy — COMMENTED** [review]
utACK 2c6047df8746a1d5333d17ad999dd32c40aba90e

**Review by sedited — APPROVED** [review]
utACK 2c6047df8746a1d5333d17ad999dd32c40aba90e

**Comment by josibake** [comment]
Post merge NACK on https://github.com/bitcoin/bitcoin/commit/b973a355c4ebd94cfa8cef61b68ac6da92fad787

I find it concerning that https://github.com/bitcoin/bitcoin/commit/b973a355c4ebd94cfa8cef61b68ac6da92fad787 was merged, where the motivation seems to be a bug fix for the wallet. It also seems to undo the original intent of the PR it references (https://github.com/bitcoin/bitcoin/pull/32723), namely to enforce that equality actually means equality.

I haven't fully read the justification for why this PR went with "custom equality," but I can almost guarantee we could have come up with a better solution that did not involve changing `CTransaction` with something that, in my strong opinion, severely worsens the class with the a massive footgun in consensus critical code.

I could be wrong and missing something really obvious here, but at the very least its clear to me that this did not receive sufficient review for merging a change to the equality operator of `CTransaction`. Is it possible to revert commit and explore other solutions for what the wallet needs here?

**Comment by sedited** [comment]
I don't think this needs to be reverted, but the introduced member function could be made a free function and placed in wallet/transaction to keep the primitive small and focused on consensus code. The PR implements maflcko's suggestion from #32723 (https://github.com/bitcoin/bitcoin/pull/32723#issuecomment-3028112892), so not sure about it undoing intent, or introducing a footgun.

**Comment by josibake** [comment]
> The PR implements maflcko's suggestion

I looked at that PR, and I don't see any discussion on the suggestion for or against it. As I mentioned above, I do think this introduces a material footgun and severely degrades local reasoning in an area where it matters most. I think the author of the referenced PR was right not to take the suggestion. I could be missing something but I do think this needs to be its own PR with its own discussion, with a better justification than "maflcko suggested it."

Perhaps its better to flip this on its head: does this change make `CTransaction` _better_, in all use cases? If this is actually needed, it seems worth discussing in its own PR.

**Comment by furszy** [comment]
> Perhaps its better to flip this on its head: does this change make CTransaction better, in all use cases? If this is actually needed, it seems worth discussing in its own PR.

I understand @josibake concern, and agree with @sedited. Instead of making this a discussion about the `CTransaction` primitive, this function could easily be moved to a utility file or the wallet module (with a different name if needed). As b973a355c4ebd94cfa8cef61b68ac6da92fad787 shows, the function use cases are pretty narrow. And comparing the fields directly has a clear advantage over the previous approach for the wallet.

> I could be missing something

The previous code was misleading. We were comparing the cached `wtxid`, which is set to the `txid` during construction when there is no witness data. This isn't obvious when looking at the equality operator, which also could be labeled as a footgun. If we move this function into util/wallet, I would be in favor of dropping it rather than re-adding the old `CTransaction` equality operator.

**Comment by josibake** [comment]
> We were comparing the cached wtxid, which is set to the txid during construction when there is no witness data

This feels off to me, not the equality operator. `wtxid` is a derived field, it shouldn't be possible to set it when the fields it hashes are missing. Regardless, this sounds like there are two specific things going on: a wallet specific use case that wants a specific comparison utility, and an equality operator on `CTransaction` that needs revisiting/removing. I think these should be separate discussions and/or PRs.

EDIT: I worded that poorly, a `wtxid`is set to a `txid` to indicate that a transaction is not a witness transaction. What I meant is it feels strange to set the `wtxid` to `txid` on a transaction that is meant to be a witness transaction. Either its a legacy transaction or its a witness transaction, and it can't _really_ be a witness transaction until the necessary inputs are there and `wtxid` can be _definitionally_ derived.

**Comment by furszy** [comment]
it feels we agree on both subjects?, just need someone doing the changes. Feel free to go ahead with them and tag me there. Happy to review them.
