### PR TITLE
net: make m_nodes_mutex non-recursive

### LINKED ISSUE #19303: Replace all of the RecursiveMutex instances with the Mutex ones
This is a tracking issue for the long-term goal to replace all of the `RecursiveMutex` instances with the `Mutex` ones throughout the code base.

Anthony Williams (_C++ Concurrency in Action_, 2019, 3.3.3 Recursive locking):
> Most of the time, if you think you want a recursive mutex, you probably need to change your design instead.

Should be noted, to insure that mutex locking policy has not been changed by accident in non-trivial cases, all of the related code branches must be covered by appropriate lock assertions: `AssertLockHeld()` or `AssertLockNotHeld()`.

Also Clang Thread Safety Analysis annotations with [Negative Capabilities](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#negative) are very useful (see #19249) but are not a panacea, of course :)

---

- [x] `RecursiveMutex cs_Shutdown` (#19180)
- [x] `RecursiveMutex cs_nTimeOffset` (#19189)
- [x] `RecursiveMutex cs_proxyInfos` (#19190)
- [ ] `RecursiveMutex csPathCached` (#19213)
- [x] `RecursiveMutex cs_warnings` (#19220)
- [ ] `RecursiveMutex CAddrMan::cs` (#19238)
- [ ] `RecursiveMutex BanMan::m_cs_banned`
- [ ] `RecursiveMutex cs_mapLocalHost`
- [ ] `RecursiveMutex CConnman::cs_totalBytesRecv`
- [ ] `RecursiveMutex CConnman::cs_totalBytesSent`
- [ ] `RecursiveMutex CConnman::cs_vOneShots`
- [ ] `RecursiveMutex CConnman::cs_vAddedNodes`
- [ ] `RecursiveMutex CConnman::cs_vNodes`
- [ ] `RecursiveMutex CNode::cs_vSend`
- [ ] `RecursiveMutex CNode::cs_hSocket`
- [ ] `RecursiveMutex CNode::cs_vRecv`
- [ ] `RecursiveMutex CNode::cs_vProcessMsg`
- [ ] `RecursiveMutex CNode::cs_sendProcessing`
- [ ] `RecursiveMutex CNode::cs_SubVer`
- [ ] `RecursiveMutex CNode::cs_inventory`
- [ ] `RecursiveMutex CNode::cs_addrName`
- [ ] `RecursiveMutex CNode::cs_addrLocal`
- [ ] `RecursiveMutex CNode::TxRelay::cs_filter`
- [ ] `RecursiveMutex CNode::TxRelay::cs_tx_inventory`
- [ ] `RecursiveMutex CNode::TxRelay::cs_feeFilter`
- [ ] `RecursiveMutex g_cs_orphans`
- [ ] `RecursiveMutex g_cs_recent_confirmed_transactions`
- [ ] `RecursiveMutex cs_most_recent_block`
- [ ] `RecursiveMutex CBlockPolicyEstimator::m_cs_fee_estimator`
- [ ] `RecursiveMutex cs_rpcWarmup`
- [ ] `RecursiveMutex SingleThreadedSchedulerClient::m_cs_callbacks_pending`
- [ ] `RecursiveMutex FillableSigningProvider::cs_KeyStore`
- [ ] `RecursiveMutex ArgsManager::cs_args`
- [ ] `RecursiveMutex cs_LastBlockFile`
- [ ] `RecursiveMutex CChainState::cs_nBlockSequenceId`
- [ ] `RecursiveMutex CChainState::m_cs_chainstate`
- [ ] `RecursiveMutex cs_db`
- [ ] `RecursiveMutex DescriptorScriptPubKeyMan::cs_desc_man`
- [ ] `RecursiveMutex cs_wallets`
- [ ] `RecursiveMutex CWallet::cs_wallet`

and

- [ ] `RecursiveMutex CTxMemPool::cs`
- [ ] `RecursiveMutex cs_main`

### PR DESCRIPTION
**Pull request by vasild**
The only case of a recursive lock was a nested `ForNode()` call to trim
the size of `lNodesAnnouncingHeaderAndIDs` to `<= 3`. This need not be
nested, so take it out.

Before:
```
fornode(newnode)
    if (size >= 3)
        fornode(front) handle removal of front
        pop front
    push back newnode
```

After:
```
fornode(newnode)
    push back newnode
if (size > 3)
    fornode(front) handle removal of front
    pop front
```

`lNodesAnnouncingHeaderAndIDs` is protected by `cs_main` which is locked
during the entire operation.

Partially resolves: https://github.com/bitcoin/bitcoin/issues/19303

---

_This PR included https://github.com/bitcoin/bitcoin/pull/32326 (first 3 commits in this PR). That PR was merged first, so the size of this was reduced._

### CODE REVIEW

**Review by Bonobirho99 — COMMENTED** [review]
.

**Comment by hebasto** [comment]
> Partially resolves: #19303

Concept ACK on that.

**Comment by vasild** [comment]
`98bba932bf...22d4c57a99`: rebase due to conflicts

**Comment by vasild** [comment]
`22d4c57a99...9a49877f26`: rebase due to conflicts

**Comment by hebasto** [comment]
Time to rebase once more?

**Comment by vasild** [comment]
`9a49877f26...aaa75c1a41`: rebase due to conflicts, also remove the first 3 commits from where because they were merged via https://github.com/bitcoin/bitcoin/pull/32326. Now this PR is just one commit. Also clarify a bit the commit message and the PR description.

**Comment by vasild** [comment]
`aaa75c1a41...492be23a18`: rebase due to conflicts

File: src/net_processing.cpp [hunk 1]
```diff
@@ -1285,23 +1285,23 @@ void PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs(NodeId nodeid)
     }
     m_connman.ForNode(nodeid, [this](CNode* pfrom) EXCLUSIVE_LOCKS_REQUIRED(::cs_main) {
         AssertLockHeld(::cs_main);
-        if (lNodesAnnouncingHeaderAndIDs.size() >= 3) {
```
Comment (l0rinc) [inline src/net_processing.cpp:1314]: there are a lot of changes in a single commit that seem not strictly related. Could you maybe extract low-risk refactorings to separate commits so that the more riskier ones are as simple as possible? I prefer the commits telling me a story for why we're doing the change, but here I see a lot of changes that aren't guiding me.

Comment (hodlinator) [reply src/net_processing.cpp:1314]: Tried cherrypicking 

<details><summary>minimal diff to change m_nodes_mutex mutex type and ForNode usage</summary>

```diff
diff --git a/src/net.h b/src/net.h
index d806b42a1e..f997bbe820 100644
--- a/src/net.h
+++ b/src/net.h
@@ -1519,7 +1519,7 @@ private:
     mutable Mutex m_added_nodes_mutex;
     std::vector<CNode*> m_nodes GUARDED_BY(m_nodes_mutex);
     std::list<CNode*> m_nodes_disconnected;
-    mutable RecursiveMutex m_nodes_mutex;
+    mutable Mutex m_nodes_mutex;
     std::atomic<NodeId> nLastNodeId{0};
     unsigned int nPrevNodeCount{0};
 
diff --git a/src/net_processing.cpp b/src/net_processing.cpp
index 3777832215..20dcca2ca7 100644
--- a/src/net_processing.cpp
+++ b/src/net_processing.cpp
@@ -1285,23 +1285,23 @@ void PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs(NodeId nodeid)
     }
     m_connman.ForNode(nodeid, [this](CNode* pfrom) EXCLUSIVE_LOCKS_REQUIRED(::cs_main) {
         AssertLockHeld(::cs_main);
-        if (lNodesAnnouncingHeaderAndIDs.size() >= 3) {
-            // As per BIP152, we only get 3 of our peers to announce
-            // blocks using compact encodings.
-            m_connman.ForNode(lNodesAnnouncingHeaderAndIDs.front(), [this](CNode* pnodeStop){
-                MakeAndPushMessage(*pnodeStop, NetMsgType::SENDCMPCT, /*high_bandwidth=*/false, /*version=*/CMPCTBLOCKS_VERSION);
-                // save BIP152 bandwidth state: we select peer to be low-bandwidth
-                pnodeStop->m_bip152_highbandwidth_to = false;
-                return true;
-            });
-            lNodesAnnouncingHeaderAndIDs.pop_front();
-        }
         MakeAndPushMessage(*pfrom, NetMsgType::SENDCMPCT, /*high_bandwidth=*/true, /*version=*/CMPCTBLOCKS_VERSION);
         // save BIP152 bandwidth state: we select peer to be high-bandwidth
         pfrom->m_bip152_highbandwidth_to = true;
         lNodesAnnouncingHeaderAndIDs.push_back(pfrom->GetId());
         return true;
     });
+    if (lNodesAnnouncingHeaderAndIDs.size() > 3) {
+        // As per BIP152, we only get 3 of our peers to announce
+        // blocks using compact encodings.
+        m_connman.ForNode(lNodesAnnouncingHeaderAndIDs.front(), [this](CNode* pnodeStop){
+            MakeAndPushMessage(*pnodeStop, NetMsgType::SENDCMPCT, /*high_bandwidth=*/false, /*version=*/CMPCTBLOCKS_VERSION);
+            // save BIP152 bandwidth state: we select peer to be low-bandwidth
+            pnodeStop->m_bip152_highbandwidth_to = false;
+            return true;
+        });
+        lNodesAnnouncingHeaderAndIDs.pop_front();
+    }
 }
 
 bool PeerManagerImpl::TipMayBeStale()
```
</details>

...and building with Clang 19.1.7 on Linux results in a lot of warnings spam:

<details><summary>"calling function 'MaybeCheckNotHeld' requires negative"-spam</summary>

```
In file included from ../src/node/peerman_args.cpp:5:
In file included from ../src/node/peerman_args.h:8:
In file included from ../src/net_processing.h:10:
../src/net.h:1186:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1186 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
In file included from ../src/node/peerman_args.cpp:5:
In file included from ../src/node/peerman_args.h:8:
In file included from ../src/net_processing.h:10:
../src/net.h:1195:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1195 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
2 warnings generated.
[3/26] Building CXX object src/CMakeFiles/bitcoin_node.dir/node/txreconciliation.cpp.o
In file included from ../src/node/txreconciliation.cpp:5:
In file included from ../src/node/txreconciliation.h:8:
../src/net.h:1186:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1186 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
In file included from ../src/node/txreconciliation.cpp:5:
In file included from ../src/node/txreconciliation.h:8:
../src/net.h:1195:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1195 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
2 warnings generated.
[4/26] Building CXX object src/CMakeFiles/bitcoin_node.dir/mapport.cpp.o
In file included from ../src/mapport.cpp:12:
../src/net.h:1186:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1186 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
In file included from ../src/mapport.cpp:12:
../src/net.h:1195:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1195 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
2 warnings generated.
[5/26] Building CXX object src/CMakeFiles/bitcoin_node.dir/headerssync.cpp.o
In file included from ../src/headerssync.cpp:5:
In file included from ../src/headerssync.h:11:
../src/net.h:1186:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1186 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
In file included from ../src/headerssync.cpp:5:
In file included from ../src/headerssync.h:11:
../src/net.h:1195:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1195 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
2 warnings generated.
[6/26] Building CXX object src/CMakeFiles/bitcoin_node.dir/node/context.cpp.o
In file included from ../src/node/context.cpp:13:
../src/net.h:1186:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1186 |         LOCK(m_nodes_mutex);
      |         ^
../src/sync.h:259:56: note: expanded from macro 'LOCK'
  259 | #define LOCK(cs) UniqueLock UNIQUE_NAME(criticalblock)(MaybeCheckNotHeld(cs), #cs, __FILE__, __LINE__)
      |                                                        ^
In file included from ../src/node/context.cpp:13:
../src/net.h:1195:9: warning: calling function 'MaybeCheckNotHeld' requires negative capability '!m_nodes_mutex' [-Wthread-safety-analysis]
 1195 |         LOCK(m_nodes_mutex);
      |         ^
...
```
</details>

So I think it's quite natural to want to add all the annotations to silence the warnings within the same commit.

**Review by hodlinator — COMMENTED** [review]
Concept ACK 492be23a1873d7165e6cc75d1282f4feb63f87b9

**Comment by vasild** [comment]
`492be23a18...4aad3714d6`: split in two commits: https://github.com/bitcoin/bitcoin/pull/32394#discussion_r2417567225

File: src/net_processing.cpp (hunk 1 above)
Comment (vasild) [reply src/net_processing.cpp:1314]: This PR includes:
1. a change around `lNodesAnnouncingHeaderAndIDs` to remove the only recursive usage of the mutex
2. change of the type from `RecursiveMutex` to `Mutex`
3. a pile of annotations to keep the compiler happy after 2.

Extracted 1. into a separate commit and kept 2. and 3. together in a single commit: "it's quite natural to want to add all the annotations to silence the warnings within the same commit"

File: src/net_processing.cpp [hunk 2]
```diff
@@ -1285,23 +1285,23 @@ void PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs(NodeId nodeid)
...
-            // As per BIP152, we only get 3 of our peers to announce
-            // blocks using compact encodings.
-            m_connman.ForNode(lNodesAnnouncingHeaderAndIDs.front(), [this](CNode* pnodeStop){
-                MakeAndPushMessage(*pnodeStop, NetMsgType::SENDCMPCT, /*high_bandwidth=*/false, /*version=*/CMPCTBLOCKS_VERSION);
-                // save BIP152 bandwidth state: we select peer to be low-bandwidth
-                pnodeStop->m_bip152_highbandwidth_to = false;
-                return true;
-            });
-            lNodesAnnouncingHeaderAndIDs.pop_front();
```
Comment (hodlinator) [inline src/net_processing.cpp:1323]: nit:
On master, we will be holding on to the `m_nodes_mutex` as we start the lookup and removal for this older node at `lNodesAnnouncingHeaderAndIDs.front()`.
This older node can be removed from `CConnman::m_nodes` just before we execute an outer `ForNode` (while not holding `m_nodes_mutex`).

Don't think there is any risk to how it works on master or in this PR, we `.pop_front()` the old entry regardless of whether we find it or not. But might still be nice to add
```
    Assume(lNodesAnnouncingHeaderAndIDs.size() <= 3);
```
as a post-condition for the function to document/communicate expectations.

File: src/net.h
Comment (hodlinator) [inline src/net.h:1828]: Shouldn't we also annotate this one with
```C++
EXCLUSIVE_LOCKS_REQUIRED(!connman.m_nodes_mutex)
```
?
...which leads to also annotating `ThreadMessageHandler`.

**Review by hodlinator — COMMENTED** [review]
Reviewed 4aad3714d66cc80c08cb1c827fb49fba7dcf8d50

All annotations make sense, but left Q regarding 1-2 potentially missing ones.

File: src/net_processing.cpp (hunk 2 above)
Comment (vasild) [reply src/net_processing.cpp:1323]: Such an `Assume()` would make for stricter requirements, even in `master`, or more complex reasoning to confirm that it does not make stricter requirements. I mean, can `lNodesAnnouncingHeaderAndIDs` have e.g. 5 elements when this code snippet starts? It is not obvious by just looking at this code, so one has to assume that it can or study the code elsewhere to confirm that it cannot have 4 or more.

So, both in `master` and in this PR such an `Assume()` would be triggered if `lNodesAnnouncingHeaderAndIDs` has e.g. 5 elements.

The logic in `master` is - add one object and remove one object if they are too many. This PR keeps it that way.

File: src/net.h
Comment (vasild) [reply src/net.h:1828]: Yes, good catch! Done.

**Comment by vasild** [comment]
`4aad3714d6...4b3a2c2360`: do https://github.com/bitcoin/bitcoin/pull/32394#discussion_r2433600255

File: src/net_processing.cpp (hunk 2 above)
Comment (hodlinator) [reply src/net_processing.cpp:1323]: Agree that one cannot know unless one greps the entire codebase for insertions to `lNodesAnnouncingHeaderAndIDs`. Currently this is the only function.
But worst case, some parallel pull request could introduce another function that inserts more elements than 3. Using a dev-only `Assume` instead of `assert` as I suggested would make it less of a hazard.

Maybe it should be a precondition as well. Anyways, just a minor suggestion to attempt making existing tests against number 3 less magical.

**Review by hodlinator — APPROVED** [review]
ACK 4b3a2c23608e709a63b9d5bd69c3eb16cf08e462

Manually went through all functions using `CConnman::m_nodes_mutex` and only remaining issue I could find is now fixed (https://github.com/bitcoin/bitcoin/pull/32394/files#r2433600255).

Also checked out first commit and only cherrypicked mutex type change to re-confirm Clang spews warnings about missing annotations (and no warnings at HEAD of PR).

**Comment by w0xlt** [comment]
Approach ACK

File: src/net_processing.cpp (hunk 2 above)
Comment (vasild) [reply src/net_processing.cpp:1323]: I considered this again. I like to have the `Assume()` for documentation purposes. But that would make it stricter compared to `master` and this is not the purpose of this PR. I mean - in `master` and in this PR (as it is now) the logic is "if there are more than 3, remove one". Yes, we do imply that there will not be more than 3 at the end, but asserting that (in dev-only `Assume()`) seems to be out of the scope of this PR. So, I will leave it as it is.

**Comment by vasild** [comment]
`4b3a2c2360...1a9274f391`: rebase due to conflicts

**Review by hodlinator — APPROVED** [review]
re-ACK 1a9274f391df0465c17b6b6664988af70910e39b

Changes since previous review (https://github.com/bitcoin/bitcoin/pull/32394#pullrequestreview-3353773054):
* Resolves conflict with #32983.

File: src/net_processing.cpp [hunk 3]
```diff
@@ -1285,23 +1285,23 @@ void PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs(NodeId nodeid)
...
+    if (lNodesAnnouncingHeaderAndIDs.size() > 3) {
+        // As per BIP152, we only get 3 of our peers to announce
+        // blocks using compact encodings.
+        m_connman.ForNode(lNodesAnnouncingHeaderAndIDs.front(), [this](CNode* pnodeStop){
+            MakeAndPushMessage(*pnodeStop, NetMsgType::SENDCMPCT, /*high_bandwidth=*/false, /*version=*/CMPCTBLOCKS_VERSION);
+            // save BIP152 bandwidth state: we select peer to be low-bandwidth
+            pnodeStop->m_bip152_highbandwidth_to = false;
+            return true;
+        });
+        lNodesAnnouncingHeaderAndIDs.pop_front();
```
Comment (Crypt-iQ) [inline src/net_processing.cpp:1329]: I was initially concerned that maybe `lNodesAnnouncingHeaderAndIDs.front()` could have been removed from in between releasing the lock and acquiring the lock again. It seems fine since if we do not find `lNodesAnnouncingHeaderAndIDs.front()`, we don't need to set `m_bip152_highbandwidth_to` false and we still remove it from the list. There was some previous discussion about the locking [here](https://github.com/bitcoin/bitcoin/pull/22147#issuecomment-855904105).

**Review by Crypt-iQ — COMMENTED** [review]
crACK 1a9274f391df0465c17b6b6664988af70910e39b

Needs a small rebase since #33956 added 2 annotations.

File: src/net_processing.cpp (hunk 3 above)
Comment (vasild) [reply src/net_processing.cpp:1329]: > removed from in between releasing the lock and acquiring the lock again

How? `lNodesAnnouncingHeaderAndIDs` is protected by `cs_main` which is held in the entire `PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs()`.

**Comment by vasild** [comment]
`1a9274f391...a6ccd6fdbf`: rebase due to conflicts

File: src/net_processing.cpp (hunk 3 above)
Comment (Crypt-iQ) [reply src/net_processing.cpp:1329]: I think I was a little unclear. I meant that the `CNode*` that `lNodesAnnouncingHeaderAndIDs.front()` refers to might have been removed from in `m_nodes` if we're not holding `m_nodes_mutex` the entire time. Though I did not write a test to check if this is actually possible, so I might be wrong.

**Comment by Crypt-iQ** [comment]
re-ACK a6ccd6fdbf838d70ada83b6079112c648c490e1c

File: src/net_processing.cpp (hunk 3 above)
Comment (vasild) [reply src/net_processing.cpp:1329]: Yes, that seems to be fine - if the last `m_connman.ForNode(...front())` does nothing (the one at the end, just before `pop_front()`).

**Review by hodlinator — APPROVED** [review]
re-ACK a6ccd6fdbf838d70ada83b6079112c648c490e1c

Rebase to fix conflict with #33956

**Comment by sedited** [comment]
This has been in need of a rebase for a while, but already got a couple of ACKs. Can you push an update?

**Comment by vasild** [comment]
> This has been in need of a rebase for a while, but already got a couple of ACKs. Can you push an update?

Yes, sorry for the delay.

`a6ccd6fdbf838d70ada83b6079112c648c490e1c...8e183f8d5768a0344ad27b8dec4974f18fd5a34a`: rebase due to conflicts

**Comment by maflcko** [comment]
```
src/net.cpp:3252:13: error: calling function 'OpenNetworkConnection' requires negative capability '!m_nodes_mutex' [-Werror,-Wthread-safety-analysis]
 3252 |         if (OpenNetworkConnection(addr,
      |             ^
1 error generated.

**Comment by vasild** [comment]
Oh, time to change `-DWERROR=ON` to `-DCMAKE_COMPILE_WARNING_AS_ERROR=ON` locally due to https://github.com/bitcoin/bitcoin/pull/34504

`8e183f8d5768a0344ad27b8dec4974f18fd5a34a...e46d0e2c801d4f68624a602d3255ddd392b2dac0`: add the missing annotation

**Review by hodlinator — APPROVED** [review]
re-ACK e46d0e2c801d4f68624a602d3255ddd392b2dac0

Just changes to diff context and adapting to private broadcast being merged.

---

nit: Might want to also do:
```diff
 
 void CConnman::ThreadPrivateBroadcast()
 {
+    AssertLockNotHeld(m_nodes_mutex);
     AssertLockNotHeld(m_unused_i2p_sessions_mutex);
 
     size_t addrman_num_bad_addresses{0};
```

**Comment by vasild** [comment]
`e46d0e2c801d4f68624a602d3255ddd392b2dac0...6da753002a7e5749e03ddb7c8879803f3144858e`: add `AssertLockNotHeld(m_nodes_mutex)`

**Review by hodlinator — APPROVED** [review]
re-ACK 6da753002a7e5749e03ddb7c8879803f3144858e

**Comment by Crypt-iQ** [comment]
crACK 6da753002a7e5749e03ddb7c8879803f3144858e

**Review by w0xlt — COMMENTED** [review]
ACK 6da753002a7e5749e03ddb7c8879803f3144858e

File: src/net_processing.cpp [hunk 4]
```diff
@@ -1310,23 +1310,23 @@ void PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs(NodeId nodeid)
...
-            });
-            lNodesAnnouncingHeaderAndIDs.pop_front();
-        }
         MakeAndPushMessage(*pfrom, NetMsgType::SENDCMPCT, /*high_bandwidth=*/true, /*version=*/CMPCTBLOCKS_VERSION);
         // save BIP152 bandwidth state: we select peer to be high-bandwidth
         pfrom->m_bip152_highbandwidth_to = true;
         lNodesAnnouncingHeaderAndIDs.push_back(pfrom->GetId());
         return true;
     });
+    if (lNodesAnnouncingHeaderAndIDs.size() > 3) {
```
Comment (l0rinc) [inline src/net_processing.cpp]: > [72bd8b7](https://github.com/bitcoin/bitcoin/pull/32394/changes/72bd8b7f46a7a7f1a0b43ce584c76b7d9401db23) _net: drop the only recursive usage of CConnman::m_nodes_mutex_:

Q: The first `ForNode()` only runs the callback if the peer is still [found and fully connected](https://github.com/bitcoin/bitcoin/blob/3b39a8aeb4c6248fa1bb15377a0c79787dada3ca/src/net.cpp#L4127), right?
What happens if the peer disconnects right before the callback runs? Then we would not append the new peer to `lNodesAnnouncingHeaderAndIDs`.
Is the list guaranteed to already be at most 3 here, so the later trim step still cannot remove someone else? I tried forcing that possible race locally, but I am not fully sure.

File: src/net_processing.cpp [hunk 5]
```diff
@@ -1310,23 +1310,23 @@ void PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs(NodeId nodeid)
...
+        // As per BIP152, we only get 3 of our peers to announce
+        // blocks using compact encodings.
+        m_connman.ForNode(lNodesAnnouncingHeaderAndIDs.front(), [this](CNode* pnodeStop){
```
Comment (l0rinc) [inline src/net_processing.cpp]: > [72bd8b7](https://github.com/bitcoin/bitcoin/pull/32394/changes/72bd8b7f46a7a7f1a0b43ce584c76b7d9401db23) _net: drop the only recursive usage of CConnman::m_nodes_mutex_:

nit:

```suggestion
        m_connman.ForNode(lNodesAnnouncingHeaderAndIDs.front(), [this](CNode* pnodeStop) {
```

**Comment by l0rinc** [comment]
I reproduced this change locally and have a question about the case where the first `ForNode()` callback does not run because the peer disconnects before it, and whether the later trim is still safe in that case.

File: src/net_processing.cpp (hunk 4 above)
Comment (Crypt-iQ) [reply src/net_processing.cpp]: Yup. Any earlier run of this function will make `lNodesAnnouncingHeaderAndIDs` be at most length 3. Then if the first callback doesn't run because the peer disconnects, it will still be at most 3. Then the second callback won't run.

Comment (l0rinc) [reply src/net_processing.cpp]: Thanks, makes sense. If it's edited again, consider documenting this invariant:
```C++
bool selected = m_connman.ForNode(nodeid, ...);
// ...
if (lNodesAnnouncingHeaderAndIDs.size() > 3) {
    Assume(selected);
    ...
}
```

**Comment by l0rinc** [comment]
code review ACK 6da753002a7e5749e03ddb7c8879803f3144858e

File: src/net.cpp [hunk 6]
```diff
@@ -3204,6 +3204,7 @@ void CConnman::ThreadI2PAcceptIncoming()
 
 void CConnman::ThreadPrivateBroadcast()
 {
+    AssertLockNotHeld(m_nodes_mutex);
```
Comment (sedited) [inline src/net.cpp:3248]: Why is this check only added for this function, and not the rest of them where a negative capability is added?

**Review by sedited — COMMENTED** [review]
Concept ACK

**Comment by achow101** [comment]
@vasild Could you please address (respond to or implement) the remaining comments here?

**Comment by vasild** [comment]
`6da753002a7e5749e03ddb7c8879803f3144858e...11713c9fa91ca583063750cc826d0138b3a611f6`: address suggestions

> @vasild Could you please address (respond to or implement) the remaining comments here?

Done.

File: src/net_processing.cpp (hunk 4 above)
Comment (vasild) [reply src/net_processing.cpp]: That `Assume()` looks unnecessary strong to me. We just want to trim the list if it grew too big. I think in the current code such an `Assume()` would never be triggered, but may be after future changes and there is no really a reason to assert that if the list is too big then we must have had appended the node to it.

Anyway, I changed it to:

```
bool nodeid_was_appended{ForNode(...)};
if (nodeid_was_appended && the list is too big) then trim it
```

File: src/net_processing.cpp (hunk 5 above)
Comment (vasild) [reply src/net_processing.cpp]: Done

File: src/net.cpp (hunk 6 above)
Comment (vasild) [reply src/net.cpp:3248]: Those `AssertLockNotHeld()` were triggered occasionally and I couldn't figure it out, so it was easiest to just remove them.

Comment (vasild) [reply src/net.cpp:3248]: Jokes aside, I don't remember a reason for their omission. I have added them now, except for functions whose very first line is `LOCK(m_nodes_mutex);`.

**Review by w0xlt — COMMENTED** [review]
ACK 11713c9fa91ca583063750cc826d0138b3a611f6

**Comment by Crypt-iQ** [comment]
utACK 11713c9fa91ca583063750cc826d0138b3a611f6

File: src/net.cpp [hunk 7]
```diff
@@ -1736,6 +1739,8 @@ bool CConnman::AttemptToEvictConnection()
 }
 
 void CConnman::AcceptConnection(const ListenSocket& hListenSocket) {
```
Comment (hodlinator) [inline src/net.cpp:1741]: nanonit: Please consider iff you touch again:
```suggestion
void CConnman::AcceptConnection(const ListenSocket& hListenSocket)
{
```

**Review by hodlinator — APPROVED** [review]
re-ACK 11713c9fa91ca583063750cc826d0138b3a611f6

Changes since previous review (6da753002a7e5749e03ddb7c8879803f3144858e):
* Added `bool nodeid_was_appended` in `PeerManagerImpl::MaybeSetPeerAsAnnouncingHeaderAndIDs` so we only check to see if we should remove an entry if we have added one. I double-checked the code to make sure the removal of entries wasn't also serving some other place where nodes were being added to `lNodesAnnouncingHeaderAndIDs`.
* Added a bunch of `AssertLockNotHeld(m_nodes_mutex)` in the bodies of methods declared with `EXCLUSIVE_LOCKS_REQUIRED(!m_nodes_mutex)`.

**Review by sedited — APPROVED** [review]
ACK 11713c9fa91ca583063750cc826d0138b3a611f6
