### ISSUE TITLE
example_test.py doesn't work with Python 3.5

### ISSUE THREAD

**Issue by adaminsky** [bitcoin/bitcoin#19701]
**Expected behavior**
The `example_test.py` functional test should run without errors with Python 3.5.0 since this is the minimum supported version.

**Actual behavior**
Test fails with 
`AttributeError: '_SelectorSocketTransport' object has no attribute 'is_closing'`

**To reproduce**
Run `example_test.py` with Python 3.5.0.

**System information**
Latest version of Bitcoin Core compiled on macOS 10.15.5.

PR #13747 fixed the issue but it seems like the Python documentation incorrectly says that `is_closing()` was added to `BaseTransport` in 3.4.4 ([here](https://docs.python.org/3.4/library/asyncio-protocol.html#asyncio.BaseTransport.is_closing)), but then on another page on the Python docs ([here](https://docs.python.org/3.5/library/asyncio-protocol.html#asyncio.BaseTransport.is_closing)) it says it was included in Python 3.5.1. The previous fix was reverted when moving to 3.5, but it seems like that may have reintroduced the problem. I'm not sure how soon the minimum Python version will be increased, so not sure if fixing this is important.

**Comment by skmcontrib** [comment]
@adaminsky do you think a noob in bitcoin code can work on this? If yes I can take a stab at this.

**Comment by adaminsky** [comment]
@skmcontrib I'm a noob too haha. I'm sure you can fix the problem, basically just do what was in the linked PR. I just saw #19504 which will increase the minimum python version to 3.6, but it seems like it could be a couple months for it to be merged.

**Comment by jnewbery** [comment]
Good catch @adaminsky . Since this only affects Python 3.5.0 (and not 3.5.1-3.5.9), and we're increasing the minimum required version to 3.6 soon (expected merge date Nov 1), I don't think it's worth fixing this.

**Comment by adaminsky** [comment]
Makes sense @jnewbery, I'm closing the issue.
