### PR TITLE
addrman: Make addrman a top-level component

### PR DESCRIPTION
**Pull request by jnewbery**
Addrman is currently a member variable of connman. Make it a top-level component with lifetime owned by node.context, and add a reference to addrman in peerman. This allows us to eliminate some functions in connman that are simply forwarding requests to addrman, and simplifies the connman-peerman interface.

By constructing the addrman in init, we can also add parameters to the ctor, which allows us to test it better. See #20233, where we enable consistency checking for addrman in our functional tests.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
does it conceptually make sense to have an addrman without connman or connman without addrman? I'd say no.

> This allows us to eliminate some functions in connman that are simply forwarding

An alternative to achieve that would be to let PeerMan steal a reference to addrman from connman (and assign it to m_addrman)

**Comment by Saibato** [comment]
> This allows us to eliminate some functions in connman that are simply forwarding

In general to have things double or more if ( ,,,)  or detrimental decision processes in the same code is a good design in industry where u can kill ppl easy, if there is no double check and just one bit ( that could be just by chance or external forces have flipped ) decides over mayhem.

In financials we used to do that the same and wrote "bad ugly code". bcs u get no bonus at the years end, if the code "looks" good but your customers got screwed. Unless that was ur biz.

**Comment by jnewbery** [comment]
> does it conceptually make sense to have an addrman without connman or connman without addrman? I'd say no.

Why not? If `-connect` is set, then we don't use addrman for choosing outbound connections (see `m_use_addrman_outgoing` inside connman). In general, I think being able to run with different components disabled enforces strict separation between components and means there can't be unintentional coupling between them.

**Comment by jnewbery** [comment]
Fixed whitespace linter issue

**Comment by MarcoFalke** [comment]
This doesn't compile on gcc4.8, but we'll drop support for that soon anyway, so the failure can be ignored/rebased out when 22.0 is branched off.

**Comment by jnewbery** [comment]
> This doesn't compile on gcc4.8

Hopefully fixed

**Comment by jnewbery** [comment]
rebased

**Comment by amitiuttarwar** [comment]
concept ACK

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
Rebased

File: src/net.h [hunk 1]
```diff
@@ -252,7 +252,7 @@ class CConnman
         m_onion_binds = connOptions.onion_binds;
     }
 
-    CConnman(uint64_t seed0, uint64_t seed1, bool network_active = true);
```
Comment (adamjonas) [inline src/net.h:255]: Look like the fuzzer is complaining about this and needs to be updated to take this additional arg type:

```
test/fuzz/connman.cpp:26:14: error: no matching constructor for initialization of 'CConnman'
    CConnman connman{fuzzed_data_provider.ConsumeIntegral<uint64_t>(), fuzzed_data_provider.ConsumeIntegral<uint64_t>(), fuzzed_data_provider.ConsumeBool()};
             ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./net.h:255:5: note: candidate constructor not viable: no known conversion from 'bool' to 'CAddrMan &' for 3rd argument
    CConnman(uint64_t seed0, uint64_t seed1, CAddrMan& addrman, bool network_active = true);
    ^
./net.h:187:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
class CConnman
      ^
1 error generated.
```

Comment (jnewbery) [reply src/net.h:255]: Thanks! Should be fixed now.

**Comment by jnewbery** [comment]
Rebased and fixed fuzz build errors.

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
Rebased

**Comment by ajtowns** [comment]
I don't think having addrman referenced from both peerman and connman makes much sense -- peerman already has a reference to connman, so avoiding the layering can be done just by letting peerman access connman's addrman directly  -- `m_connman.AddrMan().do_something()`, and that also avoids the potential for peerman and connman somehow getting their addrmans out of sync.

As far as better testing of addrman goes, I think that's easy to do without this PR or the above alternative, see https://github.com/bitcoin/bitcoin/pull/20233#issuecomment-755044221

As far as disabling addrman goes, I'm not convinced that's a meaningful benefit (most people are going to use it enabled, and I think the memory saving if done at runtime rather than compiletime would be insignificant), and if it was, it can also be done via connman rather than doing it in init/node and then passing that on to both connman and peerman.

**Comment by jnewbery** [comment]
I've left a comment on the linked PR here: https://github.com/bitcoin/bitcoin/pull/20233#issuecomment-755188580. I'll copy the parts that are relevant here:

> > I don't think there's any need for this to be based on #20228 -- passing a "check_addrman" from init to CConnman seems to work fine, see ajtowns/bitcoin@202101-addrman-check (commits) eg.

> Sure, we could continue to pass function calls and (now) ctor parameters through CConnman, but I don't see why that is desirable. Connman _uses_ addrman, but there's no reason for it to _have_ an addrman. Addrman is also used by peerman and the RPCs. Connman's resposibility is to open and maintain connections. Storing and maintaining our map of accessible nodes on the network is a separate  responsibility.
> 
> There was also some discussion here: http://www.erisian.com.au/bitcoin-core-dev/log-2020-12-16.html#l-585 about being able to manage addrman more directly. Again, in that case it'd be easier if RPC directly held a handle to the addrman instead of passing messages through connman.

For your specific objections here:

> avoids the potential for peerman and connman somehow getting their addrmans out of sync.

I don't see how that could happen. addrman gets constructed and passed to the connman and peerman ctors to be saved as a reference a few lines later. How could those possible get out of sync?

> As far as disabling addrman goes, I'm not convinced that's a meaningful benefit (most people are going to use it enabled, and I think the memory saving if done at runtime rather than compiletime would be insignificant), and if it was, it can also be done via connman rather than doing it in init/node and then passing that on to both connman and peerman.

I agree that most people aren't going run without addrman, or that the memory savings are meaningful. However, I think having it as an option is beneficial from an architectural standpoint -- being able to run with different components disabled enforces strict separation between components and means there can't be unintentional coupling between them.

**Comment by jnewbery** [comment]
rebased

File: src/test/denialofservice_tests.cpp [hunk 2]
```diff
@@ -129,8 +130,7 @@ BOOST_AUTO_TEST_CASE(outbound_slow_chain_eviction)
     BOOST_CHECK(dummyNode1.fDisconnect == true);
     SetMockTime(0);
 
-    bool dummy;
-    peerLogic->FinalizeNode(dummyNode1, dummy);
+    peerLogic->FinalizeNode(dummyNode1);
```
Comment (vasild) [inline src/test/denialofservice_tests.cpp:133]: Just an observation: before this patch `AddrMan::Connected()` would not have been called here and it will be called after this patch. Also `PeerManager::FinalizeNode()` would try to dereference `PeerManager::m_addrman`. It is fine, as far as I can see.

**Review by vasild — COMMENTED** [review]
Concept ACK f36480df7785fb9bb81027b5d59218689a11f0c8

**Comment by jnewbery** [comment]
Rebased now that the fuzz conflicts should no longer be a problem (#20828)

File: src/node/context.h [hunk 3]
```diff
@@ -13,6 +13,7 @@
 class ArgsManager;
 class BanMan;
 class CBlockPolicyEstimator;
+class CAddrMan;
```
[the remark this answers is not in the document]
Comment (jnewbery) [reply src/node/context.h:16]: Oops. Fixed.

File: src/net.h [hunk 4]
```diff
@@ -1096,7 +1093,7 @@ class CConnman
     std::vector<ListenSocket> vhListenSocket;
     std::atomic<bool> fNetworkActive{true};
     bool fAddressesInitialized{false};
-    CAddrMan addrman;
+    CAddrMan& addrman;
```
[the remark this answers is not in the document]
Comment (jnewbery) [reply src/net.h:1111]: shared_ptr implies shared ownership of a resource. In this case, CConnman and PeerManager don't own the addrman, they just hold a reference to it.

We already use this same model for holding references to mempool, chainman, conman, etc, where the resource is owned by NodeContext.

[the remark this answers is not in the document]
Comment (jnewbery) [reply src/net.h:1111]: I'd prefer not to rename this. `addrman` is used in >50 places in net.cpp/net.h, so updating the name would add a lot of noise to the diff for this PR.

File: src/init.cpp [hunk 5]
```diff
@@ -1398,7 +1401,7 @@ bool AppInitMain(const util::Ref& context, NodeContext& node, interfaces::BlockA
     ChainstateManager& chainman = *Assert(node.chainman);
 
     assert(!node.peerman);
-    node.peerman = std::make_unique<PeerManager>(chainparams, *node.connman, node.banman.get(),
+    node.peerman = std::make_unique<PeerManager>(chainparams, *node.connman, *node.addrman, node.banman.get(),
                                                  *node.scheduler, chainman, *node.mempool, ignores_incoming_txs);
```
[the remark this answers is not in the document]
Comment (jnewbery) [reply src/init.cpp]: Because net_processing doesn't depend on node/context (and adding that would be a circular dependency between net_processing and node/context). In fact, a NodeContext object isn't even needed to construct a PeerManager object - see denialofservice_tests.cpp.

File: src/test/denialofservice_tests.cpp (hunk 2 above)
Comment (jnewbery) [reply src/test/denialofservice_tests.cpp:132]: Yes, this is a slightly different ordering, but I agree that it's fine. Everything between here and the end of Finalize is just internal net_processing book-keeping.

**Comment by jnewbery** [comment]
Thanks for the review @vasild - I've addressed all your comments.

File: src/net.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/net.h:1111]: ok

File: src/init.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/init.cpp]: ok

**Review by vasild — APPROVED** [review]
ACK a4a0bdab0bf4b47ccb049982197cbea59fad1e61

I think the [usage of `shared_ptr`](https://github.com/bitcoin/bitcoin/pull/20228#discussion_r555705214) would benefit this code, but I ACK it nevertheless because the pattern of using one `unique_ptr` and a few bare pointers to its contents is already used elsewhere. Don't consider that discussion as a blocker for this PR.

File: src/net.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/net.h:1111]: > shared_ptr implies shared ownership of a resource. In this case, CConnman and PeerManager don't own the addrman, they just hold a reference to it.

`shared_ptr` would just destroy the object when its last instance is destroyed. The fact that we know that this is going to be the instance in `NodeContext` does not make it less useful.

The problem with the bare pointer (or bare reference) is that it can become dangling. `shared_ptr` aims to fix exactly that problem.

> We already use this same model for holding references to mempool, chainman, conman, etc, where the resource is owned by NodeContext.

Right, that can be improved with `shared_ptr` too.

[the remark this answers is not in the document]
Comment (jnewbery) [reply src/net.h:1111]: Another good reason to leave this as a reference is that it explicitly communicates that there *must* be a reference to an addrman, and that we can 'dereference' addrman throughout peerman without checking for nullness first.

In any case, I agree that this discussion can be deferred to another issue/PR.

**Comment by jnewbery** [comment]
Rebased

**Review by vasild — APPROVED** [review]
ACK cfbf35efb6acf182a31b57220b9001a1459c937c

**Comment by sipa** [comment]
utACK cfbf35efb6acf182a31b57220b9001a1459c937c

File: src/test/util/setup_common.cpp [hunk 6]
```diff
@@ -187,8 +188,9 @@ TestingSetup::TestingSetup(const std::string& chainName, const std::vector<const
         throw std::runtime_error(strprintf("ActivateBestChain failed. (%s)", state.ToString()));
     }
 
+    m_node.addrman = std::make_unique<CAddrMan>();
```
Comment (MarcoFalke) [inline src/test/util/setup_common.cpp:191]: 8f3d35a83affc7061e6bf9b9e6be6e9861c84632:

Any reason to implicitly deconstruct this last, as opposed to in the same order that `init` deconstructs it? This will leave a "dangling" addrman in memory after the datadir (and addrman.dat) is cleared.

File: src/test/fuzz/connman.cpp [hunk 7]
```diff
@@ -128,9 +128,6 @@ FUZZ_TARGET_INIT(connman, initialize_connman)
             [&] {
                 connman.SetNetworkActive(fuzzed_data_provider.ConsumeBool());
             },
-            [&] {
-                connman.SetServices(random_service, ConsumeWeakEnum(fuzzed_data_provider, ALL_SERVICE_FLAGS));
```
Comment (MarcoFalke) [inline src/test/fuzz/connman.cpp:131]: 48f96385c809a3e1d957538db8864ac068aca7eb

When removing this here, it would be nice to update the addrman fuzz target to use `ConsumeWeakEnum`

File: src/test/fuzz/connman.cpp [hunk 8]
```diff
@@ -98,9 +98,6 @@ FUZZ_TARGET_INIT(connman, initialize_connman)
             [&] {
                 (void)connman.GetNodeCount(fuzzed_data_provider.PickValueInArray({ConnectionDirection::None, ConnectionDirection::In, ConnectionDirection::Out, ConnectionDirection::Both}));
             },
-            [&] {
-                connman.MarkAddressGood(random_address);
```
Comment (MarcoFalke) [inline src/test/fuzz/connman.cpp:101]: 61aecae0dafcc4c050343ef9c3e0242a11614cd9

what is the point of keeping the unused variable?

File: src/net_processing.cpp [hunk 9]
```diff
@@ -993,8 +992,10 @@ void PeerManagerImpl::FinalizeNode(const CNode& node, bool& fUpdateConnectionTim
 
     if (node.fSuccessfullyConnected && misbehavior == 0 &&
         !node.IsBlockOnlyConn() && !node.IsInboundConn()) {
-        // Only change visible addrman state for outbound, full-relay peers
-        fUpdateConnectionTime = true;
+        // Only change visible addrman state for full outbound peers.  We don't
+        // call Connected() for feeler connections since they don't have
+        // fSuccessfullyConnected set.
+        m_addrman.Connected(node.addr);
```
Comment (MarcoFalke) [inline src/net_processing.cpp:998]: cfbf35efb6acf182a31b57220b9001a1459c937c

I am not a fan of moving this into the cs_main scope. The goal should be to limit cs_main to validation, not to accidentally extend it to cover addrman and other components.

**Review by maflcko — COMMENTED** [review]
I looked at cfbf35efb6acf182a31b57220b9001a1459c937c 🐣

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I looked at cfbf35efb6acf182a31b57220b9001a1459c937c 🐣
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjQXgwAifz7QTdA8HDHM9fKlC8qGtT0ayvExXLvJoVxixHPY+IecXmTOr3rcQws
/84tejW8Oylc1SCcKcw8Pdr2VF4cYZbCK+oo3Xj1NCzJlraNJ5i2nsnq0mzZJdUI
6OUyCOPa2c/a9lb7cscSHm8SIymYYMi6YwMW461BcO20xdEC3N3a4Eb0p7ECvJZU
9i5RSnLntHrEON5x1NSkzMPq1rL5iXzb7oLSFDgjlJD03t6VuKRF8CcTURGUQo1y
TV+zlETUgzvMC7/uM0M4OoJPkUChleH1Sc48SMYGWpB1FZnkbMwt49Tpyvd4vOzc
wPZwnDCwnT7xbPhkq4uJfaUZ9sCi7JAb637gKtseOIYrH6NbxfXzMsMv7vzOiT0r
CKsOOv6xonhgKre8UC4KIR/PtKP2zqzN9AV1/9Voh6sMqPNHvYUZK8I7W4UYFoEk
aAR6Z+Az2ADYUhkxI11Vk0ou2/m7iwSURenbOWikPMu5QkS+MG0OJYaoOhJQ6kG+
gfAqzFs0
=nQs9
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `f3498d80e5b4a7afbc97ad18b42947699359862c306a91e93f1dbb3d43a2cb07  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108f3498d80e5b4a7afbc97ad18b42947699359862c306a91e93f1dbb3d43a2cb07f010bdb4f9c2df516c1899bdac7544e0389e08fff0103b8f94cc96dd5dcf7eeb8dee708a9aa208f1046055b46ef008380cecc912f3b3a00083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0108658e2a8e081572b05d5943c0301615008f1046055a699f008be2363280eeb1e0c0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff0109025e3ea3f8bb5a07967d824d66f06dd08f1046055b470f008d6670bdd9c168d850083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010e323dde71a9827e5b2357adcb115654408f1046055b46ff008eb6fdc0a6b7fbf160083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

File: src/test/util/setup_common.cpp (hunk 6 above)
Comment (jnewbery) [reply src/test/util/setup_common.cpp:191]: Just to be clear, are you suggesting a `~TestingSetup()` dtor that destructs the components in reverse order, like in `Shutdown()`? That seems reasonable to me.

Comment (MarcoFalke) [reply src/test/util/setup_common.cpp:191]: No, just add `m_node.addrman.reset()` to where the other node members are reset.

File: src/test/fuzz/connman.cpp (hunk 7 above)
Comment (jnewbery) [reply src/test/fuzz/connman.cpp:131]: Improving the addrman fuzzer seems out of scope of this PR (since it doesn't change the addrman interface).

File: src/test/fuzz/connman.cpp (hunk 8 above)
Comment (jnewbery) [reply src/test/fuzz/connman.cpp:101]: Done (also removed the unused random_service variable)

File: src/net_processing.cpp (hunk 9 above)
Comment (jnewbery) [reply src/net_processing.cpp:998]: In general I agree with reducing cs_main scope, but I think doing that in Finalize can happen in a follow-up PR.

File: src/test/util/setup_common.cpp (hunk 6 above)
Comment (jnewbery) [reply src/test/util/setup_common.cpp:192]: Done. Seems odd to me that the components are constructed in the `TestingSetup()` ctor, but destructed in the `ChainTestingSetup()` destructor, but I've followed the existing pattern.

**Comment by jnewbery** [comment]
Thanks for the review @MarcoFalke. I've addressed all of your comments.

File: src/net_processing.cpp (hunk 9 above)
Comment (MarcoFalke) [reply src/net_processing.cpp:998]: Agree, but does it need to be made worse?


```diff
diff --git a/src/net_processing.cpp b/src/net_processing.cpp
index 0fa201a047..619693536b 100644
--- a/src/net_processing.cpp
+++ b/src/net_processing.cpp
@@ -972,6 +972,7 @@ void PeerManagerImpl::ReattemptInitialBroadcast(CScheduler& scheduler)
 void PeerManagerImpl::FinalizeNode(const CNode& node)
 {
     NodeId nodeid = node.GetId();
+    {
     LOCK(cs_main);
     int misbehavior{0};
     {
@@ -990,14 +991,6 @@ void PeerManagerImpl::FinalizeNode(const CNode& node)
     if (state->fSyncStarted)
         nSyncStarted--;
 
-    if (node.fSuccessfullyConnected && misbehavior == 0 &&
-        !node.IsBlockOnlyConn() && !node.IsInboundConn()) {
-        // Only change visible addrman state for full outbound peers.  We don't
-        // call Connected() for feeler connections since they don't have
-        // fSuccessfullyConnected set.
-        m_addrman.Connected(node.addr);
-    }
-
     for (const QueuedBlock& entry : state->vBlocksInFlight) {
         mapBlocksInFlight.erase(entry.hash);
     }
@@ -1022,6 +1015,14 @@ void PeerManagerImpl::FinalizeNode(const CNode& node)
         assert(m_wtxid_relay_peers == 0);
         assert(m_txrequest.Size() == 0);
     }
+    } // cs_main
+    if (node.fSuccessfullyConnected && misbehavior == 0 &&
+        !node.IsBlockOnlyConn() && !node.IsInboundConn()) {
+        // Only change visible addrman state for full outbound peers.  We don't
+        // call Connected() for feeler connections since they don't have
+        // fSuccessfullyConnected set.
+        m_addrman.Connected(node.addr);
+    }
     LogPrint(BCLog::NET, "Cleared nodestate for peer=%d\n", nodeid);
 }

Comment (jnewbery) [reply src/net_processing.cpp]: I'm really not convinced that it matters, but I've taken your diff.

**Comment by jnewbery** [comment]
@MarcoFalke - I've taken your suggested diff.

File: src/net_processing.cpp (hunk 9 above)
Comment (MarcoFalke) [reply src/net_processing.cpp]: Sorry, I didn't type `make` after writing the diff. Looks like ci doesn't like me.

Comment (jnewbery) [reply src/net_processing.cpp]: ah indeed. Fails compilation because `misbehavior` isn't in the outer scope. I've now fixed.

**Comment by MarcoFalke** [comment]
re-ACK 06653e4aaccc84dc7773d3888f687cf44e20abcd 🕸

Only changes:
* Add missing m_node.addrman.reset() in tests
* Remove unused symbols random_service and random_address in tests
* Add commit 06653e4aac

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

re-ACK 06653e4aaccc84dc7773d3888f687cf44e20abcd 🕸

Only changes:
* Add missing m_node.addrman.reset() in tests
* Remove unused symbols random_service and random_address in tests
* Add commit 06653e4aac
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUh2TQwAuta5eICUDWp5ZOK6mqTbXME6W4oZ2tq4JrradpQgatb0gd7Cvl9voHBS
95imHMkW8gS8qyTS5lCJfmaGZs6GsANQ4WY/SSMDAYPZHR7UUnicrlP5hBE1zUP0
olJXiIu/cNeTibA2gImd1bwxW11h3UII6R8fZ91lLHBTlsakqgX84n1fsRmOHdn7
UG4S6VDK9qceJ/dNTbww56vEn7hnrE9t0FUmFNqb6Yb5LgkG11Bw9XA71urWcFjc
2nvl4CBmZI73SzCyPtcyQ8iYuL6INtg6Rt6BtV6ff8Xm9cYB28cvkP6PFwjp4SHw
Zns+ZiBshcMWgODAvaetrCQNVHo597lW94zfCrSRrhsIVWw9TK6sTJRpkJRLMNxv
6ASeEetu7cME/nFHzabA+PV6nhQIcHoaczCZfdkiY+n1u83KJGvyEl3c12LW/rLT
yjNU8VV/34GM7Fr+HmjK1TJx3aBdcurK+4sNorAr+7JiAovtqTTjEavKYnoeftmm
N1OnbouT
=MOU8
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `04be068a42318cb4f710b8b8d5521a5bda7090c95bd0fa710e8d6dbc7a70894e  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010804be068a42318cb4f710b8b8d5521a5bda7090c95bd0fa710e8d6dbc7a70894ef0106b681ee27c92d6af514f057dec686f2b08fff010651420f9326a3c4c0f3183a9f06fa8ca08f10460586a5bf0080e8d5c9845ba11150083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff010678b8c1f3559a08d0259f0c52ec0026d08f10460585c84f008d8545a2a995c59ac0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff0109a3f58ada9f6e205c0bd3513237d82f708f10460586a5bf00860d97b0879d548d80083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6df010a862f07f2504cb1e04db9be29a33e61d08f1204aca68cd802afa0900011b1d7ecca286edc60978ce6c7afd6f5759a28977ed2908f10460586a5af00821206823e6e133d20083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by MarcoFalke** [comment]
Could squash the last two commits and mention that `--color-moved=dimmed-zebra` can be used on them for review?

**Comment by jnewbery** [comment]
> Could squash the last two commits

Done

> and mention that --color-moved=dimmed-zebra can be used on them for review?

I tried this and it wasn't very useful - there are only a couple of lines that are moved without changing.

**Comment by MarcoFalke** [comment]
re-ACK 3fc06d3d7b43dc1143fe0850db23c4e7ffbfe682 only change is squash 🏀

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

re-ACK 3fc06d3d7b43dc1143fe0850db23c4e7ffbfe682 only change is squash 🏀
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUhYRgv+NLihAeug6hwKodKc6lvG+BPtQdQqV3afHzM2iCE9UzX8UPEWDomfRpNr
/TCwhhMSaT1yKoWh3S9ePwDiVqEx0g9UPfJIfB0bZ20N94tDZY/L/9NXk4jxNlV7
0uqA5jtS93p3QggaVRhGOuOYUBXlgFC+kROYSLgAK9wuQmDI1X9NGlgx1h1tC3yt
qrGvDAuL+x1ALFYH6fOkAZHEwntte+lHPwymA9wktdPCntsmQaM7WimftLMK+z/H
47EYxadADEKJ84aLzeLzU2NJjb+Ow5OwEvsH6DdwcAazCrN5TnSWvpEso+EXP+qY
/CN7Iyy/beRbZsA0inj81zKs2P9k5sKvJuKvzdZLY+HjHcOBZnvB4TqgrSrlQ/sf
9smWO+ndxPc1vjakxxkB7ZFTVL+ju/sc9S14eD6zx9WAldtTeafz6/3YePo7IQlB
gq6AIW8HVsTDV0BHgjG3P2H+TclKtdT5pykhN781QhMuHVvfvkKs7p+dfCv7Lwxi
ugjJlKIA
=o4vy
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `a02bd2eb33e158baac0fe590960dabd93a73914fa44637c90c6b2566e605a7f5  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108a02bd2eb33e158baac0fe590960dabd93a73914fa44637c90c6b2566e605a7f5f0101805e3b6a239ed1e8d52c74120f918a708fff0104fcf9e974a1dd6c2d1d51e674f2bb60108f0201b97af5b7f2657988f2fe3f2b43c63f22c1c5620b5317e40baa955b886d27c5c08f020a2d4d670c37db30e22a84ef106675e943148b8f2317ab0dd3b398715620ca21808f1205f008b29dc23f538675ef2f2a5c0f89668e4903191a438b6c74aa291819303f108f020125369d571e97e6e72279cbad6eda12a3cc90110aedb65d2b6436b6be85e0ef508f1046058728cf00800f76de992cc390d0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0109d0ca8b7d1d1b85a382757c57bd89fc508f1046058728df008d46a91fdae4d188b0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff010bf622b67a5d96777b658c99d5f72ebf508f12051490204cea18e01fb69be8dc5049d74aeb54b84c561e767e38ff404cceb0d7f08f020506da4818a115ad0c2b689faa0368d343ffc3ab06b0209f542c8a6228ffbfe3808f120e4da5de34ef2939fbe48f7785ac81f3c709968e2ed461265ff65f0f44797216708f104605864b6f008ad9f6583953099530083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6df010ff2b173a5dedc96f2cb387c2d37ca78f08f0208d435ea084fb8837bdae627364e42c4ccd46c52710a6cd785771f545e8d3bfa308f1046058728df00860989d22249e16d80083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by jnewbery** [comment]
@vasild @sipa: Do you mind reACKing? There have only been minor changes since your last reviews.

**Review by vasild — APPROVED** [review]
ACK 3fc06d3d7b43dc1143fe0850db23c4e7ffbfe682

**Comment by jnewbery** [comment]
@sipa do you mind rereviewing this? It has two ACKs on the current branch.
