### PR TITLE
qt: Fix comparison function signature

### PR DESCRIPTION
**Pull request by hebasto**
This PR fixes build on CentOS 7 with GCC 4.8.5:

```
...
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from ./serialize.h:11,
                 from ./qt/sendcoinsrecipient.h:13,
                 from ./qt/recentrequeststablemodel.h:8,
                 from qt/recentrequeststablemodel.cpp:5:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = QList<RecentRequestEntry>::iterator; _Tp = RecentRequestEntry; _Compare = RecentRequestEntryLessThan]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = QList<RecentRequestEntry>::iterator; _Compare = RecentRequestEntryLessThan]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = QList<RecentRequestEntry>::iterator; _Size = int; _Compare = RecentRequestEntryLessThan]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = QList<RecentRequestEntry>::iterator; _Compare = RecentRequestEntryLessThan]’
qt/recentrequeststablemodel.cpp:208:82:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to ‘(RecentRequestEntryLessThan) (RecentRequestEntry&, const RecentRequestEntry&)’
    while (__comp(*__first, __pivot))
                                   ^
In file included from qt/recentrequeststablemodel.cpp:5:0:
./qt/recentrequeststablemodel.h:43:7: note: candidate is:
 class RecentRequestEntryLessThan
       ^
qt/recentrequeststablemodel.cpp:217:6: note: bool RecentRequestEntryLessThan::operator()(RecentRequestEntry&, RecentRequestEntry&) const
 bool RecentRequestEntryLessThan::operator()(RecentRequestEntry &left, RecentRequestEntry &right) const
      ^
qt/recentrequeststablemodel.cpp:217:6: note:   no known conversion for argument 2 from ‘const RecentRequestEntry’ to ‘RecentRequestEntry&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from ./serialize.h:11,
                 from ./qt/sendcoinsrecipient.h:13,
                 from ./qt/recentrequeststablemodel.h:8,
                 from qt/recentrequeststablemodel.cpp:5:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: no match for call to ‘(RecentRequestEntryLessThan) (const RecentRequestEntry&, RecentRequestEntry&)’
    while (__comp(__pivot, *__last))
                                  ^
In file included from qt/recentrequeststablemodel.cpp:5:0:
./qt/recentrequeststablemodel.h:43:7: note: candidate is:
 class RecentRequestEntryLessThan
       ^
qt/recentrequeststablemodel.cpp:217:6: note: bool RecentRequestEntryLessThan::operator()(RecentRequestEntry&, RecentRequestEntry&) const
 bool RecentRequestEntryLessThan::operator()(RecentRequestEntry &left, RecentRequestEntry &right) const
      ^
qt/recentrequeststablemodel.cpp:217:6: note:   no known conversion for argument 1 from ‘const RecentRequestEntry’ to ‘RecentRequestEntry&’
  CXX      qt/qt_libbitcoinqt_a-sendcoinsentry.o
make[2]: *** [qt/qt_libbitcoinqt_a-recentrequeststablemodel.o] Error 1
```

Also for `std::swap()` header `<algorithm>` is replaced with `<utility>` one.
Refs:
- [`std::swap()`](https://en.cppreference.com/w/cpp/algorithm/swap)
- [standard library header `<utility>`](https://en.cppreference.com/w/cpp/header/utility)

### CODE REVIEW

**Comment by paymog** [comment]
Does bitcoin only support C++11 and newer? If so, LGTM.

**Comment by hebasto** [comment]
> Does bitcoin only support C++11 and newer?

See #7165.

**Review by paymog — APPROVED** [review]
ACK

**Comment by jonasschnelli** [comment]
utACK 98fbd1cdffaa69357091cc67e959ac21119dfa16

**Comment by promag** [comment]
Code review ACK 98fbd1cdffaa69357091cc67e959ac21119dfa16.

**Review by fanquake — APPROVED** [review]
ACK 98fbd1cdffaa69357091cc67e959ac21119dfa16

Tested that this fixes the build in a [CentOS 7 Docker container](https://github.com/fanquake/core-review/blob/master/docker/centos.dockerfile).
Master (19698ac6bc0e6c75a92b02c8b74ae1fa51c34e08) fails with:
```bash
  CXX      qt/qt_libbitcoinqt_a-recentrequeststablemodel.o
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from ./serialize.h:11,
                 from ./qt/sendcoinsrecipient.h:13,
                 from ./qt/recentrequeststablemodel.h:8,
                 from qt/recentrequeststablemodel.cpp:5:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of '_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = QList<RecentRequestEntry>::iterator; _Tp = RecentRequestEntry; _Compare = RecentRequestEntryLessThan]':
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from '_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = QList<RecentRequestEntry>::iterator; _Compare = RecentRequestEntryLessThan]'
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from 'void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = QList<RecentRequestEntry>::iterator; _Size = int; _Compare = RecentRequestEntryLessThan]'
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from 'void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = QList<RecentRequestEntry>::iterator; _Compare = RecentRequestEntryLessThan]'
qt/recentrequeststablemodel.cpp:208:82:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to '(RecentRequestEntryLessThan) (RecentRequestEntry&, const RecentRequestEntry&)'
    while (__comp(*__first, __pivot))
                                   ^
In file included from qt/recentrequeststablemodel.cpp:5:0:
./qt/recentrequeststablemodel.h:43:7: note: candidate is:
 class RecentRequestEntryLessThan
       ^
qt/recentrequeststablemodel.cpp:217:6: note: bool RecentRequestEntryLessThan::operator()(RecentRequestEntry&, RecentRequestEntry&) const
 bool RecentRequestEntryLessThan::operator()(RecentRequestEntry &left, RecentRequestEntry &right) const
      ^
qt/recentrequeststablemodel.cpp:217:6: note:   no known conversion for argument 2 from 'const RecentRequestEntry' to 'RecentRequestEntry&'
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from ./serialize.h:11,
                 from ./qt/sendcoinsrecipient.h:13,
                 from ./qt/recentrequeststablemodel.h:8,
                 from qt/recentrequeststablemodel.cpp:5:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: no match for call to '(RecentRequestEntryLessThan) (const RecentRequestEntry&, RecentRequestEntry&)'
    while (__comp(__pivot, *__last))
                                  ^
In file included from qt/recentrequeststablemodel.cpp:5:0:
./qt/recentrequeststablemodel.h:43:7: note: candidate is:
 class RecentRequestEntryLessThan
       ^
qt/recentrequeststablemodel.cpp:217:6: note: bool RecentRequestEntryLessThan::operator()(RecentRequestEntry&, RecentRequestEntry&) const
 bool RecentRequestEntryLessThan::operator()(RecentRequestEntry &left, RecentRequestEntry &right) const
      ^
qt/recentrequeststablemodel.cpp:217:6: note:   no known conversion for argument 1 from 'const RecentRequestEntry' to 'RecentRequestEntry&'
make[2]: *** [qt/qt_libbitcoinqt_a-recentrequeststablemodel.o] Error 1
```

`std::swap` was defined in the `<algorithm>` header until `C++11`, and has been defined in `<utility>` since.

**Comment by hebasto** [comment]
@fanquake @MarcoFalke Backport to 0.19 ?

**Comment by fanquake** [comment]
Being backported as part of 17792.
