### PR TITLE
build: Drop boost-system dependency

### PR DESCRIPTION
**Pull request by hebasto**
There no reasons why the [`libboost-system-dev`](https://packages.ubuntu.com/bionic/libboost-system-dev) package could be required.

### CODE REVIEW

**Comment by fanquake** [comment]
Concept ACK. I had been thinking about splitting this out of #20744.

Does this work with Boost < 1.65.0?

You'll also need to drop `$BOOST_SYSTEM_LIB` from `BOOST_LIBS` in configure.ac.

**Comment by fanquake** [comment]
Actually, I looked at this too quickly. This doesn't modify/remove any of the `boost::system::error_code ec;` usage in our code?

**Comment by hebasto** [comment]
@fanquake 
> Actually, I looked at this too quickly. This doesn't modify/remove any of the `boost::system::error_code ec;` usage in our code?

```
$ git grep -n -e 'boost::system::error_code'
src/wallet/db.cpp:17:    boost::system::error_code ec;
src/wallet/db.cpp:81:    boost::system::error_code ec;
src/wallet/db.cpp:105:    boost::system::error_code ec;
src/wallet/load.cpp:23:        boost::system::error_code error
```

Interesting, why I have no errors during compiling and cross-compiling?

**Comment by fanquake** [comment]
> Interesting, why I have no errors during compiling and cross-compiling with depends?

If you try and build using Boost < 1.69.0, it will fail to link (1f65eac0b809ca4441cfaa6c9da4b9d3e47581d3):
```bash
make[2]: Leaving directory '/bitcoin'
  CXXLD    bitcoind
/usr/bin/ld: bitcoind-bitcoind.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:4980: recipe for target 'bitcoind' failed
make[1]: *** [bitcoind] Error 1

  AR       libbitcoin_wallet.a
  CXXLD    bitcoind
/usr/bin/ld: bitcoind-bitcoind.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:4980: recipe for target 'bitcoind' failed
make[1]: *** [bitcoind] Error 1
```

See the [Boost System revision history](https://www.boost.org/doc/libs/1_75_0/libs/system/doc/html/system.html#changes):
> Boost 1.69.0
> Boost.System is now header-only. A stub library is still built for compatibility, but linking to it is no longer necessary.

**Comment by laanwj** [comment]
> $ git grep -n -e 'boost::system::error_code'

Right-I don't think getting rid of `boost::system` makes sense before `boost::filesystem`. The error codes from `boost::system` are used internally all over the place.

**Comment by hebasto** [comment]
Closing in favor of #20744.
