### ISSUE TITLE
depends: `capnp` package fails to build on NetBSD 10.0

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#31499]
On the master branch @ b042c4f0538c6f9cdf8efbcef552796851e38a85:
- with GCC 12.4.0:
```
$ gmake -C depends capnp MULTIPROCESS=1 CC=/usr/pkg/gcc12/bin/gcc CXX=/usr/pkg/gcc12/bin/g++
<snip>
In file included from /home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-93b376fc421/src/kj/async.c++:42:
/home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-93b376fc421/src/kj/async.h:39:6: error: #error "Fibers cannot be enabled when exceptions are disabled."
   39 |     #error "Fibers cannot be enabled when exceptions are disabled."
      |      ^~~~~
gmake[3]: *** [src/kj/CMakeFiles/kj-async.dir/build.make:76: src/kj/CMakeFiles/kj-async.dir/async.c++.o] Error 1
<snip>
```
- with GCC 14.2.0:
```
$ gmake -C depends capnp MULTIPROCESS=1 CC=/usr/pkg/gcc14/bin/gcc CXX=/usr/pkg/gcc14/bin/g++
<snip>
In file included from /home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/memory.h:24,
                 from /home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/exception.h:24,
                 from /home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/async-prelude.h:27,
                 from /home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/async.h:24,
                 from /home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/async-io.h:24,
                 from /home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/async-io-unix.c++:35:
/home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/async-io-unix.c++: In lambda function:
/home/hebasto/dev/bitcoin/depends/work/build/x86_64-unknown-netbsd10.0/capnp/1.0.2-b73bfb1607d/src/kj/async-io-unix.c++:1243:24: error: 'AI_V4MAPPED' was not declared in this scope
 1243 |       hints.ai_flags = AI_V4MAPPED | AI_ADDRCONFIG;
      |                        ^~~~~~~~~~~
gmake[3]: *** [src/kj/CMakeFiles/kj-async.dir/build.make:146: src/kj/CMakeFiles/kj-async.dir/async-io-unix.c++.o] Error 1
<snip>
```

**Comment by hebasto** [comment]
cc @ryanofsky

**Comment by Winneremori** [comment]
Hi

**Comment by Sjors** [comment]
cc @vasild

**Comment by fanquake** [comment]
Shouldn't it be an upstream bug report, given that's where the issue is?

**Comment by fanquake** [comment]
Nothing for us to do here, so could be reopened/linked from a PR once a proper issue is filed upstream.

**Comment by hebasto** [comment]
> Shouldn't this be an upstream bug report, given that's where the issue is?

https://github.com/capnproto/capnproto/issues/2201.
