### PR TITLE
depends: fix mingw-w64 Qt DEBUG=1 build

### LINKED ISSUE #29734: qt: Windows build with DEBUG=1 is broken
If you try and cross-compile for Windows using master (d04324a7056a735c1127ba8ccdc720a16e7281a3) `DEBUG=1`, it fails. This is on a Ubuntu Noble machine, with `x86_64-w64-mingw32-g++ (GCC) 13-win32`. Noticed in #29527.
```bash
make -C depends HOST=x86_64-w64-mingw32 DEBUG=1 -j17
<snip>
Checking for STL compatibility... 
+ cd /root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/config.tests/stl && PKG_CONFIG_SYSROOT_DIR=/ PKG_CONFIG_LIBDIR=/root/ci_scratch/depends/x86_64-w64-mingw32/lib/pkgconfig /root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/qtbase/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += static warn_off console single_arch" 'QMAKE_CFLAGS = '\''-pipe -std=c11 -O1 -g  -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -I/root/ci_scratch/depends/x86_64-w64-mingw32/include'\''' 'QMAKE_CXX = '\''x86_64-w64-mingw32-g++-posix'\''' 'QMAKE_CXXFLAGS = '\''-pipe -std=c++20 -O1 -g  -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -I/root/ci_scratch/depends/x86_64-w64-mingw32/include'\''' 'QMAKE_LFLAGS = '\''  -L/root/ci_scratch/depends/x86_64-w64-mingw32/lib'\''' 'QMAKE_LIB = '\''x86_64-w64-mingw32-ar rc'\''' -early "CONFIG += cross_compile" /root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/qtbase/config.tests/stl
+ cd /root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/config.tests/stl && MAKEFLAGS= /usr/bin/gmake
> gmake[1]: Entering directory '/root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/config.tests/stl'
> x86_64-w64-mingw32-g++-posix -c -pipe -std=c++20 -O1 -g  -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -I/root/ci_scratch/depends/x86_64-w64-mingw32/include -O2 -w -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -I/root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/qtbase/config.tests/stl -I. -I/root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/qtbase/mkspecs/win32-g++  -o stltest.o /root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/qtbase/config.tests/stl/stltest.cpp
> x86_64-w64-mingw32-g++ -L/root/ci_scratch/depends/x86_64-w64-mingw32/lib -Wl,-s -Wl,-subsystem,console -mthreads -o stl.exe stltest.o  
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text+0x809): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text+0x81d): undefined reference to `pthread_mutex_unlock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x2ce): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x2e7): undefined reference to `pthread_mutex_unlock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x3c0): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x3d9): undefined reference to `pthread_mutex_unlock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x4b6): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x4cf): undefined reference to `pthread_mutex_unlock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x5ac): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text$_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_[_ZSt4findIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS7_EESt26random_access_iterator_tagEEiET_SF_SF_RKT0_]+0x5c5): undefined reference to `pthread_mutex_unlock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text$_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS5_EESt26random_access_iterator_tagSt20back_insert_iteratorISA_EET3_RKN11__gnu_debug14_Safe_iteratorIT0_T1_T2_EESM_SE_[_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS5_EESt26random_access_iterator_tagSt20back_insert_iteratorISA_EET3_RKN11__gnu_debug14_Safe_iteratorIT0_T1_T2_EESM_SE_]+0x352): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text$_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS5_EESt26random_access_iterator_tagSt20back_insert_iteratorISA_EET3_RKN11__gnu_debug14_Safe_iteratorIT0_T1_T2_EESM_SE_[_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPiNSt9__cxx19986vectorIiSaIiEEEEENSt7__debug6vectorIiS5_EESt26random_access_iterator_tagSt20back_insert_iteratorISA_EET3_RKN11__gnu_debug14_Safe_iteratorIT0_T1_T2_EESM_SE_]+0x36b): undefined reference to `pthread_mutex_unlock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text.startup+0x60b): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text.startup+0x62a): undefined reference to `pthread_mutex_unlock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_lock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:749:(.text.startup+0x84b): undefined reference to `pthread_mutex_lock'
> /usr/bin/x86_64-w64-mingw32-ld: stltest.o: in function `__gthread_mutex_unlock':
> /usr/lib/gcc/x86_64-w64-mingw32/13-posix/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:779:(.text.startup+0x879): undefined reference to `pthread_mutex_unlock'
> collect2: error: ld returned 1 exit status
> gmake[1]: *** [Makefile:69: stl.exe] Error 1
> gmake[1]: Leaving directory '/root/ci_scratch/depends/work/build/x86_64-w64-mingw32/qt/5.15.11-8c515c34c2a/config.tests/stl'
test config.qtbase.tests.stl FAILED
<snip>
Note: Using static linking will disable the use of dynamically
loaded plugins. Make sure to import all needed static plugins,
or compile needed modules into the library.

ERROR: Qt requires a compliant STL library.
make: *** [funcs.mk:298: /root/ci_scratch/depends/x86_64-w64-mingw32/.qt_stamp_configured] Error 3
make: Leaving directory '/root/ci_scratch/depends'
```

### PR DESCRIPTION
**Pull request by fanquake**
The issue is that compilation is done with `x86_64-w64-mingw32-g++-posix`, but then linking is done with `x86_64-w64-mingw32-g++`.

I'm guessing this has been broken since #24131 (01d1845a80ae48d741deea695ddce95d940ab0d8), but have not checked.

Fixes #29734.
Unblocks #29527 (`DEBUG=1` builds can be tested).

### CODE REVIEW

**Comment by fanquake** [comment]
Guix Build (aarch64):
```bash
979178d40158693d10fef1897f3dfd1f0fbfd008a92b1fd27713cb66e5b8b8fa  guix-build-b7e7e727abd8/output/aarch64-linux-gnu/SHA256SUMS.part
36bf67bc413ede45788a1f1cb31c83839d0f59c49e8bbf52e811854a54fe936c  guix-build-b7e7e727abd8/output/aarch64-linux-gnu/bitcoin-b7e7e727abd8-aarch64-linux-gnu-debug.tar.gz
8a5331e33ab1a23eb037841127905cbc2346ca5b84b6d1dbc6cd0a2682a4b0a5  guix-build-b7e7e727abd8/output/aarch64-linux-gnu/bitcoin-b7e7e727abd8-aarch64-linux-gnu.tar.gz
12d03eb52ef823231b2afc4632a70139ff3e7195966c76090f5da640c90f0695  guix-build-b7e7e727abd8/output/arm-linux-gnueabihf/SHA256SUMS.part
88ba75a674bb8ec537dfefdeac43785be0621ed4241be8cb858514498d98b1ef  guix-build-b7e7e727abd8/output/arm-linux-gnueabihf/bitcoin-b7e7e727abd8-arm-linux-gnueabihf-debug.tar.gz
356f9fb063360a49b263f326f1eabec36182c32a835019fb74aa7e2dc82c746e  guix-build-b7e7e727abd8/output/arm-linux-gnueabihf/bitcoin-b7e7e727abd8-arm-linux-gnueabihf.tar.gz
b7729d054d11f9d6a8e41cf511e3f0828cb5026878bce46951435cb56bdc1f4b  guix-build-b7e7e727abd8/output/arm64-apple-darwin/SHA256SUMS.part
0a69c56d7d6caf6dd9018be08f18cca7ee3007d2a10f31fa4cb25698a5b0ff7a  guix-build-b7e7e727abd8/output/arm64-apple-darwin/bitcoin-b7e7e727abd8-arm64-apple-darwin-unsigned.tar.gz
9ff5fb61733fa9c835118b40eb2afdf0d3c383765d03bb8d7ab62d3f527fdc5e  guix-build-b7e7e727abd8/output/arm64-apple-darwin/bitcoin-b7e7e727abd8-arm64-apple-darwin-unsigned.zip
dccd31f8e0be03848ae6d122536939821d1f37fe35a737651cf3a47dccd11eb3  guix-build-b7e7e727abd8/output/arm64-apple-darwin/bitcoin-b7e7e727abd8-arm64-apple-darwin.tar.gz
4c8169021c505f45d144cffe4a5db307e23a21c6e9dc7ad80a6fc396ada8fcca  guix-build-b7e7e727abd8/output/dist-archive/bitcoin-b7e7e727abd8.tar.gz
3c315c7872a4b818474525775f8b0ffadbe1ff61e84b274cd579593161665fd9  guix-build-b7e7e727abd8/output/powerpc64-linux-gnu/SHA256SUMS.part
f512dcf753b266530455fe2618be5f8717d9175a24c3b0c59b02b620f3bf2930  guix-build-b7e7e727abd8/output/powerpc64-linux-gnu/bitcoin-b7e7e727abd8-powerpc64-linux-gnu-debug.tar.gz
0274dd47a0a9ccb56253af179a7c9b9a56dad6a563ccf47921389f1ea492613b  guix-build-b7e7e727abd8/output/powerpc64-linux-gnu/bitcoin-b7e7e727abd8-powerpc64-linux-gnu.tar.gz
4d63408693a66ff21710e4eb2f669ec91e310260c64f5826d59721c93e781d15  guix-build-b7e7e727abd8/output/riscv64-linux-gnu/SHA256SUMS.part
5e2838f9819edf3fca5364e807f9453e441ed214b3ead54f3f46f584b71ec4e5  guix-build-b7e7e727abd8/output/riscv64-linux-gnu/bitcoin-b7e7e727abd8-riscv64-linux-gnu-debug.tar.gz
2f24933969e28412493a7ee1cdf381ead4282a5cac8777927216d1b58407e730  guix-build-b7e7e727abd8/output/riscv64-linux-gnu/bitcoin-b7e7e727abd8-riscv64-linux-gnu.tar.gz
163ee9499534224abe95e92f10c97303035fbf8eb769f25e5bba4b07b2f39923  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/SHA256SUMS.part
8a7e93ee54cb8916d84f577ad3872ae6192a99689ecd7b1cfe5d6fb8092a3363  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/bitcoin-b7e7e727abd8-x86_64-apple-darwin-unsigned.tar.gz
40e3510fa899127dcb042e67d5d982f19dbd684afdf9169967f544b593189723  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/bitcoin-b7e7e727abd8-x86_64-apple-darwin-unsigned.zip
3bc71d190d783d5f16da7350ed007fbb8a82504715f12ca5fe23f691cf042a9a  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/bitcoin-b7e7e727abd8-x86_64-apple-darwin.tar.gz
f332354ca500aa3ae7eec0ad2717f8d37815836147aec7a9481e9a6e8b3136b7  guix-build-b7e7e727abd8/output/x86_64-linux-gnu/SHA256SUMS.part
e8c32366e9e8a91097fbb8ec3dc820f4dcc4cb94ba4321e39ab5803d10019172  guix-build-b7e7e727abd8/output/x86_64-linux-gnu/bitcoin-b7e7e727abd8-x86_64-linux-gnu-debug.tar.gz
fea1c60824284df3bc55de9649677baef838f780a23b7cb36c811ab5d4608f70  guix-build-b7e7e727abd8/output/x86_64-linux-gnu/bitcoin-b7e7e727abd8-x86_64-linux-gnu.tar.gz
f6616cad45ea4a0079a9d4a795ae5213841c6278909bdb53e0efeb90da1b0e62  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/SHA256SUMS.part
2defacfab80d43611f8d044e4dfe6772d88e4ef4ee558d41edbc70e3e61ab4bb  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64-debug.zip
af3385820b56abe07734812560fcd238ebd8370f6cb8a15b81ca81b353ce18a3  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64-setup-unsigned.exe
eed062fcd8b58e86d855b6898e70ffed84066ac779d530d354698d4f868ab1bf  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64-unsigned.tar.gz
944d248217126efbf2e25e3e71f26c46dc64db6852b8b8e2b0bc01c76a650274  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64.zip
```

**Review by hebasto — APPROVED** [review]
ACK b7e7e727abd86104ee58beb648a94e2f453d1f6d, tested on Ubuntu 22.04 with the [installed](https://github.com/bitcoin/bitcoin/issues/29734#issuecomment-2022852344) `g++-mingw-w64-x86-64` package.

**Review by sedited — APPROVED** [review]
ACK b7e7e727abd86104ee58beb648a94e2f453d1f6d

Guix builds (x86_64)
```
979178d40158693d10fef1897f3dfd1f0fbfd008a92b1fd27713cb66e5b8b8fa  guix-build-b7e7e727abd8/output/aarch64-linux-gnu/SHA256SUMS.part
36bf67bc413ede45788a1f1cb31c83839d0f59c49e8bbf52e811854a54fe936c  guix-build-b7e7e727abd8/output/aarch64-linux-gnu/bitcoin-b7e7e727abd8-aarch64-linux-gnu-debug.tar.gz
8a5331e33ab1a23eb037841127905cbc2346ca5b84b6d1dbc6cd0a2682a4b0a5  guix-build-b7e7e727abd8/output/aarch64-linux-gnu/bitcoin-b7e7e727abd8-aarch64-linux-gnu.tar.gz
12d03eb52ef823231b2afc4632a70139ff3e7195966c76090f5da640c90f0695  guix-build-b7e7e727abd8/output/arm-linux-gnueabihf/SHA256SUMS.part
88ba75a674bb8ec537dfefdeac43785be0621ed4241be8cb858514498d98b1ef  guix-build-b7e7e727abd8/output/arm-linux-gnueabihf/bitcoin-b7e7e727abd8-arm-linux-gnueabihf-debug.tar.gz
356f9fb063360a49b263f326f1eabec36182c32a835019fb74aa7e2dc82c746e  guix-build-b7e7e727abd8/output/arm-linux-gnueabihf/bitcoin-b7e7e727abd8-arm-linux-gnueabihf.tar.gz
b7729d054d11f9d6a8e41cf511e3f0828cb5026878bce46951435cb56bdc1f4b  guix-build-b7e7e727abd8/output/arm64-apple-darwin/SHA256SUMS.part
0a69c56d7d6caf6dd9018be08f18cca7ee3007d2a10f31fa4cb25698a5b0ff7a  guix-build-b7e7e727abd8/output/arm64-apple-darwin/bitcoin-b7e7e727abd8-arm64-apple-darwin-unsigned.tar.gz
9ff5fb61733fa9c835118b40eb2afdf0d3c383765d03bb8d7ab62d3f527fdc5e  guix-build-b7e7e727abd8/output/arm64-apple-darwin/bitcoin-b7e7e727abd8-arm64-apple-darwin-unsigned.zip
dccd31f8e0be03848ae6d122536939821d1f37fe35a737651cf3a47dccd11eb3  guix-build-b7e7e727abd8/output/arm64-apple-darwin/bitcoin-b7e7e727abd8-arm64-apple-darwin.tar.gz
4c8169021c505f45d144cffe4a5db307e23a21c6e9dc7ad80a6fc396ada8fcca  guix-build-b7e7e727abd8/output/dist-archive/bitcoin-b7e7e727abd8.tar.gz
3c315c7872a4b818474525775f8b0ffadbe1ff61e84b274cd579593161665fd9  guix-build-b7e7e727abd8/output/powerpc64-linux-gnu/SHA256SUMS.part
f512dcf753b266530455fe2618be5f8717d9175a24c3b0c59b02b620f3bf2930  guix-build-b7e7e727abd8/output/powerpc64-linux-gnu/bitcoin-b7e7e727abd8-powerpc64-linux-gnu-debug.tar.gz
0274dd47a0a9ccb56253af179a7c9b9a56dad6a563ccf47921389f1ea492613b  guix-build-b7e7e727abd8/output/powerpc64-linux-gnu/bitcoin-b7e7e727abd8-powerpc64-linux-gnu.tar.gz
4d63408693a66ff21710e4eb2f669ec91e310260c64f5826d59721c93e781d15  guix-build-b7e7e727abd8/output/riscv64-linux-gnu/SHA256SUMS.part
5e2838f9819edf3fca5364e807f9453e441ed214b3ead54f3f46f584b71ec4e5  guix-build-b7e7e727abd8/output/riscv64-linux-gnu/bitcoin-b7e7e727abd8-riscv64-linux-gnu-debug.tar.gz
2f24933969e28412493a7ee1cdf381ead4282a5cac8777927216d1b58407e730  guix-build-b7e7e727abd8/output/riscv64-linux-gnu/bitcoin-b7e7e727abd8-riscv64-linux-gnu.tar.gz
163ee9499534224abe95e92f10c97303035fbf8eb769f25e5bba4b07b2f39923  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/SHA256SUMS.part
8a7e93ee54cb8916d84f577ad3872ae6192a99689ecd7b1cfe5d6fb8092a3363  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/bitcoin-b7e7e727abd8-x86_64-apple-darwin-unsigned.tar.gz
40e3510fa899127dcb042e67d5d982f19dbd684afdf9169967f544b593189723  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/bitcoin-b7e7e727abd8-x86_64-apple-darwin-unsigned.zip
3bc71d190d783d5f16da7350ed007fbb8a82504715f12ca5fe23f691cf042a9a  guix-build-b7e7e727abd8/output/x86_64-apple-darwin/bitcoin-b7e7e727abd8-x86_64-apple-darwin.tar.gz
f332354ca500aa3ae7eec0ad2717f8d37815836147aec7a9481e9a6e8b3136b7  guix-build-b7e7e727abd8/output/x86_64-linux-gnu/SHA256SUMS.part
e8c32366e9e8a91097fbb8ec3dc820f4dcc4cb94ba4321e39ab5803d10019172  guix-build-b7e7e727abd8/output/x86_64-linux-gnu/bitcoin-b7e7e727abd8-x86_64-linux-gnu-debug.tar.gz
fea1c60824284df3bc55de9649677baef838f780a23b7cb36c811ab5d4608f70  guix-build-b7e7e727abd8/output/x86_64-linux-gnu/bitcoin-b7e7e727abd8-x86_64-linux-gnu.tar.gz
f6616cad45ea4a0079a9d4a795ae5213841c6278909bdb53e0efeb90da1b0e62  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/SHA256SUMS.part
2defacfab80d43611f8d044e4dfe6772d88e4ef4ee558d41edbc70e3e61ab4bb  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64-debug.zip
af3385820b56abe07734812560fcd238ebd8370f6cb8a15b81ca81b353ce18a3  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64-setup-unsigned.exe
eed062fcd8b58e86d855b6898e70ffed84066ac779d530d354698d4f868ab1bf  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64-unsigned.tar.gz
944d248217126efbf2e25e3e71f26c46dc64db6852b8b8e2b0bc01c76a650274  guix-build-b7e7e727abd8/output/x86_64-w64-mingw32/bitcoin-b7e7e727abd8-win64.zip
```

**Comment by fanquake** [comment]
Backported to 27.x in #29888.

**Comment by glozow** [comment]
backported to 26.x in #29899
