### ISSUE TITLE
QT4 build broken after #10420

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#10452]
Not exactly sure how broken, see comment from @pstratem https://github.com/bitcoin/bitcoin/pull/10420#issuecomment-303908782.

**Comment by ryanofsky** [comment]
I'm seeing:

```
In file included from /usr/include/qt4/QtGui/QWidget:1:0,
                 from ./qt/bitcoinamountfield.h:10,
                 from qt/test/wallettests.cpp:3:
/usr/include/qt4/QtGui/qwidget.h: In function ‘void {anonymous}::BumpFee(TransactionView&, const uint256&, bool, std::__cxx11::string, bool)’:
/usr/include/qt4/QtGui/qwidget.h:651:10: error: ‘void QWidget::customContextMenuRequested(const QPoint&)’ is protected
     void customContextMenuRequested(const QPoint &pos);
          ^
qt/test/wallettests.cpp:105:41: error: within this context
     table->customContextMenuRequested({});
                                         ^
```

**Comment by ryanofsky** [comment]
#10454 should hopefully fix

**Comment by jonasschnelli** [comment]
Solved by @10454
