### PR TITLE
[depends] Add -stdlib=libc++ to darwin CXX flags

### LINKED ISSUE #7998: [depends] Boost fails to build on OSX 10.11, Xcode 7.3.1
```
clang: warning: optimization flag '-finline-functions' is not supported
In file included from libs/thread/src/pthread/once.cpp:8:
In file included from libs/thread/src/pthread/./once_atomic.cpp:9:
In file included from ./boost/thread/once.hpp:20:
In file included from ./boost/thread/pthread/once_atomic.hpp:16:
./boost/thread/detail/move.hpp:31:10: fatal error: 'type_traits' file not found
#include <type_traits>
```

It seems adding `-stdlib=libc++` to the cxxflags fixes the issue

This also occurs with the `x86_64-apple-darwin11` prefix

### PR DESCRIPTION
**Pull request by fanquake**
Fixes #7998

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK 47eda2d8820b8161b6ef550af6575cbe4f1a3207

**Comment by theuni** [comment]
ut ACK https://github.com/bitcoin/bitcoin/commit/47eda2d8820b8161b6ef550af6575cbe4f1a3207
