### PR TITLE
wallet: add parent_desc to getaddressinfo

### PR DESCRIPTION
**Pull request by achow101**
Adds `parent_desc` field to the `getaddressinfo` RPC to export a public descriptor. Using the given address, `getaddressinfo` will look up which `DescriptorScriptPubKeyMan` can be used to produce that address. It will then return the descriptor for that `DescriptorScriptPubKeyMan` in the `parent_desc` field. The descriptor will be in a normalized form where the xpub at the last hardened step is derived so that the descriptor can be imported to other wallets. Tests are added to check that the correct descriptor is being returned for the wallet's addresses and that these descriptors can be imported and used in other wallets.

As part of this PR, a `ToNormalizedString` function is added to the descriptor classes. This really only has an effect on `BIP32PubkeyProvider`s that have hardened derivation steps. Tests are added to check that normalized descriptors are returned.

### CODE REVIEW

**Comment by Sjors** [comment]
Do we need a whole new RPC for this? Why not expand `getaddressinfo`?

**Comment by meshcollider** [comment]
Agree with Sjors, unless you have plans to somehow build upon this later, I think it might as well just be added to getaddressinfo

**Comment by achow101** [comment]
Changed this to be a new field `parent_desc` in `getaddressinfo`. Also rebased.

File: src/script/descriptor.cpp [hunk 1]
```diff
@@ -212,6 +215,18 @@ class OriginPubkeyProvider final : public PubkeyProvider
         ret = "[" + OriginString() + "]" + std::move(sub);
         return true;
     }
+    bool ToNormalizedString(const SigningProvider& arg, std::string& ret, bool priv) const override
+    {
+        std::string sub;
+        if (!m_provider->ToNormalizedString(arg, sub, priv)) return false;
+        if (sub[0] == '[') {
+            sub = sub.substr(10);
```
Comment (S3RK) [inline src/script/descriptor.cpp:223]: I'm not sure I fully understand this part. From what I figured here you're handling a case when we wrap another `OriginPubkeyProvider`. If so, I have a few questions:

1) What do we even expect to happen in such case? I can't think of realistic scenario
2) Why handle it here if we don't handle it in other methods, like `ToPrivateString` or `ToString()`
3) Why do you think the origin from wrapped provider is exactly `10` chars long? Even if so, than there is a closing bracket missing

Hope my questions make at least some sense

**Comment by Sjors** [comment]
Concept ACK. This has a silent merge conflict with either #19373 or #19660: `script/descriptor.cpp:455:34: error: no matching function for call to 'HexStr'`

File: src/script/descriptor.cpp [hunk 2]
```diff
@@ -243,6 +258,15 @@ class ConstPubkeyProvider final : public PubkeyProvider
         ret = EncodeSecret(key);
         return true;
     }
+    bool ToNormalizedString(const SigningProvider& arg, std::string& ret, bool priv) const override
+    {
+        if (priv) {
```
Comment (promag) [inline src/script/descriptor.cpp:263]:
```cpp
if (priv) return ToPrivateString(arg, ret);
ret = ToString();
return true;
```

**Review by promag — COMMENTED** [review]
Concept ACK.

File: src/script/descriptor.cpp (hunk 1 above)
Comment (achow101) [reply src/script/descriptor.cpp:223]: The goal of `ToNormalizedString` is to create a descriptor that can be imported into another wallet. A descriptor might not be able to be imported because hardened derivation is in use. So for `BIP32PubkeyProvider::ToNormalizedString`, we are deriving the key at the last hardened step and returning that key. As we did additional derivation not present in the original descriptor, we are generating new origin info that needs to be combined with any existing origin info.

1. We don't actually wrap another `OriginPubkeyProvider`. Rather we might be wrapping a `BIP32PubkeyProvider` where it's `ToNormalizedString` might return us a string containing origin info as it did additional derivation.
2. `ToPrivateString` and `ToString` return the descriptor as-is, no additional derivation is done. Thus there is no need to handle this "origin within the origin provider."
3. This is to cut off the first 10 characters because we don't need them. Specifically, that's the `[` followed by 8 characters for the fingerprint, followed by the first `/`. Actually, there might be an off-by-one here as I think we need that `/`.

File: src/script/descriptor.cpp (hunk 2 above)
Comment (achow101) [reply src/script/descriptor.cpp:263]: Done

**Comment by achow101** [comment]
> Concept ACK. This has a silent merge conflict with either #19373 or #19660: `script/descriptor.cpp:455:34: error: no matching function for call to 'HexStr'`

Rebased and fixed.

File: src/script/descriptor.cpp (hunk 1 above)
Comment (S3RK) [reply src/script/descriptor.cpp]: I created and verified a test case to cover this part of code and which would have exposed the bug as well.
Feel free to add it.

```cpp
Check(
"pkh([01234567/10/20]xprv9s21ZrQH143K31xYSDQpPDxsXRTUcvj2iNHm5NUtrGiGG5e2DtALGdso3pGz6ssrdK4PFmM8NSpSBHNqPqm55Qn3LqFtT2emdEXVYsCzC2U/2147483647'/0)",
"pkh([01234567/10/20]xpub661MyMwAqRbcFW31YEwpkMuc5THy2PSt5bDMsktWQcFF8syAmRUapSCGu8ED9W6oDMSgv6Zz8idoc4a6mr8BDzTJY47LJhkJ8UB7WEGuduB/2147483647'/0)",
"pkh([01234567/10/20/2147483647']xprv9vHkqa6XAPwKqSKSEJMcAB3yoCZhaSVsGZbSkFY5L3Lfjjk8sjZucbsbvEw5o3QrSA69nPfZDCgFnNnLhQ2ohpZuwummndnPasDw2Qr6dC2/0)",
"pkh([01234567/10/20/2147483647']xpub69H7F5dQzmVd3vPuLKtcXJziMEQByuDidnX3YdwgtNsecY5HRGtAAQC5mXTt4dsv9RzyjgDjAQs9VGVV6ydYCHnprc9vvaA5YtqWyL6hyds/0)",
HARDENED,
{{"76a914ebdc90806a9c4356c1c88e42216611e1cb4c1c1788ac"}},
OutputType::LEGACY,
{{10,20,0xFFFFFFFFUL,0}}
);
```

Comment (achow101) [reply src/script/descriptor.cpp]: Added this test.

**Review by S3RK — COMMENTED** [review]
I believe it's cumbersome to work with normalised descriptor represented as a string. It has been proved to be prone to errors and also less expressive. Luckily we already have a struct for this!

What if we use object representation for such a descriptor and convert it to string only at the last step.
I have something like this in my mind:
1. Add `PubkeyProvider::GetLastUnhardenedKey(...)`. The function will be shorter and easier to understand than `ToNormalizedString` which does two things right now: a) derives the key and b) converts it to string.
2. Use it in `Descriptor::GetNormalizedDescriptor(...)`. By using `GetLastUnhardenedKey` it's obvious now what do we mean by "normalized" without going to deep into the code.
3. In `DescriptorScriptPubKeyMan::GetDescriptorString` we call `GetNormalizedDescriptor()` first and than use usual `ToPrivateSring()` or `ToString()` functions on the returned descriptor.

Another benefit of this approach is that we don't need more arguments and conditions in `ToStringHelepr`.

Let me know what you think, I can do a PoC if you'd endorse this idea.

**Comment by achow101** [comment]
@S3RK I originally attempted an approach like that but was not able to make it work well. The problem is largely in the same place that the problem with this PR is: nested origin pubkey providers. In both this PR and your proposal, you will still have some weirdness to handle when the bip32 pubkey provider returns an origin pubkey provider, but this itself is already within an origin pubkey provider.

**Comment by S3RK** [comment]
@achow101 I understand that it's an intrinsic part of the logic here. However my point is that we need to strive to make that weird part as easy to understand as possible. And this is why I believe working with objects/structs is better. When you work with `KeyOriginInfo` you don't need to rely on a magic number to strip the info from a string. Even bigger issue is not even the constant itself, but tight coupling of unrelated parts of the codebase — `BIP32PubkeyProvider` and `OriginPubkeyProvider` are now invisibly tied together by the convention of formatting origin info as a string.

The other benefits hold up as well: single responsibility and less cyclomatic complexity for functions, self-documented code.

**Comment by achow101** [comment]
@S3RK If you think you have a better solution, feel free to open a PR with it. I can close this one in favor of that if it does look better.

**Review by promag — COMMENTED** [review]
Add release note?

**Comment by S3RK** [comment]
> @S3RK If you think you have a better solution, feel free to open a PR with it. I can close this one in favor of that if it does look better.

For history. I tried to implement [alternative version](https://github.com/bitcoin/bitcoin/compare/master...S3RK:normalized_descriptor), and indeed it also has its own problems. Both with nested origin/bip32 providers and also with private key management for intermediate xpub. And the diff is bigger 😞

File: src/script/descriptor.cpp [hunk 3]
```diff
@@ -212,6 +215,18 @@ class OriginPubkeyProvider final : public PubkeyProvider
         ret = "[" + OriginString() + "]" + std::move(sub);
         return true;
     }
+    bool ToNormalizedString(const SigningProvider& arg, std::string& ret, bool priv) const override
+    {
+        std::string sub;
+        if (!m_provider->ToNormalizedString(arg, sub, priv)) return false;
+        if (sub[0] == '[') {
```
Comment (Sjors) [inline src/script/descriptor.cpp:222]: 6f5d66d2abfe241df9f27bf2b1e62e6604918034 : I'm confused about what's going on here. I assume related to this comment. Maybe explain the "weirdness" in a comment, and/or add a comment to the relevant test vector.
> you will still have some weirdness to handle when the bip32 pubkey provider returns an origin pubkey provider, but this itself is already within an origin pubkey provider.

**Review by Sjors — COMMENTED** [review]
e92546a looks mostly good, if only because the tests pass...

File: src/script/descriptor.h [hunk 4]
```diff
@@ -93,6 +93,9 @@ struct Descriptor {
     /** Convert the descriptor to a private string. This fails if the provided provider does not have the relevant private keys. */
     virtual bool ToPrivateString(const SigningProvider& provider, std::string& out) const = 0;
 
+    /** Convert the descriptor to a normalized string. Normalized descriptors have the xpub at the last hardened step. This fail if the provided provider does not have the private keys to derive that xpub. */
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/script/descriptor.h:96]: Fixed.

File: src/script/descriptor.h [hunk 5]
```diff
@@ -93,6 +93,9 @@ struct Descriptor {
...
+    virtual bool ToNormalizedString(const SigningProvider& provier, std::string& out, bool priv) const = 0;
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/script/descriptor.h:97]: Fixed.

File: src/script/descriptor.cpp (hunk 3 above)
Comment (achow101) [reply src/script/descriptor.cpp:225]: Added a comment.

**Comment by Sjors** [comment]
utACK de6b389d5db7b8426313c5be6fbd290f992c5aa8

File: src/script/descriptor.cpp [hunk 6]
```diff
@@ -386,6 +410,56 @@ class BIP32PubkeyProvider final : public PubkeyProvider
...
+    bool ToNormalizedString(const SigningProvider& arg, std::string& out, bool priv) const override
+    {
+        // For hardened derivation type, just return the typical string, nothing to normalize
+        if (m_derive == DeriveType::HARDENED) {
+            if (priv) return ToPrivateString(arg, out);
+            out = ToString();
+            return true;
+        }
+        // Step backwards to find the last hardened step in the path
+        int i = (int)m_path.size() - 1;
```
Comment (jonatack) [inline src/script/descriptor.cpp:422]: 9be1437c named cast per https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#Res-casts-named
``` suggestion
        int i = static_cast<int>(m_path.size()) - 1;
```

File: src/script/descriptor.cpp [hunk 7]
```diff
@@ -386,6 +410,56 @@ class BIP32PubkeyProvider final : public PubkeyProvider
...
+                std::copy(xprv.vchFingerprint, xprv.vchFingerprint + 4, origin.fingerprint);
+            }
+        }
+        // Build the remaining path
+        KeyPath end_path;
+        for (; k < (int)m_path.size(); ++k) {
+            end_path.push_back(m_path.at(k));
+        }
+        // Build the string
+        std::string origin_str = HexStr(origin.fingerprint) + FormatHDKeypath(origin.path);
```
Comment (jonatack) [inline src/script/descriptor.cpp:455]: 9be1437c49f986e8ed964d5f863b4bbcec340751
```suggestion
        const std::string origin_str = HexStr(origin.fingerprint) + FormatHDKeypath(origin.path);
```

File: src/script/descriptor.cpp [hunk 8]
```diff
@@ -243,6 +261,12 @@ class ConstPubkeyProvider final : public PubkeyProvider
         ret = EncodeSecret(key);
         return true;
     }
+    bool ToNormalizedString(const SigningProvider& arg, std::string& ret, bool priv) const override
```
Comment (jonatack) [inline src/script/descriptor.cpp:264]: 9be1437c49f986e8ed964d5f863b4bbcec340751 here and L218, maybe name the arg `out` like the header file declaration and the other definitions
```suggestion
    bool ToNormalizedString(const SigningProvider& arg, std::string& out, bool priv) const override
```

File: src/wallet/rpcwallet.cpp [hunk 9]
```diff
@@ -3663,6 +3663,7 @@ UniValue getaddressinfo(const JSONRPCRequest& request)
                         {RPCResult::Type::BOOL, "iswatchonly", "If the address is watchonly."},
                         {RPCResult::Type::BOOL, "solvable", "If we know how to spend coins sent to this address, ignoring the possible lack of private keys."},
                         {RPCResult::Type::STR, "desc", /* optional */ true, "A descriptor for spending coins sent to this address (only when solvable)."},
+                        {RPCResult::Type::STR, "parent_desc", /* optional */ true, "The descriptor used to derive this address if this is a descriptor wallet"},
```
Comment (jonatack) [inline src/wallet/rpcwallet.cpp:3666]: e4ac869

- missing period like the neighboring sentences and maybe add a comma
```suggestion
                        {RPCResult::Type::STR, "parent_desc", /* optional */ true, "The descriptor used to derive this address, if this is a descriptor wallet."},
```

- not sure, but maybe change from:

  "The descriptor used to derive this address, if this is a descriptor wallet."

  to

  "The descriptor used to derive this address, if generated by a descriptor wallet."

File: test/functional/wallet_descriptor.py [hunk 10]
```diff
@@ -140,5 +140,62 @@ def run_test(self):
...
+            self.log.info("Testing import of exported {} descriptor".format(addr_type))
+            imp_rpc.importdescriptors([{
+                'desc': desc,
+                'active': True,
+                'next_index': 11,
+                'timestamp': 'now',
+                'internal': internal
+            }])
+
+            for i in range(0, 10):
```
Comment (jonatack) [inline test/functional/wallet_descriptor.py:191]: de6b389 nit, if iterator is not used in the for-loop block
```suggestion
            for _ in range(0, 10):
```

File: test/functional/wallet_descriptor.py [hunk 11]
```diff
@@ -140,5 +140,62 @@ def run_test(self):
...
+                assert_equal('0', desc[int_idx])
+
+            self.log.info("Testing the same descriptor is returned for address type {} {}".format(addr_type, int_str))
+            for i in range(0, 10):
+                if internal:
+                    addr = exp_rpc.getrawchangeaddress(address_type=addr_type)
+                else:
+                    addr = exp_rpc.getnewaddress(address_type=addr_type)
+                test_desc = exp_rpc.getaddressinfo(addr)['parent_desc']
+                assert_equal(desc, test_desc)
```
Comment (jonatack) [inline test/functional/wallet_descriptor.py:180]: de6b389 nit, the `if internal...else...assert_equal` logic is repeated 4 times, maybe extract to a helper

**Review by jonatack — COMMENTED** [review]
Tested ACK de6b389d5db7b8426313c5be6fbd290f992c5aa8 modulo a few minor comments

**Review by fjahr — COMMENTED** [review]
Code review ACK de6b389d5db7b8426313c5be6fbd290f992c5aa8

Also did some light manual testing.

**Comment by S3RK** [comment]
Tested ACK de6b389

**Review by meshcollider — COMMENTED** [review]
Tested ACK de6b389d5db7b8426313c5be6fbd290f992c5aa8

**Comment by Priroch1979** [comment]
> เพิ่ม`parent_desc`ฟิลด์ไปยัง`getaddressinfo`RPC เพื่อเอ็กซ์พอร์ตตัวบอกสถานะสาธารณะ เมื่อใช้ที่อยู่ที่ระบุ`getaddressinfo`จะค้นหาซึ่ง`DescriptorScriptPubKeyMan`สามารถใช้สร้างที่อยู่นั้นได้ จากนั้นจะส่งคืน descriptor สำหรับสิ่งนั้น`DescriptorScriptPubKeyMan`ใน`parent_desc`ฟิลด์ descriptor จะอยู่ในรูปแบบที่เป็นมาตรฐานโดยที่ xpub ในขั้นตอนการชุบแข็งสุดท้ายได้รับมาเพื่อให้สามารถนำเข้า descriptor ไปยังกระเป๋าเงินอื่น ๆ ได้ มีการเพิ่มการทดสอบเพื่อตรวจสอบว่ามีการส่งคืนตัวบอกที่ถูกต้องสำหรับที่อยู่ของกระเป๋าเงินและตัวบ่งชี้เหล่านี้สามารถนำเข้าและใช้ในกระเป๋าเงินอื่น ๆ ได้
> 
> ในฐานะที่เป็นส่วนหนึ่งของ PR นี้`ToNormalizedString`ฟังก์ชันจะถูกเพิ่มลงในคลาส descriptor สิ่งนี้มีผลเฉพาะกับ`BIP32PubkeyProvider`s ที่มีขั้นตอนการทำให้แข็งขึ้นเท่านั้น มีการเพิ่มการทดสอบเพื่อตรวจสอบว่ามีการส่งคืนตัวบอกสถานะปกติ
