### ISSUE TITLE
build: build broken with older supported Boost

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#34101]
Broken by #33192.

Debian Bookworm
GCC 12.2.0
Boost 1.74.0 (our minimum supported is currently 1.73.0)
```bash
cmake -B build -DCMAKE_BUILD_TYPE=Debug
<snip>
/bitcoin/src/txrequest.cpp: In member function 'void TxRequestTracker::Impl::ReceivedInv(NodeId, const GenTxid&, bool, std::chrono::microseconds)':
/bitcoin/src/txrequest.cpp:583:35: error: 'boost::multi_index::multi_index_container<{anonymous}::Announcement, {anonymous}::Announcement_Indices>::index<{anonymous}::ByPeer>::type' {aka 'class boost::multi_index::detail::ordered_index<{anonymous}::ByPeerViewExtractor, std::less<std::tuple<long int, bool, const uint256&> >, boost::multi_index::detail::nth_layer<1, {anonymous}::Announcement, {anonymous}::Announcement_Indices, std::allocator<{anonymous}::Announcement> >, boost::mpl::v_item<{anonymous}::ByPeer, boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::ordered_unique_tag, boost::multi_index::detail::null_augment_policy>'} has no member named 'contains'
  583 |         if (m_index.get<ByPeer>().contains(ByPeerView{peer, true, gtxid.ToUint256()})) return;
      |                                   ^~~~~~~~
gmake[2]: *** [src/CMakeFiles/bitcoin_node.dir/build.make:1308: src/CMakeFiles/bitcoin_node.dir/txrequest.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /bitcoin/src/support/allocators/pool.h:17,
                 from /bitcoin/src/memusage.h:10,
                 from /bitcoin/src/core_memusage.h:10,
                 from /bitcoin/src/coins.h:10,
                 from /bitcoin/src/txmempool.h:9,
                 from /bitcoin/src/txmempool.cpp:6:
/bitcoin/src/txmempool.cpp: In member function 'CTxMemPool::ChangeSet::TxHandle CTxMemPool::ChangeSet::StageAddition(const CTransactionRef&, CAmount, int64_t, unsigned int, uint64_t, bool, int64_t, LockPoints)':
/bitcoin/src/txmempool.cpp:991:22: error: 'CTxMemPool::indexed_transaction_set' {aka 'class boost::multi_index::multi_index_container<CTxMemPoolEntry, CTxMemPool::CTxMemPoolEntry_Indices>'} has no member named 'contains'
  991 |     Assume(!m_to_add.contains(tx->GetHash()));
      |                      ^~~~~~~~
/bitcoin/src/util/check.h:125:51: note: in definition of macro 'Assume'
  125 | #define Assume(val) inline_assertion_check<false>(val, std::source_location::current(), #val)
      |                                                   ^~~
gmake[2]: *** [src/CMakeFiles/bitcoin_node.dir/build.make:1294: src/CMakeFiles/bitcoin_node.dir/txmempool.cpp.o] Error 1
```

Reported by @marcofleon.

**Comment by hebasto** [comment]
Is it a good time to consider bumping of the Boost minimum supported version?

**Comment by fanquake** [comment]
Looks like it might have been added in Boost 1.78.0: https://github.com/boostorg/multi_index/issues/35.

**Comment by maflcko** [comment]
> Is it a good time to consider bumping of the Boost minimum supported version?

I think there are users out there on Ubuntu:22.04 and Debian Bookworm, so breaking them seems a bit too early?

**Comment by l0rinc** [comment]
We could revert these instances, but in that case we have to make sure the CI catches these next time.
Let me know if there's anything you'd like me to do here.

**Comment by marcofleon** [comment]
> Looks like it might have been added in Boost 1.78.0

Just confirmed that 1.78.0 does build without errors.

**Comment by maflcko** [comment]
> We could revert these instances, but in that case we have to make sure the CI catches these next time.

I don't think it will be possible that CI catches "everything". In theory, the `ci/test/00_setup_env_native_previous_releases.sh` could be modified to run without depends to catch this, but then we wouldn't be checking depends. So a new ci config would have to be added. But that again will only check either gcc, or clang. So a new ci config will have to be added for both....

**Comment by hebasto** [comment]
> > Is it a good time to consider bumping of the Boost minimum supported version?
> 
> I think there are users out there on Ubuntu:22.04 and Debian Bookworm, so breaking them seems a bit too early?

FWIW, they could workaround using depends. For example, see https://github.com/bitcoin/bitcoin/pull/34103.

**Comment by l0rinc** [comment]
regardless of the workaround, I don't mind reverting to make it work with old boost again - we can enable the new clang-tidy rule without them as well.
I have reverted the above changes in https://github.com/bitcoin/bitcoin/pull/34095 - can someone please validate that it fixed the build with older boost?

**Comment by maflcko** [comment]
> > > Is it a good time to consider bumping of the Boost minimum supported version?
> > 
> > 
> > I think there are users out there on Ubuntu:22.04 and Debian Bookworm, so breaking them seems a bit too early?
> 
> FWIW, they could workaround using depends. For example, see [#34103](https://github.com/bitcoin/bitcoin/pull/34103).

Asking for a depends workaround when the only benefit is a `count()` vs `contains()` in two lines of code, seems a bit too much.

**Comment by hebasto** [comment]
> > > > Is it a good time to consider bumping of the Boost minimum supported version?
> > > 
> > > 
> > > I think there are users out there on Ubuntu:22.04 and Debian Bookworm, so breaking them seems a bit too early?
> > 
> > 
> > FWIW, they could workaround using depends. For example, see [#34103](https://github.com/bitcoin/bitcoin/pull/34103).
> 
> Asking for a depends workaround when the only benefit is a `count()` vs `contains()` in two lines of code, seems a bit too much.

It seems there’s nobody to ask :)

(see https://github.com/bitcoin/bitcoin/pull/34095#pullrequestreview-3594758109)

**Comment by maflcko** [comment]
> It seems there’s nobody to ask :)

Oh, I see you are referring to bumping from 1.73 to 1.74?  That seems fine, if there is no distro that ships with it.

**Comment by hebasto** [comment]
> > It seems there’s nobody to ask :)
> 
> Oh, I see you are referring to bumping from 1.73 to 1.74? That seems fine, if there is no distro that ships with it.

Done in https://github.com/bitcoin/bitcoin/pull/34107.
