### PR TITLE
tests: fix outdated include in blockfilter_index_tests

### PR DESCRIPTION
**Pull request by jamesob**
Build is currently failing due to bad merge of #15788 and #14121.

### CODE REVIEW

**Comment by fanquake** [comment]
tACK 89e8df1

fixes:
```
  CXXLD    bitcoin-tx
  CXXLD    bitcoin-wallet
  CXX      test/test_bitcoin-blockfilter_index_tests.o
test/blockfilter_index_tests.cpp:11:10: fatal error: 'test/test_bitcoin.h' file not found
#include <test/test_bitcoin.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [test/test_bitcoin-blockfilter_index_tests.o] Error 1
```

**Comment by jnewbery** [comment]
ACK 89e8df167432101ed1b9251a8ebf30fe0d4daa45. This fixes the build.

Thanks @jamesob !
