### ISSUE TITLE
bitcoind not compiling on Mac OS X 10.11.1

### ISSUE THREAD

**Issue by kirai** [bitcoin/bitcoin#7110]
I followed the instructions on:

https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md

Dependencies, "autogen.sh" and "configure" all run smoothly:
```
brew install autoconf automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf qt5 libevent
./autogen.sh
./configure --with-gui=qt5
```

But "make" stopped with this error:

```
 CXX      qt/qt_bitcoin_qt-bitcoin.o
In file included from qt/bitcoin.cpp:9:
In file included from ./qt/bitcoingui.h:14:
In file included from /usr/local/Cellar/qt5/5.5.1_2/include/QtWidgets/QLabel:1:
In file included from /usr/local/Cellar/qt5/5.5.1_2/include/QtWidgets/qlabel.h:37:
In file included from /usr/local/Cellar/qt5/5.5.1_2/include/QtWidgets/qframe.h:37:
In file included from /usr/local/Cellar/qt5/5.5.1_2/include/QtWidgets/qwidget.h:45:
/usr/local/Cellar/qt5/5.5.1_2/include/QtWidgets/qsizepolicy.h:44:24: error: variable has incomplete type 'class Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
                       ^
/usr/local/Cellar/qt5/5.5.1_2/include/QtWidgets/qsizepolicy.h:44:7: note: forward declaration of 'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/Cellar/qt5/5.5.1_2/include/QtWidgets/qsizepolicy.h:44:35: error: expected ';' after top level declarator
class Q_WIDGETS_EXPORT QSizePolicy
                                  ^
                                  ;
```

**Comment by paveljanik** [comment]
Do you have qt4 installed?
Please upload config.log.

**Comment by jonasschnelli** [comment]
He has qt5 installed. Must be related to OSX10.11.**1**. Same setup works on my OSX 10.11 machine. Will update now to 10.11.1 and check.

**Comment by jonasschnelli** [comment]
Works for me on `10.11.1`. Maybe try uninstall/reinstall qt5 over brew of try to switch to a older version (http://stackoverflow.com/questions/13477363/how-can-i-brew-link-a-specific-version).

If you still have problems, please post your `config.log` (pastebin).

**Comment by kirai** [comment]
- I just tried using "./configure" without specifying "--with-gui=qt5" but I get the same error.

- I have qt5 installed

- This is my config.log
[config.log.txt](https://github.com/bitcoin/bitcoin/files/45504/config.log.txt)

**Comment by paveljanik** [comment]
Do you have qt4 installed as well on your machine somewhere?

**Comment by laanwj** [comment]
Looks like an upstream problem with Qt developer headers. Can you compile other Qt5 applications?

**Comment by kirai** [comment]
```
pwd
/usr/local/Cellar
cd qt
qt/  qt5/
cd qt
ls
4.8.7
```
I'm going to reinstall qt

**Comment by jonasschnelli** [comment]
Hmm...

Differ your config.log. Could this be an issue:

```diff
-Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
+Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
```

I also see some boost issues on your config log.
Can you post the output of `brew info boost`?

Try to upgrade to the newest Xcode version.
Try to remove all brew qt5 and qt4 packages and reinstall qt5.5.1 (`brew install qt5`).

**Comment by kirai** [comment]
- I uninstalled all qt versions and run "brew install qt"

- I run "make" again and it worked!

- Just for reference:

I'm running Xcode 7.1.1, I think it is the latest stable build

Boost output:
```
brew info boost
boost: stable 1.59.0 (bottled), HEAD
Collection of portable C++ source libraries
http://www.boost.org
/usr/local/Cellar/boost/1.59.0 (10928 files, 454M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb
==> Dependencies
Optional: icu4c ✔
==> Options ```

**Comment by jonasschnelli** [comment]
Thanks for reporting! Closing.
