### PR TITLE
wallet, rpc: add anti-fee-sniping to `send` and `sendall`

### PR DESCRIPTION
**Pull request by ishaanam**
Currently, `send` and `sendall` don't do anti-fee-sniping because they don't use `CreateTransaction`. This PR adds anti-fee-sniping to these RPCs by calling `DiscourageFeeSniping` from `FinishTransaction` when the user does not specify a locktime.

### CODE REVIEW

**Comment by S3RK** [comment]
Concept ACK

**Comment by achow101** [comment]
ACK 5c9ac1456b7b4512845270cd850e5c33b643f575

A test for `send` would be nice as well.

File: test/functional/wallet_send.py [hunk 1]
```diff
@@ -142,7 +142,12 @@ def test_send(self, from_wallet, to_wallet=None, amount=None, data=None,
             return
 
         if locktime:
+            assert_equal(from_wallet.decoderawtransaction(from_wallet.gettransaction(res["txid"])["hex"])["locktime"], locktime)
```
Comment (achow101) [inline test/functional/wallet_send.py:145]: In 5101f054ce435ac653a3f5e780fca066e2f25088 "test: test sendall and send do anti-fee-sniping"

nit: `gettransaction` has a `verbose` argument that does the decoding so this doesn't need to call `decoderawtransaction`. Same below.

File: test/functional/wallet_sendall.py [hunk 2]
```diff
@@ -379,6 +379,20 @@ def sendall_with_maxconf(self):
...
+    def sendall_anti_fee_sniping(self):
+        self.log.info("Testing sendall does anti-fee-sniping when locktime is not specified")
+        self.add_utxos([10,11])
+        tx_from_wallet = self.test_sendall_success(sendall_args = [self.remainder_target])
+
+        assert_greater_than(tx_from_wallet["decoded"]["locktime"], tx_from_wallet["blockheight"] - 100)
+
+        self.add_utxos([10,11])
+        txid = self.wallet.sendall(recipients=[self.remainder_target], options={"locktime":0})["txid"]
+        tx_from_wallet = self.wallet.decoderawtransaction(self.wallet.getrawtransaction(txid))
```
Comment (achow101) [inline test/functional/wallet_sendall.py:392]: In 5101f054ce435ac653a3f5e780fca066e2f25088 "test: test sendall and send do anti-fee-sniping"

nit: `getrawtransaction` has a `verbosity` option that will do the decoding, so no need to call `decoderawtransaction` here.

File: test/functional/wallet_send.py [hunk 3]
```diff
@@ -142,7 +142,12 @@ def test_send(self, from_wallet, to_wallet=None, amount=None, data=None,
...
             return res
+        else:
+            if add_to_wallet:
+                decoded_tx = from_wallet.decoderawtransaction(from_wallet.gettransaction(res["txid"])["hex"])
+                assert_greater_than(decoded_tx["locktime"], 100)
```
Comment (achow101) [inline test/functional/wallet_send.py:150]: In 5101f054ce435ac653a3f5e780fca066e2f25088 "test: test sendall and send do anti-fee-sniping"

Shouldn't this check for `getblockcount() - 100`?

File: test/functional/wallet_send.py (hunk 1 above)
Comment (ishaanam) [reply test/functional/wallet_send.py]: Done

File: test/functional/wallet_sendall.py (hunk 2 above)
Comment (ishaanam) [reply test/functional/wallet_sendall.py]: Done

File: test/functional/wallet_send.py (hunk 3 above)
Comment (ishaanam) [reply test/functional/wallet_send.py]: Done

File: src/wallet/spend.h [hunk 4]
```diff
@@ -213,6 +213,7 @@ struct CreatedTransactionResult
         : tx(_tx), fee(_fee), fee_calc(_fee_calc), change_pos(_change_pos) {}
 };
 
+void DiscourageFeeSniping(CMutableTransaction& tx, FastRandomContext& rng_fast, interfaces::Chain& chain, const uint256& block_hash, int block_height);
```
Comment (luke-jr) [inline src/wallet/spend.h:216]: nit: blank line under this; ideally docs above

File: test/functional/wallet_send.py [hunk 5]
```diff
@@ -142,7 +142,12 @@ def test_send(self, from_wallet, to_wallet=None, amount=None, data=None,
             return
 
         if locktime:
+            assert_equal(from_wallet.gettransaction(txid=res["txid"], verbose=True)["decoded"]["locktime"], locktime)
             return res
+        else:
+            if add_to_wallet:
+                decoded_tx = from_wallet.decoderawtransaction(from_wallet.gettransaction(res["txid"])["hex"])
```
Comment (achow101) [inline test/functional/wallet_send.py:149]: In f348eadadd6099e7763f04eb3d42cfd8bba33146 "test: test sendall and send do anti-fee-sniping"

nit: `verbose` here too.

**Review by achow101 — COMMENTED** [review]
ACK f348eadadd6099e7763f04eb3d42cfd8bba33146

File: src/wallet/spend.h (hunk 4 above)
Comment (ishaanam) [reply src/wallet/spend.h:220]: Done

File: test/functional/wallet_send.py (hunk 5 above)
Comment (ishaanam) [reply test/functional/wallet_send.py]: Done

**Review by murchandamus — COMMENTED** [review]
Concept ACK and almost crACK d76f88051524971def5137a07ce2940dce1c33a9 except that there seems to be a type mix-up:
 
```
 wallet/rpc/spend.cpp:1299:20: error: no matching function for call to 'FinishTransaction'
            return FinishTransaction(pwallet, options, CMutableTransaction(*txr.tx));
                   ^~~~~~~~~~~~~~~~~
wallet/rpc/spend.cpp:79:17: note: candidate function not viable: expects an lvalue for 3rd argument
static UniValue FinishTransaction(const std::shared_ptr<CWallet> pwallet, const UniValue& options, CMutableTransaction& rawTx)
                ^
1 error generated.
```

**Comment by ishaanam** [comment]
Fixed silent merge conflict.

**Review by murchandamus — COMMENTED** [review]
ACK c8de459de6d22e37164583f078747facaeae69c6

**Comment by murchandamus** [comment]
I circled back to review, I think this has a merge conflict

**Review by luke-jr — CHANGES_REQUESTED** [review]
```diff
--- a/test/functional/wallet_import_rescan.py
+++ b/test/functional/wallet_import_rescan.py
@@ -293,6 +293,7 @@ class ImportRescanTest(BitcoinTestFramework):
                 add_to_wallet=False,
                 inputs=[unspent_txid_map[variant.initial_txid]],
                 outputs=[{ADDRESS_BCRT1_UNSPENDABLE : variant.initial_amount}],
+                locktime=0,
                 subtract_fee_from_outputs=[0]
             )
             variant.child_txid = child["txid"]
```

File: src/wallet/rpc/spend.cpp [hunk 6]
```diff
@@ -88,8 +88,21 @@ std::set<int> InterpretSubtractFeeFromOutputInstructions(const UniValue& sffo_in
...
 }
 
-static UniValue FinishTransaction(const std::shared_ptr<CWallet> pwallet, const UniValue& options, const CMutableTransaction& rawTx)
+static UniValue FinishTransaction(const std::shared_ptr<CWallet> pwallet, const UniValue& options, CMutableTransaction& rawTx)
 {
+    bool can_anti_fee_snipe = !options.exists("locktime");
+
+    for (const CTxIn& tx_in : rawTx.vin) {
+        // Can not be FINAL for locktime to work
+        can_anti_fee_snipe &= tx_in.nSequence != CTxIn::SEQUENCE_FINAL;
```
Comment (murchandamus) [inline src/wallet/rpc/spend.cpp:97]: In 8e5778a9fb6fbcbddd4ba87cc3f3caf41118592a (wallet, rpc: add anti-fee-sniping to `send` and `sendall`):

It seems to me that the `nSequence` check here is too restrictive. Locktime is disabled when _all_ sequences are set to final, but it seems to me that `can_anti_fee_snipe` would be set to `false` here, even if only one input’s sequence is set to final.

I’m not sure this would matter much in practice because most transactions would probably use the same sequence value for all inputs, but `can_anti_fee_snipe` should probably end up `true` if at least one `nSequence` is non-final?

Could you perhaps add a test that a transaction with final `nSequence` values does not get its `locktime` set, but one with mixed values and one with all non-final `nSequence` values both do?

**Comment by ishaanam** [comment]
> ```diff
> --- a/test/functional/wallet_import_rescan.py
> +++ b/test/functional/wallet_import_rescan.py
> @@ -293,6 +293,7 @@ class ImportRescanTest(BitcoinTestFramework):
>                  add_to_wallet=False,
>                  inputs=[unspent_txid_map[variant.initial_txid]],
>                  outputs=[{ADDRESS_BCRT1_UNSPENDABLE : variant.initial_amount}],
> +                locktime=0,
>                  subtract_fee_from_outputs=[0]
>              )
>              variant.child_txid = child["txid"]
> ```

Done

File: src/wallet/rpc/spend.cpp (hunk 6 above)
Comment (achow101) [reply src/wallet/rpc/spend.cpp:97]: > It seems to me that the `nSequence` check here is too restrictive. Locktime is disabled when _all_ sequences are set to final, but it seems to me that `can_anti_fee_snipe` would be set to `false` here, even if only one input’s sequence is set to final.

Currently `DiscourageFeeSniping` will assert if any sequence is final, so this check is appropriate for now. It also enforces that the sequences are either `MAX_SEQUENCE_NONFINAL` or `MAX_BIP125_RBF_SEQUENCE`, so this needs to be checking that as well otherwise an assertion will be hit. Or a commit could be added to relax those checks.

> Could you perhaps add a test that a transaction with final nSequence values does not get its locktime set, but one with mixed values and one with all non-final nSequence values both do?

I would also like to see tests for other sequence numbers as there is a risk of reaching an assertion here.

**Comment by murchandamus** [comment]
> > ```diff
> > --- a/test/functional/wallet_import_rescan.py
> > +++ b/test/functional/wallet_import_rescan.py
> > @@ -293,6 +293,7 @@ class ImportRescanTest(BitcoinTestFramework):
> >                  add_to_wallet=False,
> >                  inputs=[unspent_txid_map[variant.initial_txid]],
> >                  outputs=[{ADDRESS_BCRT1_UNSPENDABLE : variant.initial_amount}],
> > +                locktime=0,
> >                  subtract_fee_from_outputs=[0]
> >              )
> >              variant.child_txid = child["txid"]
> > ```
> 
> Done

It seems that you may have been working on an update, but it might not have been pushed. Is that possible?

**Comment by ishaanam** [comment]
> > > ```diff
> > > --- a/test/functional/wallet_import_rescan.py
> > > +++ b/test/functional/wallet_import_rescan.py
> > > @@ -293,6 +293,7 @@ class ImportRescanTest(BitcoinTestFramework):
> > >                  add_to_wallet=False,
> > >                  inputs=[unspent_txid_map[variant.initial_txid]],
> > >                  outputs=[{ADDRESS_BCRT1_UNSPENDABLE : variant.initial_amount}],
> > > +                locktime=0,
> > >                  subtract_fee_from_outputs=[0]
> > >              )
> > >              variant.child_txid = child["txid"]
> > > ```
> > 
> > 
> > Done
> 
> It seems that you may have been working on an update, but it might not have been pushed. Is that possible?

I pushed this change, but I had forgotten to comment until later.

File: src/wallet/rpc/spend.cpp (hunk 6 above)
Comment (S3RK) [reply src/wallet/rpc/spend.cpp:97]: > It also enforces that the sequences are either MAX_SEQUENCE_NONFINAL or MAX_BIP125_RBF_SEQUENCE, so this needs to be checking that as well otherwise an assertion will be hit. Or a commit could be added to relax those checks.

It seems like this part of the comment wasn't addressed

File: src/wallet/rpc/spend.cpp [hunk 7]
```diff
@@ -88,8 +88,21 @@ std::set<int> InterpretSubtractFeeFromOutputInstructions(const UniValue& sffo_in
...
+    }
+
+    if (can_anti_fee_snipe) {
+        LOCK(pwallet->cs_wallet);
```
Comment (S3RK) [inline src/wallet/rpc/spend.cpp:101]: I'm not clear why do we need a wallet lock here?

File: src/wallet/rpc/spend.cpp (hunk 6 above)
Comment (ishaanam) [reply src/wallet/rpc/spend.cpp]: > It also enforces that the sequences are either MAX_SEQUENCE_NONFINAL or MAX_BIP125_RBF_SEQUENCE, so this needs to be checking that as well otherwise an assertion will be hit. Or a commit could be added to relax those checks

I have added these checks to `FinishTransaction`.

File: src/wallet/rpc/spend.cpp (hunk 7 above)
Comment (ishaanam) [reply src/wallet/rpc/spend.cpp:108]: Here the wallet is locked because it runs `CWallet::GetLastBlockHash` and `CWallet::GetLastBlockHeight` which both require `pwallet->cs_wallet` to be locked.

**Review by murchandamus — COMMENTED** [review]
crACK b11d00d54ed3315901de1f53885433d864a93019

**Comment by murchandamus** [comment]
Hey @ishaanam, I noticed that this PR was rebased, but it is still set to Draft. Should this be marked as ready for review?

File: src/wallet/rpc/spend.cpp [hunk 8]
```diff
@@ -1293,7 +1306,8 @@ RPCHelpMan send()
             rawTx.vout.clear();
             auto txr = FundTransaction(*pwallet, rawTx, recipients, options, coin_control, /*override_min_fee=*/false);
 
-            return FinishTransaction(pwallet, options, CMutableTransaction(*txr.tx));
+            CMutableTransaction tx = CMutableTransaction(*txr.tx);
+            return FinishTransaction(pwallet, options, tx);
```
[the remark this answers is not in the document]
Comment (ishaanam) [reply src/wallet/rpc/spend.cpp:1343]: Because `FinishTransaction` now takes a `CMutableTransaction&` instead of a `const CMutableTransaction&`, we can't give it an rvalue.

File: src/wallet/rpc/spend.cpp [hunk 9]
```diff
@@ -95,8 +95,21 @@ std::set<int> InterpretSubtractFeeFromOutputInstructions(const UniValue& sffo_in
...
 }
 
-static UniValue FinishTransaction(const std::shared_ptr<CWallet> pwallet, const UniValue& options, const CMutableTransaction& rawTx)
+static UniValue FinishTransaction(const std::shared_ptr<CWallet> pwallet, const UniValue& options, CMutableTransaction& rawTx)
 {
+    bool can_anti_fee_snipe = !options.exists("locktime");
+
+    for (const CTxIn& tx_in : rawTx.vin) {
+        // Checks sequence values consistent with DiscourageFeeSniping
+        can_anti_fee_snipe &= (tx_in.nSequence == CTxIn::MAX_SEQUENCE_NONFINAL || tx_in.nSequence == MAX_BIP125_RBF_SEQUENCE);
```
[the remark this answers is not in the document]
Comment (ishaanam) [reply src/wallet/rpc/spend.cpp]: Done

**Comment by Sjors** [comment]
Concept ACK. Discovered this after I tried to implement it myself in #32892 :-)

I might be useful to borrow the idea from https://github.com/bitcoin/bitcoin/pull/32892/commits/642e4b6f37f5ceef2ac44b1b1c9527a660883d09 of renaming `DiscourageFeeSniping` to `MaybeDiscourageFeeSniping`. Right now the code that decides whether to do this is duplicated between `FinishTransaction` and `CreateTransactionInternal`. Both places look at `coin_control.m_locktime` and loop through the inputs, but implemented in slightly different ways.


In `wallet_send.py` it would be useful to check that a generated PSBT has the correct lock time (you could use either set `psbt` or use a watch-only wallet which always produces a PSBT).

**Review by murchandamus — COMMENTED** [review]
ACK aac0b6dd79b0db1e9d42a6f466709a61cfd1f69f

Compared to my prior ACK via range_diff, and only found this minor change and some changes due to the rebase.

```diff 
-        can_anti_fee_snipe &= (tx_in.nSequence == CTxIn::MAX_SEQUENCE_NONFINAL || tx_in.nSequence == MAX_BIP125_RBF_SEQUENCE);
+        can_anti_fee_snipe = can_anti_fee_snipe && (tx_in.nSequence == CTxIn::MAX_SEQUENCE_NONFINAL || tx_in.nSequence == MAX_BIP125_RBF_SEQUENCE);
```

Tested that the new tests fail without the first commit. Looked over again from scratch, looks good to me.

Thanks for the explanations.

I think that @Sjors’s suggestions could perhaps be addressed in a follow-up.

**Comment by achow101** [comment]
ACK aac0b6dd79b0db1e9d42a6f466709a61cfd1f69f

**Review by glozow — COMMENTED** [review]
ACK aac0b6dd79b0db1e9d42a6f466709a61cfd1f69f
