### PR TITLE
[test] Qt: Use _putenv_s instead of setenv on Windows builds

### LINKED ISSUE #10836: Compiling Error: qt/test/test_main.cpp
Hey,

When I'm compining under Linux Ubuntu 14.04 64 bit it crashes at this Step:

`cd depends // works
make HOST=i686-w64-mingw32 // works
cd .. // works
./autogen.sh # not required when building from tarball // works
CONFIG_SITE=$PWD/depends/i686-w64-mingw32/share/config.site ./configure --prefix=/ // works
make // failed`

I followed these Instructions:

https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

I used the Current Master Version.

After maybe 30 minutes, it stops compiling with this Error:

 
> Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
  GEN      qt/locale/bitcoin_uk.qm
  GEN      qt/locale/bitcoin_ur_PK.qm
  GEN      qt/locale/bitcoin_uz@Cyrl.qm
  GEN      qt/locale/bitcoin_vi.qm
  GEN      qt/locale/bitcoin_vi_VN.qm
  GEN      qt/locale/bitcoin_zh_CN.qm
  GEN      qt/locale/bitcoin_zh_HK.qm
  GEN      qt/locale/bitcoin_zh.qm
  GEN      qt/locale/bitcoin_zh_TW.qm
  GEN      qt/qrc_bitcoin_locale.cpp
  CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin_locale.o
  AR       qt/libbitcoinqt.a
  OBJCXXLD qt/bitcoin-qt.exe
  CXX      qt/test/qt_test_test_bitcoin_qt-compattests.o
  CXX      qt/test/qt_test_test_bitcoin_qt-rpcnestedtests.o
  CXX      qt/test/qt_test_test_bitcoin_qt-test_main.o
qt/test/test_main.cpp: In function ‘int main(int, char**)’:
qt/test/test_main.cpp:62:43: error: ‘setenv’ was not declared in this scope
     setenv("QT_QPA_PLATFORM", "minimal", 0);
                                           ^
make[2]: *** [qt/test/qt_test_test_bitcoin_qt-test_main.o] Error 1
make[2]: Leaving directory `/home/globaltoken/wallet-compile/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/globaltoken/wallet-compile/bitcoin/src'
make: *** [all-recursive] Error 1

What am I missing ?

Kind Regards.

### PR DESCRIPTION
**Pull request by brianmcmichael**
Fixes https://github.com/bitcoin/bitcoin/issues/10836

Error message I would get on `make`:
```
...
  CXXLD    bench/bench_bitcoin.exe
  OBJCXXLD qt/bitcoin-qt.exe
qt/test/test_main.cpp: In function ‘int main(int, char**)’:
qt/test/test_main.cpp:64:43: error: ‘setenv’ was not declared in this scope
     setenv("QT_QPA_PLATFORM", "minimal", 0);
                                           ^
make[2]: *** [qt/test/qt_test_test_bitcoin_qt-test_main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/bmcmichael/Projects/bcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/bmcmichael/Projects/bcoin/src'
make: *** [all-recursive] Error 1
```

`setenv` function is not available from the Microsoft runtime library. Need to use `_putenv_s` instead.

This solution tells the compiler to use `_putenv_s` on `WIN32` compilation (Note: this also works on 64-bit Windows instances.) and `setenv` everywhere else.

I've tested builds on Windows 10 x64 and Ubuntu 16.04 with this code.

### CODE REVIEW

**Comment by laanwj** [comment]
utACK

**Comment by TheBlueMatt** [comment]
utACK

**Comment by MarcoFalke** [comment]
utACK 0be03c71bd91db25f30bcf4d45facf1e26dcfd30
