### PR TITLE
build: Fix Qt processing of configure script for depends with DEBUG=1

### LINKED ISSUE #16391: build: configure doesn't pickup Qt if depends is built with DEBUG=1
Using `master` (536590f358dc3d3e5821eba7f1009452ea93b205) and building depends using `DEBUG=1 make -j8`.

Configuring with `./autogen.sh && ./configure --prefix=/Users/michael/github/bitcoin/depends/x86_64-apple-darwin18.6.0` I'm seeing:
```bash
Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = yes
  with test     = yes
    with fuzz   = no
  with bench    = yes
  with upnp     = yes
  use asm       = yes
  sanitizers    = 
  debug enabled = no
  gprof enabled = no
  werror        = no

  target os     = darwin
  build os      = darwin
```

In `config.log`:
```bash
configure:27984: checking for static Qt plugins: -lqcocoa
ld: library not found for -lqcocoa
configure:27813: checking for static Qt plugins: -lqminimal
ld: library not found for -lqminimal
configure:27839: WARNING: Could not resolve: -lqminimal; bitcoin-qt frontend will not be built
```

Building depends without `DEBUG=1` works as expected.

### LINKED ISSUE #17813: build: Ambiguous help string for --with-gui configure option
This help message
```
$ ./configure --help | grep -A 1 'with-gui'
  --with-gui[=no|qt5|auto]
                          build bitcoin-qt GUI (default=auto)
```
states that `--with-gui` and `--with-gui=auto` are equivalent.

But this is _not_ correct.

Consider a system without available Qt:

```
$ ./configure --with-gui | grep 'with gui'
configure: error: Qt dependencies not found
```

```
$ ./configure --with-gui=auto | grep 'with gui'
configure: WARNING: Qt dependencies not found; bitcoin-qt frontend will not be built
  with gui / qt = no
```

What should be fixed: the help message or `configure` behavior?

### LINKED ISSUE #19266: build: mingw32 issues with Qt if depends is built with DEBUG=1
On master (8c97780db8c9dd33efed134385573ba97e9cd165):

```
$ make -C depends HOST=x86_64-w64-mingw32 DEBUG=1
$ ./autogen.sh
$ CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure
...
Options used to compile and link:
  multiprocess  = no
  with wallet   = yes
  with gui / qt = no
...
```

Should be fixed by #18298.

### PR DESCRIPTION
**Pull request by hebasto**
This PR:
- makes the `configure` script correctly pickup Qt if depends is built with `DEBUG=1`:
    - for Windows -- fix #19266
    - for macOS -- fix #16391 
- is an alternative to #18117 (without downsides)

### CODE REVIEW

**Comment by hebasto** [comment]
Updated fad898c3a00ab9108710465752033a2d6b4ec90a -> 597445cec0a31465fd0ac8cb821442ed4f8f556d ([pr18298.01](https://github.com/hebasto/bitcoin/commits/pr18298.01) -> [pr18298.02](https://github.com/hebasto/bitcoin/commits/pr18298.02), [diff](https://github.com/hebasto/bitcoin/compare/pr18298.01..pr18298.02)):

- rebased on top of #18361
- OP updated

**Comment by hebasto** [comment]
Rebased 597445cec0a31465fd0ac8cb821442ed4f8f556d -> 49ab29464027a3f12f59e5e3c186741a9ddfa5ed ([pr18298.02](https://github.com/hebasto/bitcoin/commits/pr18298.02) -> [pr18298.03](https://github.com/hebasto/bitcoin/commits/pr18298.03)) due to the conflict with #18297.

**Comment by Sjors** [comment]
Tested 49ab29464027a3f12f59e5e3c186741a9ddfa5ed on macOS 10.15.5; works like a charm.
```

**Comment by Sjors** [comment]
It also works on macOS Big Sur 11.0 beta (after rebase).

cc @fanquake @theuni

**Comment by hebasto** [comment]
@fanquake Mind reviewing this PR insofar as it fixes #16391 submitted by you :)

**Comment by hebasto** [comment]
Hmm, it works for macOS, but is broken for Windows.

**Comment by hebasto** [comment]
Reasons of build fail for Windows are unrelated to this PR:
```
$ make -C depends HOST=x86_64-w64-mingw32 DEBUG=1 NO_QT=1
$ ./autogen.sh
$ CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure
$ make
...
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-merkle.o:merkle.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_]+0x34): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-merkle.o:merkle.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorI7uint256SaIS3_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS3_NSt9__cxx19986vectorIS3_S4_EEEEEEEEvT_]+0x53): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x44d): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x464): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x1189): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x11a6): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x179a): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text+0x17a1): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x200): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputerNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x217): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1be): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1d8): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1ba): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: consensus/.libs/libbitcoinconsensus_la-tx_check.o:tx_check.cpp:(.text$_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI13CSizeComputer6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x1d1): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-block.o:block.cpp:(.text+0xd09): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-block.o:block.cpp:(.text+0xd23): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x87b): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x892): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x1df3): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x1e0d): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x26f0): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x270d): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x29d1): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text+0x3009): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x669): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriterNSt7__debug6vectorIhSaIhEEESaIS4_ES4_EvRT_RKNS2_IT0_T1_EERKT2_]+0x680): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x69b): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriter5CTxInSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x6b5): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriter6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriter6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x671): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: primitives/.libs/libbitcoinconsensus_la-transaction.o:transaction.cpp:(.text$_Z14Serialize_implI11CHashWriter6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_[_Z14Serialize_implI11CHashWriter6CTxOutSaIS1_ES1_EvRT_RKNSt7__debug6vectorIT0_T1_EERKT2_]+0x688): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-bitcoinconsensus.o:bitcoinconsensus.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_]+0x34): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-bitcoinconsensus.o:bitcoinconsensus.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_]+0x53): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x5c60): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x5c77): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x6560): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x657a): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x6c3f): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x6c59): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x7dbe): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x7dd8): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x848f): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x84a9): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x8b65): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x8b7c): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x9239): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text+0x9250): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_]+0x2e): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_]+0x4e): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN7CScriptC1EN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEESF_[_ZN7CScriptC1EN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEESF_]+0x328): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN7CScriptC1EN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEESF_[_ZN7CScriptC1EN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEESF_]+0x342): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_]+0x36): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorINS2_IhSaIhEEESaIS4_EEEE16_M_invalidate_ifINS_15_After_nth_fromIN9__gnu_cxx17__normal_iteratorIPKS4_NSt9__cxx19986vectorIS4_S5_EEEEEEEEvT_]+0x69): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_]+0x2e): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_[_ZN11__gnu_debug14_Safe_sequenceINSt7__debug6vectorIhSaIhEEEE16_M_invalidate_ifINS_9_Equal_toIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhS3_EEEEEEEEvT_]+0x4e): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN7CScriptlsERKNSt7__debug6vectorIhSaIhEEE[_ZN7CScriptlsERKNSt7__debug6vectorIhSaIhEEE]+0x4ec): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-interpreter.o:interpreter.cpp:(.text$_ZN7CScriptlsERKNSt7__debug6vectorIhSaIhEEE[_ZN7CScriptlsERKNSt7__debug6vectorIhSaIhEEE]+0x506): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-script.o:script.cpp:(.text+0x27f1): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-script.o:script.cpp:(.text+0x280b): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-script.o:script.cpp:(.text$_Z6HexStrIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_SM_[_Z6HexStrIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_SM_]+0x6fa): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: script/.libs/libbitcoinconsensus_la-script.o:script.cpp:(.text$_Z6HexStrIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_SM_[_Z6HexStrIN11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKhNSt9__cxx19986vectorIhSaIhEEEEENSt7__debug6vectorIhS8_EESt26random_access_iterator_tagEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_SM_]+0x714): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: util/.libs/libbitcoinconsensus_la-strencodings.o:strencodings.cpp:(.text+0x3465): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: util/.libs/libbitcoinconsensus_la-strencodings.o:strencodings.cpp:(.text+0x347c): undefined reference to `__imp_pthread_mutex_unlock'
/usr/bin/x86_64-w64-mingw32-ld: util/.libs/libbitcoinconsensus_la-strencodings.o:strencodings.cpp:(.text+0x4263): undefined reference to `__imp_pthread_mutex_lock'
/usr/bin/x86_64-w64-mingw32-ld: util/.libs/libbitcoinconsensus_la-strencodings.o:strencodings.cpp:(.text+0x427a): undefined reference to `__imp_pthread_mutex_unlock'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:7975: libbitcoinconsensus.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/hebasto/guix/GitHub/bitcoin/src'
make[1]: *** [Makefile:18819: all-recursive] Error 1
make[1]: Leaving directory '/home/hebasto/guix/GitHub/bitcoin/src'
make: *** [Makefile:794: all-recursive] Error 1
```

**Comment by hebasto** [comment]
Rebased 49ab29464027a3f12f59e5e3c186741a9ddfa5ed -> e25cb1d45bddd09b980ea63e48735dc1aee4022f ([pr18298.03](https://github.com/hebasto/bitcoin/commits/pr18298.03) -> [pr18298.04](https://github.com/hebasto/bitcoin/commits/pr18298.04)) to prevent the merge conflict with #19689.

**Comment by fanquake** [comment]
@hebasto Sorry for the delay. Can you drop the two already-merged commits out of here?

**Comment by hebasto** [comment]
Rebased e25cb1d45bddd09b980ea63e48735dc1aee4022f -> 924900e78a38ff61a7c4cfc4afbbb103efa75580 ([pr18298.04](https://github.com/hebasto/bitcoin/commits/pr18298.04) -> [pr18298.05](https://github.com/hebasto/bitcoin/commits/pr18298.05)).

@fanquake 
> Can you drop the two already-merged commits out of here?

Done. (it was the intention of the previous rebasing, but something gone wrong)

**Comment by hebasto** [comment]
@fanquake @laanwj Mind adding 22.0 milestone?

**Comment by fanquake** [comment]
@hebasto taking a look

**Comment by dongcarl** [comment]
Concept ACK

**Comment by theuni** [comment]
From IRC discussion today:

Concept ACK. It would be nice if qt gave the option to disable adding the suffix, but since @hebasto says no such option exists, this seems like a reasonable solution.

**Comment by hebasto** [comment]
Rebased 924900e78a38ff61a7c4cfc4afbbb103efa75580 -> 76f52e3da359c3738d36bc20ac13a8ccd17e4e9f ([pr18298.05](https://github.com/hebasto/bitcoin/commits/pr18298.05) -> [pr18298.06](https://github.com/hebasto/bitcoin/commits/pr18298.06)) due to the conflict with #19683.

**Review by fanquake — APPROVED** [review]
ACK 76f52e3da359c3738d36bc20ac13a8ccd17e4e9f. Tested native darwin, and darwin/win cross compile with `DEBUG=1`.
