### PR TITLE
index: block filters sync, reduce disk read operations by caching last header

### PR DESCRIPTION
**Pull request by furszy**
Work decoupled from #26966 per request.

The aim is to remove an unnecessary disk read operation that currently takes place with every new arriving block (or scanned block during background sync). Instead of reading the last filter header from disk merely to access its hash for constructing the next filter, this work caches it, occupying just 32 more bytes in memory.

Also, reduces `cs_main` lock contention during the index initial sync process. And, simplifies the indexes initialization and shutdown procedure.

Testing Note:
To compare the changes, added a pretty basic benchmark in the second commit. Alternatively, could also test the changes by timing the block filter sync from scratch on any network; start the node with `-blockfilterindex` and monitor the logs until the syncing process finish.

Local Benchmark Results:

*Master (c252a0fc0f4dc7d262b971a5e7ff01508159193b):
|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|      132,042,516.60 |                7.57 |    0.3% |      7.79 | `BlockFilterIndexSync`

*PR (43a212cfdac6c64e82b601c664443d022f191520):
|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|      126,915,841.60 |                7.88 |    0.6% |      7.51 | `BlockFilterIndexSync`

### CODE REVIEW

**Comment by Sjors** [comment]
Ran bench on MacBook Pro 2019 (2,3 GHz 8-Core Intel Core i9, SSD):

```sh
src/bench/bench_bitcoin -filter=BlockFilterIndexSync
```

Before (486c71bc707f5765fc6698a746cf221bab1ac357):

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|      336,034,835.00 |                2.98 |    0.6% |     19.86 | `BlockFilterIndexSync`

After:

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|      339,403,771.80 |                2.95 |    0.6% |     19.98 | `BlockFilterIndexSync`

Not seeing any improvement in the bench. Haven't tried running the full indexer though.

**Comment by furszy** [comment]
> Ran bench on MacBook Pro 2019 (2,3 GHz 8-Core Intel Core i9, SSD):
> 
> ```shell
> src/bench/bench_bitcoin -filter=BlockFilterIndexSync
> ```
> 
> Before ([486c71b](https://github.com/bitcoin/bitcoin/commit/486c71bc707f5765fc6698a746cf221bab1ac357)):
> 
> ns/op	op/s	err%	total	benchmark
> 336,034,835.00	2.98	0.6%	19.86	`BlockFilterIndexSync`
> After:
> 
> ns/op	op/s	err%	total	benchmark
> 339,403,771.80	2.95	0.6%	19.98	`BlockFilterIndexSync`
> Not seeing any improvement in the bench. Haven't tried running the full indexer though.

Probably, it is because the benchmarks, same as the unit tests, create temp directories. Which may be faster to access than regular directories. See https://github.com/bitcoin/bitcoin/pull/26684#pullrequestreview-1566578747.
I should verify if the bench framework accepts custom paths so we can test this differently. Most likely, it doesn't and we should add the feature.

Also, you could increase the `CHAIN_SIZE` variable inside the benchmark. Go from 600, to 3000 or more. The time should grow up linearly. I didn't do it merely because the bench would take much more time to setup but the difference should be evident with a longer chain.

File: src/bench/index_blockfilter.cpp [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+#include <bench/bench.h>
+#include <addresstype.h>
+#include <index/blockfilterindex.h>
+#include <node/chainstate.h>
+#include <node/context.h>
+#include <test/util/index.h>
+#include <test/util/mining.h>
+#include <test/util/setup_common.h>
+#include <util/strencodings.h>
```
Comment (TheCharlatan) [inline src/bench/index_blockfilter.cpp:13]: Nit: Can you make this new file IWYU-correct?

File: src/bench/index_blockfilter.cpp [hunk 2]
```diff
@@ -0,0 +1,44 @@
+// Copyright (c) 2023-present The Bitcoin Core developers
+// Distributed under the MIT software license, see the accompanying
+// file COPYING or https://www.opensource.org/licenses/mit-license.php.
+
+#include <bench/bench.h>
```
Comment (TheCharlatan) [inline src/bench/index_blockfilter.cpp:5]: Nit: Put this include on its own line (like e.g. in `bip324_ecdh.cpp`), or fix the include order.

File: src/index/base.cpp [hunk 3]
```diff
@@ -160,23 +160,21 @@ void BaseIndex::Sync()
...
+            if (!pindex_next) {
+                SetBestBlockIndex(pindex);
+                m_synced = true;
+                // No need to handle errors in Commit. See rationale above.
+                Commit();
+                break;
             }
+            if (pindex_next->pprev != pindex && !Rewind(pindex, pindex_next->pprev)) {
+                FatalErrorf("%s: Failed to rewind index %s to a previous chain tip",
+                           __func__, GetName());
```
Comment (TheCharlatan) [inline src/index/base.cpp:173]: Nit: There is a whitespace issue at the start of this line.

**Review by sedited — APPROVED** [review]
ACK 63ef83d72a979e9e557eec9fe87c2795a963dedb

File: src/bench/index_blockfilter.cpp (hunk 2 above)
Comment (furszy) [reply src/bench/index_blockfilter.cpp:5]: done

**Review by sedited — APPROVED** [review]
Re-ACK b19585e00a52c0b571e70ddb8f7c996d598c3435

**Comment by luke-jr** [comment]
>Probably, it is because the benchmarks, same as the unit tests, create temp directories. Which may be faster to access than regular directories.

Is it, though? I would think the OS should have this cached regardless?

**Review by furszy — COMMENTED** [review]
> > Probably, it is because the benchmarks, same as the unit tests, create temp directories. Which may be faster to access than regular directories.
> 
> Is it, though? I would think the OS should have this cached regardless?

We will know it soon. I'm working on a way to test it inside https://github.com/bitcoin/bitcoin/pull/26564#pullrequestreview-1761271269.

But, it seems to be an orthogonal topic. Regardless of the result, which could vary depending on the OS, the changes in this PR should be good to go as is.

Conceptually, the block filter index synchronization process makes a db call on every new block (forever) just to get the tip's header hash when it could just cache those 32 bytes.

**Review by furszy — COMMENTED** [review]
Finished testing this on a custom directory. Results are favorable @Sjors and @luke-jr.
I have observed that access to the OS temp directory is faster than accessing regular directories locally. Benchmark outputs are provided at the end.

The testing methodology is as following:

Running `./bench_bitcoin -filter="BlockFilterIndexSync" -testdatadir=<custom_test_datadir_path>` on any of the following branches:

[Branch 1](https://github.com/furszy/bitcoin-core/tree/2023_index_blockfilter_cache_with_custom_datadir) -> Which includes: this PR changes + [#26564](https://github.com/bitcoin/bitcoin/pull/26564) + a commit that introduces the custom datadir feature for the benchmark framework.

[Branch 2](https://github.com/furszy/bitcoin-core/tree/2023_no_index_cache_with_custom_datadir) -> Which includes: the block filter index benchmark + [#26564](https://github.com/bitcoin/bitcoin/pull/26564) + a commit that introduces the custom datadir feature for the benchmark framework.

The results were:

#### For Branch 1

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|      117,648,576.33 |                8.50 |    0.5% |      6.96 | `BlockFilterIndexSync`

#### For Branch 2

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|      121,370,493.17 |                8.24 |    0.5% |      7.16 | `BlockFilterIndexSync`

**Review by andrewtoth — COMMENTED** [review]
This patch seems to be doing more than what is in the description. From my understanding, it is also reducing `cs_main` lock contention in the renamed `Sync` method, which is also now made public. The former seems like a simple win, but it's unclear to me why we want the latter?
Also, a refactor to indexes in `init.cpp` that also seems fine but unrelated?
Maybe the PR description can be updated to describe the motivation behind these other changes?

**Review by furszy — COMMENTED** [review]
Updated per feedback. Thanks @andrewtoth!

> This patch seems to be doing more than what is in the description. From my understanding, it is also reducing `cs_main` lock contention in the renamed `Sync` method, which is also now made public. The former seems like a simple win, but it's unclear to me why we want the latter?

The benchmark, introduced in the second commit, makes use of it. If `BaseIndex::Sync()` is not public, the benchmark would need to call `BaseIndex::StartBackgroundSync()`, who wraps `BaseIndex::Sync()` on a separate thread, which goes against the objective of the benchmark (we want to bench the process, not the time it takes the OS to create, wait-for and destroy a thread).

Also, it facilitates the future decoupling of the index inner thread in #26966. Replacing it for a thread-pool class provided by the caller.

> Also, a refactor to indexes in `init.cpp` that also seems fine but unrelated?
> Maybe the PR description can be updated to describe the motivation behind these other changes?

Sure. This PR improves the index sources. And, while the changes simplify the code, to me, pushing a PR just to do such small code refactoring does not seem worth the efforts (from reviewers and from myself).
Will update the description. Thanks!

**Review by andrewtoth — COMMENTED** [review]
Concept ACK

I've ran the benchmark locally on this PR and the branches you mention in https://github.com/bitcoin/bitcoin/pull/28955#pullrequestreview-1798579472, and it is sometimes better on one branch then the other for both tests. The results you show are very small improvements which I think could just be attributed to noise.

> Regardless of the result, which could vary depending on the OS, the changes in this PR should be good to go as is.

I agree, except for the first 2 commits. The benchmark as I mentioned doesn't seem particularly useful, and the `Sync` method being made public should then only be done in a patch that will take advantage of it's new accessibility.

**Comment by Sjors** [comment]
Concept ACK

I synced the block filter from scratch at c3e2915b14900c1379e4c3f1ac0262f60b362431 (rebased on master) and then on the last commit. AMD Ryzen 7950x with SSD drive running Ubuntu 23.10:

* before: TODO
* after:  TODO

Assuming the difference is small (good or bad), it's fine with the goal of #26966 in mind - which does make a dramatic difference.

I haven't measured the performance impact on syncing the index during IBD; in light of 5d5e22b979d00ca3d3c4b4013fea43ba58f571bc that might be more significant because there's more going on in `cs_main`.

Can you add some rationale to the b19585e00a52c0b571e70ddb8f7c996d598c3435 commit message as to what was preventing this simplification before?

@andrewtoth wrote:

>  The benchmark as I mentioned doesn't seem particularly useful,

Benchmarks are also useful to prevent future regressions.

File: src/index/blockfilterindex.h [hunk 4]
```diff
@@ -44,6 +44,8 @@ class BlockFilterIndex final : public BaseIndex
 
     bool AllowPrune() const override { return true; }
 
+    bool Write(const BlockFilter& filter, uint32_t block_height, const uint256& header);
```
[the remark this answers is not in the document]
Comment (furszy) [reply src/index/blockfilterindex.h]: Done as suggested

File: src/index/blockfilterindex.cpp [hunk 5]
```diff
@@ -215,6 +215,22 @@ size_t BlockFilterIndex::WriteFilterToDisk(FlatFilePos& pos, const BlockFilter&
     return data_size;
 }
 
+std::optional<uint256> BlockFilterIndex::ReadHeader(int height, const uint256& expected_block_hash)
```
[the remark this answers is not in the document]
Comment (furszy) [reply src/index/blockfilterindex.cpp]: Done as suggested

File: src/index/blockfilterindex.h [hunk 6]
```diff
@@ -42,6 +42,9 @@ class BlockFilterIndex final : public BaseIndex
     /** cache of block hash to filter header, to avoid disk access when responding to getcfcheckpt. */
     std::unordered_map<uint256, uint256, FilterHeaderHasher> m_headers_cache GUARDED_BY(m_cs_headers_cache);
 
+    // Last computed header to avoid disk reads at every new block.
+    uint256 last_header{};
```
[the remark this answers is not in the document]
Comment (furszy) [reply src/index/blockfilterindex.h]: Done as suggested

**Comment by furszy** [comment]
Updated per feedback. Thanks both.

> Can you add some rationale to the https://github.com/bitcoin/bitcoin/commit/b19585e00a52c0b571e70ddb8f7c996d598c3435 commit message as to what was preventing this simplification before?

Nothing was preventing it.

> The benchmark as I mentioned doesn't seem particularly useful

Have you tried it on a spinning disk? The diff should be noticeable there. We need to avoid disk writes/reads where is possible.

> the Sync method being made public should then only be done in a patch that will take advantage of its new accessibility.

Have merged the first two commits.

**Comment by Sjors** [comment]
tACK 08d8608c51beb66dab4e12ac06559a70517fb054

**Review by sedited — APPROVED** [review]
Re-ACK 08d8608c51beb66dab4e12ac06559a70517fb054

**Comment by furszy** [comment]
Rebased due a one-line conflict with #29236.

**Comment by Sjors** [comment]
Tidy complains about

```
index/blockfilterindex.cpp:135:22: error: Unterminated format string used with LogPrintf [bitcoin-unterminated-logprintf,-warnings-as-errors]
  135 |             LogError("Cannot read last block filter header; index may be corrupted");
      |                      ^                                                            
      |                                                                                   \n
```

**Comment by Sjors** [comment]
re-ACK 99afb9d15a08d2f46739f4d2b66c63dbabd7a44e

**Review by sedited — APPROVED** [review]
Re-ACK 99afb9d15a08d2f46739f4d2b66c63dbabd7a44e

**Review by andrewtoth — APPROVED** [review]
ACK 99afb9d15a08d2f46739f4d2b66c63dbabd7a44e

**Comment by achow101** [comment]
ACK 99afb9d15a08d2f46739f4d2b66c63dbabd7a44e

File: src/index/base.cpp [hunk 7]
```diff
@@ -159,23 +159,20 @@ void BaseIndex::Sync()
                 return;
             }
 
-            {
-                LOCK(cs_main);
```
Comment (ryanofsky) [inline src/index/base.cpp:163]: In commit "index: decrease ThreadSync cs_main contention" (0faafb57f8298547949cbc0044ee9e925ed887ba)

Note: This commit introduces a race condition, because it is no longer locking cs_main while calling `NextSyncBlock` and setting `m_synced = true`. As a result, a new block could be connected by another thread after `NextSyncBlock` returns null in this thread, but before `m_synced` is set to true, so the block will never be indexed because BlockConnected notifications are ignored while m_synced is false. This should be fixed in #29867
