### PR TITLE
cmake: Avoid fuzzer "multiple definition of `main'" errors

### PR DESCRIPTION
**Pull request by ryanofsky**
This change builds libraries with `-fsanitize=fuzzer-no-link` instead of `-fsanitize=fuzzer` when the cmake `-DSANITIZERS=fuzzer` option is specified. This is necessary to make fuzzing and IPC cmake options compatible with each other and avoid CI failures in #30975 which enables IPC in the fuzzer CI build:

https://cirrus-ci.com/task/5366255504326656?logs=ci#L2817
https://cirrus-ci.com/task/5233064575500288?logs=ci#L2384

The failures can also be reproduced by checking out #31741 and building with `cmake -B build -DBUILD_FOR_FUZZING=ON -DSANITIZERS=fuzzer -DENABLE_IPC=ON` with this fix reverted.

The fix updates the cmake build so when `-DSANITIZERS=fuzzer` is specified, the fuzz test binary is built with `-fsanitize=fuzzer` (so it can use libFuzzer's main function), and libraries are built with `-fsanitize=fuzzer-no-link` (so they can be linked into other executables with their own main functions).

Previously when `-DSANITIZERS=fuzzer` was specified, `-fsanitize=fuzzer` was applied to ALL libraries and executables. This was inappropriate because it made it impossible to build any executables other than the fuzz test executable without triggering link errors:

- `` multiple definition of `main' ``
- `` "undefined reference to `LLVMFuzzerTestOneInput' ``

if they depended on any libraries instrumented for fuzzing.

This was especially a problem when the `ENABLE_IPC` option was set because it made building the `mpgen` code generator impossible so nothing else that depended on generated sources, including the fuzz test binary, could be built either.

This commit was previously part of https://github.com/bitcoin/bitcoin/pull/31741 and had some discussion there starting in https://github.com/bitcoin/bitcoin/pull/31741#pullrequestreview-2619682385

---

This PR is part of the [process separation project](https://github.com/bitcoin/bitcoin/issues/28722).

### CODE REVIEW

**Comment by ryanofsky** [comment]
@hebasto suggested separating this change from #31741, so this is now a standalone PR.

**Comment by dergoegge** [comment]
Why do we want IPC enabled for the fuzzing builds? It's not used/tested by our fuzzing harnesses.

**Comment by ryanofsky** [comment]
> Why do we want IPC enabled for the fuzzing builds? It's not used/tested by our fuzzing harnesses.

To be clear, this PR isn't enabling IPC in the fuzzing CI configuration, just fixing a more general build system bug which causes that configuration to be broken. But a followup PR #30975 does enable IPC in the fuzzing CI configuration for a few reasons:

- To test ENABLE_IPC option in different scenarios and uncover incompatibilities like this
- To make the fuzz configuration more similar to an eventual default configuration, since a goal after #31741 is to enable ipc by default.
- To make it possible to write fuzz tests covering IPC serialization code. This could involve writing new tests or just changing setup of existing tests. For example with #29409, [`FuzzedWallet`](https://github.com/bitcoin/bitcoin/blob/8cb6ab0b971a27ba255ad6a48959a8c7b84c00f3/src/test/fuzz/util/wallet.h#L23) could be passed an IPC chain interface instead of a local one.

**Comment by ryanofsky** [comment]
Also while the PR description mentions the `ENABLE_IPC` / `SANITIZERS=fuzzer`incompatibility to motivate this change, I think the change is a more general bugfix and makes sense for a variety of reasons listed previously in https://github.com/bitcoin/bitcoin/pull/31741#issuecomment-2663597395:

> (1) It fixes the CI bug
> (2) It documents sanitize_interface and removes an attribute(weak) hack.
> (3) It doesn't compile libraries with a flag intended to bring in a main() function.
> (4) It provides immediate and clear feedback if -DSANITIZERS=fuzzer is used with without -DBUILD_FOR_FUZZING=ON which is is a perfectly logical thing to try and easy thing to forget about, instead of providing an opaque error message and failing at the very end of a slow build.
> (5) It lets us write useful fuzz tests that cover IPC code.

File: CMakeLists.txt [hunk 1]
```diff
@@ -348,13 +348,35 @@ target_link_libraries(core_interface INTERFACE
...
 add_library(sanitize_interface INTERFACE)
+add_library(fuzzer_interface INTERFACE)
 target_link_libraries(core_interface INTERFACE sanitize_interface)
 if(SANITIZERS)
+  # Transform list of sanitizers into -fsanitize flags, replacing "fuzzer" with
+  # "fuzzer-no-link" in sanitize_interface flags, and moving "fuzzer" to
+  # fuzzer_interface flags.
+  string(REGEX REPLACE "(^|,)fuzzer($|,)" "\\1fuzzer-no-link\\2" SANITIZE_FLAG "${SANITIZERS}")
+  set(FUZZ_FLAG "")
+  if (NOT "${SANITIZE_FLAG}" STREQUAL "${SANITIZERS}")
```
Comment (hebasto) [inline CMakeLists.txt:368]: I found this code hard to read. Wouldn't it better:
```suggestion
  if(SANITIZERS MATCHES "(^|,)fuzzer($|,)")
```
?

style nit: The surrounding code has no space between `if` and `(`.

File: CMakeLists.txt [hunk 2]
```diff
@@ -348,13 +348,35 @@ target_link_libraries(core_interface INTERFACE
...
+    set(FUZZ_FLAG "-fsanitize=fuzzer")
+    if(NOT BUILD_FOR_FUZZING)
+      message(FATAL_ERROR "Error: Enabling -DSANITIZERS=fuzzer without -DBUILD_FOR_FUZZING=ON is not supported.")
+    endif()
+  endif()
+  set(SANITIZE_FLAG "-fsanitize=${SANITIZE_FLAG}")
```
Comment (hebasto) [inline CMakeLists.txt:374]: Maybe avoid reusing the `SANITIZE_FLAG` variable?

style-nit: The surrounding code mostly uses `ALL_CAPS` naming for user-faced variables, not for internal ones.

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/pull/31992#issuecomment-2748719049

@hebasto thanks for the review! I can try to implement your suggested changes but since they are all about code style, maybe it would be faster if you could just post a diff with your preferred change and I can apply it? I could try to figure out how to integrate your suggestions, but since they go against my own preferences for having fewer variables and not repeating code I think it would be harder for me to figure out what you want than for you to just implement what you want.

**Review by hebasto — COMMENTED** [review]
Approach ACK 60d2afe65484f755d99191bb650b9f9a784ee2c2, I have reviewed the code and it looks OK.

Tested on Ubuntu 24.10 and in the OSS-Fuzz environment.

As '_a separate "fuzzer_interface" with flags specifically intended to apply to the fuzz test binary_', it seems reasonable to place all `<COMMAND>(fuzzer_interface ...)` invocations under the existing `if(BUILD_FUZZ_BINARY)` condition.

nit: No need to quote variables here:
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -365,7 +365,7 @@ if(SANITIZERS)
   # fuzzer_interface flags.
   string(REGEX REPLACE "(^|,)fuzzer($|,)" "\\1fuzzer-no-link\\2" SANITIZE_FLAG "${SANITIZERS}")
   set(FUZZ_FLAG "")
-  if (NOT "${SANITIZE_FLAG}" STREQUAL "${SANITIZERS}")
+  if(NOT SANITIZE_FLAG STREQUAL SANITIZERS)
     set(FUZZ_FLAG "-fsanitize=fuzzer")
     if(NOT BUILD_FOR_FUZZING)
       message(FATAL_ERROR "Error: Enabling -DSANITIZERS=fuzzer without -DBUILD_FOR_FUZZING=ON is not supported.")
```

> ... they go against my own preferences...

Understood.

---

The only question I have before final ACK: I failed to figure out the documented behaviour where both `-fsanitize=fuzzer` and `-fsanitize=fuzzer-no-link` are passed simultaneously to the compiler during linking. Any insights on that?

**Review by ryanofsky — COMMENTED** [review]
Updated 60d2afe65484f755d99191bb650b9f9a784ee2c2 -> 57d8b1f1b3375452213c48ce80e8207e2fe53ebc ([`pr/subtree-fuzz.2`](https://github.com/ryanofsky/bitcoin/commits/pr/subtree-fuzz.2) -> [`pr/subtree-fuzz.3`](https://github.com/ryanofsky/bitcoin/commits/pr/subtree-fuzz.3), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/subtree-fuzz.2..pr/subtree-fuzz.3)) making suggested code changes and also dropping the check that forbid specifying -DSANITIZERS=fuzzer without -DBUILD_FOR_FUZZING=ON.

(Before this PR specifying -DSANITIZERS=fuzzer without -DBUILD_FOR_FUZZING=ON would result in "multiple definition of main" errors, and now it won't, but this is harmless. I originally thought triggering an error in this case was important to prevent binaries from being built that could skip proof of work checks, but just this was a misconception that came from confusing the `BUILD_FUZZ_BINARY` and `BUILD_FOR_FUZZING` variables.)

---

re: https://github.com/bitcoin/bitcoin/pull/31992#pullrequestreview-2713808140

Thanks for the review!

> As '_a separate "fuzzer_interface" with flags specifically intended to apply to the fuzz test binary_', it seems reasonable to place all `<COMMAND>(fuzzer_interface ...)` invocations under the existing `if(BUILD_FUZZ_BINARY)` condition.

Thanks, moved fuzzer_interface definition there.

> nit: No need to quote variables here:

Thanks, applied suggested change.

> The only question I have before final ACK: I failed to figure out the documented behaviour where both `-fsanitize=fuzzer` and `-fsanitize=fuzzer-no-link` are passed simultaneously to the compiler during linking. Any insights on that?

I don't think you will be able to find explicit documentation on how they are combined but the options are documented at https://llvm.org/docs/LibFuzzer.html, where it says `-fsanitize=fuzzer-no-link` will "request just the instrumentation without linking" and `-fsanitize=fuzzer` "links in the libFuzzer’s main() symbol". I think the only sensible way to combine the options is to provide both features, and this is what happens in practice. If this were not the case there should be pretty obvious linker errors, so I didn't feel the need to separate the flags when there's no problem, but if there was a problem they could be separated.

**Review by hebasto — APPROVED** [review]
ACK 57d8b1f1b3375452213c48ce80e8207e2fe53ebc, tested on Ubuntu 24.04.

**Comment by hebasto** [comment]
Friendly ping @dergoegge and @maflcko  ;)

**Comment by dergoegge** [comment]
lgtm, afaiu this shouldn't have any downsides to existing infra
