### PR TITLE
fuzz: Rework strong and weak net enum fuzzing

### PR DESCRIPTION
**Pull request by maflcko**
The fuzz tests have several problems:
* The array passed to the fuzz engine to pick `net_permission_flags` is outdated
* The process_message* targets has the service flags as well as connection type hardcoded, limiting potential coverage
* The service flags deserialization from the fuzz engine doesn't allow for easy "exact matches". The fuzz engine has to explore a 64-bit space to hit an "exact match" (only one bit set)

Fix all issues in the commits in this pull

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Nice improvements!

File: src/test/util/net.h [hunk 1]
```diff
@@ -30,4 +30,35 @@ struct ConnmanTestMsg : public CConnman {
...
 };
 
+constexpr ServiceFlags ALL_SERVICE_FLAGS[]{
+    NODE_NONE,
+    NODE_NETWORK,
+    NODE_BLOOM,
+    NODE_WITNESS,
+    NODE_COMPACT_FILTERS,
+    NODE_NETWORK_LIMITED,
+};
```
Comment (vasild) [inline src/test/util/net.h:40]: I wonder if it is possible to get a warning if a new enum value is added, but this array is forgotten to be updated? I think not :/

**Review by vasild — APPROVED** [review]
ACK fa9ab9a8c

The chance of 5 random commits to all start with the same two letters is `0.00000002%` :eyes: :open_mouth:

File: src/test/util/net.h (hunk 1 above)
Comment (vasild) [reply src/test/util/net.h:40]: It is ok as it is, and I am just wondering if this can be improved wrt minimizing the chance of the actual enum and the "all" arrays going out of sync over time. Maybe one of the below would help:

o Add a comment next to the enum definition "don't forget to update `ALL_...` in `src/test/util/net.h` if you change this enum".

o Define the array immediately below the enum itself.

<details>
<summary>o Define both in one struct</summary>

```cpp
struct Color
{
    enum E : uint8_t {
        RED,
        GREEN,
        BLUE,
    };

    static constexpr E all[]{
        RED,
        GREEN,
        BLUE,
    };
};

...
    std::cout << Color::BLUE << std::endl;

    for (auto& c : Color::all) {
        std::cout << c << std::endl;
    }
```
</details>

Comment (practicalswift) [reply src/test/util/net.h:40]: Perhaps we could start using [`kMaxValue` as in the Chromium project](https://www.chromium.org/developers/coding-style/chromium-style-checker-errors). That way we could ​assert that the last element of the `ALL_*` array is equal to the `enum`'s `kMaxValue`.

Another benefit from using `kMaxValue` is that we could start using `FuzzedDataProvider::ConsumeEnum` when fuzzing.

Comment (vasild) [reply src/test/util/net.h:40]: Yeah, that is another way. `enum Network` uses this. It only works as long as enum values are left at their defaults:

https://github.com/bitcoin/bitcoin/blob/f1f26b8d5baec4a45a3a9ba0440cd4eff7af8407/src/netaddress.h#L38

and also the dummy "max" value has to be explicitly handled in `switch` without `default:`

https://github.com/bitcoin/bitcoin/blob/f1f26b8d5baec4a45a3a9ba0440cd4eff7af8407/src/netaddress.cpp#L145-L146

**Comment by MarcoFalke** [comment]
Force pushed to fix a bug. Should be trivial to re-ACK

File: src/test/fuzz/process_message.cpp [hunk 2]
```diff
@@ -63,13 +64,15 @@ void fuzz_target(const std::vector<uint8_t>& buffer, const std::string& LIMIT_TO
...
-    CDataStream random_bytes_data_stream{fuzzed_data_provider.ConsumeRemainingBytes<unsigned char>(), SER_NETWORK, PROTOCOL_VERSION};
-    CNode& p2p_node = *MakeUnique<CNode>(0, ServiceFlags(NODE_NETWORK | NODE_WITNESS | NODE_BLOOM), 0, INVALID_SOCKET, CAddress{CService{in_addr{0x0100007f}, 7777}, NODE_NETWORK}, 0, 0, CAddress{}, std::string{}, ConnectionType::OUTBOUND_FULL_RELAY).release();
+    CNode& p2p_node = *ConsumeNodeAsUniquePtr(fuzzed_data_provider).release();
     p2p_node.fSuccessfullyConnected = true;
     p2p_node.nVersion = PROTOCOL_VERSION;
     p2p_node.SetCommonVersion(PROTOCOL_VERSION);
     connman.AddTestNode(p2p_node);
     g_setup->m_node.peerman->InitializeNode(&p2p_node);
+
+    // fuzzed_data_provider is fully consumed after this call, don't use it
```
Comment (vasild) [inline src/test/fuzz/process_message.cpp:74]: What happens if we attempt to consume more bytes after `ConsumeRemainingBytes()`? Apparently CI was green. Should we `abort()` if that happens?

**Review by vasild — APPROVED** [review]
ACK fa

File: src/test/fuzz/process_message.cpp (hunk 2 above)
Comment (MarcoFalke) [reply src/test/fuzz/process_message.cpp:74]: This happens in normal operation when the fuzz engine starts with an empty byte vector or when existing inputs are trimmed, so it can't be detected by CI.

**Comment by MarcoFalke** [comment]
## Benchmarks

The goal is to benchmark the complexity of finding a strong and weak match of an enum type.
Strong match means the fuzz engine finds an exact value match. (built-in `operator==` for integers)
Weak match means the fuzz engine finds a matching flag. (built-in `operator&` for integers)

To reproduce:

* For all benchmarks `clang version 11.0.0` without sanitizers is used.
* Only the fuzz target `process_message_inv` is used.
* `-use_value_profile=1` is set at runtime.
* All patches are on top of this pull request.

### Strong (scoped) enum class

While C++ doesn't restrict how scoped enum classes are used, in our code base, scoped enum classes avoid `operator&`, so this benchmark only considers an exact match.


<details><summary>diffs</summary>




The following diff was used for "kMaxValue":

```diff
diff --git a/src/net.h b/src/net.h
index 6316c73eee..a4930b229c 100644
--- a/src/net.h
+++ b/src/net.h
@@ -178,6 +178,7 @@ enum class ConnectionType {
      * AddrMan is empty.
      */
     ADDR_FETCH,
+    kMaxValue=ADDR_FETCH,
 };
 
 class NetEventsInterface;
diff --git a/src/net_processing.cpp b/src/net_processing.cpp
index c5ea2dc85f..964d4e1899 100644
--- a/src/net_processing.cpp
+++ b/src/net_processing.cpp
@@ -2702,6 +2702,7 @@ void PeerManager::ProcessMessage(CNode& pfrom, const std::string& msg_type, CDat
                     return;
                 } else if (!fAlreadyHave && !m_chainman.ActiveChainstate().IsInitialBlockDownload()) {
                     AddTxAnnouncement(pfrom, gtxid, current_time);
+                    assert(!pfrom.IsFeelerConn());
                 }
             } else {
                 LogPrint(BCLog::NET, "Unknown inv type \"%s\" received from peer=%d\n", inv.ToString(), pfrom.GetId());
diff --git a/src/test/fuzz/util.h b/src/test/fuzz/util.h
index 465452c394..9e345d0c73 100644
--- a/src/test/fuzz/util.h
+++ b/src/test/fuzz/util.h
@@ -307,7 +307,7 @@ auto ConsumeNode(FuzzedDataProvider& fuzzed_data_provider, const std::optional<N
     const uint64_t local_host_nonce = fuzzed_data_provider.ConsumeIntegral<uint64_t>();
     const CAddress addr_bind = ConsumeAddress(fuzzed_data_provider);
     const std::string addr_name = fuzzed_data_provider.ConsumeRandomLengthString(64);
-    const ConnectionType conn_type = fuzzed_data_provider.PickValueInArray(ALL_CONNECTION_TYPES);
+    const ConnectionType conn_type = fuzzed_data_provider.ConsumeEnum<ConnectionType>();
     const bool inbound_onion = fuzzed_data_provider.ConsumeBool();
     if constexpr (ReturnUniquePtr) {
         return std::make_unique<CNode>(node_id, local_services, my_starting_height, socket, address, keyed_net_group, local_host_nonce, addr_bind, addr_name, conn_type, inbound_onion);
```

The following diff was used for "std::array":

```diff
diff --git a/src/net_processing.cpp b/src/net_processing.cpp
index c5ea2dc85f..964d4e1899 100644
--- a/src/net_processing.cpp
+++ b/src/net_processing.cpp
@@ -2702,6 +2702,7 @@ void PeerManager::ProcessMessage(CNode& pfrom, const std::string& msg_type, CDat
                     return;
                 } else if (!fAlreadyHave && !m_chainman.ActiveChainstate().IsInitialBlockDownload()) {
                     AddTxAnnouncement(pfrom, gtxid, current_time);
+                    assert(!pfrom.IsFeelerConn());
                 }
             } else {
                 LogPrint(BCLog::NET, "Unknown inv type \"%s\" received from peer=%d\n", inv.ToString(), pfrom.GetId());
```


</details>



| kMaxValue (`FuzzedDataProvider::ConsumeEnum`) | std::array (`FuzzedDataProvider::PickValueInArray`) |
|-----------------------------------------------|-----------------------------------------------------|
|                 fdp_enum                              |                        fdp_arr                             |

No difference should be observed because both calls to the fuzz engine are compiled down to the same `ConsumeIntegralInRange`. Given the limited experimental data, this seems to hold in practice.

### Weak enum

TODO WIP

#### kMaxValue (`FuzzedDataProvider::ConsumeEnum`)

#### std::array (`ConsumeWeakEnum`)

**Comment by practicalswift** [comment]
cr ACK fadbf6a83040b7a8b9f91e27b61adfaf4c5df3fb

Thanks for providing benchmarks!

File: src/test/util/net.h (hunk 1 above)
Comment (MarcoFalke) [reply src/test/util/net.h:40]: For strong enums, I was thinking about a macro `ENUM_CLASS_ALL` that writes the `enum class` and `std::array` that holds all enum types of that class. Thus, we could keep using `PickValueInArray` for strong enums. `FuzzedDataProvider::ConsumeEnum` is an alternative for strong enums that does exactly the same from the perspective of the fuzz engine.

For weak enums, `ConsumeWeakEnum` is probably the best bet. I tried `kMaxValue` and it performed strictly worse in all scenarios, in one it was unable to find a crash at all. And it can't possibly work for 64-bit enums. Someone should report those bugs to google. See also the benchmark: https://github.com/bitcoin/bitcoin/pull/20789#issuecomment-752961937

**Comment by MarcoFalke** [comment]
@vasild btw for the merge script to pick up your ack, you'll have to provide at least the first 6 chars of the git hash ;)

File: src/test/fuzz/util.h [hunk 3]
```diff
@@ -283,24 +292,30 @@ inline CService ConsumeService(FuzzedDataProvider& fuzzed_data_provider) noexcep
...
+    const ConnectionType conn_type = fuzzed_data_provider.PickValueInArray(ALL_CONNECTION_TYPES);
     const bool inbound_onion = fuzzed_data_provider.ConsumeBool();
-    return {node_id, local_services, my_starting_height, socket, address, keyed_net_group, local_host_nonce, addr_bind, addr_name, conn_type, inbound_onion};
+    if constexpr (ReturnUniquePtr) {
+        return std::make_unique<CNode>(node_id, local_services, my_starting_height, socket, address, keyed_net_group, local_host_nonce, addr_bind, addr_name, conn_type, inbound_onion);
+    } else {
+        return CNode{node_id, local_services, my_starting_height, socket, address, keyed_net_group, local_host_nonce, addr_bind, addr_name, conn_type, inbound_onion};
+    }
 }
+std::unique_ptr<CNode> ConsumeNodeAsUniquePtr(FuzzedDataProvider& fdp, const std::optional<NodeId>& node_id_in = nullopt) { return ConsumeNode<true>(fdp, node_id_in); }
```
Comment (mzumsande) [inline src/test/fuzz/util.h:318]: Trying to build this with clang I get linker errors (`multiple definition of ConsumeNodeAsUniquePtr(FuzzedDataProvider&, std::optional<long> const&)`). 
I think that adding an `inline` to  `ConsumeNodeAsUniquePtr()` would fix this.

Comment (MarcoFalke) [reply src/test/fuzz/util.h]: Thanks, fixed. Not sure why I can't reproduce locally. Are you using the macOS clang?

**Comment by vasild** [comment]
ACK fac2b6c58ee0bd1efa7a1531af3b882b451c920b

Both fadbf6a83 and fac2b6c58 compile fine with clang 12.0.0.

@MarcoFalke so you were lucky enough to get 15 straight commit ids all starting with `fa`. I guess you have to have 16777216 times more ~CPU~luck in order to make a commit with arbitrary contents that starts with `fac2b6c5` :-D

Happy New Year! :tada:

File: src/test/fuzz/util.h (hunk 3 above)
Comment (mzumsande) [reply src/test/fuzz/util.h]: I am using clang version 6.0.0-1ubuntu2

**Comment by mzumsande** [comment]
ACK fac2b6c58ee0bd1efa7a1531af3b882b451c920b

Code looks good to me, built locally and did some testing, as in the benchmarks.

As for the worse performance of kMaxValue, I think calling this a "bug" that should be reported is too hard: `FuzzedDataProvider::ConsumeEnum()` does have a disclaimer "The enum must start at 0 and be contiguous" so it's just not designed for bitmasks such as `enum ServiceFlags`. Also, considering that all `ConsumeEnum()` does is to call `ConsumeIntegralInRange` between `0` and `kMaxValue`, it is clear that `NODE_NETWORK_LIMITED | NODE_WITNESS`, which is` >  kMaxValue` in the benchmark  "Double weak match (high bits)" can't possibly ever hit.

**Comment by MarcoFalke** [comment]
Oh, this is missing from the documentation in the declaration: https://github.com/bitcoin/bitcoin/blob/e75f91eae3936269b40b4bfdfe540d5526270936/src/test/fuzz/FuzzedDataProvider.h#L70-L71

It is only mentioned in the implementation: 

https://github.com/bitcoin/bitcoin/blob/e75f91eae3936269b40b4bfdfe540d5526270936/src/test/fuzz/FuzzedDataProvider.h#L291-L298

**Comment by MarcoFalke** [comment]
Rebased due to trivial conflict in adjacent line

**Comment by jonatack** [comment]
Concept ACK, first read-through looks very good.

**Comment by mzumsande** [comment]
@MarcoFalke: These commit hashes starting with "fa" in all of your PRs are getting weird (also in 20649, 20786, 20753, 20736, 20480). With SHA-1 being broken, could this be some sort of bug or joke?

**Comment by MarcoFalke** [comment]
Rebased after removal of my_starting_height

**Comment by MarcoFalke** [comment]
Btw, should be (relatively) easy to re-ACK :pray:

**Comment by mzumsande** [comment]
ACK eeee43bc48ea7fbacd3c5e3f076f01f04744adb8 after rebase.
