### ISSUE TITLE
Master doesn't compile on MacOS X 10.13 High Sierra

### ISSUE THREAD

**Issue by feed3r** [bitcoin/bitcoin#28206]
Hello guys, I'm trying to compile the current Master branch on a quite old Macbook Pro (early 2011) for which the latest supported os is Mac OS X 10.13 high sierra, and I'm getting the following error:

```
Alessios-MacBook-Pro:src feeder$ make V=1
g++ -std=c++17 -DHAVE_CONFIG_H -I. -I../src/config   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -DHAVE_BUILD_INFO -Xclang -internal-isystem/usr/local/include -DMAC_OSX -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -DPROVIDE_FUZZ_MAIN_FUNCTION -I. -I./minisketch/include -I./secp256k1/include -I./univalue/include -I./leveldb/include   -Wstack-protector -fstack-protector-all -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wloop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wunreachable-code-loop-increment -Wimplicit-fallthrough -Wdocumentation -Wno-unused-parameter -Wno-self-assign       -g -O2 -MT bitcoind-bitcoind.o -MD -MP -MF .deps/bitcoind-bitcoind.Tpo -c -o bitcoind-bitcoind.o `test -f 'bitcoind.cpp' || echo './'`bitcoind.cpp
In file included from bitcoind.cpp:10:
In file included from ./chainparams.h:9:
In file included from ./kernel/chainparams.h:10:
In file included from ./netaddress.h:18:
./util/strencodings.h:15:10: fatal error: 'charconv' file not found
#include <charconv>
         ^~~~~~~~~~
1 error generated.
make[1]: *** [bitcoind-bitcoind.o] Error 1
make: *** [all-recursive] Error 1
```
I think this is a known issue, and seems to be related to an old compiler, that does not fully support C++17 (and charconv, in particular) 

My current compiler is an Apple LLVM 10, that I would believe is not that old:

```
Alessios-MacBook-Pro:src feeder$ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Does anybody know if MacOS 10.13 is not supported anymore and it's necessary to upgrade to a different release? 

Is it known if  MacOS 10.15 Catalina is supported?

PS: I also tried to install a newer version of GCC through BREW, but this release of MacOS is not supported anymore, so I'm just considering to change environment.

**Comment by fanquake** [comment]
> that does not fully support C++17 

Master requires a C++17 capable compiler, so you wont be able to compile it with a compiler that doesn't support C++17. I'd suggest installing a modern LLVM/Clang via brew, and using that, if possible.

> Does anybody know if MacOS 10.13 is not supported anymore
> Is it known if MacOS 10.15 Catalina is supported?

On master, the minimum supported macOS version is 11.0. The prior minimum supported macOS version was 10.15.

**Comment by fanquake** [comment]
Think we can close this for now, as it's not a bug, and I don't think there's anything we can do. @feed3r feel free to keep commenting if you have further questions etc.

**Comment by feed3r** [comment]
Thank you all guys, yes this is not a bug and I was only looking for any common experience.
I had a solution anyway and will go with a release checking the compatibility in the release notes.
Thank you all again!
