### PR TITLE
refactor: enable `readability-container-contains` clang-tidy rule

### LINKED ISSUE #34101: build: build broken with older supported Boost
Broken by #33192.

Debian Bookworm
GCC 12.2.0
Boost 1.74.0 (our minimum supported is currently 1.73.0)
```bash
cmake -B build -DCMAKE_BUILD_TYPE=Debug
<snip>
/bitcoin/src/txrequest.cpp: In member function 'void TxRequestTracker::Impl::ReceivedInv(NodeId, const GenTxid&, bool, std::chrono::microseconds)':
/bitcoin/src/txrequest.cpp:583:35: error: 'boost::multi_index::multi_index_container<{anonymous}::Announcement, {anonymous}::Announcement_Indices>::index<{anonymous}::ByPeer>::type' {aka 'class boost::multi_index::detail::ordered_index<{anonymous}::ByPeerViewExtractor, std::less<std::tuple<long int, bool, const uint256&> >, boost::multi_index::detail::nth_layer<1, {anonymous}::Announcement, {anonymous}::Announcement_Indices, std::allocator<{anonymous}::Announcement> >, boost::mpl::v_item<{anonymous}::ByPeer, boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::ordered_unique_tag, boost::multi_index::detail::null_augment_policy>'} has no member named 'contains'
  583 |         if (m_index.get<ByPeer>().contains(ByPeerView{peer, true, gtxid.ToUint256()})) return;
      |                                   ^~~~~~~~
gmake[2]: *** [src/CMakeFiles/bitcoin_node.dir/build.make:1308: src/CMakeFiles/bitcoin_node.dir/txrequest.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /bitcoin/src/support/allocators/pool.h:17,
                 from /bitcoin/src/memusage.h:10,
                 from /bitcoin/src/core_memusage.h:10,
                 from /bitcoin/src/coins.h:10,
                 from /bitcoin/src/txmempool.h:9,
                 from /bitcoin/src/txmempool.cpp:6:
/bitcoin/src/txmempool.cpp: In member function 'CTxMemPool::ChangeSet::TxHandle CTxMemPool::ChangeSet::StageAddition(const CTransactionRef&, CAmount, int64_t, unsigned int, uint64_t, bool, int64_t, LockPoints)':
/bitcoin/src/txmempool.cpp:991:22: error: 'CTxMemPool::indexed_transaction_set' {aka 'class boost::multi_index::multi_index_container<CTxMemPoolEntry, CTxMemPool::CTxMemPoolEntry_Indices>'} has no member named 'contains'
  991 |     Assume(!m_to_add.contains(tx->GetHash()));
      |                      ^~~~~~~~
/bitcoin/src/util/check.h:125:51: note: in definition of macro 'Assume'
  125 | #define Assume(val) inline_assertion_check<false>(val, std::source_location::current(), #val)
      |                                                   ^~~
gmake[2]: *** [src/CMakeFiles/bitcoin_node.dir/build.make:1294: src/CMakeFiles/bitcoin_node.dir/txmempool.cpp.o] Error 1
```

Reported by @marcofleon.

### PR DESCRIPTION
**Pull request by l0rinc**
Replace the last few instances of `.count() != 0` and `.count() == 0` and bare `count()` patterns with the more expressive C++20 `.contains()` method:

* `std::set<std::string>` in `getblocktemplate` RPC;
* `std::map<std::string, ...>` in `transaction_tests`;
* other bare `std::unordered_set` and `std::map` count calls.

Also fixes https://github.com/bitcoin/bitcoin/issues/34101 by reverting `boost::multi_index::contains` calls not available in our minimum supported version.

With no remaining violations, enable the `readability-container-contains` clang-tidy check to prevent future regressions.

Follow-up to https://github.com/bitcoin/bitcoin/pull/33192

### CODE REVIEW

**Comment by Chand-ra** [comment]
I performed a quick `grep '\.count()'` and it looks like there are quite a few instances that seem eligible for this change but aren't included here, is there some reason for doing so? For example, I found [1](https://github.com/bitcoin/bitcoin/blob/ab513103df8d1cadd2cf23397a39c652f3a2a550/src/net.cpp#L2017), [2](https://github.com/bitcoin/bitcoin/blob/ab513103df8d1cadd2cf23397a39c652f3a2a550/src/net.cpp#L2018), [3](https://github.com/bitcoin/bitcoin/blob/ab513103df8d1cadd2cf23397a39c652f3a2a550/src/net.cpp#L2322), [4](https://github.com/bitcoin/bitcoin/blob/master/src/net.cpp#L3755) such instances in `src/net.cpp`.

**Comment by janb84** [comment]
> I performed a quick `grep '\.count()'` and it looks like there are quite a few instances that seem eligible for this change but aren't included here, is there some reason for doing so? For example, I found [1](https://github.com/bitcoin/bitcoin/blob/ab513103df8d1cadd2cf23397a39c652f3a2a550/src/net.cpp#L2017), [2](https://github.com/bitcoin/bitcoin/blob/ab513103df8d1cadd2cf23397a39c652f3a2a550/src/net.cpp#L2018), [3](https://github.com/bitcoin/bitcoin/blob/ab513103df8d1cadd2cf23397a39c652f3a2a550/src/net.cpp#L2322), [4](https://github.com/bitcoin/bitcoin/blob/master/src/net.cpp#L3755) such instances in `src/net.cpp`.

The change is not about removing `.count()` everywhere. But to change it in cases where the `count()` statement is used to count the number of occurrences to indicate if something is in the collection.  The example you reference eg `bool has_received{last_recv.count() != 0};` is a "correct" usage of `count()` (is it not empty)

**Comment by maflcko** [comment]
> Task `lint`: https://github.com/bitcoin/bitcoin/actions/runs/20319772315/job/58372602822

Looks like GitHub nuked all historic commits and historic CI runs here?

**Review by rkrux — APPROVED** [review]
lgtm, code review ACK 31c8ef3d9c885fbe810d5454ba1041ee87efa917

Nice, I missed reviewing the predecessor PR.

**Comment by Chand-ra** [comment]
> The change is not about removing `.count()` everywhere. But to change it in cases where the `count()` statement is used to count the number of occurrences to indicate if something is in the collection. The example you reference eg `bool has_received{last_recv.count() != 0};` is a "correct" usage of `count()` (is it not empty)

Makes sense! I seem to have mistaken `count()` in `std::chrono` with the ones for container classes.

ACK [31c8ef3](https://github.com/bitcoin/bitcoin/pull/34095/commits).

**Comment by l0rinc** [comment]
Thanks for checking @Chand-ra - your mentioned examples are not "contains" alternatives but "exists" alternatives for `chrono::duration` (which is orthogonal to this change and doesn't seem to exist in C++20 anyway).

> Looks like GitHub nuked all historic commits and historic CI runs here?

I did push a few versions while CI was running, maybe that was confusing - is there anything you need me to do here?

**Comment by fanquake** [comment]
Moved to draft for now, given these refactors have broken our minimum version requirements (#34101). That should be resolved before doing anything else here.

**Comment by l0rinc** [comment]
Reverted the boost changes (already merged ones and new ones), clang-tidy should still pass.

**Review by marcofleon — COMMENTED** [review]
code review ACK a8a0a0ff77309a95645f6de00595c1dc39cd6eff

Tested with boost 1.74, good to go.

**Review by pablomartin4btc — APPROVED** [review]
cr-ACK a8a0a0ff77309a95645f6de00595c1dc39cd6eff

Verified the revert of `boost::multi_index::contains` instances (2).

**Review by janb84 — COMMENTED** [review]
cr ACK a8a0a0ff77309a95645f6de00595c1dc39cd6eff

Also confirmed that clang-tidy (still) works

**Review by hebasto — COMMENTED** [review]
Tested a8a0a0ff77309a95645f6de00595c1dc39cd6eff on Fedora 43 with the downloaded [Boost 1.73.0](https://www.boost.org/releases/1.73.0/) and the following patch:
```diff
--- a/cmake/module/AddBoostIfNeeded.cmake
+++ b/cmake/module/AddBoostIfNeeded.cmake
@@ -29,7 +29,7 @@ function(add_boost_if_needed)
     endif()
   endif()
 
-  find_package(Boost 1.73.0 REQUIRED CONFIG)
+  find_package(Boost 1.73.0 REQUIRED)
   mark_as_advanced(Boost_INCLUDE_DIR boost_headers_DIR)
   # Workaround for a bug in NetBSD pkgsrc.
   # See: https://github.com/NetBSD/pkgsrc/issues/167.
--- a/src/ipc/CMakeLists.txt
+++ b/src/ipc/CMakeLists.txt
@@ -20,6 +20,7 @@ target_link_libraries(bitcoin_ipc
   PRIVATE
     core_interface
     univalue
+    Boost::headers
 )
 
 if(BUILD_TESTS)
```

The compilation fails for another similar reason:
```
$ cmake -B build -DBoost_INCLUDE_DIR=/home/hebasto/Downloads/boost_1_73_0
$ cmake --build build
[398/621] Building CXX object src/CMakeFiles/bitcoin_node.dir/txmempool.cpp.o
FAILED: [code=1] src/CMakeFiles/bitcoin_node.dir/txmempool.cpp.o 
/usr/bin/ccache /usr/lib64/ccache/c++ -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_NO_CXX98_FUNCTION_BASE -I/home/hebasto/dev/bitcoin/build/src -I/home/hebasto/dev/bitcoin/src -I/home/hebasto/dev/bitcoin/src/leveldb/include -I/home/hebasto/dev/bitcoin/src/minisketch/include -I/home/hebasto/dev/bitcoin/src/univalue/include -isystem /home/hebasto/Downloads/boost_1_73_0 -O2 -g -std=c++20 -fPIC -fno-extended-identifiers -fdebug-prefix-map=/home/hebasto/dev/bitcoin/src=. -fmacro-prefix-map=/home/hebasto/dev/bitcoin/src=. -fstack-reuse=none -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -Wall -Wextra -Wformat -Wformat-security -Wvla -Wredundant-decls -Wdate-time -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Woverloaded-virtual -Wsuggest-override -Wimplicit-fallthrough -Wunreachable-code -Wbidi-chars=any -Wundef -Wleading-whitespace=spaces -Wtrailing-whitespace=any -Wno-unused-parameter -MD -MT src/CMakeFiles/bitcoin_node.dir/txmempool.cpp.o -MF src/CMakeFiles/bitcoin_node.dir/txmempool.cpp.o.d -o src/CMakeFiles/bitcoin_node.dir/txmempool.cpp.o -c /home/hebasto/dev/bitcoin/src/txmempool.cpp 
/home/hebasto/dev/bitcoin/src/txmempool.cpp: In member function ‘void CTxMemPool::Apply(ChangeSet*)’:
/home/hebasto/dev/bitcoin/src/txmempool.cpp:205:48: error: ‘CTxMemPool::indexed_transaction_set’ {aka ‘class boost::multi_index::multi_index_container<CTxMemPoolEntry, CTxMemPool::CTxMemPoolEntry_Indices>’} has no member named ‘extract’
  205 |         auto node_handle = changeset->m_to_add.extract(tx_entry);
      |                                                ^~~~~~~
[415/621] Building CXX object src/CMakeFiles/bitcoin_node.dir/validation.cpp.o
ninja: build stopped: subcommand failed.
```

UPDATE: Boost 1.74 compiles without the error.

**Comment by hebasto** [comment]
@l0rinc 

Feel free to incorporate https://github.com/bitcoin/bitcoin/pull/34107 into this PR, if that makes sense.

**Comment by l0rinc** [comment]
Thanks @hebasto, I think the two can be merged independently.

**Review by hebasto — COMMENTED** [review]
Approach ACK a8a0a0ff77309a95645f6de00595c1dc39cd6eff.

> Also fixes #34101 by reverting `boost::multi_index::contains` calls not available in our minimum supported version.

I'd prefer having this change in a separate commit.

Also there's a typo in the commit message:
"... available in Boost 1.74.0 only" --> "... available in Boost since 1.78.0 only"

**Comment by l0rinc** [comment]
Rebased and split into two commits and updated commit message to reference `Boost 1.78.0` instead.

**Review by hebasto — APPROVED** [review]
ACK 1e94e562f76e6152dffb2a2d07dc3429137098b5.

**Review by pablomartin4btc — APPROVED** [review]
re-ACK 1e94e562f76e6152dffb2a2d07dc3429137098b5

Boost fix/ revert split in a separate commit.

**Review by janb84 — COMMENTED** [review]
ACK 1e94e562f76e6152dffb2a2d07dc3429137098b5

changes since last ack:
- reverted boost library contains calls
- split out the revert in separate commit.

**Review by rkrux — COMMENTED** [review]
re-ACK 1e94e562f76e6152dffb2a2d07dc3429137098b5
