### ISSUE TITLE
MacOSX travis build broken since #9891 (qt avx512)

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#9898]
@theuni strange compile issue below appeared after merging #9891, seems unrelated to your change:

https://travis-ci.org/bitcoin/bitcoin/jobs/206540499
```
make[1]: Entering directory `/home/travis/build/bitcoin/bitcoin/depends/work/build/x86_64-apple-darwin11/qt/5.7.1-e178b34980a/qtbase/config.tests/common/avx512'
clang++ -c -pipe -pipe -O2 -I/home/travis/build/bitcoin/bitcoin/depends/x86_64-apple-darwin11/include -stdlib=libc++ -pipe -pipe -O2 -I/home/travis/build/bitcoin/bitcoin/depends/x86_64-apple-darwin11/include -target x86_64-apple-darwin11 -isysroot /home/travis/build/bitcoin/bitcoin/depends/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -mavx512vl -g -Wall -W -fPIC -DAVX512WANT=VL -I. -I../../../mkspecs/macx-clang-linux -o avx512.o avx512.cpp
avx512.cpp:87:18: error: use of undeclared identifier '_mm256_maskz_loadu_epi32'
    __m256i i2 = _mm256_maskz_loadu_epi32(0, argv);
                 ^
avx512.cpp:88:5: error: use of undeclared identifier '_mm256_mask_storeu_epi32';
      did you mean '_mm256_maskstore_epi32'?
    _mm256_mask_storeu_epi32(argv + 1, m, i2);
    ^~~~~~~~~~~~~~~~~~~~~~~~
    _mm256_maskstore_epi32
/home/travis/build/bitcoin/bitcoin/depends/x86_64-apple-darwin11/native/bin/../lib/clang/3.7.1/include/avx2intrin.h:931:1: note: 
      '_mm256_maskstore_epi32' declared here
_mm256_maskstore_epi32(int *__X, __m256i __M, __m256i __Y)
^
avx512.cpp:88:30: error: cannot initialize a parameter of type 'int *' with an
      rvalue of type 'char **'
    _mm256_mask_storeu_epi32(argv + 1, m, i2);
                             ^~~~~~~~
/home/travis/build/bitcoin/bitcoin/depends/x86_64-apple-darwin11/native/bin/../lib/clang/3.7.1/include/avx2intrin.h:931:29: note: 
      passing argument to parameter '__X' here
_mm256_maskstore_epi32(int *__X, __m256i __M, __m256i __Y)
                            ^
3 errors generated.
make[1]: *** [avx512.o] Error 1
```

**Comment by laanwj** [comment]
Closing this. It looks like the problem disappeared as mysteriously as it appeared.

**Comment by theuni** [comment]
@laanwj I commented on IRC, but looks like I didn't paste here.

Those are compile-checks to see what the host compiler can build, so failures are expected. The error here was the timeout, caused by the s3 downtime. So indeed, nothing to see here.
