### ISSUE TITLE
TestShell doesn't work

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#27904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Following the instructions here:

https://github.com/bitcoin/bitcoin/blob/master/test/functional/test-shell.md#2-importing-testshell-from-the-bitcoin-core-repository

```
AttributeError: type object 'TestShell' has no attribute 'setup'
```

### Expected behaviour

It should setup the TestShell

### Steps to reproduce

Build binaries.

On macOS:

```
$ python
Python 3.8.16 (default, May 19 2023, 13:41:40) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> import sys
>>> sys.path.insert(0,"/home/sjors/dev/bitcoin/test/functional")
>>> from test_framework.test_shell import TestShell
>>> TestShell.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'TestShell' has no attribute 'setup'
```

On Ubuntu:

```
ython 3.8.16 (default, May  8 2023, 15:02:46) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0,"/home/sjors/dev/bitcoin/test/functional")
>>> from test_framework.test_shell import TestShell
>>> TestShell.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'TestShell' has no attribute 'setup'

```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@f0758d8a6696657269d9c057e7aa079ffa9e1c16

### Operating system and version

Ubuntu 23.04 / macOS 13.4

### Machine specifications

Using Python 3.8.16 on both. macOS is on an Intel machine. Python is installed via PyEnv. I'm not using a virtual environment.

**Comment by Sjors** [comment]
From IRC: 

```
@theStack: seems like the parantheses are missing and it should be `TestShell().setup()` instead of `TestShell.setup()` (i.e. it's not a class method, but needs an instance)
```

**Comment by ismaelsadeeq** [comment]
Tested and it works on pop-OS 22.04, with  Python 3.10.6,  I would update the  TestShell instruction. 👍🏾
