### ISSUE TITLE
macOS build error: bench/bench_bitcoin-data.o redefinition of 'block413567'

### ISSUE THREAD

**Issue by brentkearney** [bitcoin/bitcoin#16567]
The latest master branch (as of commit e5fdda6) fails to compile on macOS 10.14.6.

```
Making all in src
  CXX      bench/bench_bitcoin-data.o
In file included from bench/data.cpp:10:
./bench/data/block413567.raw.h:1:28: error: redefinition of 'block413567' with a different type: 'const unsigned char []' vs 'const std::vector<uint8_t>'
      (aka 'const vector<unsigned char>')
static unsigned const char block413567[] = {
                           ^
./bench/data.h:14:35: note: previous declaration is here
extern const std::vector<uint8_t> block413567;
                                  ^
bench/data.cpp:11:40: error: use of undeclared identifier 'block413567_raw'; did you mean 'block413567'?
const std::vector<uint8_t> block413567{block413567_raw, block413567_raw + sizeof(block413567_raw) / sizeof(block413567_raw[0])};
                                       ^~~~~~~~~~~~~~~
                                       block413567
bench/data.cpp:11:28: note: 'block413567' declared here
const std::vector<uint8_t> block413567{block413567_raw, block413567_raw + sizeof(block413567_raw) / sizeof(block413567_raw[0])};
                           ^
bench/data.cpp:11:82: error: use of undeclared identifier 'block413567_raw'; did you mean 'block413567'?
const std::vector<uint8_t> block413567{block413567_raw, block413567_raw + sizeof(block413567_raw) / sizeof(block413567_raw[0])};
                                                                                 ^~~~~~~~~~~~~~~
                                                                                 block413567
bench/data.cpp:11:28: note: 'block413567' declared here
const std::vector<uint8_t> block413567{block413567_raw, block413567_raw + sizeof(block413567_raw) / sizeof(block413567_raw[0])};
                           ^
bench/data.cpp:11:108: error: use of undeclared identifier 'block413567_raw'; did you mean 'block413567'?
const std::vector<uint8_t> block413567{block413567_raw, block413567_raw + sizeof(block413567_raw) / sizeof(block413567_raw[0])};
                                                                                                           ^~~~~~~~~~~~~~~
                                                                                                           block413567
bench/data.cpp:11:28: note: 'block413567' declared here
const std::vector<uint8_t> block413567{block413567_raw, block413567_raw + sizeof(block413567_raw) / sizeof(block413567_raw[0])};
                           ^
bench/data.cpp:11:57: error: use of undeclared identifier 'block413567_raw'
const std::vector<uint8_t> block413567{block413567_raw, block413567_raw + sizeof(block413567_raw) / sizeof(block413567_raw[0])};
                                                        ^
5 errors generated.
make[2]: *** [bench/bench_bitcoin-data.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

To reproduce:
```
cd bitcoin
make clean
git pull origin master
./autogen.sh ; ./configure; make
```

Version:
Latest source as of commit e5fdda68c6d2313edb74443f0d1e6d2ce2d97f5e

On machine:
MacOS Mojave 10.14.6, MBP 2.9 GHz Intel Core i7, SSD

The conflig.log: https://pastebin.com/nA5F7gLZ

**Comment by fanquake** [comment]
Try a `git clean -fx` in your `bitcoin` dir. Then `./autogen.sh && ./configure && make -j4` again.

**Comment by brentkearney** [comment]
That did it. Thanks!
