### ISSUE TITLE
[depends] Boost fails to build on OSX 10.11, Xcode 7.3.1

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#7998]
```
clang: warning: optimization flag '-finline-functions' is not supported
In file included from libs/thread/src/pthread/once.cpp:8:
In file included from libs/thread/src/pthread/./once_atomic.cpp:9:
In file included from ./boost/thread/once.hpp:20:
In file included from ./boost/thread/pthread/once_atomic.hpp:16:
./boost/thread/detail/move.hpp:31:10: fatal error: 'type_traits' file not found
#include <type_traits>
```

It seems adding `-stdlib=libc++` to the cxxflags fixes the issue

This also occurs with the `x86_64-apple-darwin11` prefix

**Comment by fanquake** [comment]
@theuni if this would be an appropriate fix I can add it it to #7993

**Comment by theuni** [comment]
Hmm, I would expect you to have the same problem with all other c++ deps as well.

Let's just match the way we do it on the host side. Does this work?
```diff
diff --git a/depends/builders/darwin.mk b/depends/builders/darwin.mk
index 200d6ed..27f550a 100644
--- a/depends/builders/darwin.mk
+++ b/depends/builders/darwin.mk
@@ -11,7 +11,7 @@ build_darwin_DOWNLOAD = curl --location --fail --connect-timeout $(DOWNLOAD_CONN
 
 #darwin host on darwin builder. overrides darwin host preferences.
 darwin_CC=$(shell xcrun -f clang) -mmacosx-version-min=$(OSX_MIN_VERSION)
-darwin_CXX:=$(shell xcrun -f clang++) -mmacosx-version-min=$(OSX_MIN_VERSION)
+darwin_CXX:=$(shell xcrun -f clang++) -mmacosx-version-min=$(OSX_MIN_VERSION) -stdlib=libc++
 darwin_AR:=$(shell xcrun -f ar)
 darwin_RANLIB:=$(shell xcrun -f ranlib)
 darwin_STRIP:=$(shell xcrun -f strip)
```
