### PR TITLE
build: fix linking against -latomic when building for riscv

### PR DESCRIPTION
**Pull request by fanquake**
Since the merge of #19937, riscv builds have been failing, due to a link issue with [`std::atomic_exchange`](https://en.cppreference.com/w/cpp/atomic/atomic_exchange) in `bitcoin-util`:
```bash
  CXXLD    bitcoin-util
bitcoin_util-bitcoin-util.o: In function `grind_task':
/home/ubuntu/build/bitcoin/distsrc-riscv64-linux-gnu/src/bitcoin-util.cpp:98: undefined reference to `__atomic_exchange_1'
collect2: error: ld returned 1 exit status

```

We have a [macro](https://github.com/bitcoin/bitcoin/blob/master/build-aux/m4/l_atomic.m4) that tries to determine when `-latomic` is required, however it doesn't quite work well enough, as it's currently determining it isn't needed:
```bash
./autogen.sh
./configure --prefix=/home/ubuntu/bitcoin/depends/riscv64-linux-gnu
...
checking whether std::atomic can be used without link library... yes
```

This PR adds a call to `std::atomic_exchange` to the macro, which will get us properly linked against `-latomic` on riscv:
```bash
checking whether std::atomic can be used without link library... no
checking whether std::atomic needs -latomic... yes
```

Also adds an `<atomic>` include to `bitcoin-util.cpp`.

### CODE REVIEW

**Review by monstro805 — APPROVED** [review]

**Comment by laanwj** [comment]
Testing this. Doing a compile on the SiFive Unleashed is a bit slow, so give it some time.

Master without this PR:
```
configure:5619: checking whether std::atomic can be used without link library
configure:5637: g++ -std=c++17 -o conftest -g -O2   conftest.cpp  >&5
configure:5637: $? = 0
configure:5639: result: yes
```
Now trying a build of master to see if it fails. Will then try with this PR.

**Comment by laanwj** [comment]
Tested ACK 54ce4fac80689621dcbcc76169b2b00b179ee743
