### ISSUE TITLE
main.cpp error during make. Ubuntu 16.04 with boost 1.77

### ISSUE THREAD

**Issue by cvcook7** [bitcoin/bitcoin#24619]
Does anyone know how to address the rpcserver.cpp error during the make process? 

I am using Ubuntu 16.04 with the default boost 1.58.

```
  CXX      rpcserver.o
rpcserver.cpp:447:102: error: wrong number of template arguments (2, should be 1)
 static void RPCAcceptHandler(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
                                                                                                      ^
In file included from /usr/local/include/boost/asio.hpp:30,
                 from rpcprotocol.h:15,
                 from rpcserver.h:10,
                 from rpcserver.cpp:6:
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: provided for ‘template<class Protocol> class boost::asio::basic_socket_acceptor’
 class basic_socket_acceptor
       ^~~~~~~~~~~~~~~~~~~~~
rpcserver.cpp:447:104: error: template argument 1 is invalid
 static void RPCAcceptHandler(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
                                                                                                        ^
rpcserver.cpp:457:95: error: wrong number of template arguments (2, should be 1)
 static void RPCListen(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,

```

**System information**
Ubuntu 16.04, default boost 1.58 installed.

**Comment by hebasto** [comment]
> Ubuntu 16.04, default boost 1.58 installed.

The minimum required Boost is [1.64.0](https://github.com/bitcoin/bitcoin/pull/22320) since v22.0. To build Bitcoin Core on your system try build with [depends](https://github.com/bitcoin/bitcoin/blob/master/depends/README.md).

**Comment by cvcook7** [comment]
Thanks. I have removed the Boost 1.58 and manually installed by Ubuntu 16.04 with Boost 1.77.

Now, I have a new error with the `main.cpp` during make. Does anyone know how to address this `main.cpp` issue?
 
```
main.cpp: In function ‘void RegisterWallet(CWalletInterface*)’:
main.cpp:152:98: error: ‘_1’ was not declared in this scope
     g_signals.SyncTransaction.connect(boost::bind(&CWalletInterface::SyncTransaction, pwalletIn, _1, _2, _3));

```

**Comment by hebasto** [comment]
@cvcook7 

What version of source are you trying to build (a branch, or a tag, or a commit)?

What are options you provided to the `configure` script?

Have you successfully built with depends?

**Comment by cvcook7** [comment]
Hi @hebasto ,

Thanks for your reply. I have actually found a way to solve the problem. I just needed to add the following to the `main.cpp` so that it could work with my boost 1.77.

```
#include <boost/bind/bind.hpp> 
using namespace boost::placeholders;
``` 

I think it is because the Bind placeholders (_1, _2, ...) in the global namespace are deprecated in newer versions of boost. Thanks.
