### ISSUE TITLE
[build] cannot build tests using v26.0

### ISSUE THREAD

**Issue by nymkappa** [bitcoin/bitcoin#29051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I'm trying to upgrade to core v26.0 on macOS (M1 processor) but I'm getting the following error when building from sources:

```
  CXX      test/test_bitcoin-base58_tests.o
test/base58_tests.cpp:26:22: error: no matching function for call to 'read_json'
    UniValue tests = read_json(json_tests::base58_encode_decode);
                     ^~~~~~~~~
./test/util/json.h:12:10: note: candidate function not viable: no known conversion from 'const unsigned char[1462]' to 'const std::string' (aka 'const basic_string<char>') for 1st argument
UniValue read_json(const std::string& jsondata);
         ^
test/base58_tests.cpp:46:22: error: no matching function for call to 'read_json'
    UniValue tests = read_json(json_tests::base58_encode_decode);
                     ^~~~~~~~~
./test/util/json.h:12:10: note: candidate function not viable: no known conversion from 'const unsigned char[1462]' to 'const std::string' (aka 'const basic_string<char>') for 1st argument
UniValue read_json(const std::string& jsondata);
         ^
2 errors generated.
make[2]: *** [test/test_bitcoin-base58_tests.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

Previous tag (v25.1) is building fine. I've also tested latest master @ 3e691258d8789a4a89cce42e7e71b130491594d7 and resulted in the same error.

### Expected behaviour

Should build just fine.

### Steps to reproduce

`./configure && make -j 4`

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v26.0 @ 44d8b13c81e5276eb610c99f227a4d090cc532f6

### Operating system and version

macOS Sonoma 14.1.12 (23B92)

### Machine specifications

macBook Pro with Apple M1 Max chip

**Comment by nymkappa** [comment]
> Have you run `make clean` since updating your local repo to v26.0?

I did not. I was not aware I should do this when upgrading. Thanks for the tip. It builds and run fine now on v26.0 @ 44d8b13c81e5276eb610c99f227a4d090cc532f6. All tests also passed. Thank you!

**Comment by luke-jr** [comment]
This should be reopened. It's a bug if `make clean` fixes things. The build system is supposed to automatically detect when a file needs to be rebuilt. (Maybe CMake will fix it?)
