### PR TITLE
Add libtest_util library to msvc build configuration

### PR DESCRIPTION
**Pull request by sipsorcery**
libtest_util was introduced in #17542. This PR adds the msvc build configuration.

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks!
ACK if it passes AppVeyor

**Comment by fanquake** [comment]
```powershell
msbuild /p:TrackFileAccess=false /p:CLToolExe=clcache.exe build_msvc\bitcoin.sln /m /v:q /nologo
bench_bench.obj : error LNK2001: unresolved external symbol "public: __cdecl TestingSetup::~TestingSetup(void)" (??1TestingSetup@@QEAA@XZ) [C:\projects\bitcoin\build_msvc\bench_bitcoin\bench_bitcoin.vcxproj]
bench_bench.obj : error LNK2001: unresolved external symbol "public: __cdecl TestingSetup::TestingSetup(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0TestingSetup@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\projects\bitcoin\build_msvc\bench_bitcoin\bench_bitcoin.vcxproj]
bench_verify_script.obj : error LNK2001: unresolved external symbol "struct CMutableTransaction __cdecl BuildSpendingTransaction(class CScript const &,struct CScriptWitness const &,class CTransaction const &)" (?BuildSpendingTransaction@@YA?AUCMutableTransaction@@AEBVCScript@@AEBUCScriptWitness@@AEBVCTransaction@@@Z) [C:\projects\bitcoin\build_msvc\bench_bitcoin\bench_bitcoin.vcxproj]
bench_verify_script.obj : error LNK2001: unresolved external symbol "struct CMutableTransaction __cdecl BuildCreditingTransaction(class CScript const &,int)" (?BuildCreditingTransaction@@YA?AUCMutableTransaction@@AEBVCScript@@H@Z) [C:\projects\bitcoin\build_msvc\bench_bitcoin\bench_bitcoin.vcxproj]
libbitcoin_server.lib(validation.obj) : error LNK2001: unresolved external symbol "class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(char const *)> const G_TRANSLATION_FUN" (?G_TRANSLATION_FUN@@3V?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z@std@@B) [C:\projects\bitcoin\build_msvc\bench_bitcoin\bench_bitcoin.vcxproj]
C:\projects\bitcoin\build_msvc\x64\Release\bench_bitcoin.exe : fatal error LNK1120: 5 unresolved externals [C:\projects\bitcoin\build_msvc\bench_bitcoin\bench_bitcoin.vcxproj]
```

**Comment by sipsorcery** [comment]
Appveyor should now pass. Ready for review.

**Review by fanquake — APPROVED** [review]
ACK b509554433cb4bd32852239d0dd195ec059657f6 - Appveyor looks good.

**Comment by MarcoFalke** [comment]
Are the gui unit tests not build on appveyor?

**Comment by sipsorcery** [comment]
@MarcoFalke there's no msbuild project for the Qt tests so they have never been built on appveyor. I don't think there's any reason they can't be built. I'll look into it.

**Comment by MarcoFalke** [comment]
Interestingly, even though this build succeeded, the build on master did not

**Comment by sipsorcery** [comment]
Did the appveyor job fail at the test stage? I do get occasional failures on a python test. I haven't tracked down the culprit yet.

All my appveyor builds on master since this PR have worked.

master_builds
