### PR TITLE
Full CJDNS support

### PR DESCRIPTION
**Pull request by vasild**
CJDNS overview
=====

CJDNS is like a distributed, shared VPN with multiple entry points where every participant can reach any other participant. All participants use addresses from the `fc00::/8` network (reserved IPv6 range). Installation and configuration is done outside of applications, similarly to VPN (either in the host/OS or on the network router).

Motivation
=====

Even without this PR it is possible to connect two Bitcoin Core nodes through CJDNS manually by using e.g. `-addnode` in environments where CJDNS is set up. However, this PR is necessary for address relay to work properly and automatic connections to be made to CJDNS peers. I.e. to make CJDNS a first class citizen network like IPv4, IPv6, Tor and I2P.

Considerations
=====

An address from the `fc00::/8` network, could mean two things:
1. Part of a local network, as defined in RFC 4193. Like `10.0.0.0/8`. Bitcoin Core could be running on a machine with such address and have peers with those (e.g. in a local network), but those addresses are not relayed to other peers because they are not globally routable on the internet.
2. Part of the CJDNS network. This is like Tor or I2P - if we have connectivity to that network then we could reach such peers and we do relay them to other peers.

So, Bitcoin Core needs to be able to tell which one is it when it encounters a bare `fc00::/8` address, e.g. from `-externalip=` or by looking up the machine's own addresses. Thus a new config option is introduced `-cjdnsreachable`:
* `-cjdnsreachable=0`: it is assumed a `fc00::/8` address is a private IPv6 (1.)
* `-cjdnsreachable=1`: it is assumed a `fc00::/8` address is a CJDNS one (2.)

After setting up CJDNS outside of Bitcoin Core, a node operator only needs to enable this option.
Addresses from P2P relay/gossip don't need that because they are properly tagged as IPv6 or as CJDNS.

For testing
=====
```
[fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333
[fc68:7026:cb27:b014:5910:e609:dcdb:22a2]:8333
[fcb3:dc50:e1ae:7998:7dc0:7fa6:4582:8e46]:8333
[fcc7:be49:ccd1:dc91:3125:f0da:457d:8ce]:8333
[fcf2:d9e:3a25:4eef:8f84:251b:1b4d:c596]:8333
```

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK and building to try it :smiley:

**Comment by kristapsk** [comment]
Concept ACK

**Comment by Zero-1729** [comment]
Concept ACK 🌱

**Comment by prayank23** [comment]
> CJDNS is like a distributed, shared VPN with multiple entry points where every participant can reach any other participant. All participants use addresses from the fc00::/8 network (reserved IPv6 range). Installation and configuration is done outside of applications, similarly to VPN (either in the host/OS or on the network router).

Sorry but this doesn't look good enough to add one more network to Bitcoin Core. We already have 4 options: ipv4, ipv6, Tor, i2p and 14 combinations which can be used in `onlynet` for outgoing connections.

Will do more research about CJDNS and compare with other networks before ACKing the concept. Let me know if you know any links.

**Comment by amitiuttarwar** [comment]
@vasild 

> However, this PR is necessary for address relay to work properly and automatic connections to be made to CJDNS peers. I.e. to make CJDNS a first class citizen network like IPv4, IPv6, Tor and I2P.

Thanks for providing this motivation, it's helpful to understand the aim of this PR. Could you go a bit further and share your perspective on _why_ you think CJDNS should be a first class citizen network in bitcoin core? Does it provide different features / privacy / etc. from other networks? Or is this a case where you think optionality is good, so supporting more networks is better? Thanks in advance!

**Comment by sipa** [comment]
FWIW, BIP155 does already reserve a network ID for CJDNS.

**Comment by prayank23** [comment]
I did some research about CJDNS, GNUnet and Yggdrasil.

Will read more about these networks and also compare with few others in next few days. Shared initial thoughts and things I did here: https://blockchaincommons.github.io/Bitcoin-Camouflage//blog/cjdns/

**Comment by vasild** [comment]
@prayank23, @amitiuttarwar,

Compared to IPv4/6, CJDNS provides e2e encryption and protects nodes from the traditional traffic analysis and filtering. For example, an ISP blocks port 8333 (dumb) or analyses the traffic to/from a given node, regardless of the port (it is easy to detect that it is Bitcoin P2P protocol being talked on a TCP connection, even if the port is not 8333).

Compared to Tor and I2P, CJDNS provides redundancy. Each of those have their own shades, which may suit different users. For example Tor is popular/widespread but is somewhat centralized, which could lead to [problems](https://darknetdaily.com/2021/01/09/all-v3-onion-addresses-down-after-attack-on-the-tor-network/). I2P connections have source address, but I2P is somewhat slow. CJDNS does not hide the sender and the recipient from intermediate routers, but it is fast. Different things may work for different people. It is good to have options.

So, why not have support for CJDNS? It must be noted that support for X does not come for free. We have to pay the following prices:
* Implementation cost
* Review cost
* Maintenance cost

For the _implementation cost_, notice that CJDNS is already included in [BIP155](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki#specification) and that there is already rudimentary support for it in `master`:

```sh
$ git grep -i cjdns origin/master |wc -l
      49
```

As a result this PR is relatively small and straight-forward. _Review cost_ should be low. From the application's point of view, connecting to CJDNS is as easy as connecting to a normal IPv6 address. Bitcoin Core need not implement support for a specific proxy that talks a specific protocol. Tor and I2P require that. We have this maintenance cost for them:

```sh
$ wc -l src/torcontrol.cpp src/i2p.cpp 
     636 src/torcontrol.cpp
     418 src/i2p.cpp
```

Support for CJDNS goes without that, so its _maintenance cost_ is low compared to Tor and I2P.

Notice also that [OpenWRT routers support CJDNS](https://openwrt.org/packages/pkgdata/cjdns), so from user's perspective it would be a matter of enabling it on their routers and running Bitcoin Core with `-cjdnsreachable`.

In the case of CJDNS, my personal opinion is that the benefits outweigh the cost.

**Comment by jonatack** [comment]
Yes, BIP155 and Tor v3 implementation were both fairly deep changes. I2P was also extensive. This change set is relatively tiny, I've done a first review pass, and in terms of time it was well under 10% that of any of the BIP155 impl, Tor v3, and I2P for me.

**Comment by benthecarman** [comment]
Concept ACK, awesome to see this!

**Comment by duncandean** [comment]
Concept ACK seeing as there is already basic existing support for this in master and noting that this may match some users' needs of speed while still protecting against traffic analysis.

Going to build and try this out

**Comment by vasild** [comment]
An testing/experimental Bitcoin Core node is running (most of the time) at `[fcc7:be49:ccd1:dc91:3125:f0da:457d:8ce]:8333`.

File: src/netaddress.cpp [hunk 1]
```diff
@@ -674,7 +674,7 @@ bool CNetAddr::GetInAddr(struct in_addr* pipv4Addr) const
  */
 bool CNetAddr::GetIn6Addr(struct in6_addr* pipv6Addr) const
```
Comment (naumenkogs) [inline src/netaddress.cpp:675]: In commit 7b4005008bce3b2d77a4a40db7db7f6626170f87, do you want to keep this function name and parameter?

File: src/init.cpp [hunk 2]
```diff
@@ -1258,6 +1259,14 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
         }
     }
 
+    if (!args.IsArgSet("-cjdnsreachable")) {
+        SetReachable(NET_CJDNS, false);
+    }
+    // Now IsReachable(NET_CJDNS) is true if:
```
Comment (naumenkogs) [inline src/init.cpp:1265]: In commit 3064e8b1474f955c2506711c57dfbf3b7af48686, how about the regular -reachable flag? What's the interaction here?

File: src/net.cpp [hunk 3]
```diff
@@ -229,9 +229,27 @@ std::optional<CAddress> GetLocalAddrForPeer(CNode *pnode)
...
+    CService ret{service};
+    if (ret.m_net == NET_IPV6 && ret.m_addr[0] == 0xfc && IsReachable(NET_CJDNS)) {
+        ret.m_net = NET_CJDNS;
+    }
+    return ret;
+}
+
 // learn a new local address
-bool AddLocal(const CService& addr, int nScore)
+bool AddLocal(const CService& addr_, int nScore)
```
Comment (naumenkogs) [inline src/net.cpp:249]: In commit ec2dc3915a8cb645afceb0a5a80b539a77e77a4b, 

Not sure I like this addr_ approach.
Don't you think a caller should be aware of the transition to CJDNS?

**Comment by naumenkogs** [comment]
ACK baae5be7122056cd78fd66cd2ee4b6bd54cb8620 modulo questions above.
I expect it to be implemented very similarly to Tor/I2P which are already manually tested, so it seems we aren't missing anything.

I haven't run the code.

File: src/netaddress.cpp (hunk 1 above)
Comment (vasild) [reply src/netaddress.cpp:675]: The function semantics remain unchanged - it is still used to "get `struct in6_addr`", so I think it is ok to leave it as is.

File: src/init.cpp (hunk 2 above)
Comment (vasild) [reply src/init.cpp:1265]: By "regular -reachable flag" you mean `-onlynet=cjdns`? The interaction is that we can connect to CJDNS if `-cjdnsreachable` is given and CJDNS is not restricted by `-onlynet=`:
```cpp
    // 1. -cjdnsreachable is given and
    // 2.1. -onlynet is not given or
    // 2.2. -onlynet=cjdns is given
```

File: src/net.cpp (hunk 3 above)
Comment (vasild) [reply src/net.cpp:249]: I think the callers of `AddLocal()` do not care that a passed `fc...` address may be interpreted as CJDNS instead of IPv6.

Actually, I started by doing the flip just before `AddLocal()` is called, but ended up with duplicated code all over the place in all callers of `AddLocal()` which prompted me to move that snippet inside `AddLocal()`.

Ideally a CJDNS object should be returned by `LookupIntern()` which is the function which creates the `CNetAddr` objects, so they will not be created as IPv6 and later flipped to CJDNS. However `LookupIntern()` and `WrappedGetAddrInfo()` (which it uses) are defined in `netbase.cpp` and `IsReachable()` (needed to tell whether IPv6 or CJDNS should be created) is in `net.cpp` which would create a circular dependency. Hmm... maybe I should move `IsReachable()` to `netbase.cpp`?

File: src/init.cpp (hunk 2 above)
Comment (naumenkogs) [reply src/init.cpp:1265]: Dismiss this comment, I was very confused.

File: src/net.cpp (hunk 3 above)
Comment (naumenkogs) [reply src/net.cpp:249]: >Actually, I started by doing the flip just before AddLocal() is called, but ended up with duplicated code all over the place in all callers of AddLocal() which prompted me to move that snippet inside AddLocal().

I think this is a good move, i was just wondering whether it's ok to do it quietly.
Imagine logging something like "finished processing IPv6 addr" after calling AddLocal, while it's not actually IPv6. 

I think since this is not really the case now, making a comment along AddrLocal might be sufficient to prevent the confusion.

>Hmm... maybe I should move IsReachable() to netbase.cpp?

Perhaps attempt that in a separate PR then?

**Comment by luke-jr** [comment]
How about simply requiring a "`%cjdns`" suffix on CJDNS addresses?

**Comment by vasild** [comment]
> How about simply requiring a "`%cjdns`" suffix on CJDNS addresses?

Internally the addresses are already distinguished in the `CNetAddr` class by having `m_net` set to either `NET_IPV6` or `NET_CJDNS`.

For representation purposes:
* On output: yes, we can print CJDNS ones with `%cjdns` suffix
* On input: we can recognize e.g. `fc00::123` as reserved-IPv6 and `fc00::123%cjdns` as CJDNS, however that would not remove the need to have the config flag `-cjdnsreachable` because if we stumble on `fc00::123%cjdns` we need to know whether we can connect to it or not (e.g. whether the OS is configured to connect to the CJDNS network). I think the existence of a config flag `-cjdnsreachable` makes it unnecessary to require `%cjdns` suffix. In this sense, having a `%cjdns` suffix would not make it possible to remove any of the bits of this PR. It would be possible, but would add some complexity on top of this PR.

Does that answer the question or did I misunderstand it?

**Comment by laanwj** [comment]
> FWIW, BIP155 does already reserve a network ID for CJDNS (that's not an argument either way of course, but perhaps the BIP's author have opinions on this too). @laanwj?

From what I understood back then is that CJDNS is fairly pervasive in mesh networking. You can peer it over arbitrary networks and physical layers but you'll still have a global address *from the viewpoint of software*.  With no central authority that needs to assign that.

What makes it different to I2P and Tor is that it is not an anonymity network. It encrypts the payload but does not hide where it comes from. This means it can be very lightweight and low-latency. This is good for initial sync and gossip, maybe not so much for transaction broadcasting. But it's not worse than clearnet.

Also unlike those, from the viewpoint of software it's simply another IPv6 interface. This means it requires only little extra code to support (mostly related to gossip and reachability). No need for proxies or special negotiation (as @vasild already mentions above).

**Comment by jonatack** [comment]
Connected to @vasild with his help (thanks!) and the connection has been reliable and fast so far.

Running a bitcoind cjdns service at `[fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333` if anyone wants to connect.

**Comment by dunxen** [comment]
> Connected to @vasild with his help (thanks!) and the connection has been reliable and fast so far.
> 
> 
> 
> Running a bitcoind cjdns service at `[fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333` if anyone wants to connect.

Ah, I did try to connect to Vasil a few days ago and had trouble. Was there something specific you had to resolve before you could? I'll try again tomorrow when I can.

**Comment by jonatack** [comment]
> > Connected to @vasild with his help (thanks!) and the connection has been reliable and fast so far.
> > Running a bitcoind cjdns service at `[fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa]:8333` if anyone wants to connect.
> 
> Ah, I did try to connect to Vasil a few days ago and had trouble. Was there something specific you had to resolve before you could? I'll try again tomorrow when I can.

Nice! For Debian I followed the instructions starting from https://github.com/cjdelisle/cjdns#1-retrieve-cjdns-from-github. My rookie mistake was skipping over section 2 (https://github.com/cjdelisle/cjdns#2-find-a-friend) and going straight to the sections after that, and so I wasn't connected to the network. @vasild diagnosed and solved this by suggesting a peer to add to `connectTo` in the `cjdroute.conf` file. See also the IRC discussion starting from https://www.erisian.com.au/bitcoin-core-dev/log-2021-10-04.html#l-417 up to line 652 yesterday, and maybe particularly line 469.

**Comment by jonatack** [comment]
@dunxen Yay, you're connected in my inbound cjdns peers :ice_cream: 
```
        ipv4    ipv6   onion     i2p   cjdns   total   block  manual
in         0       0       8       5       1      14
out        6       0       5       6       1      18       2       8
total      6       0      13      11       2      32
```

**Comment by dunxen** [comment]
> See also the IRC discussion starting from https://www.erisian.com.au/bitcoin-core-dev/log-2021-10-04.html#l-417 up to line 652 yesterday, and maybe particularly line 469.

`[fcf2:d9e:3a25:4eef:8f84:251b:1b4d:c596]:8333` for me.

I actually did have two public peers in `connectTo` but they might have been offline when I tried so probably couldn't connect to the network. So I added around 5 more by following those instructions to find ones that were up :)

**Comment by jamesob** [comment]
Concept ACK; will review this week.

**Comment by vasild** [comment]
> ... did have two public peers in connectTo but they might have been offline when I tried ...

[tools/peerStats](https://github.com/cjdelisle/cjdns/blob/7fca8223dc4eac8483d9d0f317cded1e0d2492a8/tools/peerStats) helps to see to which nodes you are connected.

Added the known CJDNS addresses at the bottom of th PR description.

**Review by jonatack — COMMENTED** [review]
ACK baae5be7122056cd78fd66cd2ee4b6bd54cb8620 rebased to current master, debug built with clang 13 on debian, git cloned and built cjdns per https://github.com/cjdelisle/cjdns#1-retrieve-cjdns-from-github, and have been running with `-cjdnsreachable` and currently 2 CJDNS peers (1 in, 1 out) with IP/TorV3/I2P open too

```
$ ./src/bitcoin-cli -netinfo 

        ipv4    ipv6   onion     i2p   cjdns   total   block  manual
in         0       0       9       4       1      14
out        6       0       6       5       1      18       2       8
total      6       0      15       9       2      32

Local addresses
abcd:abc:123:abcd:1234:abcd:1234:abcd                              port   8333    score      1
abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd.onion     port   8333    score      4
abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd.b32.i2p       port      0    score      4
fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa                            port   8333    score      1
```

Things I would like to test further:
- launching bitcoind with the new config option passed but cjdns not up seemed to cause bitcoind to hang or take some time to respond again; only tried once so far
- onlynet=cjdns / onlynet=cjdns onlynet=tor onlynet=i2p

File: contrib/seeds/generate-seeds.py [hunk 4]
```diff
@@ -77,7 +77,14 @@ def name_to_bip155(addr):
                 sub[x].append(val & 0xff)
         nullbytes = 16 - len(sub[0]) - len(sub[1])
         assert((x == 0 and nullbytes == 0) or (x == 1 and nullbytes > 0))
-        return (BIP155Network.IPV6, bytes(sub[0] + ([0] * nullbytes) + sub[1]))
+        addr_bytes = bytes(sub[0] + ([0] * nullbytes) + sub[1])
+        if addr_bytes[0] == 0xfc:
+            # Assume that seeds with fc00::/8 addresses belong to CJDNS,
+            # not to the publicly unroutable "Unique Local Unicast" network
```
[the remark this answers is not in the document]
Comment (jonatack) [reply contrib/seeds/generate-seeds.py:83]: FWIW the CJDNS peers appear to be providing addresses as logged by `CAddrMan:Add()`:
```
$ grep "addresses from fc" ~/.bitcoin/debug.log
...
2021-10-05T14:33:26Z [msghand] Added 1 addresses from fcf2:d9e:3a25:4eef:8f84:251b:1b4d:c596: 3007 tried, 64742 new
2021-10-05T14:46:00Z [msghand] Added 308 addresses from fcc7:be49:ccd1:dc91:3125:f0da:457d:8ce: 3007 tried, 64742 new
```

**Comment by vasild** [comment]
`baae5be712...a36b806169`: rebase and address suggestions

Invalidates ACKs by @naumenkogs, @jonatack

File: src/netbase.cpp [hunk 5]
```diff
@@ -120,7 +123,7 @@ std::vector<std::string> GetNetworkNames(bool append_unroutable)
     std::vector<std::string> names;
     for (int n = 0; n < NET_MAX; ++n) {
         const enum Network network{static_cast<Network>(n)};
-        if (network == NET_UNROUTABLE || network == NET_CJDNS || network == NET_INTERNAL) continue;
+        if (network == NET_UNROUTABLE || network == NET_INTERNAL) continue;
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/netbase.cpp:126]: Done.

File: src/net.cpp [hunk 6]
```diff
@@ -229,9 +229,27 @@ std::optional<CAddress> GetLocalAddrForPeer(CNode *pnode)
...
 }
 
+/**
+ * If an IPv6 address belongs to the address range used by the CJDNS network and
+ * the CJDNS network is reachable (-cjdnsreachable config is set), then change
+ * the type from NET_IPV6 to NET_CJDNS.
+ * @param[in] service Address to convert.
+ * @return either `addr` or `addr` with modified network.
+ */
+CService MaybeFlipIPv6toCJDNS(const CService& service)
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/net.cpp:240]: Took the doc suggestions. Left the comment in `net.cpp`. This should really be `static` function in `net.cpp` (in which case the comment belongs to `net.cpp`). The only reason it is not is that we need to make it a friend of `CService` (in `netaddress.h`). It is not a public/exported function for everybody to use and as such does not have a declaration in `net.h`.

**Comment by vasild** [comment]
> Should the cjdns tests in `feature_proxy.py` be behind the `self.have_ipv6` conditional?

That's only required if the Socks5 proxy has IPv6 address (`::1`). For CJDNS tests, `self.serv1` is used which listens at `127.0.0.1`.

**Review by jamesob — APPROVED** [review]
ACK a36b806169f1706053800fcecaab9b678258f39e ([`jamesob/ackr/23077.1.vasild.full_cjdns_support`](https://github.com/jamesob/bitcoin/tree/ackr/23077.1.vasild.full_cjdns_support))

Looks like I code-reviewed an older version of this branch, but I verified that the range-diff is empty (`git range-diff master..96083eb8c8 master..HEAD`).

I booted a cjdroute instance (`fcb3:dc50:e1ae:7998:7dc0:7fa6:4582:8e46`) and started bitcoind with `./src/bitcoind -cjdnsreachable -onlynet=cjdns -debug=net`. I had to manually `bitcoin-cli addnode ...` a few of the IPs listed in the PR description to get P2P traffic going, but once I did that I was getting the usual P2P chatter. Verified the reception of a new block and a bunch of txn data.

I don't seem to be connecting to other cjdns-network nodes automatically (seems I need to `addnode` them each manually), but I'm not sure if that's part of the expected feature set here, though I thought it was.

In any case, the complexity of this change is low since it's essentially just stamping out diffs along the lines of I2P and Tor. Maintenance burden seems negligible and the changes all look pretty well tested. Thanks, @vasild!


<details><summary>Show signature data</summary>
<p>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK a36b806169f1706053800fcecaab9b678258f39e ([`jamesob/ackr/23077.1.vasild.full_cjdns_support`](https://github.com/jamesob/bitcoin/tree/ackr/23077.1.vasild.full_cjdns_support))

Looks like I code-reviewed an older version of this branch, but I verified that the range-diff is empty (`git range-diff master..96083eb8c8 master..HEAD`).

I booted a cjdnsroute instance (`fcb3:dc50:e1ae:7998:7dc0:7fa6:4582:8e46`) and started bitcoind with `./src/bitcoind -cjdnsreachable -onlynet=cjdns -debug=net`. I had to manually `bitcoin-cli addnode ...` a few of the IPs listed in the PR description to get P2P traffic going, but once I did that I was getting the usual P2P chatter. Verified the reception of a new block and a bunch of txn data.

I don't seem to be connecting to other cjdns-network nodes automatically (seems I need to `addnode` them each manually), but I'm not sure if that's part of the expected feature set here, though I thought it was.

In any case, the complexity of this change is low since it's essentially just stamping out diffs along the lines of I2P and Tor. Maintenance burden seems negligible and the changes all look pretty well tested. Thanks, @vasild!

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEGNRVI1NPYuZCSIrGepNdrbLETwUFAmFg0KYACgkQepNdrbLE
TwVL7hAAoT5irn5aFYl3Wl8vi6bT8T+/JK+vTCB2KBR37ZxaM1IlpSyRYwXPm8+3
atpfPT1X9erw8Xoin4i9a1qKQu6HLnEE89vgB9/FZ6dnsagd8rGvl7cCoYoY/RzL
oj7Md1TeyQTZG4bGiO4fSHD0E9AGMFZkRhHiV7uh0qiHlrOUO1Brusfod1pL1iUO
ufYj8Ap9JRNdU0ysQEPZysgV8SZ33bPWbb7mmUTpiP6puA8DqPM2mRyk5pS1N2cP
C2p+QTAF5GOlevXrPJ2yO0UwfcuYj1PYZ6zNsjwYIzjzNfedOZY9OPjox8K3Lx5p
J5tG7iF3ScvWmMiMFMi+X7kDqzxd5DYR5LlTfsKAdsE7hWgb5ypYj9fcbRjlL6e5
jN2fkihRi1kvXRmeM6u09WILuKlx/wl8KW74fQVoRU2gN3Frt9tMthSCdVbKK7KB
/fxm2kmIzgt2XKyxodRn8YnZ6s5CqTHPuYHFjyBvgR/rHwjA9hJA1FXx1zJYYF06
P/MrfWLdSCwIcGwkE9hWjypdWfxAOMjFec+2w4ArSb0Hh55mt9UiF/sff5nKEF7r
od84EdHvS70OQogAcRtF/E+LMHH8eg0fV31WSdxkeMhL7LA51UlzXALsQrT2saoN
hhhsabaAlVxA//yOZMSoetowIu4MxYxvRwxacN9BHmJpFXk+3gE=
=ZzwN
-----END PGP SIGNATURE-----

```

</p></details>

<details><summary>Show platform data</summary>
<p>

```
Tested on Linux-4.19.0-10-amd64-x86_64-with-glibc2.28

Configured with ./configure LDFLAGS=-L/home/james/src/bitcoin/db4/lib/ CPPFLAGS=-I/home/james/src/bitcoin/db4/include/ CXXFLAGS=-fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare -Wsign-compare -Werror=thread-safety-analysis --enable-wallet --enable-debug --with-daemon --enable-natpmp-default

Compiled with /usr/bin/ccache /usr/bin/clang++ -std=c++17 -mavx -mavx2 -fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare -Wsign-compare -Werror=thread-safety-analysis -O0 -g3 -ftrapv -fdebug-prefix-map=$(abs_srcdir)=.  -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -msse4 -msha -msse4.1 -msse4.2  i

Compiler version: Debian clang version 12.0.1-++20210905123925+fed41342a82f-1~exp1~20210904224639.138
```

</p></details>

**Comment by cjdelisle** [comment]
I created a fake seed node with the two nodes I found from here which are working: `btc-fake.cjdns.fr`

```diff
diff --git a/src/chainparams.cpp b/src/chainparams.cpp
index b15574579..4ce0edc7d 100644
--- a/src/chainparams.cpp
+++ b/src/chainparams.cpp
@@ -127,6 +127,7 @@ public:
         vSeeds.emplace_back("seed.bitcoin.sprovoost.nl"); // Sjors Provoost
         vSeeds.emplace_back("dnsseed.emzy.de"); // Stephan Oeste
         vSeeds.emplace_back("seed.bitcoin.wiz.biz"); // Jason Maurice
+        vSeeds.emplace_back("btc-fake.cjdns.fr"); // cjd's fake cjdns-only seed for testing                                                                                                                 
         base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1,0);
         base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1,5);                                                                                                                                   
```

I'm also running `[fc68:7026:cb27:b014:5910:e609:dcdb:22a2]:8333` but it is running with `-cjdnsreachable -onlynet=cjdns` so it is still syncing (headers). But I can confirm the seeding seems to work.

**Comment by dunxen** [comment]
Tested ACK 4fbff39

Been running this for some time now without any issues.

**Comment by jonatack** [comment]
ACK 4fbff39e8fb0c110025b2c0ee6eb933b6d16182a have been testing this off and on since October 4, for this review verified change is rebase-only since my last review, then rebased to latest master, debug build clean, started bitcoind with ip/onion/i2p/cjdns running, connected manually to vasild's and cjdelisle's bitcoind cjdns services and seeing nominal operation

**Comment by jonatack** [comment]
Rebased this PR just now on latest master and seeing what might be a merge conflict (at first glance possibly from #22766 but haven't looked further):
```
init.cpp:425:184: error: no member named 'ALLOW_BOOL' in 'ArgsManager'; did you mean 'ALLOW_ANY'?
    argsman.AddArg("-cjdnsreachable", "If set then this host is configured for CJDNS (connecting to fc00::/8 addresses would lead us to the CJDNS network) (default: 0)", ArgsManager::ALLOW_BOOL, OptionsCategory::CONNECTION);
                                                                                                                                                                          ~~~~~~~~~~~~~^~~~~~~~~~
                                                                                                                                                                                       ALLOW_ANY
./util/system.h:166:9: note: 'ALLOW_ANY' declared here
        ALLOW_ANY = 0x01,         //!< disable validation
        ^
1 error generated.
```

**Comment by vasild** [comment]
`4fbff39e8f...420695c193`: rebase due to a silent merge conflict with #22766

Thanks, @jonatack!

Invalidates ACKs from @naumenkogs, @dunxen, @jonatack 

Previously invalidated ACK from @jamesob

**Comment by dunxen** [comment]
ACK 420695c

**Comment by jonatack** [comment]
re-ACK 420695c1933e2b9c6e594fcd8885f1c261e435cf per `git range-diff 23ae793 4fbff39 420695c`

**Comment by laanwj** [comment]
Code review ACK 420695c1933e2b9c6e594fcd8885f1c261e435cf
