### PR TITLE
refactor: Fix clang compile failure

### PR DESCRIPTION
**Pull request by maflcko**
Fix

```
script/standard.cpp:278:22: error: default initialization of an object of const type 'const (anonymous namespace)::CScriptVisitor' without a user-provided default constructor
const CScriptVisitor g_script_visitor;
                     ^
                                     {}
1 error generated.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
<!--

https://en.cppreference.com/w/cpp/io/ios_base/failure

**Comment by MarcoFalke** [comment]
Broken in 5f72ddb7ee4cc177de31f43c69390ee72687222a cc @promag

**Comment by sipa** [comment]
utACK code change. I don't understand what the clang version bump accomplishes.

**Comment by MarcoFalke** [comment]
We use C++11 features such as https://en.cppreference.com/w/cpp/io/ios_base/failure, which is not part of clang-3.7, so Bitcoin Core can only be compiled with clang-3.8 (or higher).

**Comment by sipa** [comment]
Strange. https://clang.llvm.org/cxx_status.html says clang 3.3 implement all of C++11.

**Comment by MarcoFalke** [comment]
Hmm

No supported versions of Bitcoin Core can be compiled with clang-3.7 (see compile log below) and we haven't had any bug reports, so I doubt there is a user or even an operating system running on clang-3.7 today.


<details><summary>compile log</summary>

```
git log -1 && make V=1
commit 58ba7c314d552cea8cb024960a8504577aee586f
Author: Wladimir J. van der Laan <laanwj@protonmail.com>
Date:   Wed Mar 4 13:13:02 2020 +0100

    build: Bump version for 0.19.1 final
    
    Tree-SHA512: c0a5fbc072b03e36ffb9af23e699c6b3a897fcd509fdc3c6741ecc8e510aea5d87851c5a7926909746d03d390af10cae266189160b4a7b303f8be9418ea6a0c0
Making all in src
make[1]: Entering directory '/bitcoin/src'
make[2]: Entering directory '/bitcoin/src'
make[3]: Entering directory '/bitcoin'
make[3]: Leaving directory '/bitcoin'
/bin/bash ../libtool  --tag=CXX --preserve-dup-deps  --mode=link /usr/bin/ccache clang++-3.7 -std=c++11  -Wstack-protector -fstack-protector-all -Wall -Wextra -Wformat -Wvla -Wswitch -Wformat-security -Wthread-safety-analysis -Wrange-loop-analysis -Wredundant-decls -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -Wno-implicit-fallthrough    -fPIE -g -O2  -pthread  -Wl,-z,relro -Wl,-z,now -pie      -o bitcoind bitcoind-bitcoind.o  libbitcoin_server.a  libbitcoin_server.a libbitcoin_common.a univalue/libunivalue.la libbitcoin_util.a  libbitcoin_consensus.a crypto/libbitcoin_crypto_base.a crypto/libbitcoin_crypto_sse41.a crypto/libbitcoin_crypto_avx2.a crypto/libbitcoin_crypto_shani.a leveldb/libleveldb.a leveldb/libleveldb_sse42.a leveldb/libmemenv.a secp256k1/libsecp256k1.la -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem -lboost_thread -lpthread -lboost_chrono  -lcrypto  -levent_pthreads -levent -levent  
libtool: link: /usr/bin/ccache clang++-3.7 -std=c++11 -Wstack-protector -fstack-protector-all -Wall -Wextra -Wformat -Wvla -Wswitch -Wformat-security -Wthread-safety-analysis -Wrange-loop-analysis -Wredundant-decls -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -Wno-implicit-fallthrough -fPIE -g -O2 -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o bitcoind bitcoind-bitcoind.o  libbitcoin_server.a libbitcoin_server.a libbitcoin_common.a univalue/.libs/libunivalue.a libbitcoin_util.a libbitcoin_consensus.a crypto/libbitcoin_crypto_base.a crypto/libbitcoin_crypto_sse41.a crypto/libbitcoin_crypto_avx2.a crypto/libbitcoin_crypto_shani.a leveldb/libleveldb.a leveldb/libleveldb_sse42.a leveldb/libmemenv.a secp256k1/.libs/libsecp256k1.a -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem -lboost_thread -lpthread -lboost_chrono -lcrypto -levent_pthreads -levent -levent -pthread
libbitcoin_server.a(libbitcoin_server_a-dbwrapper.o): In function `unsigned long ReadCompactSize<CDataStream>(CDataStream&)':
/bitcoin/src/./serialize.h:313: undefined reference to `std::ios_base::failure::failure(char const*, std::error_code const&)'
/bitcoin/src/./serialize.h:316: undefined reference to `std::ios_base::failure::failure(char const*, std::error_code const&)'
/bitcoin/src/./serialize.h:307: undefined reference to `std::ios_base::failure::failure(char const*, std::error_code const&)'
/bitcoin/src/./serialize.h:301: undefined reference to `std::ios_base::failure::failure(char const*, std::error_code const&)'
libbitcoin_server.a(libbitcoin_server_a-dbwrapper.o): In function `CDataStream::read(char*, unsigned long)':
/bitcoin/src/./streams.h:406: undefined reference to `std::ios_base::failure::failure(char const*, std::error_code const&)'
libbitcoin_server.a(libbitcoin_server_a-net_processing.o):/bitcoin/src/./serialize.h:510: more undefined references to `std::ios_base::failure::failure(char const*, std::error_code const&)' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:4817: recipe for target 'bitcoind' failed
make[2]: *** [bitcoind] Error 1
make[2]: Leaving directory '/bitcoin/src'
Makefile:13231: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/bitcoin/src'
Makefile:775: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```

</details>

**Comment by sipa** [comment]
@MarcoFalke No objection to bumping this if it reflects reality - 3.7 is certainly quite old (though GCC 4.8 is older).

However, I don't understand what's happening here. The `std::ios_base::failure(const std::string&)` constructor has been used in the codebase since 2009: https://github.com/bitcoin/bitcoin/blob/v0.1.5/serialize.h#L289. Could it be an ABI incompatibility issue?

**Comment by MarcoFalke** [comment]
Reverted doc change for now. I might take another look some time later.

**Comment by ajtowns** [comment]
Looks to me like this is https://bugs.llvm.org/show_bug.cgi?id=23529 (see also https://bugs.llvm.org/show_bug.cgi?id=24844) which seems to be that clang prior to 3.9 doesn't work with libstdc++ from gcc version 5 or later? Fix seems to have been backported to 3.8 in debian, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797038 if I'm following correctly.

**Comment by MarcoFalke** [comment]
Thanks. I'll deal with the clang-3.7 bug in a different pull. Let's focus here on fixing the compile failure with clang-3.8

**Comment by MarcoFalke** [comment]
Anything left to do here?

File: src/script/standard.cpp [hunk 1]
```diff
@@ -274,14 +274,11 @@ class CScriptVisitor : public boost::static_visitor<CScript>
...
 };
-
-const CScriptVisitor g_script_visitor;
-
 } // namespace
 
 CScript GetScriptForDestination(const CTxDestination& dest)
 {
-    return boost::apply_visitor(::g_script_visitor, dest);
+    return boost::apply_visitor(CScriptVisitor{}, dest);
```
Comment (laanwj) [inline src/script/standard.cpp:281]: I think this is an improvement in any case. No value in using a global here, the only case where a setup like this would make sense is when there is an expensive pre-computation.

Comment (MarcoFalke) [reply src/script/standard.cpp:281]: This is also restoring the way it has always been before commit 5f72ddb

**Comment by laanwj** [comment]
ACK fa3b35a189c4a4fd9667ef0af1c7059471ac8b01
