### PR TITLE
Fix rounding privacy leak introduced in #9260

### PR DESCRIPTION
**Pull request by TheBlueMatt**
#9260 accidentally changed behavior of the fee filter rounder - from DEFAULT_MIN_RELAY_TX_FEE to -minrelaytxfee. While technically a violation of our dont-hardcode-values policy, its probably better to use the default here to preserve privacy (which was the original purpose of the rounder, AFAIU).

### CODE REVIEW

**Comment by fanquake** [comment]
Travis failure:
```
../../src/net_processing.cpp:2999:54: error: request for member ‘round’ in ‘filterRounder’, which is of non-class type ‘FeeFilterRounder(CFeeRate)’
                 CAmount filterToSend = filterRounder.round(currentFilter);
```

**Comment by btcdrak** [comment]
utACK 9b9324e

**Comment by gmaxwell** [comment]
Seems sensible to me.

**Review by dcousens — APPROVED** [review]

**Comment by dcousens** [comment]
Tested ACK 9b9324e, fixes a bitcoind deadlock for me

**Comment by morcos** [comment]
utACK

**Comment by MarcoFalke** [comment]
utACK 9b9324e

**Comment by sipa** [comment]
utACK 9b9324ee49e3e9cd401cedb8cdfce9a4b7c040de
