### PR TITLE
validation: Separate check-only version of ConnectBlock

### PR DESCRIPTION
**Pull request by optout21**
This is a small code-hygiene refactor to `ConnectBlock` method.

Problem:  In the "check-only" mode of `ConnectBlock` the mutability of the `CBlockIndex` parameter is inconsistent with the semantics. In the default operation, `ConnectBlock` changes the provided `CBlockIndex`. However, it has a special "check-only" mode, where the provided chain is not changed. This mode is used from only one call site (`TestBlockValidity`), and is signaled by the `fJustCheck = true` flag.

Solution:  Provide two versions of `ConnectBlock`: one with mutable chain and one "check-only" with const chain. There is no need for the `fJustCheck` flag. Both reuse the same internal implementation.

Benefits:
- The mutability of the `pindex` parameter is in sync with the semantics
- One less feature flag (`fJustCheck`)
- Calling "check-only" mode is smoother, creating a dummy mutable `CBlockIndex` is now unnecessary

Additional details:
- This has been triggered by #35187, there is also a new usage of "check-only" `ConnectBlock`, with dummy `CBlockIndex`.
- The "check-only" mode was introduced as early as 3cd01fdf0e540c4e06cd27b6c0d6b6abc00767d1 .
- No behavior change (pure refactor).
- Some internal variables (`blockundo`,  `nInputs`, `nSigOpsCost`) are now outputs of the internal method, and used in the default outer method (`ConnectBlock`).
- `SetBestBlock` has been moved to the outer `ConnectBlock`. It was also present in the special genesis block early return, this is preserved.
- The tracepoints are in the outer methods
- Timing is present both in the inner method (logs) and the outer methods (logs, tracepoint)

### CODE REVIEW

File: src/validation.cpp [hunk 1]
```diff
@@ -2670,7 +2689,7 @@ bool Chainstate::ConnectBlock(const CBlock& block, BlockValidationState& state,
              Ticks<MillisecondsDouble>(m_chainman.time_index) / m_chainman.num_blocks_total);
 
     TRACEPOINT(validation, block_connected,
-        block_hash.data(),
+        block.GetHash().data(),
```
Comment (l0rinc) [inline src/validation.cpp:2692]: `ConnectBlockChecks()` already hashes the block and verifies that it matches `pindex`.
Could we use the stored index hash here instead?

```suggestion
        pindex->GetBlockHash().data(),
```

File: src/validation.cpp [hunk 2]
```diff
@@ -4547,8 +4577,8 @@ BlockValidationState TestBlockValidity(
     index_dummy.phashBlock = &block_hash;
     CCoinsViewCache view_dummy(&chainstate.CoinsTip());
 
-    // Set fJustCheck to true in order to update, and not clear, validation caches.
-    if(!chainstate.ConnectBlock(block, state, &index_dummy, view_dummy, /*fJustCheck=*/true)) {
+    // Call TestConnectBlock(), it updates, and does not clear, validation caches.
+    if (!chainstate.TestConnectBlock(block, state, &index_dummy, view_dummy)) {
```
Comment (l0rinc) [inline src/validation.cpp:4581]: `TestConnectBlock`  is never called with a possibly-nullptr block index, consider a const reference instead:

<details><summary>pass block index by reference
</summary>

```patch
diff --git a/src/validation.cpp b/src/validation.cpp
index a4b86f18a9..83bd02944c 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -2700,7 +2700,7 @@ bool Chainstate::ConnectBlock(const CBlock& block, BlockValidationState& state,
     return true;
 }
 
-bool Chainstate::TestConnectBlock(const CBlock& block, BlockValidationState& state, const CBlockIndex* pindex,
+bool Chainstate::TestConnectBlock(const CBlock& block, BlockValidationState& state, const CBlockIndex& index,
                                    CCoinsViewCache& view)
 {
     AssertLockHeld(cs_main);
@@ -2708,7 +2708,7 @@ bool Chainstate::TestConnectBlock(const CBlock& block, BlockValidationState& sta
     CBlockUndo blockundo;
     int nInputs = 0;
     int64_t nSigOpsCost = 0;
-    return ConnectBlockChecks(block, state, pindex, view, /*fJustCheck=*/true, blockundo, nInputs, nSigOpsCost);
+    return ConnectBlockChecks(block, state, &index, view, /*fJustCheck=*/true, blockundo, nInputs, nSigOpsCost);
 }
 
 CoinsCacheSizeState Chainstate::GetCoinsCacheSizeState()
@@ -4578,7 +4578,7 @@ BlockValidationState TestBlockValidity(
     CCoinsViewCache view_dummy(&chainstate.CoinsTip());
 
     // Call TestConnectBlock(), it updates, and does not clear, validation caches.
-    if (!chainstate.TestConnectBlock(block, state, &index_dummy, view_dummy)) {
+    if (!chainstate.TestConnectBlock(block, state, index_dummy, view_dummy)) {
         if (state.IsValid()) NONFATAL_UNREACHABLE();
         return state;
     }
diff --git a/src/validation.h b/src/validation.h
index dfc87331e8..1d2c773296 100644
--- a/src/validation.h
+++ b/src/validation.h
@@ -784,8 +784,8 @@ public:
     //! Connect a block to the chain, updating pindex and the block undo/index files on disk.
     bool ConnectBlock(const CBlock& block, BlockValidationState& state, CBlockIndex* pindex,
         CCoinsViewCache& view) EXCLUSIVE_LOCKS_REQUIRED(cs_main);
-    //! Run the same validity checks as ConnectBlock() without mutating pindex or writing anything to disk.
-    bool TestConnectBlock(const CBlock& block, BlockValidationState& state, const CBlockIndex* pindex,
+    //! Run the same validity checks as ConnectBlock() without mutating the block index or writing anything to disk.
+    bool TestConnectBlock(const CBlock& block, BlockValidationState& state, const CBlockIndex& index,
         CCoinsViewCache& view) EXCLUSIVE_LOCKS_REQUIRED(cs_main);
 
     // Apply the effects of a block disconnection on the UTXO set.
```
</details>

File: src/validation.h [hunk 3]
```diff
@@ -781,8 +781,12 @@ class Chainstate
     // Block (dis)connection on a given view:
     DisconnectResult DisconnectBlock(const CBlock& block, const CBlockIndex* pindex, CCoinsViewCache& view)
         EXCLUSIVE_LOCKS_REQUIRED(::cs_main);
+    //! Connect a block to the chain, updating pindex and the block undo/index files on disk.
     bool ConnectBlock(const CBlock& block, BlockValidationState& state, CBlockIndex* pindex,
-                      CCoinsViewCache& view, bool fJustCheck = false) EXCLUSIVE_LOCKS_REQUIRED(cs_main);
+        CCoinsViewCache& view) EXCLUSIVE_LOCKS_REQUIRED(cs_main);
+    //! Run the same validity checks as ConnectBlock() without mutating pindex or writing anything to disk.
```
Comment (l0rinc) [inline src/validation.h:787]: Some of the related comments could be updated now.

<details><summary>update check-only block comments</summary>

```patch
diff --git a/src/validation.cpp b/src/validation.cpp
index 611fc16805..3c0dd35729 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -4568,7 +4568,7 @@ BlockValidationState TestBlockValidity(
         return state;
     }
 
-    // We don't want ConnectBlock to update the actual chainstate, so create
+    // We don't want TestConnectBlock to update the actual chainstate, so create
     // a cache on top of it, along with a dummy block index.
     CBlockIndex index_dummy{block};
     uint256 block_hash(block.GetHash());
diff --git a/test/functional/interface_usdt_utxocache.py b/test/functional/interface_usdt_utxocache.py
index da90790d70..37cc205541 100755
--- a/test/functional/interface_usdt_utxocache.py
+++ b/test/functional/interface_usdt_utxocache.py
@@ -241,7 +241,7 @@ class UTXOCacheTracepointTest(BitcoinTestFramework):
         # of the UTXO set (see CoinsTip() of CCoinsViewCache). However, in some cases
         # temporary clones of the active cache are made. For example, during mining with
         # the generate RPC call, the block is first tested in TestBlockValidity(). There,
-        # a clone of the active cache is modified during a test ConnectBlock() call.
+        # a clone of the active cache is modified during a TestConnectBlock() call.
         # These are implementation details we don't want to test here. Thus, after
         # mining, we invalidate the block, start the tracing, and then trace the cache
         # changes to the active utxo cache.
```
</details>

**Comment by purpleKarrot** [comment]
What about the mutability and mutations of the `Chainstate` (the implicit `this` argument)?
With the proposed change, calling `TestConnectBlock` still has the side effect of mutating `num_blocks_total`, for example.

Please have a look at https://github.com/bitcoin/bitcoin/issues/35904, which proposes extracting the block validation parts from `ConnectBlock` into a function that has no side effects.

**Comment by optout21** [comment]
Thanks for the feedback, @purpleKarrot ! I will check out #35904 (I've seen 35906, but not 35904).
I'm also continuing exploring, currently looking at these small issues:
- in check-only mode, block undo data is computed unnecessarily (a small optimization potential).
- in check-only mode, the coins view that is being updated can be created inside (by `TestConnectBlock`), so the caller does not need to create a dummy. Also, the CBlockIndex supplied can be simplified (not to require a CBlockIndex that already contains the new block).

**Review by l0rinc — CHANGES_REQUESTED** [review]
Concept ACK

Separating the check-only entry point makes the `CBlockIndex` mutability clearer and removes `fJustCheck` from the public `ConnectBlock()` interface.
I've split this locally (consider splitting the change similarly, see https://github.com/bitcoin/bitcoin/compare/master...l0rinc:bitcoin:l0rinc/validation-test-connect-block):
* add and route through `TestConnectBlock()`
* expose the connection outputs
* handle failed checks and genesis in `ConnectBlock()`
* move the ordered undo/index/tracepoint updates
* then make the check-only index const.

My pending comments cover reusing the stored index hash, passing the index by const reference, and updating the related comments. The broader `Chainstate` side effects are already being discussed above.

> proposes extracting the block validation parts from ConnectBlock into a function that has no side effects

+1 for these functional-style refactors (though, as mentioned, exceptions are the opposite of that), but given how consensus-critical this code is, I’d prefer moving toward side-effect-free validation through tiny, trivial-to-review changes, with this PR limited to making the `CBlockIndex` mutability explicit (and split into smaller changes that are all obviously correct).

**Comment by optout21** [comment]
@purpleKarrot, to revisit your comment:
I agree that the right approach would be to rework `ConnectBlock` to take whatever data it needs, and produce update data as output, without side effects. The update data then can be applied (in normal connect block use case), or discarded (check only use case). This structure is also more compatible with validation needs where certain parts (e.g. the UTXO set) is supplied differently (see #35187). I see that this change is not trivial (and touching critical code).

I think that the small change from this PR is compatible with the approach laid out in #35904. It is a small step, but it makes the input and update data slightly more explicit.

I've also made an attempt to make `ConnectBlock` static, thus exposing the dependencies even better (https://github.com/optout21/bitcoin/pull/23), but I'm not sure how to progress with that.

For reference, I detail here the updates that happen in `ConnectBlock`:

- The passed `CCoinsView` is updated with the coin changes (spent&new)
- The script execution cache is updated (`ValidationCache` `ChainstateManager.m_validation_cache`)
- `ChainstateManager`'s `num_blocks_total` is incremented
- `ChainstateManager`'s `time_Xxx` fields are incremented (`time_check`, `time_forks`, etc.)
- `Chainstate::m_last_script_check_reason_logged` may be updated
- `BlockManager` is updated with the block undo data (skipped for JustCheck)
- `BlockManager::m_dirty_blockindex` is updated (in case of script failure; skipped for JustCheck)

File: src/validation.cpp (hunk 1 above)
Comment (optout21) [reply src/validation.cpp]: Good point, that's more optimal. I will store the block hash in a local variable, right after `ConnectBlockChecks` call, and use it from there. This way it's more similar how the `ConnectBlockChecks` does it internally.

File: src/validation.cpp (hunk 2 above)
Comment (optout21) [reply src/validation.cpp]: Good point! Applied. (I've overlooked this, even though I have a separate open PR with exactly such changes...)

File: src/validation.h (hunk 3 above)
Comment (optout21) [reply src/validation.h:792]: Taken.

**Review by optout21 — COMMENTED** [review]
Applied review suggestions, minor changes. Thanks for the review, and sorry for the delay.
`git diff 0e832dbd0488bb358b7505de5326e20e068eca9c..36739b5f0caeaeb2ac7e77eae75ff0954b8fcd0b`

**Comment by optout21** [comment]
UPDATE: Was due to silent merge conflict, fixed.

I'm struggling with the CI build errors. Fuzz compile fails for `src/test/fuzz/connect_block.cpp`, however, I can't find that file, by name, or by contents. Locally fuzz compile works with the same commit (36739b5f0caeaeb2ac7e77eae75ff0954b8fcd0b).

```
/home/runner/work/_temp/src/test/fuzz/connect_block.cpp:476:68: error: too many arguments to function call, expected 4, have 5
  472 |     bool connected = active_chainstate.ConnectBlock(block,
```

**Comment by optout21** [comment]
I've noticed an accidental mistake in the newly-touched `test/functional/interface_usdt_utxocache.py` (the first '#' character was dropped), fixed.
I doubt this has anything to do with the CI failures though.

`git diff 36739b5f0caeaeb2ac7e77eae75ff0954b8fcd0b..ddc6be9d37699473658c3da55cb6e4590ac6f0b3`

**Comment by optout21** [comment]
CI failure is due to silent merge conflict with #35850, fixing.

**Comment by optout21** [comment]
Rebased and fixed silent merge error, fuzz compile error due to newly introduced `connect_block.cpp` fuzzer (in #35850, @marcofleon).

`git range-diff ddc6be9d37699473658c3da55cb6e4590ac6f0b3...fe970b7b19ea944fcbc9159345217ee7fbd02238`

File: src/test/fuzz/connect_block.cpp [hunk 4]
```diff
@@ -436,7 +436,7 @@ CBlock ConsumeBlock(FuzzedDataProvider& fuzzed_data_provider, const CBlock& prev
 }
 
 
-FUZZ_TARGET(connect_block, .init = initialize_connect_block)
+FUZZ_TARGET(test_connect_block, .init = initialize_connect_block)
```
Comment (marcofleon) [inline src/test/fuzz/connect_block.cpp:439]: Seems unnecessary to change the target name, no? I would just keep it the same. Our fuzzing infra corpora are keyed by target name, so we'd have to manually deal with renaming.

Comment (optout21) [reply src/test/fuzz/connect_block.cpp:439]: Thanks for the feedback. I've just changed it as it was in sync with the name of the method being tested, and that has changed. But it can stay, no problem. I will revert this rename.
