### ISSUE TITLE
[depends] Qt fails to build on OSX 10.11, Xcode 7.3.1

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#7999]
```
In file included from qcocoacursor.mm:35:
./qcocoawindow.h:223:11: warning: 'devicePixelRatio' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    qreal devicePixelRatio() const;
          ^
../../../../include/QtGui/5.5.0/QtGui/qpa/../../../../../src/gui/kernel/qplatformwindow.h:110:19: note: overridden virtual function is here
    virtual qreal devicePixelRatio() const;
                  ^
qcocoacursor.mm:76:20: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef e = CGEventCreateMouseEvent(0, kCGEventMouseMoved, pos, 0);
                   ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: 
      candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^
26 warnings and 1 error generated.
make[4]: *** [.obj/qcocoacursor.o] Error 1
```

This seems to be fixed in [Qt 5.5.1](https://code.qt.io/cgit/qt/qtbase.git/commit/src/plugins/platforms/cocoa/qcocoacursor.mm?id=02ea0235216beef390e9868ff770c7a54d70db83&h=5.5), but probably isn't worth an intermediate bump to 5.5.1 if we're going to shift to 5.6 soon?

**Comment by theuni** [comment]
Hmm, lots to bump. I was planning on doing a clang bump for the cross build, with an SDK bump to match. That would introduce this problem I suppose, so we'll need to fix this one first.

Just going straight to 5.6.0 probably makes the most sense.

**Comment by jonasschnelli** [comment]
Yes. Lets just go to 5.6.0.
5.6.0 also would give us (better) HiDPI support for Win/Linux.

**Comment by fanquake** [comment]
Fixed since we've upgraded to QT 5.6.1
