### PR TITLE
Bump SCRIPT_VERIFY flags to 64 bit

### PR DESCRIPTION
**Pull request by ajtowns**
We currently use 21 of 32 possible bits for `SCRIPT_VERIFY_*` flags, with open PRs that may use 8 more (#29247, #31989, #32247, #32453). The mutinynet fork that has included many experimental soft fork features is [already reusing bits here](https://github.com/benthecarman/bitcoin/blob/d4a86277ed8a0712e03fbbce290e9209165e049c/src/script/interpreter.h#L175-L195). Therefore, bump this to 64 bits.

In order to make it easier to update this logic in future, this PR also introduces a dedicated type for the script flags, and disables implicit conversion between that type and the underlying integer type. To make verifying that this change doesn't cause flags to disappear, this PR also resurrects the changes from #28806 so that the script flags that are consensus enforced on each block can be queried via getdeploymentinfo.

### CODE REVIEW

**Comment by ajtowns** [comment]
The "introduce script_verify_flags typename" commit is probably best reviewed with `--word-diff` fwiw.

cc @instagibbs @darosior @benthecarman

**Comment by ajtowns** [comment]
CI failure seems to be due to [a bug in qt6 6.4](https://bugreports.qt.io/browse/QTBUG-31496?focusedId=888930&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-888930):

> Also for people coming here from Google: I had the same error message, but for me the problem was that I was using Qt 6.4.2 which apparently thinks that #if 202002L < 201103L is true, which causes c++config.h to not be included (and no #error is generated because moc doesn't support the directive) . This has been fixed somewhere before Qt 6.7.3.


```
[20:04:17.396] Get:287 http://archive.ubuntu.com/ubuntu noble/universe amd64 qt6-base-dev-tools amd64 6.4.2+dfsg-21.1build5 [970 kB]
[20:04:17.414] Get:288 http://archive.ubuntu.com/ubuntu noble/universe amd64 qt6-qpa-plugins amd64 6.4.2+dfsg-21.1build5 [89.3 kB]
[20:04:17.417] Get:289 http://archive.ubuntu.com/ubuntu noble/universe amd64 qt6-base-dev amd64 6.4.2+dfsg-21.1build5 [1458 kB]
...
[20:12:02.187] Command
[20:12:02.187] -------
[20:12:02.187] /usr/lib/qt6/libexec/moc -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_NO_CXX98_FUNCTION_BASE -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -I/ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src -I/ci_container_base/src -I/ci_container_base/src/univalue/include -I/ci_container_base/src/leveldb/include -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtDBus -I/usr/include -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/llvm-20/lib/clang/20/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu --include /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/qt/bitcoinqt_autogen/moc_predefs.h -p/ci_container_base/src/qt --output-dep-file -o /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/qt/bitcoinqt_autogen/include/qt/intro.moc /ci_container_base/src/qt/intro.cpp
[20:12:02.187] 
[20:12:02.187] Output
[20:12:02.187] ------
[20:12:02.187] usr/include/c++/13/concept:46:1: error: Parse error at "std"
```

The error output also seems to be cutting off the last letter of the filename ("concept" vs "concepts" here, and "stl_relops." vs "stl_relops.h" in the original bug report linked above).

**Comment by hebasto** [comment]
> CI failure seems to be due to [a bug in qt6 6.4](https://bugreports.qt.io/browse/QTBUG-31496?focusedId=888930&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-888930):

Although both failed CI job use Clang 20.1.7, the error can also be reproduced with GCC 13.3.

**Comment by instagibbs** [comment]
agreed, build issue also on my end with gcc 13.3.0

**Comment by fanquake** [comment]
Minified this is:
```bash
# podman run -it ubuntu:noble

apt update && apt upgrade -y
apt install g++ qt6-base-dev qt6-tools-dev git

git clone https://github.com/bitcoin/bitcoin
cd bitcoin
git fetch origin pull/32998/head:32998
git checkout 32998

/usr/lib/qt6/libexec/moc -I/usr/include/c++/13 --output-dep-file -o test.moc /bitcoin/src/qt/intro.cpp
usr/include/c++/13/bits/cpp_type_traits.:69:1: error: Parse error at "std"
```

**Comment by hebasto** [comment]
> > CI failure seems to be due to [a bug in qt6 6.4](https://bugreports.qt.io/browse/QTBUG-31496?focusedId=888930&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-888930):
> 
> Although both failed CI job use Clang 20.1.7, the error can also be reproduced with GCC 13.3.

[Refactoring](https://github.com/hebasto/bitcoin/commits/pr32998/0717.refactored/) helps.

File: src/test/script_tests.cpp [hunk 1]
```diff
@@ -1745,4 +1751,13 @@ BOOST_AUTO_TEST_CASE(compute_tapleaf)
     BOOST_CHECK_EQUAL(ComputeTapleafHash(0xc2, std::span(script)), tlc2);
 }
 
+BOOST_AUTO_TEST_CASE(formatscriptflags)
+{
+    // quick check that FormatScriptFlags reports any unknown/unexpected bits
+    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_P2SH), "P2SH");
+    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_P2SH | (1u<<31)), "P2SH,0x80000000");
+    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_TAPROOT | (1u<<27)), "TAPROOT,0x08000000");
```
Comment (instagibbs) [inline src/test/script_tests.cpp]: bit of coverage of multiple unknown bits (didn't validate)
```Suggestion
    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_TAPROOT | (1u<<27)), "TAPROOT,0x08000000");
    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_TAPROOT | (1u<<27) | (1u<<31)), "TAPROOT,0x88000000");
```

File: src/test/script_tests.cpp [hunk 2]
```diff
@@ -1745,4 +1751,13 @@ BOOST_AUTO_TEST_CASE(compute_tapleaf)
     BOOST_CHECK_EQUAL(ComputeTapleafHash(0xc2, std::span(script)), tlc2);
 }
 
+BOOST_AUTO_TEST_CASE(formatscriptflags)
+{
+    // quick check that FormatScriptFlags reports any unknown/unexpected bits
+    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_P2SH), "P2SH");
```
Comment (instagibbs) [inline src/test/script_tests.cpp:1718]:
```Suggestion
    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_P2SH), "P2SH");
    BOOST_CHECK_EQUAL(FormatScriptFlags(SCRIPT_VERIFY_P2SH | SCRIPT_VERIFY_TAPROOT), "P2SH,TAPROOT");
```

**Comment by ajtowns** [comment]
> Minified this is:

I don't think you need the `git fetch; git checkout` here -- you get the same error with that command (dropping the `/bitcoin`) on master afaics?

**Comment by fanquake** [comment]
@hebasto how can we move past the GUI build failures here? https://github.com/bitcoin/bitcoin/actions/runs/16538448423/job/46776353144?pr=32998#step:6:3769.

**Comment by hebasto** [comment]
> @hebasto how can we move past the GUI build failures here? https://github.com/bitcoin/bitcoin/actions/runs/16538448423/job/46776353144?pr=32998#step:6:3769.

Sure!

> > > CI failure seems to be due to [a bug in qt6 6.4](https://bugreports.qt.io/browse/QTBUG-31496?focusedId=888930&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-888930):
> > 
> > 
> > Although both failed CI job use Clang 20.1.7, the error can also be reproduced with GCC 13.3.
> 
> [Refactoring](https://github.com/hebasto/bitcoin/commits/pr32998/0717.refactored/) helps.

Implemented in https://github.com/bitcoin-core/gui/pull/881.

File: src/script/verify_flags.h [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+
+enum class script_verify_flag_name : uint8_t;
+
+class script_verify_flags
+{
+public:
+    using value_type = uint64_t;
+
+    // default constructor is SCRIPT_VERIFY_NONE
+    consteval script_verify_flags() : m_value{0} { }
```
Comment (DrahtBot) [inline src/script/verify_flags.h]:
```
[20:54:44.710] [676/676][43.3s] clang-tidy-20 -p=/ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu -quiet -load=/tidy-build/libbitcoin-tidy.so /ci_container_base/src/qt/walletmodel.cpp
[20:54:44.710] /ci_container_base/src/script/verify_flags.h:20:39: error: member initializer for 'm_value' is redundant [modernize-use-default-member-init,-warnings-as-errors]
[20:54:44.710]    20 |     consteval script_verify_flags() : m_value{0} { }
[20:54:44.710]       |                                       ^~~~~~~~~~

**Comment by darosior** [comment]
Concept ACK.

**Comment by ajtowns** [comment]
Rebased past header conflict with #33116

File: src/test/fuzz/script.cpp [hunk 4]
```diff
@@ -118,8 +118,8 @@ FUZZ_TARGET(script, .init = initialize_script)
             (void)FindAndDelete(script_mut, *other_script);
         }
         const std::vector<std::string> random_string_vector = ConsumeRandomLengthStringVector(fuzzed_data_provider);
-        const uint32_t u32{fuzzed_data_provider.ConsumeIntegral<uint32_t>()};
-        const script_verify_flags flags{u32 | SCRIPT_VERIFY_P2SH};
+        const auto flags_rand{fuzzed_data_provider.ConsumeIntegral<script_verify_flags::value_type>()};
+        const auto flags = script_verify_flags::from_int(flags_rand) | SCRIPT_VERIFY_P2SH;
```
Comment (instagibbs) [inline src/test/fuzz/script.cpp:122]: bddcadee82daf3ed1441820a0ffc4c5ef78f64f1

could be here or elsewhere, but round-simply round-tripping adds some coverage:

```
assert(script_verify_flags::from_int(flags.as_int()) == flags);
```

**Comment by sipa** [comment]
utACK 417437eb01ac014c57aca47f44d7f8d3da351987

**Review by instagibbs — APPROVED** [review]
ACK 417437eb01ac014c57aca47f44d7f8d3da351987

non-blocking suggestions for coverage

File: src/test/script_tests.cpp (hunk 1 above)
Comment (ajtowns) [reply src/test/script_tests.cpp]: Added something like this, though without the "88"

File: src/test/script_tests.cpp (hunk 2 above)
Comment (ajtowns) [reply src/test/script_tests.cpp:1718]: Added

File: src/test/fuzz/script.cpp (hunk 4 above)
Comment (ajtowns) [reply src/test/fuzz/script.cpp:122]: Round-trip assertions in both directions added to fuzz/script_flags.cpp

File: src/script/verify_flags.h [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+
+class script_verify_flags
+{
+public:
+    using value_type = uint64_t;
+
+    consteval script_verify_flags() = default;
+
+    // also allow construction with hard-coded 0 (but not other integers)
+    consteval explicit(false) script_verify_flags(value_type f) : m_value{f} { if (f != 0) throw 0; }
```
Comment (darosior) [inline src/script/verify_flags.h:22]: I was curious why this constructor from `int` with a runtime check was necessary. It's because of all the `if ((flags & SCRIPT_VERIFY_X) != 0)` in the interpreter. This permits to implicitly construct a `script_verify_flags` from the `0` there instead of either having an implicit conversion *to* integer (the very thing this aims to avoid), or touching every single of those checks to make the conversion from the `0` integer explicit.

File: src/script/verify_flags.h [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+
+    // implicit construction from a hard-coded SCRIPT_VERIFY_* constant is also okay
+    constexpr explicit(false) script_verify_flags(script_verify_flag_name f) : m_value{value_type{1} << static_cast<uint8_t>(f)} { }
+
+    // rule of 5
+    constexpr script_verify_flags(const script_verify_flags&) = default;
+    constexpr script_verify_flags(script_verify_flags&&) = default;
+    constexpr script_verify_flags& operator=(const script_verify_flags&) = default;
+    constexpr script_verify_flags& operator=(script_verify_flags&&) = default;
+    constexpr ~script_verify_flags() = default;
```
Comment (darosior) [inline src/script/verify_flags.h:32]: How is the rule of 5 relevant for this class? It does not need a user-defined destructor.

From cppreference's [Rule of 5 section](https://en.cppreference.com/w/cpp/language/rule_of_three.html#Rule_of_five):
> Because the presence of a user-defined (include = default or = delete declared) destructor, copy-constructor, or copy-assignment operator prevents implicit definition of the [move constructor](https://en.cppreference.com/w/cpp/language/move_constructor.html) and the [move assignment operator](https://en.cppreference.com/w/cpp/language/move_operator.html), any class for which move semantics are desirable, has to declare all five special member functions:

**Review by darosior — APPROVED** [review]
ACK 652424ad162b63d73ecb6bd65bd26946e90c617f

I think it would also make sense, in a follow-up, to move the rest of the Script verification flags stuff to the new `verify_flags.h`.

**Comment by instagibbs** [comment]
reACK https://github.com/bitcoin/bitcoin/pull/32998/commits/652424ad162b63d73ecb6bd65bd26946e90c617f

File: src/script/verify_flags.h (hunk 6 above)
Comment (ajtowns) [reply src/script/verify_flags.h:32]: The rule of 5 just says if you define one, define/delete them all; I do it because that ensures I get a compile time error if there's some problem that makes one of them not possible. Move semantics probably aren't very interesting for a wrapper around an int though.

The C++ Core Guidelines version of the ["rule of 0"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-zero) says not to define any of them when possible, however.

File: src/script/verify_flags.h (hunk 5 above)
Comment (ajtowns) [reply src/script/verify_flags.h:22]: Note that it's consteval, so the throw is a compile-time check, not a runtime one.

File: src/test/transaction_tests.cpp [hunk 7]
```diff
@@ -81,9 +60,11 @@ unsigned int ParseScriptFlags(std::string strFlags)
     std::vector<std::string> words = SplitString(strFlags, ',');
     for (const std::string& word : words)
     {
-        if (!mapFlagNames.count(word))
+        if (!mapFlagNames.count(word)) {
```
Comment (theStack) [inline src/test/transaction_tests.cpp:63]: nit: while touching, could switch to the more modern `.contains`
```suggestion
        if (!mapFlagNames.contains(word)) {
```

File: src/script/verify_flags.h [hunk 8]
```diff
@@ -6,8 +6,66 @@
...
+
+    // tests
+    constexpr explicit operator bool() const { return m_value != 0; }
+    constexpr bool operator==(script_verify_flags other) const { return m_value == other.m_value; }
+
+    /** Compare two script_verify_flags. <, >, <=, and >= are auto-generated from this. */
+    friend constexpr std::strong_ordering operator<=>(const script_verify_flags& a, const script_verify_flags& b) noexcept
+    {
+        return a.m_value <=> b.m_value;
+    }
```
Comment (theStack) [inline src/script/verify_flags.h:55]: nit: `operator<` would be sufficient (currently only needed in the transaction tests, where a [`std::set` of script flag combinations](https://github.com/bitcoin/bitcoin/blob/86eaa4d6cd5c428f6635a8d44fa6b5a9545ea909/src/test/transaction_tests.cpp#L183) is used), I doubt that the other ones would ever have a use-case
```diff
diff --git a/src/script/verify_flags.h b/src/script/verify_flags.h
index 95a55d2c79..e14a329ace 100644
--- a/src/script/verify_flags.h
+++ b/src/script/verify_flags.h
@@ -47,11 +47,9 @@ public:
     // tests
     constexpr explicit operator bool() const { return m_value != 0; }
     constexpr bool operator==(script_verify_flags other) const { return m_value == other.m_value; }
-
-    /** Compare two script_verify_flags. <, >, <=, and >= are auto-generated from this. */
-    friend constexpr std::strong_ordering operator<=>(const script_verify_flags& a, const script_verify_flags& b) noexcept
+    friend constexpr bool operator<(const script_verify_flags& a, const script_verify_flags& b) noexcept
     {
-        return a.m_value <=> b.m_value;
+        return a.m_value < b.m_value;
     }

 private:
```

**Review by theStack — APPROVED** [review]
Code-review ACK 652424ad162b63d73ecb6bd65bd26946e90c617f :flags:

**Comment by achow101** [comment]
ACK 652424ad162b63d73ecb6bd65bd26946e90c617f

**Comment by fanquake** [comment]
Note that this caused the MSAN Fuzz job to start failing, so is being fixed / changed again in #33600.
