### PR TITLE
LibreSSL doesn't define OPENSSL_VERSION, use LIBRESSL_VERSION_TEXT instead

### LINKED ISSUE #7447: build options for OpenBSD incomplete/out-of-date
Trying the instructions in build-openbsd.md on OpenBSD 5.7 fails with

    In file included from addrman.h:14:0,
                     from init.cpp:12:
    init.cpp: In function 'bool AppInit2(boost::thread_group&, CScheduler&)':
    init.cpp:1076:61: error: 'OPENSSL_VERSION' was not declared in this scope
         LogPrintf("Using OpenSSL version %s\n", OpenSSL_version(OPENSSL_VERSION));

Apparently, this is due to OpenSSL no longer being present on recent versions of OpenBSD. To fix this, I had to `pkg_add openssl` (which installs the `eopenssl` package, which is a kind of wrapper for libressl afaik) and replace the configure command given in the instructions by

`./configure --with-gui=no --with-boost=$BOOST_PREFIX CC=egcc CXX=eg++ CPP=ecpp LDFLAGS="-L${BDB_PREFIX}/lib/ -L/usr/local/lib/eopenssl/" CPPFLAGS="-I${BDB_PREFIX}/include/ -I/usr/local/include/eopenssl/"`

Perhaps the documentation could be updated to reflect that.

### LINKED ISSUE #7515: recipe for target 'libbitcoin_server_a-init.o' failed
Trying to build on OpenBSD 5.8.
```
# gmake
Making all in src
gmake[1]: Entering directory '/home/bitcoin/bitcoin/src'
gmake[2]: Entering directory '/home/bitcoin/bitcoin/src'
  CXX      crypto/libbitcoinconsensus_la-hmac_sha256.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CXX      libbitcoinconsensus_la-arith_uint256.lo
  CXX      consensus/libbitcoinconsensus_la-merkle.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      primitives/libbitcoinconsensus_la-block.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      script/libbitcoinconsensus_la-script_error.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
gmake[3]: Entering directory '/home/bitcoin/bitcoin/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
gmake[3]: Leaving directory '/home/bitcoin/bitcoin/src/secp256k1'
  CXXLD    libbitcoinconsensus.la

*** Warning: This system can not link to static lib archive secp256k1/libsecp256k1.la.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have.
  CXX      bitcoind-bitcoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
In file included from ui_interface.h:12:0,
                 from httprpc.cpp:16:
/home/bitcoin/bitcoin/boost/include/boost/signals2/last_value.hpp: In member function 'boost::signals2::detail::signal3_impl<R, T1, T2, T3, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::detail::signal3_impl<R, T1, T2, T3, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(T1, T2, T3) [with R = bool; T1 = const std::basic_string<char>&; T2 = const std::basic_string<char>&; T3 = unsigned int; Combiner = boost::signals2::last_value<bool>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<bool(const std::basic_string<char>&, const std::basic_string<char>&, unsigned int)>; ExtendedSlotFunction = boost::function<bool(const boost::signals2::connection&, const std::basic_string<char>&, const std::basic_string<char>&, unsigned int)>; Mutex = boost::signals2::mutex; boost::signals2::detail::signal3_impl<R, T1, T2, T3, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = bool]':
/home/bitcoin/bitcoin/boost/include/boost/signals2/last_value.hpp:51:36: warning: '*((void*)& value +1)' may be used uninitialized in this function [-Wmaybe-uninitialized]
         if(value) return value.get();
                                    ^
/home/bitcoin/bitcoin/boost/include/boost/signals2/last_value.hpp:41:21: note: '*((void*)& value +1)' was declared here
         optional<T> value;
                     ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign"
  CXX      libbitcoin_server_a-httpserver.o
In file included from ui_interface.h:12:0,
                 from httpserver.cpp:13:
/home/bitcoin/bitcoin/boost/include/boost/signals2/last_value.hpp: In member function 'boost::signals2::detail::signal3_impl<R, T1, T2, T3, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::detail::signal3_impl<R, T1, T2, T3, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(T1, T2, T3) [with R = bool; T1 = const std::basic_string<char>&; T2 = const std::basic_string<char>&; T3 = unsigned int; Combiner = boost::signals2::last_value<bool>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<bool(const std::basic_string<char>&, const std::basic_string<char>&, unsigned int)>; ExtendedSlotFunction = boost::function<bool(const boost::signals2::connection&, const std::basic_string<char>&, const std::basic_string<char>&, unsigned int)>; Mutex = boost::signals2::mutex; boost::signals2::detail::signal3_impl<R, T1, T2, T3, Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = bool]':
/home/bitcoin/bitcoin/boost/include/boost/signals2/last_value.hpp:51:36: warning: '*((void*)& value +1)' may be used uninitialized in this function [-Wmaybe-uninitialized]
         if(value) return value.get();
                                    ^
/home/bitcoin/bitcoin/boost/include/boost/signals2/last_value.hpp:41:21: note: '*((void*)& value +1)' was declared here
         optional<T> value;
                     ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign"
  CXX      libbitcoin_server_a-init.o
In file included from addrman.h:14:0,
                 from init.cpp:12:
init.cpp: In function 'bool AppInit2(boost::thread_group&, CScheduler&)':
init.cpp:1095:61: error: 'OPENSSL_VERSION' was not declared in this scope
     LogPrintf("Using OpenSSL version %s\n", OpenSSL_version(OPENSSL_VERSION));
                                                             ^
util.h:77:39: note: in definition of macro 'LogPrintf'
 #define LogPrintf(...) LogPrint(NULL, __VA_ARGS__)
                                       ^
init.cpp:1095:76: error: 'OpenSSL_version' was not declared in this scope
     LogPrintf("Using OpenSSL version %s\n", OpenSSL_version(OPENSSL_VERSION));
                                                                            ^
util.h:77:39: note: in definition of macro 'LogPrintf'
 #define LogPrintf(...) LogPrint(NULL, __VA_ARGS__)
                                       ^
In file included from /home/bitcoin/bitcoin/boost/include/boost/system/system_error.hpp:14:0,
                 from /home/bitcoin/bitcoin/boost/include/boost/thread/exceptions.hpp:22,
                 from /home/bitcoin/bitcoin/boost/include/boost/thread/pthread/thread_data.hpp:10,
                 from /home/bitcoin/bitcoin/boost/include/boost/thread/pthread/condition_variable.hpp:12,
                 from /home/bitcoin/bitcoin/boost/include/boost/thread/condition_variable.hpp:16,
                 from sync.h:11,
                 from addrman.h:12,
                 from init.cpp:12:
/home/bitcoin/bitcoin/boost/include/boost/system/error_code.hpp: At global scope:
/home/bitcoin/bitcoin/boost/include/boost/system/error_code.hpp:221:36: warning: 'boost::system::posix_category' defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
/home/bitcoin/bitcoin/boost/include/boost/system/error_code.hpp:222:36: warning: 'boost::system::errno_ecat' defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
/home/bitcoin/bitcoin/boost/include/boost/system/error_code.hpp:223:36: warning: 'boost::system::native_ecat' defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
cc1plus: warning: unrecognized command line option "-Wno-self-assign"
Makefile:3916: recipe for target 'libbitcoin_server_a-init.o' failed
gmake[2]: *** [libbitcoin_server_a-init.o] Error 1
gmake[2]: Leaving directory '/home/bitcoin/bitcoin/src'
Makefile:7057: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory '/home/bitcoin/bitcoin/src'
Makefile:666: recipe for target 'all-recursive' failed
gmake: *** [all-recursive] Error 1
```

### PR DESCRIPTION
**Pull request by paveljanik**
OpenBSD is using LibreSSL by default instead of openssl. The build ends with

```
CXX      libbitcoin_server_a-init.o
In file included from addrman.h:14:0,
                 from init.cpp:12:
init.cpp: In function 'bool AppInit2(boost::thread_group&, CScheduler&)':
init.cpp:1095:61: error: 'OPENSSL_VERSION' was not declared in this scope
     LogPrintf("Using OpenSSL version %s\n", OpenSSL_version(OPENSSL_VERSION));
                                                             ^
```

This change adds LIBRESSL_VERSION_TEXT macrocheck and adds conditionals before these macros. If none is defined, nothing is printed at all.

Fixes #7515.
Fixes #7447.

### CODE REVIEW

**Comment by luke-jr** [comment]
utACK a0a17b3e441ac82bc64ca183d458258ded26c9ed

**Comment by laanwj** [comment]
utACK
