### PR TITLE
serialization: Support for multiple parameters

### PR DESCRIPTION
**Pull request by ryanofsky**
Currently it is only possible to attach one serialization parameter to a stream at a time. For example, it is not possible to set a parameter controlling the transaction format and a parameter controlling the address format at the same time because one parameter will override the other.

This limitation is inconvenient for multiprocess code since it is not possible to create just one type of stream and serialize any object to it. Instead it is necessary to create different streams for different object types, which requires extra boilerplate and makes using the new parameter fields a lot more awkward than the older version and type fields.

Fix this problem by allowing an unlimited number of serialization stream parameters to be set, and allowing them to be requested by type. Later parameters will still override earlier parameters, but only if they have the same type.

For an example of different ways multiple parameters can be set, see the new [`with_params_multi`](https://github.com/bitcoin/bitcoin/blob/40f505583f4edeb2859aeb70da20c6374d331a4f/src/test/serialize_tests.cpp#L394-L410) unit test.

This change requires replacing the `stream.GetParams()` method with a `stream.GetParams<T>()` method in order for serialization code to retrieve the desired parameters. The change is more verbose, but probably a good thing for readability because previously it could be difficult to know what type the `GetParams()` method would return, and now it is more obvious.

---

This PR is part of the [process separation project](https://github.com/bitcoin/bitcoin/issues/28722).

### CODE REVIEW

File: src/primitives/transaction.h [hunk 1]
```diff
@@ -332,7 +332,7 @@ class CTransaction
     template <typename Stream>
     CTransaction(deserialize_type, const TransactionSerParams& params, Stream& s) : CTransaction(CMutableTransaction(deserialize, params, s)) {}
     template <typename Stream>
-    CTransaction(deserialize_type, ParamsStream<TransactionSerParams,Stream>& s) : CTransaction(CMutableTransaction(deserialize, s)) {}
+    CTransaction(deserialize_type, Stream& s) : CTransaction(CMutableTransaction(deserialize, s)) {}
```
Comment (ajtowns) [inline src/primitives/transaction.h:335]: This is more generalising, than dropping...

File: src/protocol.h [hunk 2]
```diff
@@ -406,9 +406,10 @@ class CAddress : public CService
     static constexpr SerParams V1_DISK{{CNetAddr::Encoding::V1}, Format::Disk};
     static constexpr SerParams V2_DISK{{CNetAddr::Encoding::V2}, Format::Disk};
 
-    SERIALIZE_METHODS_PARAMS(CAddress, obj, SerParams, params)
+    SERIALIZE_METHODS(CAddress, obj)
     {
         bool use_v2;
+        auto& params = SER_PARAMS(SerParams);
```
Comment (ajtowns) [inline src/protocol.h:412]: Dropping `SERIALIZE_METHODS_PARAMS` doesn't seem like an improvement?

I would have expected something more like:

```c++
// this pr: #define SER_PARAMS(type) (s.template GetParams<type>())
// instead:
template<typename T, typename Stream>
const auto& GetSerParams(const Stream& s)
{
    return s.template GetParams<T>();
}

// FORMATTER_METHODS_PARAMS has the same signature, but now uses the new GetSerParams<>()
#define FORMATTER_METHODS_PARAMS(cls, obj, paramcls, paramobj) \
    template<typename Stream> \
    static void Ser(Stream& s, const cls& obj) { SerializationOps(obj, s, GetSerParams<paramcls>(s), ActionSerialize{}); } \
    template<typename Stream> \
    static void Unser(Stream& s, cls& obj) { SerializationOps(obj, s, GetSerParams<paramcls>(s), ActionUnserialize{}); } \
    template<typename Stream, typename Type, typename Operation> \
    static void SerializationOps(Type& obj, Stream& s, const paramcls& paramobj, Operation ser_action)

// protocol.h
// this pr:
//  SERIALIZE_METHODS(CAddress, obj) {
//      auto& params = SER_PARAMS(SerParams);
// instead:
    SERIALIZE_METHODS_PARAMS(CAddress, obj, SerParams, params) {


// netaddress.h:
// original:
//      if (s.GetParams().enc == Encoding::V2) {
// this pr:
//      if (s.template GetParams<SerParams>().enc == Encoding::V2) {
// instead:
        if (GetSerParams<SerParams>(s).enc == Encoding::V2) { ... }
```

**Review by ajtowns — COMMENTED** [review]
Concept ACK

**Comment by dergoegge** [comment]
Concept ACK

**Review by ryanofsky — COMMENTED** [review]
Updated 334f75acfdfd8c8737f0fc5da41d25ec8e6ab588 -> 97338eec9e35401f42c376062ea161a22143d628 ([`pr/iparams.1`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.1) -> [`pr/iparams.2`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.2), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.1..pr/iparams.2)) adding comments and improving test

**Comment by ryanofsky** [comment]
Rebased 97338eec9e35401f42c376062ea161a22143d628 -> ffc1e9fd8cf53cfcf4d7926ca2963958eacf73d7 ([`pr/iparams.2`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.2) -> [`pr/iparams.3`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.3), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.2-rebase..pr/iparams.3)) due to minor conflict with #28451

**Comment by ryanofsky** [comment]
Updated ffc1e9fd8cf53cfcf4d7926ca2963958eacf73d7 -> 3c311734d2fc6a4ca410f254ba3c8e923d58be70 ([`pr/iparams.3`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.3) -> [`pr/iparams.4`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.4), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.3..pr/iparams.4)) to fix unused variable in test https://cirrus-ci.com/task/4527517751574528?logs=ci#L2260

re: https://github.com/bitcoin/bitcoin/pull/28929#issuecomment-1888552974

> ```
> test/serialize_tests.cpp:394:11: error: unused variable 'oi2' [-Werror,-Wunused-variable]
> ```

Fixed, thanks. Also renamed variables in the test to make it more readable

**Review by maflcko — COMMENTED** [review]
did not review the last commit 3c311734d2fc6a4ca410f254ba3c8e923d58be70 🚔

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: did not review the last commit 3c311734d2fc6a4ca410f254ba3c8e923d58be70 🚔
HgBPRyZaqsA6IWO/nWpFwiv5/omKRQ3fZmFGkrNfInSb0WBx0SgqbIdQPEkb2NkO/KoxscmLPJRXjk2Ia3ixCA==
```

</details>

File: src/serialize.h [hunk 3]
```diff
@@ -1108,10 +1108,15 @@ template <typename SubStream, typename Params>
 class ParamsStream
 {
     const Params& m_params;
-    SubStream& m_substream; // private to avoid leaking version/type into serialization code that shouldn't see it
+    SubStream m_substream; // private to avoid leaking version/type into serialization code that shouldn't see it
 
 public:
-    ParamsStream(SubStream& substream LIFETIMEBOUND, const Params& params LIFETIMEBOUND) : m_params{params}, m_substream{substream} {}
+    ParamsStream(SubStream substream LIFETIMEBOUND, const Params& params LIFETIMEBOUND) : m_params{params}, m_substream{substream} {}
```
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/serialize.h:1114]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1484199895

> [3c31173](https://github.com/bitcoin/bitcoin/commit/3c311734d2fc6a4ca410f254ba3c8e923d58be70):
> 
> I don't understand this. For example, if `SubStream` is a `DataStream` that holds data, this will now create a copy of this data, when previously it didn't?

I will add a comment here, but this does not happen due to the "Template deduction guide for a single params argument that's slightly different from the default generated deduction guide because it stores a reference to the substream inside `ParamsStream` instead of a copy" on line 1147 below.

With this change, a caller constructing the `ParamsStream` is in control and can decide whether  `ParamsStream` should hold a value or a reference by specifying `DataStream` if they want a value, or `DataSteam&` if they want a reference.

The default behavior for a single parameter is unchanged, and will use a reference. But if there are multiple parameters, the inner `ParamsStream` instances are stored by value so we have a single tuple-like object containing all the parameters, not multiple `ParamsStream` objects with unpredictable lifetimes referencing each other.
 
> It seems odd that the stream has to be passed down the whole "type-stack" anyway. Maybe it is simpler to just create a stack of params only to hold the types?

I don't think it's odd. Ultimately the `ParamsStream` wrapper methods (`read`, `write`, `size`) etc need to call the corresponding methods need to call the corresponding methods on the wrapped streams so types of all the streams need to be known.

> One could consider to completely disallow wrapping streams into each other, see also https://www.github.com/bitcoin/bitcoin/pull/25284/commits/faec591d64e40ba7ec7656cbfdda1a05953bde13#r1315927911

That would be a problem because "wrapping a `ParamsStream` in a `ParamsStream`" is a useful thing to do, and shouldn't be forbidden. It's the most straightforward way to support multiple parameters because each `ParamStream` can hold one parameter, and `ParamsStream::GetParams` can return its own parameter if requested, or call the wrapped `GetParams` method otherwise.

[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/serialize.h]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1484436443

> Yes, an example would be in net.cpp, but feel free to ignore, if it is too much hassle.
> 
> ```c++
> src/net.cpp-    DataStream underlying_stream{vSeedsIn};
> src/net.cpp:    ParamsStream s{underlying_stream, CAddress::V2_NETWORK};
> ```

Since it didn't complicate implementation of this PR too much, I implemented support for passing any type of substream as an rvalue to ParamsStream, instead of only passing nested ParamStreams to by value, and I added a test for this. The change didn't complicate implementation of this PR too much, it just required changing & to && and adding std::forward a few places.

Unfortunately, however, I could not find a way to simplify `net.cpp` without triggering a compiler warning:

```diff
--- a/src/net.cpp
+++ b/src/net.cpp
@@ -198,8 +198,7 @@ static std::vector<CAddress> ConvertSeeds(const std::vector<uint8_t> &vSeedsIn)
     const auto one_week{7 * 24h};
     std::vector<CAddress> vSeedsOut;
     FastRandomContext rng;
-    DataStream underlying_stream{vSeedsIn};
-    ParamsStream s{underlying_stream, CAddress::V2_NETWORK};
+    ParamsStream s{DataStream{vSeedsIn}, CAddress::V2_NETWORK};
     while (!s.eof()) {
         CService endpoint;
         s >> endpoint;

```

This change *should* work, but unfortunately it triggers a clang [`-Wdangling` ](https://clang.llvm.org/docs/DiagnosticsReference.html#wdangling) warning, which I believe is spurious:

```c++
net.cpp:201:20: error: temporary whose address is used as value of local variable 's' will be destroyed at the end of the full-expression [-Werror,-Wdangling]
  201 |     ParamsStream s{DataStream{vSeedsIn}, CAddress::V2_NETWORK};
      |                   
```

The warning doesn't make sense and I think it is a compiler bug. It happens for me with clang 17.0.6.

**Review by ryanofsky — COMMENTED** [review]
Updated 3c311734d2fc6a4ca410f254ba3c8e923d58be70 -> e02ab1577f51a6c9af96b49e29ffaa3918ddae6c ([`pr/iparams.4`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.4) -> [`pr/iparams.5`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.5), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.4..pr/iparams.5)) using && and std::forward to support rvalue substream arguments and adding tests and documentation

File: src/serialize.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/serialize.h]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1496589417

> The warning doesn't make sense and I think it is a compiler bug.

Actually it is not a compiler bug. It happens because of the lifetimebound annotation and goes away if I change:

```diff
-    ParamsStream(SubStream&& substream LIFETIMEBOUND, const Params& params LIFETIMEBOUND) : m_params{params}, m_substream{std::forward<SubStream>(substream)} {}
+    ParamsStream(SubStream&& substream, const Params& params LIFETIMEBOUND) : m_params{params}, m_substream{std::forward<SubStream>(substream)} {}
```

But that change is potentially less safe, because we really do want the [lifetimebound](https://clang.llvm.org/docs/AttributeReference.html#lifetimebound) attribute to be specified if Substream is an lvalue reference, just not in other cases. I'm not sure if there is an attribute syntax which would support doing that.

[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/serialize.h]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1496625389

This should be resolved in latest push, which just drops the LIFETIMEBOUND annotation since it isn't always accurate. The only case where specifying the annotation is actually correct is the case where the argument is an lvalue. And in that case, I think the annotation is probably not useful. The language already doesn't allow passing temporaries as rvalues so there is probably not anything the compiler can helpfully warn about in that case.

**Review by ryanofsky — COMMENTED** [review]
Updated e02ab1577f51a6c9af96b49e29ffaa3918ddae6c -> 33d99bad01637a3454358841b5c1aaf099002afb ([`pr/iparams.5`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.5) -> [`pr/iparams.6`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.6), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.5..pr/iparams.6)) adding a new commit simplifying usage of ParamsStream in net.cpp, and fixing inaccurate lifetimebound annotations

**Review by maflcko — APPROVED** [review]
left some comments/nits. Feel free to ignore.

very nice. lgtm ACK 33d99bad01 👆

<details><summary>Show signature</summary>

Signature:

```
untrusted comment: signature from minisign secret key on empty file; verify via: minisign -Vm "${path_to_any_empty_file}" -P RWTRmVTMeKV5noAMqVlsMugDDCyyTSbA3Re5AkUrhvLVln0tSaFWglOw -x "${path_to_this_whole_four_line_signature_blob}"
RUTRmVTMeKV5npGrKx1nqXCw5zeVHdtdYURB/KlyA/LMFgpNCs+SkW9a8N95d+U4AP1RJMi+krxU1A3Yux4bpwZNLvVBKy0wLgM=
trusted comment: very nice. lgtm ACK 33d99bad01 👆
vYXG8JolRRudeR/EvljO02nNhTpLVh7ae9EjSBP82mgGSRDkUFhYYlnx9S2EOpzD0z1dE4QHOEHx7YYNx8ksAQ==
```

</details>

File: src/serialize.h [hunk 4]
```diff
@@ -1103,22 +1103,36 @@ size_t GetSerializeSize(const T& t)
     return (SizeComputer() << t).size();
 }
 
-/** Wrapper that overrides the GetParams() function of a stream (and hides GetVersion/GetType). */
-template <typename SubStream, typename Params>
+/** Wrapper that overrides the GetParams() function of a stream. */
```
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/serialize.h:1106]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1497210553

> [af7f90d](https://github.com/bitcoin/bitcoin/commit/af7f90da74b935c17d986b0f4d21e4bce6f56343): Thanks for removing it, but I think it can be a separate (trivial) 4 line diff commit?

Sure, moved to separate commit

**Review by ryanofsky — COMMENTED** [review]
Updated 33d99bad01637a3454358841b5c1aaf099002afb -> 9dc839a7fd1c8c7648f9e0a025d5ebecee8d289a ([`pr/iparams.6`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.6) -> [`pr/iparams.7`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.7), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.6..pr/iparams.7)) applying various suggestions and splitting commits

File: src/serialize.h [hunk 5]
```diff
@@ -1103,22 +1103,36 @@ size_t GetSerializeSize(const T& t)
...
+template <typename SubStream, typename Params, bool nested = false>
```
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/serialize.h]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1497303755

> I wonder if the `nested` bool could somehow be derived with a C++20 concept

Nice suggestion, implemented this

**Review by ryanofsky — COMMENTED** [review]
Updated 9dc839a7fd1c8c7648f9e0a025d5ebecee8d289a -> 40f505583f4edeb2859aeb70da20c6374d331a4f ([`pr/iparams.7`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.7) -> [`pr/iparams.8`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.8), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.7..pr/iparams.8)) using concept to replace `bool nested` as suggested

File: src/serialize.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/serialize.h]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1497272449

> I think you meant to say "lvalues"? Also, const lvalues should be fine by the language. For example, the following should cause a use-after-free:

Thanks that was supposed to say lvalues, and that's a good point, so it's possible lifetimebound could still help avoid bugs in some cases. I think it should be possible to add back lifetimebound by overloading the constructor using `std::is_reference`. But it would add a little complexity, so I think it makes sense to omit it for now, and maybe add it later if it looks like there are cases where a const stream would be used.

File: src/serialize.h [hunk 6]
```diff
@@ -1118,27 +1103,85 @@ size_t GetSerializeSize(const T& t)
...
+    //! Get reference to underlying stream.
+    auto& GetStream()
+    {
+        if constexpr (ContainsStream<SubStream>) {
+            return m_substream.GetStream();
+        } else {
+            return m_substream;
+        }
+    }
+    auto& GetStream() const
```
Comment (cbergqvist) [inline src/serialize.h:1159]: If `m_substream` is an owned instance, it will become `const SubStream` in const member functions, and the return value here will be `const Substream&`.
However, if `m_substream` is a reference/pointer, the constness is applied to the reference part, so the method will return a mutable reference.
See https://stackoverflow.com/questions/5055427/returning-non-const-reference-from-a-const-member-function

My suggestion would be to return `const auto&` here unless the intent is to enable mutability (which only happens when the member is a reference).

#### Illustrative example
```C++
class A
{
    int& b;
public:
    A(int& n) : b(n) {}
    auto& foo() const { return b; }
};

    ....
    int bar = 123;
    const A a(bar);
    int& mutating = a.foo();
    mutating = 2;
```

**Review by ryanofsky — COMMENTED** [review]
Updated 40f505583f4edeb2859aeb70da20c6374d331a4f -> 8d491ae9ecf1948ea29f67b50ca7259123f602aa ([`pr/iparams.8`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.8) -> [`pr/iparams.9`](https://github.com/ryanofsky/bitcoin/commits/pr/iparams.9), [compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.8..pr/iparams.9)) just adding `const` as suggested

**Comment by ryanofsky** [comment]
@theuni any chance you'd be interested in reviewing this? (There are 7 commits so this looks looks like a bigger change, but all the complexity is basically in the first commit, the other commits are small or obvious changes.)

File: src/serialize.h [hunk 7]
```diff
@@ -1142,6 +1146,24 @@ class ParamsStream
             return m_substream.template GetParams<P>();
         }
     }
+
+    //! Get reference to underlying stream.
+    auto& GetStream()
```
Comment (TheCharlatan) [inline src/serialize.h:1151]: Are you going to be using this method for other purposes besides tests and as an internal getter?

File: src/serialize.h [hunk 8]
```diff
@@ -1142,6 +1146,24 @@ class ParamsStream
...
+    {
+        if constexpr (ContainsStream<SubStream>) {
+            return m_substream.GetStream();
```
Comment (TheCharlatan) [inline src/serialize.h:1154]: Just a comment: This does indeed not trigger clang-tidy's recursion check (I'm guessing because of the constexpr condition).

**Review by sedited — APPROVED** [review]
Nice, reviewing this was fun.
ACK 8d491ae9ecf1948ea29f67b50ca7259123f602aa

File: src/serialize.h (hunk 7 above)
Comment (ryanofsky) [reply src/serialize.h:1151]: re: https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1600617406

> Are you going to be using this method for other purposes besides tests and as an internal getter?

I could see some other uses. Initially this was just added for testing, but then marco pointed out it could be used as an internal getter in https://github.com/bitcoin/bitcoin/pull/28929#discussion_r1497229478 to avoid recursion in read, write, size, etc methods. The other case it might be useful is if you have have a custom stream type like a file or socket and want to call some method on that stream that ParamsStream() is not wrapping, without having to pass around separate pointers to both streams.

**Review by ryanofsky — COMMENTED** [review]
Thanks for the review!

**Comment by ryanofsky** [comment]
@sipa, could you re-ack? Only change since your last review was adding a missing `const` ([compare](https://github.com/ryanofsky/bitcoin/compare/pr/iparams.8..pr/iparams.9))

**Comment by theuni** [comment]
@ryanofsky Sorry for not getting to this before merge. Will give it a look tomorrow.
