### ISSUE TITLE
Bitcoin Core (0.11.0) does not build on OpenBSD 5.7

### ISSUE THREAD

**Issue by wolololo** [bitcoin/bitcoin#6491]
Why is bitcoind always such a PoS to compile...

Making all in src
  CXX    crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX    crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX    crypto/libbitcoinconsensus_la-sha1.lo
  CXX    crypto/libbitcoinconsensus_la-sha256.lo
  CXX    crypto/libbitcoinconsensus_la-sha512.lo
  CXX    libbitcoinconsensus_la-eccryptoverify.lo
  CXX    libbitcoinconsensus_la-ecwrapper.lo
  CXX    libbitcoinconsensus_la-hash.lo
  CXX    primitives/libbitcoinconsensus_la-transaction.lo
  CXX    libbitcoinconsensus_la-pubkey.lo
  CXX    script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX    script/libbitcoinconsensus_la-interpreter.lo
script/interpreter.cpp: In function 'bool CheckMinimalPush(const valtype&, opcodetype)':
script/interpreter.cpp:227: warning: comparison between signed and unsigned integer expressions
  CXX    script/libbitcoinconsensus_la-script.lo
  CXX    libbitcoinconsensus_la-uint256.lo
  CXX    libbitcoinconsensus_la-utilstrencodings.lo
  CXXLD  libbitcoinconsensus.la
  CXX    bitcoind-bitcoind.o
In file included from main.h:14,
                 from bitcoind.cpp:9:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-addrman.o
  CXX    libbitcoin_server_a-alert.o
  CXX    libbitcoin_server_a-bloom.o
  CXX    libbitcoin_server_a-chain.o
In file included from chain.cpp:6:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-checkpoints.o
In file included from main.h:14,
                 from checkpoints.cpp:8:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-init.o
In file included from main.h:14,
                 from init.cpp:18:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
init.cpp: In function 'bool AppInit2(boost::thread_group&, CScheduler&)':
init.cpp:797: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-leveldbwrapper.o
  CXX    libbitcoin_server_a-main.o
In file included from main.h:14,
                 from main.cpp:6:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-merkleblock.o
  CXX    libbitcoin_server_a-miner.o
In file included from main.h:14,
                 from miner.cpp:13:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-net.o
  CXX    libbitcoin_server_a-noui.o
  CXX    policy/libbitcoin_server_a-fees.o
  CXX    libbitcoin_server_a-pow.o
In file included from pow.cpp:9:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-rest.o
In file included from main.h:14,
                 from rest.cpp:8:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
rest.cpp: In function 'bool rest_getutxos(AcceptedConnection*, const std::string&, const std::string&, const std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&, bool)':
rest.cpp:430: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-rpcblockchain.o
In file included from main.h:14,
                 from rpcblockchain.cpp:8:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-rpcmining.o
In file included from main.h:14,
                 from rpcmining.cpp:12:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-rpcmisc.o
In file included from main.h:14,
                 from rpcmisc.cpp:9:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
In member function 'bool CBlockIndex::IsValid(BlockStatus) const  CXX    libbitcoin_server_a-rpcnet.o
In file included from main.h:14,
                 from rpcnet.cpp:8:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-rpcrawtransaction.o
In file included from main.h:14,
                 from rpcrawtransaction.cpp:11:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-rpcserver.o
  CXX    script/libbitcoin_server_a-sigcache.o
  CXX    libbitcoin_server_a-timedata.o
  CXX    libbitcoin_server_a-txdb.o
In file included from main.h:14,
                 from txdb.cpp:10:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-txmempool.o
In file included from main.h:14,
                 from txmempool.cpp:11:
chain.h: In member function 'bool CBlockIndex::IsValid(BlockStatus) const':
chain.h:260: warning: comparison between signed and unsigned integer expressions
chain.h: In member function 'bool CBlockIndex::RaiseValidity(BlockStatus)':
chain.h:270: warning: comparison between signed and unsigned integer expressions
txmempool.cpp: In member function 'void CTxMemPool::removeCoinbaseSpends(const CCoinsViewCache*, unsigned int)':
txmempool.cpp:169: warning: comparison between signed and unsigned integer expressions
  CXX    libbitcoin_server_a-validationinterface.o
  AR     libbitcoin_server.a
  CXX    libbitcoin_common_a-amount.o
  CXX    libbitcoin_common_a-arith_uint256.o
  CXX    libbitcoin_common_a-base58.o
  CXX    libbitcoin_common_a-chainparams.o
chainparams.cpp: In constructor 'CMainParams::CMainParams()':
chainparams.cpp:127: error: too many initializers for 'Checkpoints::CCheckpointData'
chainparams.cpp: In constructor 'CTestNetParams::CTestNetParams()':
chainparams.cpp:186: error: too many initializers for 'Checkpoints::CCheckpointData'
chainparams.cpp: In constructor 'CRegTestParams::CRegTestParams()':
chainparams.cpp:233: error: too many initializers for 'Checkpoints::CCheckpointData'
/usr/local/include/boost/assign/list_of.hpp: In member function 'Container boost::assign_detail::converter<DerivedTAssign, Iterator>::convert(const Container*, boost::assign_detail::default_type_tag) const [with Container = Checkpoints::CCheckpointData, DerivedTAssign = boost::assign_detail::generic_list<std::pair<int, uint256> >, Iterator = std::_Deque_iterator<std::pair<int, uint256>, std::pair<int, uint256>&, std::pair<int, uint256>*>]':
/usr/local/include/boost/assign/list_of.hpp:142:   instantiated from 'Container boost::assign_detail::converter<DerivedTAssign, Iterator>::convert_to_container() const [with Container = Checkpoints::CCheckpointData, DerivedTAssign = boost::assign_detail::generic_list<std::pair<int, uint256> >, Iterator = std::_Deque_iterator<std::pair<int, uint256>, std::pair<int, uint256>&, std::pair<int, uint256>*>]'
/usr/local/include/boost/assign/list_of.hpp:436:   instantiated from 'boost::assign_detail::generic_list<T>::operator Container() const [with Container = Checkpoints::CCheckpointData, T = std::pair<int, uint256>]'
chainparams.cpp:127:   instantiated from here
/usr/local/include/boost/assign/list_of.hpp:163: error: no matching function for call to 'Checkpoints::CCheckpointData::CCheckpointData(std::_Deque_iterator<std::pair<int, uint256>, std::pair<int, uint256>&, std::pair<int, uint256>*>, std::_Deque_iterator<std::pair<int, uint256>, std::pair<int, uint256>&, std::pair<int, uint256>*>)'
checkpoints.h:22: note: candidates are: Checkpoints::CCheckpointData::CCheckpointData()
checkpoints.h:22: note:                 Checkpoints::CCheckpointData::CCheckpointData(const Checkpoints::CCheckpointData&)
/usr/local/include/boost/system/error_code.hpp: At global scope:
/usr/local/include/boost/system/error_code.hpp:214: warning: 'boost::system::posix_category' defined but not used
/usr/local/include/boost/system/error_code.hpp:215: warning: 'boost::system::errno_ecat' defined but not used
/usr/local/include/boost/system/error_code.hpp:216: warning: 'boost::system::native_ecat' defined but not used
*** Error 1 in src (Makefile:3054 'libbitcoin_common_a-chainparams.o': @echo "  CXX   " libbitcoin_common_a-chainparams.o;g++ -DHAVE_CONFIG_...)
*** Error 1 in src (Makefile:6287 'all-recursive')
*** Error 1 in /home/bitcoin-0.11.0 (Makefile:549 'all-recursive')

**Comment by wolololo** [comment]
I tested previous version and 0.10.2 works well.

**Comment by Lokutos** [comment]
Same on debian 7 

root@is05 /usr/local/src/bitcoin # make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /usr/local/src/bitcoin/build-aux/missing --run aclocal-1.11 -I build-aux/m4
 cd . && /bin/bash /usr/local/src/bitcoin/build-aux/missing --run automake-1.11 --foreign
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /usr/local/src/bitcoin/build-aux/missing --run autoconf
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --with-cli --without-gui --with-incompatible-bdb --disable-shared --with-pic --with-bignum=no --disable-shared --with-pic --no-create --no-recursion
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for g++... g++
checking whether we are using the GNU Objective C++ compiler... no
checking whether g++ accepts -g... no
checking how to print strings... printf
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for strip... /usr/bin/strip
checking for gcov... /usr/bin/gcov
checking for lcov... no
checking for java... no
checking for genhtml... no
checking for git... /usr/bin/git
checking for ccache... no
checking for xgettext... no
checking for hexdump... /usr/bin/hexdump
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether byte ordering is bigendian... no
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... yes
checking whether the linker accepts -Wl,--large-address-aware... no
checking for __attribute__((visibility))... yes
checking for __attribute__((dllexport))... no
checking for __attribute__((dllimport))... no
checking whether C++ compiler accepts -Wstack-protector... yes
checking whether C++ compiler accepts -fstack-protector-all... yes
checking whether C++ preprocessor accepts -D_FORTIFY_SOURCE=2... yes
checking whether C++ preprocessor accepts -U_FORTIFY_SOURCE... yes
checking whether the linker accepts -Wl,--dynamicbase... no
checking whether the linker accepts -Wl,--nxcompat... no
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking whether C++ compiler accepts -fPIE... yes
checking whether the linker accepts -pie... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for strings.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking for library containing getaddrinfo_a... -lanl
checking for library containing inet_pton... none required
checking whether strnlen is declared... yes
checking whether le16toh is declared... yes
checking whether le32toh is declared... yes
checking whether le64toh is declared... yes
checking whether htole16 is declared... yes
checking whether htole32 is declared... yes
checking whether htole64 is declared... yes
checking whether be16toh is declared... yes
checking whether be32toh is declared... yes
checking whether be64toh is declared... yes
checking whether htobe16 is declared... yes
checking whether htobe32 is declared... yes
checking whether htobe64 is declared... yes
checking whether bswap_16 is declared... yes
checking whether bswap_32 is declared... yes
checking whether bswap_64 is declared... yes
checking for MSG_NOSIGNAL... yes
checking for library containing clock_gettime... -lrt
checking for visibility attribute... yes
checking for Berkeley DB C++ headers... default
configure: WARNING: Found Berkeley DB other than 4.8; wallets opened by this build will not be portable!
checking for main in -ldb_cxx-4.8... no
checking for main in -ldb_cxx... yes
checking miniupnpc/miniwget.h usability... no
checking miniupnpc/miniwget.h presence... no
checking for miniupnpc/miniwget.h... no
checking miniupnpc/miniupnpc.h usability... no
checking miniupnpc/miniupnpc.h presence... no
checking for miniupnpc/miniupnpc.h... no
checking miniupnpc/upnpcommands.h usability... no
checking miniupnpc/upnpcommands.h presence... no
checking for miniupnpc/upnpcommands.h... no
checking miniupnpc/upnperrors.h usability... no
checking miniupnpc/upnperrors.h presence... no
checking for miniupnpc/upnperrors.h... no
checking whether to build Bitcoin Core GUI... no (Qt)
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Program_Options library is available... yes
checking for exit in -lboost_program_options-mt... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the Boost::Chrono library is available... yes
checking for exit in -lboost_chrono-mt... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
checking for dynamic linked boost test... yes
checking for SSL... yes
checking for CRYPTO... yes
checking for RAND_egd in -lcrypto... yes
checking openssl/ec.h usability... yes
checking openssl/ec.h presence... yes
checking for openssl/ec.h... yes
checking whether to build bitcoind... yes
checking whether to build utils (bitcoin-cli bitcoin-tx)... yes
checking whether to build libraries... yes
checking if ccache should be used... no
checking if wallet should be enabled... yes
checking whether to build with support for UPnP... no
checking whether to build test_bitcoin... yes
checking whether to reduce exports... no
configure: creating ./config.status
Fixing libtool for -rpath problems.
 /bin/bash ./config.status
config.status: creating libbitcoinconsensus.pc
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating share/setup.nsi
config.status: creating share/qt/Info.plist
config.status: creating src/test/buildenv.py
config.status: creating qa/pull-tester/run-bitcoind-for-test.sh
config.status: creating qa/pull-tester/tests-config.sh
config.status: creating src/config/bitcoin-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in src
make[1]: Entering directory `/usr/local/src/bitcoin/src'
make[2]: Entering directory `/usr/local/src/bitcoin/src'
  CXX    crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX    crypto/libbitcoinconsensus_la-ripemd160.lo
In file included from ./crypto/common.h:14:0,
                 from crypto/ripemd160.cpp:7:
./compat/endian.h:111:17: error: expected unqualified-id before '__extension__'
./compat/endian.h:111:17: error: expected ')' before '__extension__'
./compat/endian.h:111:17: error: expected unqualified-id before ')' token
./compat/endian.h:118:17: error: expected ')' before 'host_16bits'
./compat/endian.h:125:17: error: expected unqualified-id before '__extension__'
./compat/endian.h:125:17: error: expected ')' before '__extension__'
./compat/endian.h:125:17: error: expected unqualified-id before ')' token
./compat/endian.h:132:17: error: expected ')' before 'little_endian_16bits'
make[2]: *** [crypto/libbitcoinconsensus_la-ripemd160.lo] Error 1
make[2]: Leaving directory `/usr/local/src/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/bitcoin/src'
make: *** [all-recursive] Error 1

**Comment by mkabatek** [comment]
I had a similar problem on Ubuntu 14.04 LTS going from v0.10.x to v0.11.x. To solve it, I did the following:

    make clean
    git status
    
Delete any files/changes reported by git (since I didn't edit any source). Then it built as normal.

**Comment by laanwj** [comment]
Alternatively, if there is nothing important in the tree you can wipe it clean in one command with `git clean -f -x -d`.

**Comment by Lokutos** [comment]
cd /usr/local/src/bitcoind/
git checkout v0.10.2 -> make -> make install -> Works 

make clean
git clean -f -x -d
git pull
git checkout v0.11.0
git status -> no reports 
./autogen.sh
./configure --with-cli --without-gui --with-incompatible-bdb
make
make install

works. 

Thanks 4 Support 

LOG: http://pastebin.com/JJhbi76S

**Comment by wolololo** [comment]
Without git?

**Comment by chaosgrid** [comment]
I have the same issue. I'm compiling with gcc 4.1.2, maybe that is the reason? (I'm on Centos 5 :\)

**Comment by j04gd2h5h** [comment]
up

**Comment by laanwj** [comment]
Git master compiles using OpenBSD 5.7, but needs some special steps, follow this guide: https://github.com/bitcoin/bitcoin/blob/master/doc/build-openbsd.md
