### PR TITLE
prune, import: allow pruning to work during loadblock import

### LINKED ISSUE #23852: -prune doesn't work during import
It appears that `-prune` is ignored during import (`-reindex`, or `-loadblock`).

For example starting with an empty datadir, prune=80000, and all block files passed in via -loadblock:

```
...
2021-12-23T12:49:44Z [loadblk] [node/blockstorage.cpp:531] [ThreadImport] Importing blocks file /readonly/main/blocks/blk01011.dat...
2021-12-23T12:49:44Z [loadblk] [node/blockstorage.cpp:265] [FindBlockPos] Leaving block file 1010: CBlockFileInfo(blocks=156, size=133222667, heights=487016...487360, time=2017-09-26...2017-09-28)
2021-12-23T12:49:45Z [loadblk] [flatfile.cpp:69] [Allocate] Pre-allocating up to position 0x1000000 in blk01011.dat
2021-12-23T12:49:45Z [loadblk] [logging/timer.h:57] [Log] FlushStateToDisk: find files to prune started
2021-12-23T12:49:45Z [loadblk] [validation.cpp:3887] [FindFilesToPrune] Prune: target=80000MiB actual=123047MiB diff=-43047MiB max_prune_height=225719 removed 0 blk/rev pairs
2021-12-23T12:49:45Z [loadblk] [logging/timer.h:57] [Log] FlushStateToDisk: find files to prune completed (0.05ms)
...
```

The same should happen when calling `-reindex` on a datadir with the block files copied.

So prune only works with IBD from the network?

### PR DESCRIPTION
**Pull request by mruddy**
Fixes #23852

This allows pruning to work during the `-loadblock` import process.

An example use case is where you have a clean set of block files and you want to create a pruned node from them, but you don't want to alter the input set of block files.

#23852 noted that pruning was not working reliably during the loadblock import process. The reason why the loadblock process was not pruning regularly as it progressed is that the pruning process (`BlockManager::FindFilesToPrune`) checks the tip height of the active chainstate, and `CChainState::ActivateBestChain` was not called (which updates that tip height) in `ThreadImport` until after all the import files were processed.

An example bash command line that makes it easy to import a bunch of block files:
```
./src/qt/bitcoin-qt -debug -logthreadnames -datadir=/tmp/btc -prune=550 -loadblock=/readonly/btc/main/blk{00000..00043}.dat
```

One interesting side note is that `CChainState::ActivateBestChain` can be called while the import process is running (in the `loadblk` thread) by concurrent network message processing activity in the `msghand` thread. For example, one way to reproduce this easily is with the `getblockfrompeer` RPC (requesting a block with height greater than 100000) run from a node connected to an importing node. There are other ways too, but this is an easy way. I only mention this to explain how the `max_prune_height=225719` log message in the original issue came to occur.

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Concept ACK

**Review by luke-jr — APPROVED** [review]
Code safety utACK. Did not verify if it fixes a bug or impacts performance.

**Comment by mruddy** [comment]
It doesn't seem like there is much interest in merging this change. If nobody really chimes up about wanting this, then I'll close it in a week or so.

**Comment by jamesob** [comment]
Concept ACK. I think this should be reopened, as it's a small diff and a good change. I can review more thoroughly next week.

**Comment by laanwj** [comment]
Yeah, concept ACK

**Comment by mruddy** [comment]
I closed this to garbage collect because I thought it was dead. But, since there's interest I've reopened it. Thanks!

**Comment by mruddy** [comment]
Reopening since I have time to usher this to completion now.

**Comment by aureleoules** [comment]
I'm not sure how to test this? 
I let a fresh bitcoind node sync (enough to generate 20 blk.dat files) and tried importing on another fresh bitcoind node these blk files using `./src/bitcoind -debug -logthreadnames -datadir=/tmp/btc -prune=550 -loadblock=/tmp/btc1/blocks/blk{00000..00020}.dat`

where `/tmp/btc1` contains the 20 blk.dat files

but I get these logs for every block (both on master and this PR):
```
2022-10-31T16:30:15Z [loadblk] [reindex] LoadExternalBlockFile: Out of order block 000000000000061a9e7540272dd4cb607350b5f704d89bf87d4757078e0d2aa5, parent 0000000000000627a077a5b46189adeb9b345d3f5b9a4c8cfd847f5ba67af26c not known
...
2022-10-31T16:30:16Z [loadblk] Loaded 0 blocks from external file in 1135ms
```

**Comment by mruddy** [comment]
@aureleoules thanks for looking into this. your block files have blocks out of order. it's nothing that you did wrong. it's just that with the `-loadblock` option, there is no unknown-parent tracking like there is with `-reindex`. i forget the historical reason for why that is at the moment. but, that's how it is. for reference:
https://github.com/bitcoin/bitcoin/blob/master/src/node/blockstorage.cpp#L885
https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L4431-L4439

There is a tool to make some block files for testing where the blocks are in order and loadable with `-loadblock` at https://github.com/bitcoin/bitcoin/tree/master/contrib/linearize

If I remember correctly, another snag you'll come across is that you need to have at least 100,000 blocks for mainnet due to `nPruneAfterHeight` see https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L109

I'll make a todo item for myself to see how I can make testing this easier via a follow-up comment, and maybe a set of test input block files or something.

File: src/validation.cpp [hunk 1]
```diff
@@ -4461,6 +4461,21 @@ void Chainstate::LoadExternalBlockFile(
...
                 }
 
+                if (fPruneMode && !fReindex) {
+                    // must update the tip for pruning to work while importing with -loadblock.
+                    // this is a tradeoff to conserve disk space at the expense of time
+                    // spent updating the tip to be able to prune.
+                    // otherwise, ActivateBestChain won't be called by the import process
+                    // until after all of the block files are loaded. ActivateBestChain can be
+                    // called by concurrent network message processing. but, that is not
+                    // reliable for the puspose of pruning while importing.
```
[the remark this answers is not in the document]
Comment (mruddy) [reply src/validation.cpp:4471]: ah, thanks. will update with my next push.

**Comment by mruddy** [comment]
@aureleoules I put a set of linearized block files that are useful for testing this at:

https://github.com/mruddy/test_blk_files

A way to use the files and be able to watch what is going on in the debugger is with:

```
mkdir -p /tmp/btc && gdb --tui --args ./src/qt/bitcoin-qt -debug -logthreadnames -datadir=/tmp/btc -prune=550 -loadblock=/readonly/btc/main/blk{00000..00014}.dat -connect=0
```

The debug log will log related messages and can be found easily with grep like the following examples:

```
grep 'removed 1 blk/rev pairs' /tmp/btc/debug.log
2022-11-01T14:50:40Z [loadblk] [prune] target=550MiB actual=388MiB diff=161MiB max_prune_height=140633 removed 1 blk/rev pairs

grep 'unlink pruned files' /tmp/btc/debug.log
2022-11-01T14:50:46Z [loadblk] [bench] FlushStateToDisk: unlink pruned files started
2022-11-01T14:50:46Z [loadblk] [bench] FlushStateToDisk: unlink pruned files completed (28.22ms)
```

Depending on what you're looking to understand, various breakpoints can be set within gdb, for example:
```
b ThreadImport
b LoadExternalBlockFile
b FlushStateToDisk
b FindFilesToPrune
b PruneOneBlockFile
```

**Review by aureleoules — APPROVED** [review]
ACK 488682e785194f807f21b4dc6826df7714d78a25

Thanks @mruddy for the linearized block files!
I was able to verify with the given block files that pruning occurs during the import process in this PR and not at the end (master). 
If I understand correctly, this would allow cloning a full node into a pruned node without needing the double amount of disk space during the import process and without needing a workaround (`-connect=localhost`).

**Comment by luke-jr** [comment]
In the future, please don't rebase for no reason

**Comment by luke-jr** [comment]
P.S. Needs rebase. Silent conflict with #16981

```diff
diff --git a/src/validation.cpp b/src/validation.cpp
index 40d15b60d63..285aeb16d4e 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -4366,6 +4366,7 @@ void Chainstate::LoadExternalBlockFile(
                 // next block, but it's still possible to rewind to the start of the current block (without a disk read).
                 nRewind = nBlockPos + nSize;
                 blkdat.SkipTo(nRewind);
+                std::shared_ptr<CBlock> recent_block_maybe_not_this_block;
                 {
                     LOCK(cs_main);
                     // detect out of order blocks, and store them for later
@@ -4383,7 +4384,7 @@ void Chainstate::LoadExternalBlockFile(
                     if (!pindex || (pindex->nStatus & BLOCK_HAVE_DATA) == 0) {
                         // This block can be processed immediately; rewind to its start, read and deserialize it.
                         blkdat.SetPos(nBlockPos);
-                        std::shared_ptr<CBlock> pblock{std::make_shared<CBlock>()};
+                        auto& pblock = recent_block_maybe_not_this_block = std::make_shared<CBlock>();
                         blkdat >> *pblock;
                         nRewind = blkdat.GetPos();
 
@@ -4416,7 +4417,7 @@ void Chainstate::LoadExternalBlockFile(
                     // called by concurrent network message processing. but, that is not
                     // reliable for the purpose of pruning while importing.
                     BlockValidationState state;
-                    if (!ActivateBestChain(state, pblock)) {
+                    if (!ActivateBestChain(state, recent_block_maybe_not_this_block)) {
                         LogPrint(BCLog::REINDEX, "failed to activate chain (%s)\n", state.ToString());
                         break;
                     }

```

**Comment by mruddy** [comment]
@luke-jr Thanks! I just rebased and had to make a small change due to the #16981 updates. Those updates moved the block data read from disk into the coded block that is guarded by `cs_main`. I couldn't move my updates for this PR into that code block because `ActivateBestChain` asserts that `cs_main` is not held. So, I brought `pblock` one level back out of that `cs_main` guarded scope (leaving the read where #16981 moved it) so that I could access it without the lock being held.

> Should we be doing this check later on when processing out of order successor blocks?

No, because `-loadblock` doesn't support the out of order processing, and I don't want to make `-prune` work with `-reindex` for the reasons that I listed at https://github.com/bitcoin/bitcoin/issues/23852#issuecomment-1104200340

File: src/validation.cpp [hunk 2]
```diff
@@ -4471,6 +4474,21 @@ void Chainstate::LoadExternalBlockFile(
                     }
                 }
 
+                if (fPruneMode && !fReindex && pblock) {
```
Comment (luke-jr) [inline src/validation.cpp:4477]: Any reason not to just move this up to [after we accept the block](https://github.com/bitcoin/bitcoin/pull/24957/files#diff-97c3a52bc5fad452d82670a7fd291800bae20c7bc35bb82686c2c0a4ea7b5b98L4461)?

**Review by luke-jr — APPROVED** [review]
utACK 734355b470764c523ef08b25320a5fabb73358a6

File: src/validation.cpp (hunk 2 above)
Comment (mruddy) [reply src/validation.cpp:4477]: Yes, I can't move my updates for this PR into that code block because `ActivateBestChain` asserts that `cs_main` is not held.

**Comment by mruddy** [comment]
Thanks to those that have reviewed/tested this already, I think it's ready to go.

@jamesob Is there a chance that you might be able to review or test this PR? Thanks!

**Review by aureleoules — APPROVED** [review]
re-tACK 734355b470764c523ef08b25320a5fabb73358a6

**Comment by achow101** [comment]
ACK 734355b470764c523ef08b25320a5fabb73358a6

**Comment by achow101** [comment]
Looks like there's a silent merge conflict:

```
../../../src/validation.cpp: In member function ‘void Chainstate::LoadExternalBlockFile(FILE*, FlatFilePos*, std::multimap<uint256, FlatFilePos>*)’:
../../../src/validation.cpp:4518:21: error: ‘fPruneMode’ was not declared in this scope; did you mean ‘node::fPruneMode’?
 4518 |                 if (fPruneMode && !fReindex && pblock) {
      |                     ^~~~~~~~~~
      |                     node::fPruneMode
In file included from ../../../src/validation.h:22,
                 from ../../../src/validation.cpp:6:
../../../src/node/blockstorage.h:51:13: note: ‘node::fPruneMode’ declared here
   51 | extern bool fPruneMode;
      |             ^~~~~~~~~~
make[2]: *** [Makefile:10619: libbitcoin_node_a-validation.o] Error 1
```

**Comment by mruddy** [comment]
@achow101 Thanks! I rebased and then resolved the silent merge conflict by changing `fPruneMode` to `m_blockman.IsPruneMode()`.

**Comment by achow101** [comment]
re-ACK c4981e7f63a3e0aeec1ef3dec040261e993dd724
