### ISSUE TITLE
bitcoind fails to compile with boost 1.72.0 

### ISSUE THREAD

**Issue by meeDamian** [bitcoin/bitcoin#17856]
**Expected behavior**

`make` succeeds

**Actual behavior**

```sh
$ make
Making all in src
  …
  CXX      wallet/libbitcoin_wallet_a-walletutil.o
wallet/walletutil.cpp:77:23: error: no member named 'level' in 'boost::filesystem::recursive_directory_iterator'
        } else if (it.level() == 0 && it->symlink_status().type() == fs::regular_file && IsBerkeleyBtree(it->path())) {
                   ~~ ^
1 error generated.
make[2]: *** [wallet/libbitcoin_wallet_a-walletutil.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**To reproduce**

For MacOS:

```sh
brew update
brew install boost
cd bitcoin
./contrib/install_db4.sh $(pwd)
export BDB_PREFIX=$(pwd)/db4
./autogen.sh
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" --enable-cxx --without-gui --disable-tests --disable-bench
make
```

For Alpine see: [Dockerfile](https://github.com/lncm/docker-bitcoind/blob/boost-1.72.0/0.19/Dockerfile#L107), [build log](https://github.com/lncm/docker-bitcoind/runs/372097468#step:3:942).

**System information**

Tested for `v0.19.0.1` & e6f167bfd .

Reproducible on MacOS/amd64 as well as debian/arm, and ubuntu/amd64.

**Speculation**

It seems to be caused by a change in `boost` described as ([src](https://www.boost.org/users/history/version_1_72_0.html)):

> * **Deprecated:** The following members of `recursive_directory_iterator` are now marked as deprecated: `level()`, `no_push_pending()`, `no_push_request()`, `no_push()`. Users are advised to replace their use with the standard counterparts: `depth()`, `recursion_pending()`, `disable_recursion_pending()`. Note that `recursion_pending()` has the opposite meaning compared to `no_push_pending()` and `no_push_request()`. Deprecated methods will be removed in a future release.

**Comment by fanquake** [comment]
This is fixed with #17654. I'll backport that change and some other commits to the 0.19 branch shortly.

**Comment by nickycutesc** [comment]
@meeDamian @fanquake I am still getting this failed test! I have pulled 0.19.1 and the test is still failing. How would I go about debugging this?

**Comment by MarcoFalke** [comment]
@nickycutesc Please provide the config log and steps to reproduce

**Comment by nickycutesc** [comment]
Config Log:

# Auto-Generated Configuration File
# Node Launcher version 5.3.0
rpcuser=default_user
rpcpassword=""
datadir=/Volumes/BITCOIN
prune=1
txindex=0
server=1
timeout=6000
zmqpubrawblock=tcp://127.0.0.1:18500
zmqpubrawtx=tcp://127.0.0.1:18501
dbcache=6426
disablewallet=0
testnet=1



Steps to Reproduce:

1. $ bitcoind --version

<img width="217" alt="image" src="https://user-images.githubusercontent.com/24903257/80315617-c664f180-87c6-11ea-91ce-77118ce3a39d.png">

2. $ make

<img width="541" alt="image" src="https://user-images.githubusercontent.com/24903257/80315640-f4e2cc80-87c6-11ea-8f9d-5f232b0b3ea9.png">

**Comment by MarcoFalke** [comment]
The config log is in the folder where you type `make`

**Comment by nickycutesc** [comment]
config.status, right?

**Comment by MarcoFalke** [comment]
`./config.log`

**Comment by nickycutesc** [comment]
Are there any sensitive data in the config.log file that I should not publicize here (passwords, etc.)? From what I'm seeing, it's just my local directory dependencies.

**Comment by MarcoFalke** [comment]
It shouldn't contain passwords, but it contains you system software and hardware configuration.

Alternatively, can you provide `head -n 20 ./src/fs.h`.

**Comment by nickycutesc** [comment]
Understood, thanks!

// Copyright (c) 2017-2018 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef BITCOIN_FS_H
#define BITCOIN_FS_H

#include <stdio.h>
#include <string>
#if defined WIN32 && defined __GLIBCXX__
#include <ext/stdio_filebuf.h>
#endif

#define BOOST_FILESYSTEM_NO_DEPRECATED
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

/** Filesystem operations and types */
namespace fs = boost::filesystem;

**Comment by MarcoFalke** [comment]
Ok, what is `grep PACKAGE_STRING= ./config.log`?

**Comment by nickycutesc** [comment]
PACKAGE_STRING='Bitcoin Core 0.19.99'

**Comment by MarcoFalke** [comment]
Clearly this is not version 19.1

> I have pulled 0.19.1 and the test is still failing. 

> PACKAGE_STRING='Bitcoin Core 0.19.99'

How did you pull?

**Comment by nickycutesc** [comment]
1. git clone https://github.com/bitcoin/bitcoin
2. Opened in GitHub desktop
3. Switched to Master branch
4. Fetch changes.

**Comment by MarcoFalke** [comment]
You will need to checkout the correct version (like `git checkout v0.19.1`)

**Comment by nickycutesc** [comment]
Understood, trying now.

**Comment by nickycutesc** [comment]
Ahhh, sorting out git issues. Thanks for your help! I'm running the tests now.

**Comment by nickycutesc** [comment]
Finished running the tests in 0.19.1! However, I'm getting this error:

unknown location:0: fatal error: in "psbt_wallet_tests/psbt_updater_test": memory access violation at address: 0x02800000: no mapping at fault address

I tried searching for similar issues, but I'm not sure this particular error is addressed.

$ grep PACKAGE_STRING= ./config.log
PACKAGE_STRING='Bitcoin Core 0.19.1'


$ head -n 20 ./src/fs.h or git log -1
==> ./src/fs.h <==
// Copyright (c) 2017-2018 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef BITCOIN_FS_H
#define BITCOIN_FS_H

#include <stdio.h>
#include <string>
#if defined WIN32 && defined __GLIBCXX__
#include <ext/stdio_filebuf.h>
#endif

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

/** Filesystem operations and types */
namespace fs = boost::filesystem;

/** Bridge operations to C stdio */
head: or: No such file or directory
head: git: No such file or directory
head: log: No such file or directory
head: -1: No such file or directory

**Comment by MarcoFalke** [comment]
@nickycutesc Please open a new issue about that and include all relevant information

**Comment by nickycutesc** [comment]
Understood, thanks for your help @MarcoFalke !

**Comment by foodaka** [comment]
When running 0.19.0 i had this issue, after bumping to 0.19.1 it seemed to be fixed
