### ISSUE TITLE
errors compiling httpserver.cpp

### ISSUE THREAD

**Issue by crackfoo** [bitcoin/bitcoin#7031]
httpserver.cpp: In function ‘void StopHTTPServer()’:
httpserver.cpp:490:25: error: ‘class boost::thread’ has no member named ‘try_join_for’
httpserver.cpp:490:45: error: ‘boost::chrono’ has not been declared
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
make[2]: *** [libbitcoin_server_a-httpserver.o] Error 1
make[2]: Leaving directory `/src/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/src/bitcoin/src'
make: *** [all-recursive] Error 1

Any idea's what is causing this? only started with recent updates...

**Comment by MarcoFalke** [comment]
Prob. caused by #6990

**Comment by laanwj** [comment]
What version of boost?

**Comment by crackfoo** [comment]
ii  libboost-all-dev                      1.49.0.1                          amd64        Boost C++ Libraries development files (ALL) (default version)

**Comment by laanwj** [comment]
Looks like `try_join_for` was introduced in Boost 1.50: http://www.boost.org/doc/libs/1_50_0/doc/html/thread/thread_management.html#thread.thread_management.thread.try_join_for

1.49 has `timed_join`, I think you can accomplish the same with that:
http://www.boost.org/doc/libs/1_49_0/doc/html/thread/thread_management.html#thread.thread_management.thread.timed_join

However, `timed_join` was deprecated in 1.50, with boost::chrono. How convenient. This needs something like:
```
#if BOOST_VERSION >= 105000
    if (!threadHTTP.try_join_for(boost::chrono::milliseconds(2000))) {
#else
    if (!threadHTTP.timed_join(boost::posix_time::milliseconds(2000))) {
#endif
```

**Comment by crackfoo** [comment]
thanks for this. httpserver.cpp compilation succeeded after that suggested change. I'll report if it causes any further issues.

**Comment by laanwj** [comment]
Closed by #7065

**Comment by miguelmorales85** [comment]
This happens also when make is done to 0.12.1
