### PR TITLE
mining: always pad scriptSig at low heights, drop include_dummy_extranonce

### LINKED ISSUE #35126: Mining IPC `createNewBlock` fails with `bad-cb-length` on low-height regtest chains
I’m not sure whether this is expected after #32420, but I’m seeing `Mining.createNewBlock` over IPC fail on low-height regtest chains before the IPC client can receive a template and construct its own coinbase.

### Observed behavior

On Bitcoin Core v31.0, when using the Mining IPC interface on regtest at low block heights, `Mining.createNewBlock` can throw:

```text
remote exception: std::exception: TestBlockValidity failed: bad-cb-length, Transaction check failed
```

In my case this happens with a regtest node after mining one initial block through RPC, so the next template height is 2.

## Potential root cause

(according to my clanker, @Sjors please sanity check?)

`BlockAssembler::CreateNewBlock()` builds an internal coinbase with:

```
coinbaseTx.vin[0].scriptSig = CScript() << nHeight;
```

For heights 1 through 16, the BIP34 height is encoded as a one-byte `OP_1` through `OP_16`. That is below the consensus minimum coinbase `scriptSig` length of 2 bytes, so `TestBlockValidity()` rejects the internally assembled block with `bad-cb-length`.

RPC mining paths appear to avoid this by setting `include_dummy_extranonce = true`, but that option does not seem to be exposed in the IPC `BlockCreateOptions` schema.

## Workaround
Pre-mine 16 regtest blocks before using the IPC Mining interface. Then the next template height is 17, the BIP34 height encoding is no longer one byte, and `createNewBlock` succeeds.

### PR DESCRIPTION
**Pull request by Sjors**
Blocks 0-16 on any new chain require mining code to be careful not to violate the `bad-cb-length` rule, which states the coinbase transaction scriptSig must be at least 2 bytes.  

Our mining code deals with that by padding the `scriptSig` with a 0 `extraNonce`. It does this for every height. As a result IPC clients would get an unnecessary `0` in the `scriptSigPrefix` field of  `CoinbaseTx`. #32420 fixed that by introducing a `include_dummy_extranonce` option in `BlockCreateOptions` and turning that off for IPC clients.

A minor issue was missed though: `createNewBlock()` now fails with `bad-cb-length`. An easy workaround is to use the `generate` RPC for the first 16 blocks, as demonstrated in the 2nd commit.

The real fix is to have the miner code always pad the `scriptSig` at lower heights, but to _not_ include that in the `scriptSigPrefix` field of  `CoinbaseTx` (introduced in #33819). This is what the 3rd commit implements.

Now that we set `scriptSigPrefix` independent of what our internal miner code does - to get past `CheckBlock()` - the original motivation for `include_dummy_extranonce` goes away and we can just drop it entirely. The last commit drops it, while the 4th commit adjusts the tests and hardcoded block and assume utxo hashes.

This last change does not break IPC clients, because `include_dummy_extranonce` was never exposed in `mining.capnp`.

Instead of adjusting the hardcoded hashes, an alternative approach would be to just always pad the `scriptSig` internally, since we exclude the padding from `scriptSigPrefix` anyway. However, IPC clients can also call `getBlock()` to get the raw block and might be confused about the difference. The miner code is also easier to understand if we limit the exception (`coinbase_tx.script_sig_prefix != coinbaseTx.vin[0].scriptSig`) to `nHeight <= 16`, where the explanation is based purely on consensus rules rather than historical test suite reasons.

The first two commits are preperation test changes:
-  extract `assert_capnp_failed` helper for macOS (also part of #34727)
-  use `script_BIP34_coinbase_height` in IPC mining test (existing code in `interface_ipc_mining.py` was incorrect for low height

Fixes #35126

### CODE REVIEW

**Comment by Sjors** [comment]
Given the easy workaround, I don't think it's necessary to backport this. The only downside of that workaround, and the reason I noticed the issue while working on another project, is that the `generate` RPC methods can't be used to create a deterministic regtest chain. With `createNewBlock()` -> `submitSolution()` the IPC client can pick specific (cached) `nonce` and `nTime` values.

---

Historical note: the introduction of a `CoinbaseTx` struct for IPC clients in #33819 probably made the `include_dummy_extranonce` approach in #32420 unnecessary, since we can now give clients a different `scriptSigPrefix` than what we use in the block template in order to get past `CheckBlock()`.

**Comment by maflcko** [comment]
> A nice benefit of this change is that it's now possible to get rid of the `include_dummy_extranonce` option entirely, without breaking IPC clients because it's not exposed in `mining.capnp`, but it would involve significant test churn

I don't think test churn is a reason to leave deprecated/unused/confusing stuff in the real code. Test code should always follow the real code, not the other way round.

**Comment by Sjors** [comment]
@maflcko I'll push a commit to this PR to drop it entirely, updating the hashes where needed.

**Comment by fanquake** [comment]
>  without breaking IPC clients

Until the interface stabilizes, and is marked as such, "breaking clients" should be much less of an issue? I don't think we should have an interface that is marked as brand new/experimental, but then also not have the freedom to iterate/change it, because we are also half-pretending that it is meant to be stable/backwards compatible.

**Comment by Sjors** [comment]
> "breaking clients" should be much less of an issue?

Indeed, I just observed that it's nice that we never exposed `include_dummy_extranonce` to clients in the first place, so dropping it is an internal change to Bitcoin Core that has no impact on IPC clients. But if it _was_ a breaking change, we could indeed just do that as long as the interface is marked experimental.

**Comment by Sjors** [comment]
The [ancestor commits failure](https://github.com/bitcoin/bitcoin/actions/runs/23294168432/job/67737094456?pr=34860) seems unrelated, but the fuzzer failures seem relevant. Will investigate.

**Comment by Sjors** [comment]
The fuzzer was still adding the dummy extraNonce, should be fixed now.

File: src/node/miner.cpp [hunk 1]
```diff
@@ -184,14 +184,19 @@ std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock()
     // increasing its length would reduce the space they can use and may break
     // existing clients.
     coinbaseTx.vin[0].scriptSig = CScript() << nHeight;
-    if (m_options.include_dummy_extranonce) {
+    // Set script_sig_prefix here, so IPC mining clients are not affected by
+    // the optional scriptSig padding below. They provide their own extraNonce,
+    // and in a typical setup a pool name or realistic extraNonce already makes
+    // the scriptSig long enough.
+    coinbase_tx.script_sig_prefix = coinbaseTx.vin[0].scriptSig;
+    if (nHeight <= 16 || m_options.include_dummy_extranonce) {
```
Comment (enirox001) [inline src/node/miner.cpp]: In commit "mining: always set dummy_extranonce at low heights" (https://github.com/bitcoin/bitcoin/pull/34860/changes/d6f9ab4d082dc12a9df976668689d7c75cfe34cd):

The condition `nHeight <= 16 `technically includes height 0. But height 0 is caught by the `Assert` below. Would it be cleaner to write i`f (nHeight <= 16 && nHeight > 0)`? or move the `Assert` above the condition?

File: src/node/miner.cpp [hunk 2]
```diff
@@ -184,14 +184,19 @@ std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock()
     // increasing its length would reduce the space they can use and may break
     // existing clients.
     coinbaseTx.vin[0].scriptSig = CScript() << nHeight;
-    if (m_options.include_dummy_extranonce) {
+    // Set script_sig_prefix here, so IPC mining clients are not affected by
+    // the optional scriptSig padding below. They provide their own extraNonce,
+    // and in a typical setup a pool name or realistic extraNonce already makes
```
Comment (enirox001) [inline src/node/miner.cpp:189]: In commit "mining: always set dummy_extranonce at low heights" (https://github.com/bitcoin/bitcoin/pull/34860/changes/d6f9ab4d082dc12a9df976668689d7c75cfe34cd):

The comment says "in a typical setup a pool name or realistic extraNonce already makes the scriptSig long enough" but this puts the responsibility entirely on the client at `heights ≤ 16`. I tested this by removing the extra nonce in `run_low_height_test()` and it causes `submitSolution()` to silently return False with no explanation. Should we at minimum document in the code or the IPC interface that at `heights ≤ 16` the client must provide at least 1 byte of extra nonce?

File: src/node/miner.cpp [hunk 3]
```diff
@@ -184,14 +184,19 @@ std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock()
...
+    // the scriptSig long enough.
+    coinbase_tx.script_sig_prefix = coinbaseTx.vin[0].scriptSig;
```
Comment (enirox001) [inline src/node/miner.cpp:191]: In commit "mining: always set dummy_extranonce at low heights" (https://github.com/bitcoin/bitcoin/pull/34860/changes/d6f9ab4d082dc12a9df976668689d7c75cfe34cd):

At heights ≤ 16, `getBlock()` and `getCoinbaseTx()` return different scriptSig data since `script_sig_prefix` is snapshotted here before the OP_0 padding is added. I verified this in the test. `getBlock()` returns `5100` ([OP_1, OP_0]) while `scriptSigPrefix` returns 51 ([OP_1] only). Would an IPC client comparing both would be confused? Should this discrepancy be documented in the IPC interface or the code?

**Review by enirox001 — COMMENTED** [review]
Concept ACK. Changes look good to me. Left a few questions about some of the changes made.

I also tested that the boundary works correctly across all heights up to 17. At heights 1-16 the discrepancy between `getBlock()` and `scriptSigPrefix` exists as expected, and disappears exactly at height 17

**Comment by w0xlt** [comment]
Concept ACK

File: src/node/miner.cpp (hunk 1 above)
Comment (Sjors) [reply src/node/miner.cpp]: I think they're separate issues:

1. if we ever supported regtest or signets with a custom genesis block, and if we decided such custom genesis blocks _are_ subject to validation, then the `bad-cb-length` would apply. Either way it wouldn't cause a crash if we padded it.

2. our mining code is not expected to be used on a genesis block. The `nHeight - 1` logic below would crash if that changes. So I think the assert is in the right place to make that that clear.

File: src/node/miner.cpp (hunk 2 above)
Comment (Sjors) [reply src/node/miner.cpp:189]: #34672 adds a failure reason to `submitSolution()`

I'm tempted to not document this rule so implementers actually have to handle failure correctly to learn it :-)

File: src/node/miner.cpp (hunk 3 above)
Comment (Sjors) [reply src/node/miner.cpp:191]: They would indeed be confused, but only for these lower heights.

Might indeed be worth documenting in `getBlock()`, more generally that it contains a dummy coinbase that should not be used and may not match `getCoinbaseTx()`

File: src/node/miner.cpp (hunk 2 above)
Comment (enirox001) [reply src/node/miner.cpp:189]: Good to know #34672 addresses this. Fair point on not documenting it, clients should handle failures regardless.

Comment (Sjors) [reply src/node/miner.cpp:189]: Documented in e5ec15d3a229fe933313b46e5e2af9cbc54c9247.

File: src/node/miner.cpp (hunk 3 above)
Comment (Sjors) [reply src/node/miner.cpp:191]: Documented in e5ec15d3a229fe933313b46e5e2af9cbc54c9247.

**Review by enirox001 — COMMENTED** [review]
ACK 647407c - Thanks for applying the documentation suggestions.

**Comment by Sjors** [comment]
Rebased after #34727, which included the original variant of 7881e298c7491f070e1c10318b84655a894d8889.

**Comment by Sjors** [comment]
It also introduced a new `make_mining_ctx` method.

File: test/functional/interface_ipc_mining.py [hunk 4]
```diff
@@ -412,6 +449,9 @@ def run_test(self):
         self.run_coinbase_and_submission_test()
         self.run_ipc_option_override_test()
 
+        # Needs to run last
```
Comment (ryanofsky) [inline test/functional/interface_ipc_mining.py]: In commit "test: bad-cb-length for createNewBlock() at low heights" (2544b73f0d9db1736c6fee70351ad73a3fd3b40d)

Maybe add it needs to run last because it resets the chain

**Review by ryanofsky — APPROVED** [review]
Code review ACK 0b0aa376ec51f86c9cf3fb170ccde7abd64db353.

I think the end state here is an improvement, but the PR feels a bit broader than it needs to be, and I wonder if it would be nicer to split it up.

As I understand it, the PR is doing three things:

1. It removes the `createNewBlock` `dummy_extranonce` option introduced in [#32420](https://github.com/bitcoin/bitcoin/pull/32420). That option created a footgun because `createNewBlock` could build invalid blocks at heights <= 16 when the option was false. Over IPC there was no way to set `dummy_extranonce=true`, and no way to disable `test_block_validity`, so `createNewBlock` was effectively unusable below height 16 because it would always throw `TestBlockValidity` exceptions.

2. It implements a different fix for the usability problem [#32420](https://github.com/bitcoin/bitcoin/pull/32420) was trying to address. Instead of returning a `coinbase_template.script_sig_prefix` that may contain a dummy `OP_0` which clients need to strip off before adding their own extra nonce, it now always returns the unpadded prefix.

3. It changes the `scriptSig << OP_0` behavior so the dummy `OP_0` is only appended at heights <= 16 instead of at all heights. This is externally visible beyond IPC, including through RPC, and requires a number of hash updates.

I think all three changes are reasonable, but (3) seems separate from fixing the IPC usability problem. and not strictly necessary, so would seem good to move it into separate commit at the end, so it is not mixed in with changes in (1) and (2).

I also think it would be good if (2) were the first non-test change in the series, and if the `script_sig_prefix` documentation were updated in the same commit to clarify that clients may need to add extra data at low heights for the resulting scriptSig to be valid, not just that they may append extra data in general.

**Comment by Sjors** [comment]
@ryanofsky I rewrote the commit history (first two test commits are the same, just rebased and with your comment added).

**Comment by Sjors** [comment]
Replaced `rmtree(node.chain_path)` with `self.cleanup_folder` as requested by the linter.

File: src/node/miner.cpp (hunk 3 above)
Comment (ryanofsky) [inline src/node/miner.cpp:191]: In commit "mining: always pad script_sig_prefix at heights <= 16" (26d28e3cfdcf77d5b16465cecc6a5db49dd3a8ad)

Change looks good and thanks for the updates! I think the commit message saying "always pad script_sig_prefix" is misleading since actually this never pads it. I think i'd rewrite it to focus on the main change and list the other changes later like:

```
mining: pad coinbase to fix createNewBlock at heights <=16

Since #32420, createNewBlock has thrown `bad-cb-length` errors when called at
low block heights because `OP_0` padding stopped being added to coinbase
transactions. (#32420 did add an `include_dummy_extranonce` option which could
bypass this, but it was not exposed to IPC clients.) Fix the problem by padding
coinbase transactions with `OP_0` when necessary to produce valid blocks.

Additionally this commit stops adding `OP_0` padding to the template
`script_sig_prefix` field when `include_dummy_extranonce` is true. This is safe
because non-IPC clients don't use this field, and IPC clients could never set
the option to true, and are expected to add their own nonces in any case.

This also improves documentation about the `script_sig_prefix` field and
`getCoinbaseTx` method.
```

File: src/test/fuzz/utxo_total_supply.cpp [hunk 5]
```diff
@@ -107,8 +107,13 @@ FUZZ_TARGET(utxo_total_supply)
     // Assuming that the fuzzer will mine relatively short chains (less than 200 blocks), we want the duplicate coinbase to be not too high.
     // Up to 300 seems reasonable.
     int64_t duplicate_coinbase_height = fuzzed_data_provider.ConsumeIntegralInRange(0, 300);
-    // Always pad with OP_0 at the end to avoid bad-cb-length error
-    const CScript duplicate_coinbase_script = CScript() << duplicate_coinbase_height << OP_0;
+    // Build the scriptSig exactly as CreateNewBlock does for the given height:
```
Comment (ryanofsky) [inline src/test/fuzz/utxo_total_supply.cpp]: In commit "mining: always pad script_sig_prefix at heights <= 16" (26d28e3cfdcf77d5b16465cecc6a5db49dd3a8ad)

Is it important this is building the scriptSig in the exact same way as CreateNewBlock? If not maybe say "similarly to" instead of "exactly as" to avoid giving this impression

**Review by ryanofsky — APPROVED** [review]
Code review ACK 48c32df97f7a6197e912e22eb7de3e2780d89404. Nice fix, and everything seems pretty clearly spelled out in the PR description.

I do think the alternate approach of always adding padding instead of only adding it at low heights would be a good fix as well, since it would restore previous behavior prior to #32420 and simplify this PR by avoiding the need to update hashes, pruning offsets, and feature_assumetxo data offsets. Both both approaches seem reasonable.

File: src/node/miner.cpp (hunk 3 above)
Comment (Sjors) [reply src/node/miner.cpp:191]: Taken

File: src/test/fuzz/utxo_total_supply.cpp (hunk 5 above)
Comment (Sjors) [reply src/test/fuzz/utxo_total_supply.cpp]: It's not, it just needs to avoid `avoid bad-cb-length error`, updated the comment.

File: test/functional/interface_ipc_mining.py [hunk 6]
```diff
@@ -407,6 +403,45 @@ async def async_routine():
...
+                template = await mining_create_block_template(mining, stack, ctx, opts, cooldown=False)
+                assert template is not None
+                block = await mining_get_block(template, ctx)
+                coinbase = await self.build_coinbase_test(template, ctx, miniwallet, extra_nonce=b'\xaa\xbb\xcc\xdd')
+                block.vtx[0] = coinbase
+                block.hashMerkleRoot = block.calc_merkle_root()
+                block.solve()
+                submitted = (await template.submitSolution(ctx, block.nVersion, block.nTime, block.nNonce, coinbase.serialize())).result
+                assert_equal(submitted, True)
+                assert_equal(node.getblockcount(), 1)
```
Comment (sedited) [inline test/functional/interface_ipc_mining.py]: Nit, maybe do this for 17 iterations to exercise the boundary condition?

**Review by sedited — APPROVED** [review]
ACK f6e546b89bd4ebeca9091cdc7cce389d2751fe9a

File: test/functional/interface_ipc_mining.py (hunk 6 above)
Comment (Sjors) [reply test/functional/interface_ipc_mining.py]: Done (required some additional test changes to limit churn between 55c3104a739252bee86b77a880f03227079988bc and 3ed62f3ff0f8f2a9a8cd42b08d9d1d5d0bc6a322)

**Review by sedited — APPROVED** [review]
Re-ACK c4c701ca3efa5ed4d0c4207cd8a4d9b950c5d58b

**Review by enirox001 — COMMENTED** [review]
Re-ACK c4c701ca3e

Reviewed the changes. The previous comments seem addressed: the low-height scriptSig behavior is documented, the `getBlock()`/`getCoinbaseTx()` difference is documented, `include_dummy_extranonce` is gone, and the hash/test updates are kept separate.

**Comment by Sjors** [comment]
@ryanofsky can you give it another look?

File: test/functional/interface_ipc_mining.py [hunk 7]
```diff
@@ -79,8 +75,8 @@ async def build_coinbase_test(self, template, ctx, miniwallet):
 
         # Verify there's no dummy extraNonce in the coinbase scriptSig
         current_block_height = self.nodes[0].getchaintips()[0]["height"]
-        expected_scriptsig = CScript([CScriptNum(current_block_height + 1)])
-        assert_equal(coinbase_res.scriptSigPrefix.hex(), expected_scriptsig.hex())
+        bip34_prefix = script_BIP34_coinbase_height(current_block_height + 1, padding=False)
+        assert_equal(coinbase_res.scriptSigPrefix, bip34_prefix)
```
Comment (ryanofsky) [inline test/functional/interface_ipc_mining.py:79]: In commit "test: use script_BIP34_coinbase_height in IPC mining test" (a2682ed95c06400ce3ac116f9e31abf8e04bcbd4)

In case, this is updated, it would be good to add "refactor" to commit description to be clear this commit isn't changing what the test does

File: test/functional/test_framework/ipc_util.py [hunk 8]
```diff
@@ -109,9 +109,9 @@ async def make_capnp_init_ctx(self):
     return ctx, init
 
 
-async def mining_create_block_template(mining, stack, ctx, opts):
+async def mining_create_block_template(mining, stack, ctx, opts, cooldown=True):
```
Comment (ryanofsky) [inline test/functional/test_framework/ipc_util.py]: In commit "test: bad-cb-length for createNewBlock() at low heights" (55c3104a739252bee86b77a880f03227079988bc)

Hardcoding cooldown=True here is not ideal because it duplicates that capnp interface definition, makes it harder to verify this commit is not changing behavior, could potentially cause bugs if the python and capnproto interfaces get out of sync, especially if new parameters are added. Would suggest forwarding args instead with:

```diff
--- a/test/functional/test_framework/ipc_util.py
+++ b/test/functional/test_framework/ipc_util.py
@@ -109,9 +109,9 @@ async def make_capnp_init_ctx(self):
     return ctx, init
 
 
-async def mining_create_block_template(mining, stack, ctx, opts, cooldown=True):
+async def mining_create_block_template(mining, stack, ctx, *args, **kwargs):
     """Call mining.createNewBlock() and return template, then call template.destroy() when stack exits."""
-    response = await mining.createNewBlock(ctx, opts, cooldown)
+    response = await mining.createNewBlock(ctx, *args, **kwargs)
     if not response._has("result"):
         return None
     return await stack.enter_async_context(destroying(response.result, ctx))
```

File: test/functional/interface_ipc_mining.py [hunk 9]
```diff
@@ -403,6 +403,45 @@ async def async_routine():
...
+            ctx, mining = await make_mining_ctx(self)
+            opts = self.capnp_modules['mining'].BlockCreateOptions()
+
+            # IPC createNewBlock() currently fails with bad-cb-length at heights
+            # <= 16, so use the generate RPC as a workaround. The next commit
+            # fixes this and replaces the loop body with a createNewBlock() /
+            # submitSolution() flow.
+            for i in range(17):
+                async with AsyncExitStack() as stack:
+                    # Disable cooldown to avoid hanging in the IBD loop on a fresh chain
```
Comment (ryanofsky) [inline test/functional/interface_ipc_mining.py:434]: In commit "test: bad-cb-length for createNewBlock() at low heights" (55c3104a739252bee86b77a880f03227079988bc)

Comment doesn't apply to the `try` block, should probably be moved above the line specifying cooldown=False

File: test/functional/interface_ipc_mining.py [hunk 10]
```diff
@@ -416,28 +421,27 @@ def run_low_height_test(self):
...
-                        if i != 16:
-                            raise AssertionError(f"createNewBlock() should have failed at height {i + 1}")
-                    except capnp.lib.capnp.KjException as e:
-                        assert i < 16
-                        assert_capnp_failed(e, "remote exception: std::exception: TestBlockValidity failed: bad-cb-length")
-                    self.generate(node, 1, sync_fun=self.no_op)
+                    template = await mining_create_block_template(mining, stack, ctx, opts, cooldown=False)
+                    assert template is not None
+                    block = await mining_get_block(template, ctx)
+                    extra_nonce = b'\xaa\xbb\xcc\xdd' if i < 16 else b""
```
Comment (ryanofsky) [inline test/functional/interface_ipc_mining.py]: In commit "mining: pad coinbase to fix createNewBlock at heights <=16" (3ed62f3ff0f8f2a9a8cd42b08d9d1d5d0bc6a322)

I was confused by this line because it seems like it is not padding at height 16. Maybe add a comment like:

```python
extra_nonce = b'\xaa\xbb\xcc\xdd' if i < 16 else b"" # Height is i + 1; heights <=16 need padding.
```

File: test/functional/interface_ipc_mining.py [hunk 11]
```diff
@@ -416,28 +421,27 @@ def run_low_height_test(self):
...
+
         async def async_routine():
             ctx, mining = await make_mining_ctx(self)
             opts = self.capnp_modules['mining'].BlockCreateOptions()
 
-            # IPC createNewBlock() currently fails with bad-cb-length at heights
-            # <= 16, so use the generate RPC as a workaround. The next commit
-            # fixes this and replaces the loop body with a createNewBlock() /
-            # submitSolution() flow.
+            # Mine 17 blocks to exercise the boundary at height 16, where the
```
Comment (ryanofsky) [inline test/functional/interface_ipc_mining.py]: In commit "mining: pad coinbase to fix createNewBlock at heights <=16" (3ed62f3ff0f8f2a9a8cd42b08d9d1d5d0bc6a322)

Maybe tweak the comment to say "Mine blocks 1-17" instead of "Mine 17 blocks" to make the discrepancy between `i` and height more obvious.

Would also consider `for height in range(1, 18):`

File: src/node/miner.cpp [hunk 12]
```diff
@@ -189,12 +189,11 @@ std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock()
     // and in a typical setup a pool name or realistic extraNonce already makes
     // the scriptSig long enough.
     coinbase_tx.script_sig_prefix = coinbaseTx.vin[0].scriptSig;
-    if (nHeight <= 16 || m_options.include_dummy_extranonce) {
```
Comment (ryanofsky) [inline src/node/miner.cpp]: In commit "mining: only pad with OP_0 at heights <= 16" (cb6e85a53fb2d3efbfbc48efb1ad597799f006e5)

Would seem appropriate to update `src/node/types.h` in this commit and add a line saying this option is ignored and no longer has any effect. This would make the diff self-evident without needing to read the commit message, and it would make code consistent in case someone happened to check out this commit (e.g. while bisecting)

**Review by ryanofsky — APPROVED** [review]
Code review ACK c4c701ca3efa5ed4d0c4207cd8a4d9b950c5d58b. Just test and comment changes since the last review, extending the tests to cover more blocks heights. I left some review suggestions below but they are all minor, and could be ignored or considered for followups

**Comment by ryanofsky** [comment]
Looks like there is a silent merge conflict with #33300 and this needs to be rebased. Error:

```
src/test/fuzz/cmpctblock.cpp:124:13: error: no member named 'include_dummy_extranonce' in 'node::BlockAssembler::Options'
  124 |     options.include_dummy_extranonce = true;
      |     ~~~~~~~ ^
1 error generated.
```

**Comment by Sjors** [comment]
Thanks @ryanofsky. Since I need to rebase and deal with the silent conflict anyway, I'll apply your review suggestions too.

File: test/functional/interface_ipc_mining.py (hunk 10 above)
Comment (Sjors) [reply test/functional/interface_ipc_mining.py]: Looping over `height` now so that should be more clear, also added a comment.

**Comment by Sjors** [comment]
Rebased after silent (trivial) conflict with #33300 and addressed feedback: https://github.com/bitcoin/bitcoin/pull/34860#pullrequestreview-4281163793

File: src/node/miner.cpp (hunk 3 above)
Comment (ryanofsky) [inline src/node/miner.cpp:191]: In commit "mining: pad coinbase to fix createNewBlock at heights <=16" (00d22328b0560bf9773417495123ae68bb89e4d1)

Not important, but it occurs to me that this commit would be easier to understand if it were split in two: an initial commit that stopped adding the extranonce to script_sig_prefix and a second commit actually fixing the createNewBlock bug.

File: test/functional/interface_ipc_mining.py (hunk 10 above)
Comment (ryanofsky) [reply test/functional/interface_ipc_mining.py]: re: https://github.com/bitcoin/bitcoin/pull/34860#discussion_r3235889610

> Looping over `height` now so that should be more clear, also added a comment.

Not important but the initial commit still uses `i + 1` and could also be switched to use `height`.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 8544537f41df568e6e1cb94eeab9e699b9190427. Just rebased to fix silent conflict and applied some minor suggestions since last review. As part of rereviewing I left some more minor suggestions that are fine to ignore.

**Comment by Sjors** [comment]
Thanks @ryanofsky, I'll leave those changes for a next push if needed.

**Review by sedited — APPROVED** [review]
Re-ACK 8544537f41df568e6e1cb94eeab9e699b9190427

File: test/functional/interface_ipc_mining.py [hunk 13]
```diff
@@ -416,29 +421,29 @@ def run_low_height_test(self):
         node.wait_for_rpc_connection()
         assert_equal(node.getblockcount(), 0)
 
+        miniwallet = MiniWallet(node)
```
Comment (ryanofsky) [inline test/functional/interface_ipc_mining.py:424]: In commit "mining: pad coinbase to fix createNewBlock at heights <=16" (00d22328b0560bf9773417495123ae68bb89e4d1)

Probably makes sense to drop this and use self.miniwallet below

Comment (Sjors) [reply test/functional/interface_ipc_mining.py:424]: Done in #33966.
