### PR TITLE
test: Add missing include

### PR DESCRIPTION
**Pull request by maflcko**
Fix the silent merge conflict introduced in commit 7d60f7ec6bbf293c6f23f442a0fd985111a15ff7

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK 6666ec9e059ea66065a11f5e25c0a17d7d0834fe - fixes:
```bash
test/miner_tests.cpp: In member function ‘void miner_tests::CreateNewBlock_validity::test_method()’:
test/miner_tests.cpp:219:32: error: ‘VERSIONBITS_TOP_BITS’ was not declared in this scope
  219 |             pblock->nVersion = VERSIONBITS_TOP_BITS;
      |                                ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:15329: test/test_bitcoin-miner_tests.o] Error 1
```
