### PR TITLE
test: doc: follow-up #28368

### LINKED ISSUE #29000: Test `policyestimator_tests/BlockPolicyEstimates` failure
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I have a reproducible test case failure on my machine. I've bisected it to commit 714523918ba2b853fc69bee6b04a33ba0c828bf5. Since this commit, the test case `policyestimator_tests/BlockPolicyEstimates` fails, but only when I use my builds script:

```sh
chrt -i 0 make -j32 check
```

`chrt` runs the make command in idle priority (I use that so I can smoothly browse while testing). I have an AMD 7950x with 16 cores/32 threads. When I remove `chrt -i 0` the test works. I suspect that it fails because for whatever reason it can't run in parallel with another test, but so far I couldn't narrow it down.

```
❯ chrt -i 0 make -j32 check |grep error
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(129): error: in "policyestimator_tests/BlockPolicyEstimates": check origFeeEst[i-1] < mult*baseRate.GetFeePerK() + deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
test/policyestimator_tests.cpp(151): error: in "policyestimator_tests/BlockPolicyEstimates": check feeEst.estimateFee(i).GetFeePerK() > origFeeEst[i-1] - deltaFee has failed
make[3]: *** [Makefile:22606: test/policyestimator_tests.cpp.test] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:20548: check-am] Error 2
make[1]: *** [Makefile:20213: check-recursive] Error 1
make: *** [Makefile:813: check-recursive] Error 1
```

### Expected behaviour

All unit tests should succeed

### Steps to reproduce

```sh
./autogen.sh
./configure CXX=clang++ CC=clang --disable-wallet --with-guid=no
chrt -i 0 make -j32 check
```

### Relevant log output

I uploaded the full log of `chrt -i 0 make -j32 check >out.txt` here: https://gist.github.com/martinus/5d6795cd618f7d203e95d4f5426746f0

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

160d23677ad

### Operating system and version

Linux 6.6.2-201.fc39.x86_64

### Machine specifications

AMD 7950x

### PR DESCRIPTION
**Pull request by ismaelsadeeq**
This is a simple PR that does two things
1.   Fixes #29000 by waiting for the fee estimator to catch up after `removeForBlock` calls before calling `estimateFee` in the `BlockPolicyEstimates` unit test.

2. Addressed some outstanding review comments from #28368 
- Updated `NewMempoolTransactionInfo::m_from_disconnected_block` to `NewMempoolTransactionInfo::m_mempool_limit_bypassed` which now correctly indicates what the boolean does.
- Changed  input of `processTransaction`'s tx_info  `m_submitted_in_package` input from false to fuzz data provider boolean.
- Fixed some typos, and update incorrect comment

### CODE REVIEW

File: src/test/fuzz/policy_estimator.cpp [hunk 1]
```diff
@@ -48,7 +48,7 @@ FUZZ_TARGET(policy_estimator, .init = initialize_policy_estimator)
                 const auto tx_info = NewMempoolTransactionInfo(entry.GetSharedTx(), entry.GetFee(),
                                                                entry.GetTxSize(), entry.GetHeight(),
                                                                /* m_mempool_limit_bypassed */ false,
-                                                               /* m_submitted_in_package */ false,
```
Comment (martinus) [inline src/test/fuzz/policy_estimator.cpp:51]: I'm not sure it is a good idea to have two calls to `fuzzed_data_provider` in the function call. The problem is that the order of evaluation of function arguments is unspecified: https://en.cppreference.com/w/cpp/language/eval_order
So evaluation order can change at any time. Then the same fuzzing input will produce different results.
I'd move the calls in front of `NewMempoolTransactionInfo`

**Review by martinus — CHANGES_REQUESTED** [review]

**Comment by martinus** [comment]
I can confirm that #29000 is fixed for me in commit 76d0c07ee94b8720964d9d71d462550ecc8b5147.

File: src/test/fuzz/policy_estimator.cpp [hunk 2]
```diff
@@ -48,7 +48,7 @@ FUZZ_TARGET(policy_estimator, .init = initialize_policy_estimator)
...
+                                                               /* m_submitted_in_package */ fuzzed_data_provider.ConsumeBool(),
```
[the remark this answers is not in the document]
Comment (martinus) [reply src/test/fuzz/policy_estimator.cpp]: Hm, as far as I know there's no easy way... I once found a bug like that where a deterministic random generator was used, and the unit test was asserting the exact output of an algorithm given a fixed but random input. On Windows the result was different because there the compiler had chosen a different evaluation order.

[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply src/test/fuzz/policy_estimator.cpp]: Fixed in https://github.com/bitcoin/bitcoin/commit/fab46cc454f94b33dda6bc68a7234b439310f358 thank you @martinus

[the remark this answers is not in the document]
Comment (martinus) [reply src/test/fuzz/policy_estimator.cpp]: @maflcko I just looked through the code a bit to find other usages of `fuzzed_data_provider` that depend on the evaluation order, and there are quite a few of them. E.g.

* https://github.com/bitcoin/bitcoin/blob/master/src/test/fuzz/addrman.cpp#L272
* https://github.com/bitcoin/bitcoin/blob/master/src/test/fuzz/addrman.cpp#L286-L290
* https://github.com/bitcoin/bitcoin/blob/master/src/test/fuzz/banman.cpp#L79
* https://github.com/bitcoin/bitcoin/blob/master/src/test/fuzz/bloom_filter.cpp#L22-L26
* https://github.com/martinus/bitcoin/blob/master/src/test/fuzz/buffered_file.cpp#L28
* ...

It would be great if it were possible to find these automatically, but as far as I know that doesn't exist anywhere. Maybe with a custom clang-tidy plugin for specific classes, (random generator and fuzzer)?

[the remark this answers is not in the document]
Comment (martinus) [reply src/test/fuzz/policy_estimator.cpp]: I created #29043

**Comment by ismaelsadeeq** [comment]
Thanks for reviewing @martinus @maflcko 
Forced pushed from https://github.com/bitcoin/bitcoin/commit/fab46cc454f94b33dda6bc68a7234b439310f358 to https://github.com/bitcoin/bitcoin/commit/f8ef5dbc8471b711d233e3bec64597498a641252
to fix CI failure
[compare_changes](https://github.com/bitcoin/bitcoin/compare/fab46cc454f94b33dda6bc68a7234b439310f358..f8ef5dbc8471b711d233e3bec64597498a641252)

File: src/test/fuzz/policy_estimator.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply src/test/fuzz/policy_estimator.cpp]: Thanks @martinus Will review

**Review by glozow — COMMENTED** [review]
concept ACK, thanks for fixing the issue

File: src/kernel/mempool_entry.h [hunk 3]
```diff
@@ -190,6 +190,10 @@ class CTxMemPoolEntry
 
 using CTxMemPoolEntryRef = CTxMemPoolEntry::CTxMemPoolEntryRef;
 
+/**
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply src/kernel/mempool_entry.h:193]: All the doc changes here or only `TransactionInfo` doctring?

[the remark this answers is not in the document]
Comment (glozow) [reply src/kernel/mempool_entry.h:193]: Just the added docstrings. I think it's self-explanatory that they store information about a tx.

[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply src/kernel/mempool_entry.h]: Thanks fixed now

**Review by glozow — COMMENTED** [review]
utACK b1318dcc56a0181783ee7ddbd388ae878a0efc52

**Comment by martinus** [comment]
re-ACK b1318dcc56a0181783ee7ddbd388ae878a0efc52
