### PR TITLE
[0.19] Backports

### LINKED ISSUE #17856: bitcoind fails to compile with boost 1.72.0
**Expected behavior**

`make` succeeds

**Actual behavior**

```sh
$ make
Making all in src
  …
  CXX      wallet/libbitcoin_wallet_a-walletutil.o
wallet/walletutil.cpp:77:23: error: no member named 'level' in 'boost::filesystem::recursive_directory_iterator'
        } else if (it.level() == 0 && it->symlink_status().type() == fs::regular_file && IsBerkeleyBtree(it->path())) {
                   ~~ ^
1 error generated.
make[2]: *** [wallet/libbitcoin_wallet_a-walletutil.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**To reproduce**

For MacOS:

```sh
brew update
brew install boost
cd bitcoin
./contrib/install_db4.sh $(pwd)
export BDB_PREFIX=$(pwd)/db4
./autogen.sh
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" --enable-cxx --without-gui --disable-tests --disable-bench
make
```

For Alpine see: [Dockerfile](https://github.com/lncm/docker-bitcoind/blob/boost-1.72.0/0.19/Dockerfile#L107), [build log](https://github.com/lncm/docker-bitcoind/runs/372097468#step:3:942).

**System information**

Tested for `v0.19.0.1` & e6f167bfd .

Reproducible on MacOS/amd64 as well as debian/arm, and ubuntu/amd64.

**Speculation**

It seems to be caused by a change in `boost` described as ([src](https://www.boost.org/users/history/version_1_72_0.html)):

> * **Deprecated:** The following members of `recursive_directory_iterator` are now marked as deprecated: `level()`, `no_push_pending()`, `no_push_request()`, `no_push()`. Users are advised to replace their use with the standard counterparts: `depth()`, `recursion_pending()`, `disable_recursion_pending()`. Note that `recursion_pending()` has the opposite meaning compared to `no_push_pending()` and `no_push_request()`. Deprecated methods will be removed in a future release.

### PR DESCRIPTION
**Pull request by fanquake**
Backports the following PRs to the 0.19 branch:
* https://github.com/bitcoin/bitcoin/pull/17654 - Unbreak build with Boost 1.72.0
* https://github.com/bitcoin/bitcoin/pull/17695 - gui: disable File->CreateWallet during startup
* https://github.com/bitcoin/bitcoin/pull/17687 - cli: fix Fatal LevelDB error when specifying -blockfilterindex=basic twice
* https://github.com/bitcoin/bitcoin/pull/17728 - rpc: require second argument only for scantxoutset start action
* https://github.com/bitcoin/bitcoin/pull/17450 - util: Add missing headers to util/fees.cpp
* https://github.com/bitcoin/bitcoin/pull/17488 - test: fix "bitcoind already running" warnings on macOS
* https://github.com/bitcoin/bitcoin/pull/17762 - Log to net category for exceptions in ProcessMessages
* https://github.com/bitcoin/bitcoin/pull/17364 - Updates to appveyor config for VS2019 and Qt5.9.8 + msvc project fixes
* https://github.com/bitcoin/bitcoin/pull/17416 - Appveyor improvement - text file for vcpkg package list 
* https://github.com/bitcoin/bitcoin/pull/17736 - Update msvc build for Visual Studio 2019 v16.4
* https://github.com/bitcoin/bitcoin/pull/17857 - scripts: fix symbol-check & security-check argument passing

Fixes #17856.

### CODE REVIEW

**Comment by hebasto** [comment]
https://github.com/bitcoin/bitcoin/pull/17450#issuecomment-570444499 ?

**Comment by sipsorcery** [comment]
ACK (tested: Windows 10 & msvc build) 99b54076ff2d2dd357dafb9f0275713cd8d0111f.

**Comment by laanwj** [comment]
ACK 99b54076ff2d2dd357dafb9f0275713cd8d0111f
