### PR TITLE
tests: fix incorrect assumption in v2transport_test

### PR DESCRIPTION
**Pull request by sipa**
One part of the current `v2transport_test` introduced in #28196 assumes that if a bit gets modified in a message, failure should instantly be detected after sending that message. This is not correct in case the length descriptor is modified, as that may cause the receiver to need more data first. Fix this by sending more messages until failure actually occurs.

Discovered in https://github.com/bitcoin/bitcoin/pull/27495#issuecomment-1719934041.

### CODE REVIEW

**Review by theStack — APPROVED** [review]
ACK 3f4e1bb9ae5ee43da9503da37b9894037d613c6d

Tested by applying the following simple patch for only damaging the first byte (being part of the length descriptor):
```diff
diff --git a/src/test/net_tests.cpp b/src/test/net_tests.cpp
index 3eb7bdec62..0b623af0ef 100644
--- a/src/test/net_tests.cpp
+++ b/src/test/net_tests.cpp
@@ -1324,7 +1324,7 @@ public:
     /** Introduce a bit error in the data scheduled to be sent. */
     void Damage()
     {
-        m_to_send[InsecureRandRange(m_to_send.size())] ^= (uint8_t{1} << InsecureRandRange(8));
+        m_to_send[0] ^= (uint8_t{1} << InsecureRandRange(8));
     }
 };
``` 


which causes several failed assertions on master, e.g. (the number varies due to randomness):

```
$ ./src/test/test_bitcoin 
Running 523 test cases...
test/net_tests.cpp(1364): error: in "net_tests/v2transport_test": check !ret has failed
test/net_tests.cpp(1364): error: in "net_tests/v2transport_test": check !ret has failed
test/net_tests.cpp(1364): error: in "net_tests/v2transport_test": check !ret has failed
test/net_tests.cpp(1364): error: in "net_tests/v2transport_test": check !ret has failed
test/net_tests.cpp(1364): error: in "net_tests/v2transport_test": check !ret has failed
test/net_tests.cpp(1364): error: in "net_tests/v2transport_test": check !ret has failed
test/net_tests.cpp(1364): error: in "net_tests/v2transport_test": check !ret has failed

*** 7 failures are detected in the test module "Bitcoin Core Test Suite"
```

but succeeds on the PR.
