### ISSUE TITLE
Fail to build on ubuntu14.04

### ISSUE THREAD

**Issue by tarukosu** [bitcoin/bitcoin#6603]
Fail to build bitcoin with this error.
```
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/local/include/boost/filesystem/operations.hpp:497: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
```
Ubuntu 14.04, bitcoin  v0.10.2, boost1.55

I tried this but it does not work.
http://www.ridgesolutions.ie/index.php/2013/05/30/boost-link-error-undefined-reference-to-boostfilesystemdetailcopy_file/

**Comment by jonasschnelli** [comment]
Did you install `sudo apt-get install libboost-all-dev`?

**Comment by tarukosu** [comment]
Sure.

**Comment by laanwj** [comment]
Can you try with the latest stable version, 0.11.0?

**Comment by tarukosu** [comment]
Similar error occurred.
```
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `path<boost::filesystem::directory_entry>':
/usr/local/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/local/include/boost/filesystem/operations.hpp:497: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
```

**Comment by jamesob** [comment]
Can't reproduce; builds fine for me:
```
(venv) [Wed 2 23:28] job/code/bitcoin master 
 $ cat /etc/lsb-release 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
                                                                                                                                              
(venv) [Wed 2 23:28] job/code/bitcoin master 
 $ uname -a                      

Linux box 3.16.0-44-generic #59~14.04.1-Ubuntu SMP Tue Jul 7 15:07:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
                                                                                                                                              
(venv) [Wed 2 23:29] job/code/bitcoin master 
 $ git show HEAD --format=oneline

3932ff50c563df19c14e9987f2297d9f99a299ac Merge pull request #6620
```
@tarukosu have you followed the instructions in `doc/build-unix.md`?

**Comment by laanwj** [comment]
Indeed -  many developers are using Ubuntu 14.04 and experience no issues. 
Unsure what the issue here is. Your boost-dev install looks broken. But the error remains strange. Maybe a version conflict. Have you upgraded from an older distro? Can you try reinstalling libboost-all -dev?

**Comment by tarukosu** [comment]
The problem was solved thanks to your support.
The reason was that two versions of boost were installed.
When I specified the directory of boost, the build succeeded.
```
$ ./configure --with-boost-libdir=/usr/local/lib
$ make
```
Thank you so much.
