### PR TITLE
netbase: extend CreateSock() to support creating arbitrary sockets

### PR DESCRIPTION
**Pull request by vasild**
Allow the callers of `CreateSock()` to pass all 3 arguments to the `socket(2)` syscall. This makes it possible to create sockets of any domain/type/protocol. In addition to extending arguments, some extra safety checks were put in place.

The need for this came up during the discussion in https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1618837102

### CODE REVIEW

**Comment by laanwj** [comment]
Concept and code review (but untested, will use this to make a testing harness for #30043) ACK 77e34ded543e19ba27cab8d0cfc464af27f04bbf

**Comment by Sjors** [comment]
This seems very useful. I'll try to use it for the (currently very brittle) `Sv2Transport` tests in #29432, and review it along the way.

File: src/netbase.cpp [hunk 1]
```diff
@@ -485,24 +485,23 @@ bool Socks5(const std::string& strDest, uint16_t port, const ProxyCredentials* a
...
 
-std::unique_ptr<Sock> CreateSockOS(sa_family_t address_family)
+std::unique_ptr<Sock> CreateSockOS(int domain, int type, int protocol)
 {
     // Not IPv4, IPv6 or UNIX
-    if (address_family == AF_UNSPEC) return nullptr;
-
-    int protocol{IPPROTO_TCP};
-#if HAVE_SOCKADDR_UN
-    if (address_family == AF_UNIX) protocol = 0;
```
Comment (tdb3) [inline src/netbase.cpp:495]: Seems ok to remove, since `protocol` is now a passthrough argument.

File: src/netbase.cpp [hunk 2]
```diff
@@ -485,24 +485,23 @@ bool Socks5(const std::string& strDest, uint16_t port, const ProxyCredentials* a
...
     // Create a socket in the specified address family.
-    SOCKET hSocket = socket(address_family, SOCK_STREAM, protocol);
+    SOCKET hSocket = socket(domain, type, protocol);
     if (hSocket == INVALID_SOCKET) {
         return nullptr;
     }
 
     auto sock = std::make_unique<Sock>(hSocket);
 
+    if (domain != AF_INET && domain != AF_INET6 && domain != AF_UNIX) {
```
Comment (tdb3) [inline src/netbase.cpp:501]: Seems good to add this sanity check to prevent setting non-pertinent sockopts.  Might be worthwhile to mention in the PR description that in addition to extending arguments, some extra safety checks were put in place.

File: src/netbase.cpp [hunk 3]
```diff
@@ -527,18 +526,21 @@ std::unique_ptr<Sock> CreateSockOS(sa_family_t address_family)
...
+        if (sock->SetSockOpt(IPPROTO_TCP, TCP_NODELAY, &on, sizeof(on)) == SOCKET_ERROR) {
+            LogPrint(BCLog::NET, "Unable to set TCP_NODELAY on a newly created socket, continuing anyway\n");
+        }
     }
+
     return sock;
 }
 
-std::function<std::unique_ptr<Sock>(const sa_family_t&)> CreateSock = CreateSockOS;
+std::function<std::unique_ptr<Sock>(int, int, int)> CreateSock = CreateSockOS;
```
Comment (tdb3) [inline src/netbase.cpp:543]: Since these are simple `int`s passed by value, seems ok to change from the previous const reference approach.

**Review by tdb3 — APPROVED** [review]
ACK for 77e34ded543e19ba27cab8d0cfc464af27f04bbf

Thanks.  Seems like a reasonable change.

Sanity checks performed:
- Synced the last 1.5 day's worth of blocks on signet.  Binding and sync seemed to work fine.
- Ran all unit and functional tests (passed).

Left some minor notes (just thinking out loud, so no need to answer/comment unless you feel it's necessary).

File: src/net.cpp [hunk 4]
```diff
@@ -3029,7 +3029,7 @@ bool CConnman::BindListenPort(const CService& addrBind, bilingual_str& strError,
         return false;
     }
 
-    std::unique_ptr<Sock> sock = CreateSock(addrBind.GetSAFamily());
+    std::unique_ptr<Sock> sock = CreateSock(addrBind.GetSAFamily(), SOCK_STREAM, IPPROTO_TCP);
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/net.cpp:3032]: Returning `sa_family_t` is slightly more self-documenting, imo, would prefer to keep it as-is.
But yes it's simply a type-def'd integer type not a real enum, i suppose because it's "open", as in, new OS headers could potentially define their own address family without having to update a central list.

**Review by theStack — APPROVED** [review]
Concept and code-review ACK 77e34ded543e19ba27cab8d0cfc464af27f04bbf

File: src/netbase.cpp (hunk 2 above)
Comment (vasild) [reply src/netbase.cpp:501]: Done

**Comment by vasild** [comment]
`77e34ded54...5f549c35d9`: fix typo in the comment: `s/socke/socket/`

File: src/netbase.h [hunk 5]
```diff
@@ -262,16 +262,18 @@ CService LookupNumeric(const std::string& name, uint16_t portDefault = 0, DNSLoo
 CSubNet LookupSubNet(const std::string& subnet_str);
 
 /**
- * Create a TCP or UNIX socket in the given address family.
- * @param[in] address_family to use for the socket.
+ * Create a real socket from the operating system.
+ * @param[in] domain Communications domain, first argument to the socket(2) syscall.
+ * @param[in] type Type of the socket, second argument to the socket(2) syscall.
+ * @param[in] protocol The particular protocol to be used with the socke, third argument to the socket(2) syscall.
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/netbase.h]: Oh, it is usually either `s`, `sock` or `socket`. `socke` is something new, that is extra genuine ;-)

Fixed, invalidating 3 ACKs but should be trivial to re-review.

Thanks!

**Review by theStack — APPROVED** [review]
re-ACK 5f549c35d9a75c7019fe8a96963b988df5498eed 🧦

**Review by tdb3 — APPROVED** [review]
re-ACK 5f549c35d9a75c7019fe8a96963b988df5498eed

**Comment by achow101** [comment]
ACK 5f549c35d9a75c7019fe8a96963b988df5498eed

**Comment by achow101** [comment]
Silent merge conflict

```
../../../src/test/fuzz/i2p.cpp:30:16: error: no viable overloaded '='
   30 |     CreateSock = [&fuzzed_data_provider](const sa_family_t&) {
      |     ~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   31 |         return std::make_unique<FuzzedSock>(fuzzed_data_provider);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   32 |     };
      |     ~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/std_function.h:469:7: note: candidate function not viable: no known conversion from '(lambda at ../../../src/test/fuzz/i2p.cpp:30:18)' to 'const function<unique_ptr<Sock> (int, int, int)>' for 1st argument
  469 |       operator=(const function& __x)
      |       ^         ~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/std_function.h:487:7: note: candidate function not viable: no known conversion from '(lambda at ../../../src/test/fuzz/i2p.cpp:30:18)' to 'function<unique_ptr<Sock> (int, int, int)>' for 1st argument
  487 |       operator=(function&& __x) noexcept
      |       ^         ~~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/std_function.h:501:7: note: candidate function not viable: no known conversion from '(lambda at ../../../src/test/fuzz/i2p.cpp:30:18)' to 'nullptr_t' (aka 'std::nullptr_t') for 1st argument
  501 |       operator=(nullptr_t) noexcept
      |       ^         ~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/std_function.h:531:2: note: candidate template ignored: requirement '_Callable<(lambda at ../../../src/test/fuzz/i2p.cpp:30:18), (lambda at ../../../src/test/fuzz/i2p.cpp:30:18), std::__invoke_result<(lambda at ../../../src/test/fuzz/i2p.cpp:30:18) &, int, int, int>>::value' was not satisfied [with _Functor = (lambda at ../../../src/test/fuzz/i2p.cpp:30:18)]
  531 |         operator=(_Functor&& __f)
      |         ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/std_function.h:541:2: note: candidate template ignored: could not match 'reference_wrapper<_Functor>' against '(lambda at ../../../src/test/fuzz/i2p.cpp:30:18)'
  541 |         operator=(reference_wrapper<_Functor> __f) noexcept
      |         ^
1 error generated.
make[2]: *** [Makefile:17184: test/fuzz/fuzz-i2p.o] Error 1
```

**Comment by vasild** [comment]
`5f549c35d9...1245d1388b`: rebase due to (silent) merge conflict

**Comment by tdb3** [comment]
re ACK 1245d1388b003c46092937def7041917aecec8de

**Review by tdb3 — APPROVED** [review]
re ACK 1245d1388b003c46092937def7041917aecec8de

**Review by theStack — APPROVED** [review]
re-ACK 1245d1388b003c46092937def7041917aecec8de

**Comment by achow101** [comment]
ACK 1245d1388b003c46092937def7041917aecec8de
